---
title: "2666"
author: Roberto Bolaño
date: 2024-04-22
Rating: 9 / 10
---

### Highlights
> porque por qué no.
> 
> **La parte de los críticos** (Location 1523)

---

> El dibujo 3, por el contrario, tenía cierta lógica, una lógica de adolescente tarado, de adolescente vagabundo en el desierto, con las ropas deshilachadas, pero con ropas. Todos los nombres, se podría decir, pertenecían a filósofos preocupados por el argumento ontológico.
> 
> **La parte de Amalfitano** (Location 3491)

---

> No hay amistad, dijo la voz, no hay amor, no hay épica, no hay poesía lírica que no sea un gorgoteo o un gorjeo de egoístas, trino de tramposos, borbollón de traidores, burbujeo de arribistas, gorgorito de maricones.
> 
> **La parte de Amalfitano** (Location 3783)

---

> Ésta es la ecuación: oferta + demanda + magia.
> 
> **La parte de Amalfitano** (Location 4133)

---

> —Cada cosa de este país es un homenaje a todas las cosas del mundo, incluso a las que aún no han sucedido
> 
> **La parte de Fate** (Location 6185)

---

> Aparte del peligro de un mar temible y desconocido, ¿quién va a dejar Asia, África o Italia para marchar a Germania, con un terreno difícil, un clima duro, triste de habitar y contemplar si no es su patria?
> 
> **La parte de Archimboldi** (Location 14826)