---
title: "As Cidades Invisíveis"
author: Italo Calvino
date: 2024-9-29
Rating: 9 / 10
---

### Highlights
> Existe um momento na vida dos imperadores que se segue ao orgulho pela imensa amplitude dos territórios que conquistamos, à melancolia e ao alívio de saber que em breve desistiremos de conhecê-los e compreendê-los, uma sensação de vazio que surge ao calar da noite com o odor dos elefantes após a chuva e das cinzas de sândalo que se resfriam nos braseiros,
> 
> **Capítulo 1** (Location 85)

---

> é o desesperado momento em que se descobre que este império, que nos parecia a soma de todas as maravilhas, é um esfacelo sem fim e sem forma, que a sua corrupção é gangrenosa demais para ser remediada pelo nosso cetro, que o triunfo sobre os soberanos adversários nos fez herdeiros de suas prolongadas ruínas.
> 
> **Capítulo 1** (Location 91)

---

> o imperador é aquele que é estrangeiro para cada um de seus súditos e somente por meio de olhos e ouvidos estrangeiros o império podia manifestar a sua existência para Kublai.
> 
> **Capítulo 1** (Location 216)

---

> Ao chegar a uma nova cidade, o viajante reencontra um passado que não lembrava existir: a surpresa daquilo que você deixou de ser ou deixou de possuir revela-se nos lugares estranhos, não nos conhecidos.
> 
> **Capítulo 2** (Location 260)

---

> Os futuros não realizados são apenas ramos do passado: ramos secos.
> 
> **Capítulo 2** (Location 265)

---

> Os outros lugares são espelhos em negativo. O viajante reconhece o pouco que é seu descobrindo o muito que não teve e o que não terá.
> 
> **Capítulo 2** (Location 269)

---

> Todas as vezes que descrevo uma cidade digo algo a respeito de Veneza.
> 
> **Capítulo 6** (Location 679)

---

> Talvez do mundo só reste um terreno baldio coberto de imundícies e o jardim suspenso do paço imperial do Grande Khan. São as nossas pálpebras que os separam, mas não se sabe qual está dentro e qual está fora.
> 
> **Capítulo 7** (Location 809)

---

> Ao retornar de sua última missão, Marco Polo encontrou o Khan a sua espera, sentado diante de um tabuleiro de xadrez. Com um gesto, convidou-o a sentar à sua frente e descrever-lhe as cidades que visitara apenas com o auxílio do xadrez.
> 
> **Capítulo 8** (Location 949)

---

> Kublai Khan já não precisava mandar Marco Polo em expedições distantes: detinha-o para jogar intermináveis partidas de xadrez. O conhecimento do império escondia-se no desenho traçado pelos angulosos saltos do cavalo, pelos espaços diagonais que se abrem nas incursões do bispo, pelo passo arrastado e prudente do rei e do humilde peão, pelas alternativas inexoráveis de cada partida.
> 
> **Capítulo 8** (Location 959)

---

> Quem vai a Olinda com uma lente de aumento e procura com atenção pode encontrar em algum lugar um ponto não maior do que a cabeça de um alfinete que um pouco ampliado mostra em seu interior telhados antenas claraboias jardins tanques, faixas através das ruas, quiosques nas praças, pistas para as corridas de cavalos.
> 
> **Capítulo 8** (Location 1012)

---

> Quem comanda a narração não é a voz: é o ouvido.
> 
> **Capítulo 9** (Location 1050)

---

> Viajando percebe-se que as diferenças desaparecem: uma cidade vai se tornando parecida com todas as cidades, lugares alternam formas ordens distâncias, uma poeira informe invade os continentes.
> 
> **Capítulo 9** (Location 1072)

---

> O inferno dos vivos não é algo que será; se existe, é aquele que já está aqui, o inferno no qual vivemos todos os dias, que formamos estando juntos. Existem duas maneiras de não sofrer. A primeira é fácil para a maioria das pessoas: aceitar o inferno e tornar-se parte deste até o ponto de deixar de percebê-lo. A segunda é arriscada e exige atenção e aprendizagem contínuas: tentar saber reconhecer quem e o que, no meio do inferno, não é inferno, e preservá-lo, e abrir espaço.
> 
> **Capítulo 9** (Location 1312)