---
title: "Doctor Faustus"
author: Thomas Mann
date: 2024-08-19
Rating: 8 / 10
---

### Highlights
> And yet there is something else – some of us fear it at moments which seem to us criminal, but others quite frankly and steadily – something we fear more than German defeat, and that is German victory.
> 
> **5** (Location 525)

---

> nobody for a long time thought of connecting young Adrian in any way with music.
> 
> **7** (Location 754)

---

> his apparent interest in a discipline in which I myself did not shine – mathematics.
> 
> **7** (Location 776)

---

> “Relationship is everything. And if you want to give it a more precise name, it is ambiguity.”
> 
> **7** (Location 804)

---

> People positively did not want to know why Op. 111 has only two movements.
> 
> **8** (Location 870)

---

> We had only needed, he said, to hear the piece to answer the question ourselves. A third movement? A new approach? A return after this parting – impossible! It had happened that the sonata had come, in the second, enormous movement, to an end, an end without any return. And when he said “the sonata,” he meant not only this one in C minor, but the sonata in general, as a species, as traditional art-form;
> 
> **8** (Location 950)

---

> Music was actually the most intellectual of all the arts, as was evident from the fact that in it, as in no other, form and content are interwoven and absolutely one and the same.
> 
> **8** (Location 1057)

---

> “Do you know a stronger?” “Yes, interest.” “By which you presumably mean a love from which the animal warmth has been withdrawn.” “Let us agree on the definition!” he laughed.
> 
> **8** (Location 1204)

---

> The mania he then developed of thinking out musical problems, which he solved like chess problems, might make one fear lest he thought this contriving and mastering of technical difficulties was already composition.
> 
> **9** (Location 1263)

---

> Christianity was a political revolution which, having failed, became a moral one.
> 
> **14** (Location 2085)

---

> “The Russians,” said Deutschlin sententiously, “have profundity but no form. And in the west they have form but no profundity. Only we Germans have both.”
> 
> **14** (Location 2158)

---

> he was too self-conscious, too proud, too difficult, too solitary, to be a virtuoso.
> 
> **15** (Location 2300)

---

> Why does almost everything seem to me like its own parody? Why must I think that almost all, no, all the methods and conventions of art today are good for parody only?
> 
> **15** (Location 2342)

---

> they always addressed each other with their last names and Sie. If I did not know how to entertain Adrian as Schildknapp did, I did have our childhood tie, our du, to my advantage over the Silesian.
> 
> **20** (Location 2998)

---

> For it belongs in the realm of the fantastic, it offends against all order and expectation that Germany itself should become the theatre of one of Germany’s wars.
> 
> **21** (Location 3042)

---

> Art would like to stop being pretence and play, it would like to become knowledge.”
> 
> **21** (Location 3169)

---

> But precisely on that account freedom becomes the principle of an all-round economy that leaves in music nothing casual, and develops the utmost diversity while adhering to the identical material. Where there is nothing unthematic left, nothing which could not show itself to derive from the same basic material, there one can no longer speak of a ‘free style.’”
> 
> **22** (Location 3343)

---

> Every note of the whole composition, both melody and harmony, would have to show its relation to this fixed fundamental series. Not one might recur until the other notes have sounded.
> 
> **22** (Location 3356)

---

> would result in a probably unavoidable serious musical impoverishment and stagnation.”
> 
> **22** (Location 3362)

---

> indifference to harmony and melody.”
> 
> **22** (Location 3373)

---

> “But do you hope to have people hear all that?”
> 
> **22** (Location 3374)

---

> the perception of it would afford an unknown aesthetic satisfaction.”
> 
> **22** (Location 3378)

---

> “Bound by a self-imposed compulsion to order, hence free.”
> 
> **22** (Location 3382)

---

> the emancipation of dissonance from its resolution, its becoming ‘absolute’ as it appears already in some passages of the later Wagner – would warrant any combination of notes which can justify itself before the system.”
> 
> **22** (Location 3385)

---

> He was in the real sense of the word a man of disinclination, avoidance, reserve, aloofness.
> 
> **24** (Location 3869)

---

> There are people with whom it is not easy to live; but to leave impossible.
> 
> **24** (Location 3876)

---

> Did not Bismarck say something about the Germans needing half a bottle of champagne to arrive at their normal height?
> 
> **25** (Location 4021)

---

> Gifted but halt is the German – gifted enough to be angry with his paralysis, and to overcome it by hand-over-head illumination.
> 
> **25** (Location 4022)

---

> That is the secret delight and security of hell, that it is not to be informed on, that it is protected from speech, that it just is,
> 
> **25** (Location 4320)

---

> We are in league and business – with your blood you have affirmed it and promised yourself to us, and are baptized ours. This my visit concerns only the confirmation thereof.
> 
> **25** (Location 4388)

---

> Love is forbidden you, in so far as it warms. Thy life shall be cold, therefore thou shalt love no human being.
> 
> **25** (Location 4404)

---

> Cold we want you to be, that the fires of creation shall be hot enough to warm yourself in. Into them you will flee out of the cold of your life.
> 
> **25** (Location 4410)

---

> But in our Germany its effect was undeniably and preeminently enthusiasm, historic ardour, joy at being released from dull everyday, and from a world-stagnation that could go on no longer; as hope for the future, an appeal to duty and manhood, in short as a holiday for heroes.
> 
> **30** (Location 5289)

---

> yet we thought nothing at all, on the contrary we found it glorious, that our national unification – and even so a partial, a compromise unification – cost three serious wars.
> 
> **30** (Location 5313)

---

> The peoples beyond our borders might consider us disturbers of the peace if they chose, enemies of life and not to be borne with; but we had the means to knock the world on the head until it changed its mind and came not only to admire but to love us.
> 
> **30** (Location 5327)

---

> The time of which I write was for us Germans an era of national collapse, of capitulation, of uprisings due to exhaustion, of helpless surrender into the hands of strangers. The time in which I write, which must serve me to set down these recollections here in my silence and solitude, this time has a horribly swollen belly, it carries in its womb a national catastrophe compared with which the defeat of those earlier days seems a moderate misfortune, the sensible liquidation of an unsuccessful enterprise.
> 
> **33** (Location 5922)

---

> the perfectly uncanny rapidity with which the work came to be: the chief part of it in four and a half months, a period which one would have allowed for the mere mechanical task of putting it down.
> 
> **34** (Location 6332)

---

> ordering and normalizing the notes was the condition and first self-manifestation of what we understand by music. Stuck there, so to speak, a naturalistic atavism, a barbaric rudiment from pre-musical days, is the gliding voice, the glissando, a device to be used with the greatest restraint on profoundly cultural grounds;
> 
> **34** (Location 6595)

---

> The whole work is dominated by the paradox (if it is a paradox) that in it dissonance stands for the expression of everything lofty, solemn, pious, everything of the spirit; while consonance and firm tonality are reserved for the world of hell, in this context a world of banality and commonplace.
> 
> **34** (Location 6615)

---

> O Germany, thou art undone! And I am mindful of thy hopes. Those hopes, I mean, which you aroused (it may even be that you did not share them) after your former relatively mild collapse and the abdication of the Empire. The world then placed on you certain hopes; and you seemed – aside from that reckless, utterly crazy, desperate, and hysterical “inflation” of your own misery, the giddy heavenward climb of the exchange – that aside, you seemed for some years to be about to justify, to some extent, those hopes.
> 
> **36** (Location 6831)

---

> There was some hope for Germany of social progress in peace and freedom; of adult and forward-looking effort; of a voluntary adaptation of our thoughts and feelings to those of the normal world. Despite all her inherent weakness and self-hatred, this was beyond a doubt the meaning and the hope of the German republic – again, the hope I mean is the one she awakened in the world outside.
> 
> **36** (Location 6839)

---

> To be German, that means above all to be national – and who expects a Jew to be nationalistic?
> 
> **37** (Location 7171)

---

> We Jews have everything to fear from the German character, qui est essentiellement antisémitique; and that is reason enough, of course, for us to plump for the worldly side and arrange sensational entertainments.
> 
> **37** (Location 7173)

---

> cast in three movements, it has no key-signature, but, if I may so express myself, three tonalities are built into it: B-flat major, C major, and D major,
> 
> **38** (Location 7213)

---

> He objected to Goethe’s saying that art is concerned with the good and difficult; he held that ‘light’ music is difficult too, if it is good, which it can be, just as well as ‘heavy’ music.
> 
> **38** (Location 7275)

---

> the word “German” is today by no means synonymous with intellectual clarity, being, as it is, a party cry.
> 
> **42** (Location 7889)

---

> “I find,” he said, “that it is not to be.”
> 
> **45** (Location 8431)

---

> “The good and noble,” he answered me; “what we call the human, although it is good, and noble. What human beings have fought for and stormed citadels, what the ecstatics exultantly announced – that is not to be. It will be taken back. I will take it back.”
> 
> **45** (Location 8432)

---

> it is now the 25th of April in this year of destiny 1945
> 
> **46** (Location 8462)

---

> Germany had become a thick-walled underground torture-chamber, converted into one by a profligate dictatorship vowed to nihilism from its beginnings on. Now the torture-chamber has been broken open, open lies our shame before the eyes of the world.
> 
> **46** (Location 8483)

---

> conceive. I say our shame. For is it mere hypochondria to say to oneself that everything German, even the German mind and spirit, German thought, the German Word, is involved in this scandalous exposure and made subject to the same distrust?
> 
> **46** (Location 8486)

---

> This giant “lamento” (it lasts an hour and a quarter) is very certainly non-dynamic, lacking in development, without drama, in the same way that concentric rings made by a stone thrown into water spread ever farther, without drama and always the same.
> 
> **46** (Location 8585)

---

> the reverse of the “Ode to Joy,” the negative, equally a work of genius, of that transition of the symphony into vocal jubilation. It is the revocation.
> 
> **46** (Location 8641)

---

> He wrote it, no doubt, with his eye on Beethoven’s Ninth, as its counterpart in a most melancholy sense of the word.
> 
> **46** (Location 8646)

---

> For listen to the end, listen with me: one group of instruments after another retires, and what remains, as the work fades on the air, is the high G of a cello, the last word, the last fainting sound, slowly dying in a pianissimofermata. Then nothing more: silence, and night.
> 
> **46** (Location 8668)

---

> I am wedded to Satan and with due knowing of peril, out of well-considered courage, pride, and presumption because I would win glory in this world,
> 
> **47** (Location 8770)

---

> Germany is free, in so far as one may apply the word to a land prostrate and proscribed.
> 
> **Epilogue** (Location 8906)