---
title: "El Aleph"
author: Jorge Luís Borges
date: 2024-04-27
Rating: 10 / 10
---

### Highlights
> Ser inmortal es baladí; menos el hombre, todas las criaturas lo son, pues ignoran la muerte; lo divino, lo terrible, lo incomprensible, es saberse inmortal.
> 
> **El Inmortal** (Location 173)

---

> leal a su capitán y a su tribu, no al universo.
> 
> **Historia del Guerrero y la Cautiva** (Location 453)

---

> Súbitamente comprendí la reserva y la obstinada soledad de Damián; no las había dictado la modestia, sino el bochorno.
> 
> **La otra muerte** (Location 682)

---

> más poético es el caso de un hombre que se propone un fin que no está vedado a los otros, pero sí a él.
> 
> **La busca de Averroes** (Location 945)

---

> Sentí, en la última página, que mi narración era un símbolo del hombre que yo fui, mientras la escribía y que, para redactar esa narración, yo tuve que ser aquel hombre y que, para ser aquel hombre, yo tuve que redactar esa narración, y así hasta lo infinito.
> 
> **La busca de Averroes** (Location 949)

---

> pensé que nada hay menos material que el dinero, ya que cualquier moneda (una moneda de veinte centavos, digamos) es, en rigor, un repertorio de futuros posibles.
> 
> **El Zahir** (Location 998)

---

> Un dios, reflexioné, sólo debe decir una palabra y en esa palabra la plenitud. Ninguna voz articulada por él puede ser inferior al universo o menos que la suma del tiempo.
> 
> **La escritura de Dios** (Location 1113)

---

> Quien ha entrevisto el universo, quien ha entrevisto los ardientes designios del universo, no puede pensar en un hombre, en sus triviales dichas o desventuras, aunque ese hombre sea él.
> 
> **La escritura de Dios** (Location 1140)