---
title: "Ficciones"
author: Jorge Luís Borges
date: 2024-05-2
Rating: 10 / 10
---

### Highlights
> Los metafísicos de Tlön no buscan la verdad ni siquiera la verosimilitud: buscan el asombro.
> 
> **El jardín de senderos que se bifurcan (1941)** (Location 159)

---

> la empresa era de antemano imposible y de todos los medios imposibles para llevarla a término, éste era el menos interesante.
> 
> **El jardín de senderos que se bifurcan (1941)** (Location 372)

---

> El texto de Cervantes y el de Menard son verbalmente idénticos, pero el segundo es casi infinitamente más rico.
> 
> **El jardín de senderos que se bifurcan (1941)** (Location 421)

---

> Una doctrina filosófica es al principio una descripción verosímil del universo; giran los años y es un mero capítulo —cuando no un párrafo o un nombre— de la historia de la filosofía.
> 
> **El jardín de senderos que se bifurcan (1941)** (Location 436)

---

> ahora que mis ojos casi no pueden descifrar lo que escribo, me preparo a morir a unas pocas leguas del hexágono en que nací.
> 
> **El jardín de senderos que se bifurcan (1941)** (Location 726)

---

> Pensé en un laberinto de laberintos, en un sinuoso laberinto creciente que abarcara el pasado y el porvenir y que implicara de algún modo los astros.
> 
> **El jardín de senderos que se bifurcan (1941)** (Location 902)

---

> Lo cierto es que vivimos postergando todo lo postergable; tal vez todos sabemos profundamente que somos inmortales y que tarde o temprano, todo hombre hará todas las cosas y sabrá todo.
> 
> **Artificios (1944)** (Location 1112)

---

> Pensar es olvidar diferencias, es generalizar, abstraer. En el abarrotado mundo de Funes no había sino detalles, casi inmediatos.
> 
> **Artificios (1944)** (Location 1143)

---

> deseo administrativo de obrar impersonal y pausadamente, como los vegetales y los planetas.
> 
> **Artificios (1944)** (Location 1494)