---
title: "Lolita"
author: Vladimir Nabokov
date: 2024-09-21
Rating: 10 / 10
---

### Highlights
> How queer life is! We hasten to alienate the very fates we intended to woo.
> 
> **12** (Location 808)

---

> The rapist was Charlie Holmes; I am the therapist—
> 
> **1** (Location 2218)

---

> one hardly had to be a Coleridgian to appreciate the trite poke of “A. Person, Porlock, England.”
> 
> **23** (Location 3773)

---

> I have often noticed that we are inclined to endow our friends with the stability of type that literary characters acquire in the reader’s mind. No matter how many times we reopen “King Lear,” never shall we find the good king banging his tankard in high revelry, all woes forgotten, at a jolly reunion with all three daughters and their lapdogs. Never will Emma rally, revived by the sympathetic salts in Flaubert’s father’s timely tear. Whatever evolution this or that popular character has gone through between the book covers, his fate is fixed in our minds, and, similarly, we expect our friends to follow this or that logical and conventional pattern we have fixed for them.
> 
> **27** (Location 3989)

---

> We have it all arranged in our minds, and the less often we see a particular person the more satisfying it is to check how obediently he conforms to our notion of him every time we hear of him. Any deviation in the fates we have ordained would strike us as not only anomalous but unethical. We would prefer not to have known at all our neighbor, the retired hot-dog stand operator, if it turns out he has just produced the greatest book of poetry his age has seen.
> 
> **27** (Location 3995)

---

> It had become gradually clear to my conventional Lolita during our singular and bestial cohabitation that even the most miserable of family lives was better than the parody of incest, which, in the long run, was the best I could offer the waif.
> 
> **32** (Location 4339)

---

> For me a work of fiction exists only insofar as it affords me what I shall bluntly call aesthetic bliss, that is a sense of being somehow, somewhere, connected with other states of being where art (curiosity, tenderness, kindness, ecstasy) is the norm.
> 
> **Vladimir Nabokov ON A BOOK ENTITLED LOLITA** (Location 4740)