---
title: "Por Que Ler os Clássicos"
author: Italo Calvino
date: 2024-10-8
Rating: 8 / 10
---

### Highlights
> 1. Os clássicos são aqueles livros dos quais, em geral, se ouve dizer: “Estou relendo…” e nunca ‘‘ Estou lendo…”.
> 
> **Por que ler os clássicos** (Location 64)

---

> 2. Dizem-se clássicos aqueles livros que constituem uma riqueza para quem os tenha lido e amado; mas constituem uma riqueza não menor para quem se reserva a sorte de lê-los pela primeira vez nas melhores condições para apreciá-los.
> 
> **Por que ler os clássicos** (Location 81)

---

> 3. Os clássicos são livros que exercem uma influência particular quando se impõem como inesquecíveis e também quando se ocultam nas dobras da memória, mimetizando-se como inconsciente coletivo ou individual.
> 
> **Por que ler os clássicos** (Location 89)

---

> Portanto, usar o verbo ler ou o verbo reler não tem muita importância. De fato, poderíamos dizer: 4. Toda releitura de um clássico é uma leitura de descoberta como a primeira. 5. Toda primeira leitura de um clássico é na realidade uma releitura. A definição 4 pode ser considerada corolário desta: 6. Um clássico é um livro que nunca terminou de dizer aquilo que tinha para dizer. Ao passo que a definição 5 remete para uma formulação mais explicativa, como: 7. Os clássicos são aqueles livros que chegam até nós trazendo consigo as marcas das leituras que precederam a nossa e atrás de si os traços que deixaram na cultura ou nas culturas que atravessaram (ou mais simplesmente na linguagem ou nos costumes).
> 
> **Por que ler os clássicos** (Location 93)

---

> Existe uma inversão de valores muito difundida segundo a qual a introdução, o instrumental crítico, a bibliografia são usados como cortina de fumaça para esconder aquilo que o texto tem a dizer e que só pode dizer se o deixarmos falar sem intermediários que pretendam saber mais do que ele.
> 
> **Por que ler os clássicos** (Location 111)

---

> 8. Um clássico é uma obra que provoca incessantemente uma nuvem de discursos críticos sobre si, mas continuamente a repele para longe.
> 
> **Por que ler os clássicos** (Location 114)

---

> 9. Os clássicos são livros que, quanto mais pensamos conhecer por ouvir dizer, quando são lidos de fato mais se revelam novos, inesperados, inéditos.
> 
> **Por que ler os clássicos** (Location 119)

---

> A escola é obrigada a dar-lhe instrumentos para efetuar uma opção: mas as escolhas que contam são aquelas que ocorrem fora e depois de cada escola. É só nas leituras desinteressadas que pode acontecer deparar-se com aquele que se torna o “seu” livro.
> 
> **Por que ler os clássicos** (Location 123)

---

> 11. O “seu” clássico é aquele que não pode ser-lhe indiferente e que serve para definir a você próprio em relação e talvez em contraste com ele.
> 
> **Por que ler os clássicos** (Location 135)

---

> 12. Um clássico é um livro que vem antes de outros clássicos; mas quem leu antes os outros e depois lê aquele reconhece logo o seu lugar na genealogia.
> 
> **Por que ler os clássicos** (Location 141)

---

> 13. É clássico aquilo que tende a relegar as atualidades à posição de barulho de fundo, mas ao mesmo tempo não pode prescindir desse barulho de fundo. 14. É clássico aquilo que persiste como rumor mesmo onde predomina a atualidade mais incompatível.
> 
> **Por que ler os clássicos** (Location 159)

---

> A única razão que se pode apresentar é que ler os clássicos é melhor do que não ler os clássicos.
> 
> **Por que ler os clássicos** (Location 178)

---

> “Enquanto era preparada a cicuta, Sócrates estava aprendendo uma ária com a flauta. ‘Para que lhe servirá?’, perguntaram-lhe. ‘Para aprender esta ária antes de morrer’”.
> 
> **Por que ler os clássicos** (Location 180)

---

> descobrir Borges para nós foi ver realizada uma potencialidade almejada desde sempre: ver tomar forma um mundo à imagem e semelhança dos espaços do intelecto, habitado por um zodíaco de signos que correspondem a uma geometria rigorosa.
> 
> **Jorge Luis Borges** (Location 3687)

---

> Dentre estas colocarei à frente a economia da expressão: Borges é um mestre do escrever breve.
> 
> **Jorge Luis Borges** (Location 3690)

---

> Lendo Borges, me veio repetidas vezes a tentação de formular uma poética do escrever breve, louvando suas vantagens em relação ao escrever longo, contrapondo as duas ordens mentais que a inclinação para um ou para o outro pressupõe, por temperamento, por ideia da forma, por substância dos conteúdos.
> 
> **Jorge Luis Borges** (Location 3696)

---

> Para escrever breve, a invenção fundamental de Borges, que foi também a invenção de si mesmo como narrador, o ovo de Colombo que lhe permitiu superar o bloqueio que o impedia, até cerca dos quarenta anos, de passar da prosa ensaística para a prosa narrativa, fingiu que o livro que desejava escrever já estivesse escrito, escrito por um outro, por um hipotético autor desconhecido, um autor de uma outra língua, de uma outra cultura, e descreveu, resumiu, resenhou esse livro hipotético.
> 
> **Jorge Luis Borges** (Location 3700)

---

> O que mais me interessa anotar aqui é que nasce com Borges uma literatura elevada ao quadrado e ao mesmo tempo uma literatura como extração da raiz quadrada de si mesma:
> 
> **Jorge Luis Borges** (Location 3707)

---

> Que para Borges só a palavra escrita tenha plena realidade ontológica e que as coisas do mundo existam para ele somente enquanto remetem a coisas escritas, foi dito muitas vezes;
> 
> **Jorge Luis Borges** (Location 3710)

---

> E aqui convém lembrar que do epos de Borges não faz parte somente aquilo que se lê nos clássicos, mas também a história argentina, que em alguns episódios se identifica com a sua história familiar, com os feitos de armas de seus antepassados militares nas guerras da jovem nação.
> 
> **Jorge Luis Borges** (Location 3721)

---

> Consideremos um exemplo clássico da arte borgiana: seu conto mais famoso, “El jardín de senderos que se bifurcan”. O enredo evidente é o de um conto de espionagem convencional, um enredo aventuroso condensado numa dúzia de páginas e um pouco forçado para chegar a um final surpresa.
> 
> **Jorge Luis Borges** (Location 3745)

---

> Percebemos no final que, sob a aparência de um thriller, é um conto filosófico, ou melhor, um ensaio sobre a ideia do tempo aquilo que acabamos de ler.
> 
> **Jorge Luis Borges** (Location 3750)