---
title: "Six Memos for the Next Millennium"
author: Italo Calvino
date: 2024-10-3
Rating: 8 / 10
---

### Highlights
> In this talk I shall try to explain— both to myself and to you— why I have come to consider lightness a value rather than a defect;
> 
> **Início** (Location 68)

---

> between the facts of life that should have been my raw materials and the quick light touch I wanted for my writing, there was a gulf that cost me increasing effort to cross.
> 
> **Início** (Location 73)

---

> We might say that throughout the centuries two opposite tendencies have competed in literature: one tries to make language into a weighdess element that hovers above things like a cloud or better, perhaps, the finest dust or, better still, a field of magnetic impulses. The other tries to give language the weight, density, and concreteness of things, bodies, and sensations.
> 
> **Início** (Location 229)

---

> When Dante wants to express lightness, even in the Dinna Commedia, no one can do it better than he does, but his real genius lies in the opposite direction— in extracting all the possibilities of sound and emotion and feeling from the language,
> 
> **Início** (Location 236)

---

> I might say that Dante gives solidity even to the most abstract intellectual speculation, whereas Cavalcanti dissolves the concreteness of tangible experience in lines of measured rhythm, syllable by syllable, as if thought were darting out of darkness in swift lightning flashes.
> 
> **Início** (Location 239)

---

> Lightness for me goes with precision and determination, not with vagueness and the haphazard. Paul Valery said: “II faut etre leger comme l'oiseau, et non comme la plume” (One should be light like a bird, and not like a feather).
> 
> **Início** (Location 242)

---

> As soon as the moon appears in poetry, it brings with it a sensation of lightness, suspension, a silent calm enchantment.
> 
> **Início** (Location 344)

---

> Just as in poems and songs the rhymes help to create the rhythm, so in prose narrative there are events that rhyme.
> 
> **Início** (Location 468)

---

> It was the invention of himself as narrator, that “Columbus' egg,” which enabled him to get over the mental block that until nearly forty years of age prevented him from moving beyond essays to fiction. The idea that came to Borges was to pretend that the book he wanted to write had already been written by someone else, some unknown hypothetical author— an author in a different language, of a different culture— and that his task was to describe and review this invented book.
> 
> **Início** (Location 667)

---

> Borges has created a literature raised to the second power and, at the same time, a literature that is like the extraction of the square root of itself.
> 
> **Início** (Location 677)

---

> To my mind exactitude means three things above all: a well-defined and well-calculated plan for the work in question; an evocation of clear, incisive, memorable visual images; in Italian we have an adjective that doesn't exist in English, “icastico,” from the Greek e?? ast????; a language as precise as possible both in choice of words and in expression of the subtleties of thought and imagination.
> 
> **Início** (Location 738)

---

> That's why I try to talk as little as possible. If I prefer writing, it is because I can revise each sentence until I reach the point where— if not exactly satisfied with my words— I am able at least to eliminate those reasons for dissatisfaction that I can put a finger on.
> 
> **Início** (Location 745)

---

> I wanted to tell you of my fondness for geometrical forms, for symmetries, for numerical series, for all that is combinatory, for numerical proportions; I wanted to explain the things I had writ ten in terms of my fidelity to the idea of limits, of measure But perhaps it is precisely this idea of forms that evokes the idea of the endless: the sequence of whole numbers, Euclid's straight lines
> 
> **Início** (Location 907)

---

> Sometimes I try to concentrate on the story I would like to write, and I realize that what interests me is something else entirely or, rather, not anything precise but everything that does not fit in with what I ought to write— the relationship between a given argument and all its possible variants and alternatives, everything that can happen in time and space. This is a devouring and destructive obsession, which is enough to render writing impossible.
> 
> **Início** (Location 911)

---

> the models for the process of formation of living beings “are best visualized by the crystal on one side (invariance of specific structures) and thefiame on the other (constancy of external forms in spite of relentless internal agitation).”
> 
> **Início** (Location 941)

---

> The book in which I think I managed to say most remains Invisible Cities, because I was able to concentrate all my reflections, experiments, and conjectures on a single symbol; and also because I built up a many-faceted structure in which each brief text is close to the others in a series that does not imply logical sequence or a hierarchy, but a network in which one can follow multiple routes and draw multiple, ramified conclusions.
> 
> **Início** (Location 955)

---

> At a certain point Kublai Khan personifies the intellectual tendency toward rationalization, geometry, and algebra, reducing knowledge of his empire to the combina-toria of pieces on a chessboard.
> 
> **Início** (Location 958)

---

> The final conclusion to which this operation leads him is that the object of his conquest is nothing other than the block of wood on which each piece rests: an emblem of nothingness. But just at this moment comes a coup de scene, for Marco Polo requests Kublai to look more closely at what he sees as nothingness:
> 
> **Início** (Location 961)

---

> The fact is, my writing has always found itself facing two divergent paths that correspond to two different types of knowledge. One path goes into the mental space of bodiless rationality, where one may trace lines that converge, projections, abstract forms, vectors of force. The other path goes through a space crammed with objects and attempts to create a verbal equivalent of that space by filling the page with words,
> 
> **Início** (Location 992)

---

> “natural” languages always say something more than formalized languages can— natural languages always involve a certain amount of noise that impinges upon the essentiality of the information— and the other because, in representing the density and continuity of the world around us, language is revealed as defective and fragmentary, always saying something less with respect to the sum of what can be experienced.
> 
> **Início** (Location 996)

---

> Leonardo, “omo sanza lettere” (an unlettered man), as he described himself, had a difficult relationship with the written word. His knowledge was without equal in all the world, but his ignorance of Latin and grammar prevented him from communicating in writing with the learned men of his time.
> 
> **Início** (Location 1044)

---

> We may distinguish between two types of imaginative process: the one that starts with the word and arrives at the visual image, and the one that starts with the visual image and arrives at its verbal expression.
> 
> **Início** (Location 1106)

---

> I wished to begin with this passage from Gadda because it seems to me an excellent introduction to the subject of my lecture— which is the contemporary novel as an encyclopedia, as a method of knowledge, and above all as a network of connections between the events, the people, and the things of the world.
> 
> **Início** (Location 1389)

---

> Overambitious projects may be objectionable in many fields, but not in literature. Literature remains alive only if we set ourselves immeasurable goals, far beyond all hope of achievement.
> 
> **Início** (Location 1481)

---

> Let us remember that the book many call the most complete introduction to the culture of our century is itself a novel: Thomas Mann's Magic Mountain. It is not too much to say that the small, enclosed world of an alpine sanatorium is the starting point for all the threads that were destined to be followed by the maitres a penser of the century: all the subjects under discussion today were heralded and reviewed there.
> 
> **Início** (Location 1531)

---

> Joyce sets out with every intention of constructing a systematic and encyclopedic work that can be interpreted on various levels according to medieval exegetics (drawing up tables of the correspondences of the various chapters of Ulysses with the parts of the human body, the arts, colors, and symbols), though what he achieves above all, chapter by chapter in Ulysses, is an encyclopedia of styles,
> 
> **Início** (Location 1544)

---

> The reasons for my fondness for Borges do not end here, but I will mention only the main ones. I love his work because every one of his pieces contains a model of the universe or of an attribute of the universe (infinity, the innumerable, time eternal or present or cyclic); because they are texts contained in only a few pages, with an exemplary economy of expression; because his stories often take the outer form of some genre from popular literature, a form proved by long usage, which creates almost mythical structures.
> 
> **Início** (Location 1569)

---

> “El jardin de senderos que se bifurcan” (The Garden of Forking Paths), which is presented as a spy story and includes a totally logico-metaphysical story, which in turn contains the description of an endless Chinese novel— and all this concentrated into a dozen pages.
> 
> **Início** (Location 1573)

---

> This idea of infinite contemporary universes in which all possibilities are realized in all possible combinations is by no means a digression in the story, but rather the very reason why the protagonist feels authorized to carry out the absurd and abominable crime imposed on him by his spy mission, perfectly sure that this happens only in one of the universes but not in the others; and indeed that, if he commits this crime here and now, in other universes he and his victim will be able to hail each other as friends and brothers.
> 
> **Início** (Location 1583)

---

> These considerations are at the basis of what I call the “hyper-novel,” which I tried to exemplify in If on a winter's night a traveler (Se una notte d'inverno un viaggiatore). My aim was to give the essence of what a novel is by providing it in concentrated form, in ten beginnings; each beginning develops in very different ways from a common nucleus, and each acts within a framework that both determines and is determined.
> 
> **Início** (Location 1590)