---
title: "The Hitchhiker's Guide to the Galaxy"
author: Douglas Adams
date: 2024-07-20
Rating: 8 / 10
---

### Highlights
> The ships hung in the sky in much the same way that bricks don’t.
> 
> **Chapter 3** (Location 444)

---

> If they don’t keep on exercising their lips, he thought, their brains start working.
> 
> **Chapter 5** (Location 611)

---

> the poor Babel fish, by effectively removing all barriers to communication between different races and cultures, has caused more and bloodier wars than anything else in the history of creation.”
> 
> **Chapter 6** (Location 748)

---

> as if relationships between people were susceptible to the same laws that governed the relationships between atoms and molecules.
> 
> **Chapter 14** (Location 1318)

---

> He attacked everything in life with a mixture of extraordinary genius and naive incompetence and it was often difficult to tell which was which.
> 
> **Chapter 14** (Location 1333)

---

> So long and thanks for all the fish.
> 
> **Chapter 23** (Location 1838)

---

> I think the problem, to be quite honest with you, is that you’ve never actually known what the question is.”
> 
> **Chapter 28** (Location 2099)

---

> Science has achieved some wonderful things, of course, but I’d far rather be happy than right any day.”
> 
> **Chapter 30** (Location 2217)

---

> “Because there are some things you have to do even if you are an enlightened liberal cop who knows all about sensitivity and everything!”
> 
> **Chapter 32** (Location 2394)

---

> His job is not to wield power but to draw attention away from it.
> 
> **Notes** (Location 2485)