---
title: "The Rest is Noise"
author: Alex Ross
date: 2024-5-31
Rating: 9 / 10
---

### Highlights
> Throughout his later writings, most forcefully in the essay The Case of Wagner, Nietzsche declared that music must be liberated from Teutonic heaviness and brought back to popular roots. “Il faut méditerraniser la musique,” he wrote.
> 
> **1. The Golden Age: Strauss, Mahler, and the Fin de Siècle** (Location 420)

---

> he set forth an elaborate teleology of musical history, a theory of irreversible progress, to justify his actions.
> 
> **2. Doctor Faust: Schoenberg, Debussy, and Atonality** (Location 804)

---

> The bourgeois worship of art had implanted in artists’ minds an attitude of infallibility, according to which the imagination made its own laws. That mentality made possible the extremes of modern art.
> 
> **2. Doctor Faust: Schoenberg, Debussy, and Atonality** (Location 862)

---

> 84 percent of the repertory of the Leipzig Gewandhaus Orchestra consisted of music by living composers. By 1855, the figure had declined to 38 percent, by 1870 to 24 percent.
> 
> **2. Doctor Faust: Schoenberg, Debussy, and Atonality** (Location 867)

---

> Schoenberg’s reasoning was this: if the bourgeois audience was losing interest in new music, and if the emerging mass audience had no appetite for classical music new or old, the serious artist should stop flailing his arms in a bid for attention and instead withdraw into a principled solitude.
> 
> **2. Doctor Faust: Schoenberg, Debussy, and Atonality** (Location 869)

---

> After a rehearsal of Schoenberg’s First Chamber Symphony, Mahler asked the musicians to play a C-major triad. “Thank you,” he said, and walked out.
> 
> **2. Doctor Faust: Schoenberg, Debussy, and Atonality** (Location 1019)

---

> Just as Beethoven, in his Heiligenstadt Testament, resolved to forge ahead into a life of misery, Schoenberg pressed on.
> 
> **2. Doctor Faust: Schoenberg, Debussy, and Atonality** (Location 1071)

---

> Looking at a painting in a gallery is fundamentally different from listening to a new work in a concert hall.
> 
> **2. Doctor Faust: Schoenberg, Debussy, and Atonality** (Location 1178)

---

> Instead of separating himself from the titans of the past, from Bach, Mozart, and Beethoven, he presented himself as their heir, and pointed out that many now canonical masterpieces had caused confusion when they first appeared.
> 
> **2. Doctor Faust: Schoenberg, Debussy, and Atonality** (Location 1200)

---

> The Franco-Prussian War of 1870-71 sounded the alarm among other European nations that the new German empire intended to be more than a major player on the international stage— that it had designs of supremacy. So Debussy and Satie began to seek a way out of the hulking fortresses of Beethovenian symphonism and Wagnerian opera.
> 
> **3. Dance of the Earth: The Rite, the Folk, le Jazz** (Location 1533)

---

> The mark of authenticity was not racial but economic; he paid heed mainly to the people on the social margins, those who had lived the toughest lives.
> 
> **3. Dance of the Earth: The Rite, the Folk, le Jazz** (Location 1625)

---

> He saw how phrases were seldom symmetrical in shape, how a beat or two might be added or subtracted. He savored “bent” notes— shadings above or below the given note— and “wrong” notes that added flavor and bite.
> 
> **3. Dance of the Earth: The Rite, the Folk, le Jazz** (Location 1632)

---

> Hungarian modernists were not prone to annihilating rage of the Viennese type; instead, they sought higher unities, transcendent reconciliations.
> 
> **3. Dance of the Earth: The Rite, the Folk, le Jazz** (Location 1649)

---

> Ravel carried out a kind of velvet revolution, renewing the language of music without disturbing the peace.
> 
> **3. Dance of the Earth: The Rite, the Folk, le Jazz** (Location 1675)

---

> the bebop master spotted Stravinsky at one of the tables and immediately incorporated a motif from Firebird into “Koko,” causing the composer to spill his scotch in ecstasy.
> 
> **3. Dance of the Earth: The Rite, the Folk, le Jazz** (Location 1803)

---

> The long-standing resentment of Teutonic hegemony in the classical repertory blossomed into hate.
> 
> **3. Dance of the Earth: The Rite, the Folk, le Jazz** (Location 1826)

---

> Taruskin suggests that the confluence of praise abroad and criticism at home essentially impelled Stravinsky to cut his ties to home and to become a Western European composer:
> 
> **3. Dance of the Earth: The Rite, the Folk, le Jazz** (Location 1868)

---

> Heitor Villa-Lobos was merging rhythmic ideas from Stravinsky with complex patterns that he had detected in Afro-Brazilian music. In neoprimitivist scores such as Amazonas and Uirapuru, Villa-Lobos wrote percussion parts of riotous intensity;
> 
> **3. Dance of the Earth: The Rite, the Folk, le Jazz** (Location 1969)

---

> “That is no country for old men,” William Butler Yeats cries in “Sailing to Byzantium.”
> 
> **3. Dance of the Earth: The Rite, the Folk, le Jazz** (Location 2136)

---

> Cook’s musicals, sophisticated in technique and assertive in tone, anticipated the spirit of the Harlem Renaissance, which came into its own around 1925.
> 
> **4. Invisible Men: American Composers from Ives to Ellington** (Location 2428)

---

> The same scenario kept repeating. Middle-class parents would send their sons and daughters to Oberlin or Fisk or the National Conservatory, hoping that they could achieve the wonderful things that Dvořák had forecast for African-American music. Hitting the wall of prejudice, these young creative musicians would turn to popular styles instead— first out of frustration, then out of ambition, finally out of pride.
> 
> **4. Invisible Men: American Composers from Ives to Ellington** (Location 2455)

---

> Three Places in New England, begun around 1914 and finished as late as 1929, is Ives’s deepest meditation on American myth. Coincidentally or not, it is also the work in which the black experience matters most.
> 
> **4. Invisible Men: American Composers from Ives to Ellington** (Location 2522)

---

> A gap had opened up between the ideal of modernism as the antithesis of mass culture and the reality of America as a marketplace in which absolutely anything could be bought and sold.
> 
> **4. Invisible Men: American Composers from Ives to Ellington** (Location 2625)

---

> Jewish Americans’ identification with black music might have had something to do with inherited memories of European suffering.
> 
> **4. Invisible Men: American Composers from Ives to Ellington** (Location 2678)

---

> The Harlem Renaissance, insofar as W. E. B. Du Bois and others defined it, aspired to create an African-American version of “high culture.”
> 
> **4. Invisible Men: American Composers from Ives to Ellington** (Location 2846)

---

> Dvorak had assumed that American music would come into its own when it succeeded in importing African-American material into European form, but in the end the opposite thing happened: African-American composers appropriated European material into self-invented forms of blues and jazz.
> 
> **4. Invisible Men: American Composers from Ives to Ellington** (Location 2871)

---

> Many twentieth-century symphonies, concertos, oratorios, and chamber works of the so-called conservative type were rich in lamentations for a lost world, elegies for the golden age, forebodings of disaster.
> 
> **5. Apparition from the Woods: The Loneliness of Jean Sibelius** (Location 2995)

---

> In a certain sense, Finns are strangers in the European family. Belonging to the Finno-Ugrian category, they speak a language largely unrelated to the Indo-European group. For centuries they were governed by the kingdom of Sweden; then, in 1809, they became a semi-autonomous grand duchy of tsarist Russia. In the late nineteenth century, the Swedish influence remained strong, with a minority of Swedish speakers forming the upper crust of society. Sibelius belonged to this Swedish elite;
> 
> **5. Apparition from the Woods: The Loneliness of Jean Sibelius** (Location 3020)

---

> It was in the wake of composing this terse, elusive work that Sibelius got into a debate with Gustav Mahler on the nature of the symphony. Mahler came to Helsinki in 1907 to conduct some concerts, and Sibelius presented his latest ideas about “severity of form,” about the “profound logic” that should connect symphonic themes. “No!” Mahler replied. “The symphony must be like the world. It must be all-embracing.”
> 
> **5. Apparition from the Woods: The Loneliness of Jean Sibelius** (Location 3073)

---

> The Fifth begins and ends in crystalline major-key tonality, but it is an unconventional and staggeringly original work. The schemata of sonata form dissolve before the listener’s ears; in place of a methodical development of well-defined themes there is a gradual, incremental evolution of material through trancelike repetitions.
> 
> **5. Apparition from the Woods: The Loneliness of Jean Sibelius** (Location 3116)

---

> The Seventh Symphony expands on the formal innovation of the Fifth, the telescoping of two movements into one. Contrasting episodes are fused into one continuous structure, so that Adagio hymns become Scherzo dances by imperceptible degrees.
> 
> **5. Apparition from the Woods: The Loneliness of Jean Sibelius** (Location 3161)

---

> Theodor Adorno prepared a dire analysis of the Sibelius phenomenon for a sociological think tank called the Princeton Radio Research Project: “The work of Sibelius is not only incredibly overrated, but it fundamentally lacks any good qualities
> 
> **5. Apparition from the Woods: The Loneliness of Jean Sibelius** (Location 3247)

---

> Adorno é um idiota
> 
> **5. Apparition from the Woods: The Loneliness of Jean Sibelius** (Location 3249)

---

> “All the doctors who wanted to forbid me to smoke and to drink are dead,” he once said.
> 
> **5. Apparition from the Woods: The Loneliness of Jean Sibelius** (Location 3282)

---

> Brecht barged into Weill’s life in early 1927. Scholars are still trying to capture the dynamic of their collaboration, which Brecht obfuscated for many years by telling arrogant, self-serving lies; the playwright used to say that he had written all the best tunes of The Threepenny Opera and Mahagonny and that Weill, a “composer of atonal psychological operas,” had merely transcribed them. Subsequent investigations have shown that it was Brecht who relied quite often on the work of others—
> 
> **6. City of Nets: Berlin in the Twenties** (Location 3514)

---

> Brecht loved outlaws, thugs, men of no principles.
> 
> **6. City of Nets: Berlin in the Twenties** (Location 3541)

---

> “Mack the Knife.” This most famous of Weimar songs takes the form of a “murder ballad,” a catalog of killings. Macheath is revealed not merely as a high-living highwayman but as an apparent psychopath who kills as much for pleasure as for financial gain.
> 
> **6. City of Nets: Berlin in the Twenties** (Location 3555)

---

> Threepenny sits on the border between classical and popular genres, combining “hit” numbers with modernistic textures and socially critical themes.
> 
> **6. City of Nets: Berlin in the Twenties** (Location 3575)

---

> In the 1950s, “Mack the Knife” began a second life as an American pop standard, and new variations were rung on the tune. When Louis Armstrong sang it, he warmed up Brecht’s hard-bitten lyrics with the husky humanity of his voice, and jokingly added Lenya’s name to the list of Mackie’s victims:
> 
> **6. City of Nets: Berlin in the Twenties** (Location 3583)

---

> A particular arrangement of twelve notes is called a series or row. The idea is not to consider the row a theme in itself but to employ it as a kind of fund of notes, or, more precisely, of relationships among notes, or intervals.
> 
> **6. City of Nets: Berlin in the Twenties** (Location 3626)

---

> Nearly all of Schoenberg’s early twelve-tone works are couched in established forms, usually from the Baroque and Classical periods. Formal rules are observed, dance rhythms replicated, ideas clearly spelled out and rigorously developed. Schoenberg has almost entirely abandoned the mystical mind-set of his early atonal period, when he wished to dissolve form and leap into the unknown.
> 
> **6. City of Nets: Berlin in the Twenties** (Location 3635)

---

> Along the way, a peculiar thing happens: the tonal building blocks that Schoenberg formerly disavowed begin popping up on occasion. One may even find that rootless cosmopolitan, the diminished seventh: the Variations starts with one.
> 
> **6. City of Nets: Berlin in the Twenties** (Location 3638)

---

> There was a nationalistic thrust, too, to Schoenberg’s return to order; at a time when Russian, French, and American composers were seizing headlines with their Jazz Age antics, Schoenberg was reasserting the primacy of Austro-German composition, its ancient arts of counterpoint and thematic development.
> 
> **6. City of Nets: Berlin in the Twenties** (Location 3659)

---

> Curiously, even as Schoenberg vented against the popular styles of the day, he not so subtly assimilated them in his music. The Serenade, for example, originally had movements titled “Jo-Jo-Foxtrot,” “Film Dva,” and “Tenn Ski.”
> 
> **6. City of Nets: Berlin in the Twenties** (Location 3683)

---

> The Schoenberg-Weill dispute began in October 1927, when Weill wrote an article drawing a pointed contrast between those composers “who, filled with disdain for the public, work toward the solution of aesthetic problems as if behind closed doors” and those who “open up a connection with any kind of public.”
> 
> **6. City of Nets: Berlin in the Twenties** (Location 3705)

---

> German music entered a new period of sobriety. Many young composers abandoned notions of entertaining a mass public and instead began writing music of aggressively political character, in anticipation of a coming battle with the right.
> 
> **6. City of Nets: Berlin in the Twenties** (Location 3736)

---

> That a work conceived like Wozzeck’s apparitions in the field, a work satisfying Berg’s own standards, could please a first-night audience, was incomprehensible to him and struck him as an argument against the opera.”
> 
> **6. City of Nets: Berlin in the Twenties** (Location 3843)

---

> Prokofiev died on March 5, 1953, about fifty minutes before Stalin breathed his last.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 3984)

---

> Having long depended on the largesse of the Church, the upper classes, and the high bourgeoisie, composers suddenly found themselves, in the Jazz Age, without obvious means of support. Some fell to dreaming of a political knight in shining armor who would come to their aid.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 3995)

---

> As in Weimar, artists embraced Communism because it promised to cut the throat of a common enemy, the decadent bourgeoisie.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4023)

---

> Lunacharsky pleaded for multiple perspectives and freedom of expression—“ Let the worker hear and evaluate everything, the old and the new”— but he steadily lost ground as the twenties went on.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4036)

---

> Stalin liked to use the telephone, and had an unnerving habit of calling artists in the middle of the night. Sometimes, like a Roman emperor in an indulgent mood, he would grant his petitioners an extraordinary favor. Others would be told to expect a call that never came, and they would interpret the silence as an omen of disaster.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4045)

---

> The piece was initially titled To October, and later became the Second Symphony.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4088)

---

> The Third Symphony, subtitled “The First of May,” follows the same template, redeeming abstraction with bombast.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4093)

---

> It was after the premiere of The Nose— in concert form, in June 1929— that Shostakovich found himself first accused of “formalism.” The word was Soviet shorthand for any style that smacked too strongly of Western modernism.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4115)

---

> From the meeting emerged the concept of socialist realism, according to which Soviet artists would depict the people’s lives both realistically and heroically, as if from the standpoint of the socialist utopia to come.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4138)

---

> Seen from one angle, then, Lady Macbeth is nearly an opera in the service of genocide. In other ways, however, it is anything but a propaganda work.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4153)

---

> Many close to Shostakovich or favorable to his cause were disappearing. Elena Konstantinovskaya, the translator who had caused a separation in his marriage in 1934, was arrested and briefly imprisoned in 1935. Galina Serebryakova, who had observed Shostakovich at work on Lady Macbeth, was sent into the gulags the following year, not to return for almost two decades. Shostakovich’s brother-in-law, mother-in-law, sister, and uncle were all imprisoned at around this time. Maxim Gorky died mysteriously in June 1936. Bukharin’s name was mentioned many times during the August show trial— a sign that his days were numbered. Isaac Babel, who had advised that “Muddle Instead of Music” shouldn’t be taken seriously, found in 1937 that his books could no longer be published. He had three years to live, as did Meyerhold. Most ominous of all was the fate of Tukhachevsky. Despite the sterling work that he had done in liquidating the anti-Bolshevik opposition, Stalin saw him as a dangerous rival— too independent, too charismatic. He was arrested in May 1937, and in the torture chamber he confessed his part in a nonexistent conspiracy to overthrow Stalin, evidence of which Hitler’s SS helped to fabricate. When the text of the confession was retrieved decades later, there were bloodstains on several pages.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4243)

---

> The Mahler symphony that Shostakovich’s work most resembles is the Sixth— both in the militaristic thrust of its opening and in the drawnout anguish of its close.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4259)

---

> The change in style was dramatic. The Fifth followed an ordinary fourmovement pattern: Moderato, Allegretto, Largo, Allegro non troppo.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4290)

---

> Beethoven’s “hero” symphonies, the Eroica and the Fifth, tell stories of conflict and resolution, of protagonists overcoming obstacles to win victory.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4298)

---

> Shostakovich and Prokofiev, the two giants of Soviet music, never understood each other particularly well. They met only occasionally, and often traded criticisms in front of colleagues and in haphazard correspondence. Prokofiev would comment on Shostakovich’s supposed melodic deficiency, while Shostakovich would chide Prokofiev for his habit of farming out orchestration to colleagues.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4354)

---

> Where Shostakovich was cagey, Prokofiev was forthright, even blatant in his opinions—“ a kind of big baby who must tell the truth on all occasions,” said his friend Nicolas Nabokov.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4360)

---

> The better part of the years 1918 to 1922 was spent in America, where audiences applauded Prokofiev’s virtuosic piano playing but struggled to make sense of his compositions.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4394)

---

> Since socialist-realist ideology was demanding the same, Prokofiev concluded that the Soviet worldview magically coincided with his own. In fact, he had been carefully primed to think so. Stalin placed a priority on bringing illustrious cultural exiles back into the fold, and the project of seducing Prokofiev was supervised by the OGPU, as the secret police were known at the time.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4424)

---

> Prokofiev’s first “official” Soviet work, the dance epic Romeo and Juliet, showed him at his optimistic peak.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4436)

---

> What Prokofiev could never understand was that these difficulties had nothing to do with the notes he put on paper; they were the ritual of humiliation that every Soviet composer had to undergo.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4444)

---

> In contrast to Shostakovich, who dispatched his official duties as efficiently and soullessly as possible, Prokofiev worked painfully hard at such projects as the Cantata for the Twentieth Anniversary of October, Songs of Our Days, and Zdravitsa (Toast to Stalin).
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4447)

---

> This quintessentially Shostakovichian utterance exemplifies the composer’s penchant for talking through a mask of Soviet doublespeak. Indeed, he appears to be echoing, for comic effect, Stalin’s own wearyingly repetitive prose style; the threefold use of the word “joy” (radost’) is a typical Stalinist tic.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4500)

---

> Irony, in the standard definition, is saying something other than what one appears to be saying. To talk about musical irony, we first have to agree on what the music appears to be saying, and then we have to agree on what the music is really saying.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4509)

---

> As The New Yorker reported in a Talk of the Town item, the score was transferred to microfilm, put in a tin can, flown to Tehran, driven by car to Cairo, flown to South America, and finally flown to New York.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4524)

---

> Three members of the orchestra died of starvation before the premiere took place.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4532)

---

> I am not aiming for the naturalistic depiction of war, the depiction of the clatter of arms, the explosion of shells, and so on. I am trying to convey the image of war emotionally.”
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4539)

---

> Prokofiev was careful to end the opera not with Tolstoy’s meditations on man’s insignificance before the forces of history but with a rousing nationalist pageant.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4579)

---

> he dashed off a kind of anti-Ninth, an alternately satiric and melancholic fivemovement suite, which occasioned intense debate after its November 1945 premiere.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4631)

---

> forty-two works by “formalists”— including Shostakovich’s Sixth, Eighth, and Ninth symphonies, Prokofiev’s Sixth and Eighth sonatas, and Popov’s unlucky First Symphony— were banned.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4667)

---

> Shostakovich had reluctantly agreed to travel to the United States the following month as part of a Soviet cultural and scientific delegation, but he had trouble understanding how he could represent Soviet culture abroad when so many of his compositions were forbidden at home.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4712)

---

> The “other Shostakovich” was a gnomic, cryptic, secretly impassioned figure who spoke through chamber music (twelve string quartets from 1948 on), piano music (the epic cycle of Twenty-four Preludes and Fugues), and songs. The string quartet became his favorite medium: it gave him the freedom to write labyrinthine narratives full of blankly winding fugues, near-motionless funeral marches, wry displays of folkish jollity, off-kilter genre exercises, and stretches of deliberate blandness.
> 
> **7. The Art of Fear: Music in Stalin’s Russia** (Location 4731)

---

> The trouble was that Toscanini could not make classical music American. As the Times’s list of names suggested, the Maestro’s canon was focused on European composers and stopped short of the present, Sibelius having fallen silent. During his tenure with the New York Philharmonic, from 1926 to 1936, Toscanini had ignored American music week after week, conducting only six native works in ten years.
> 
> **8. Music for All: Music in FDR’s America** (Location 4842)

---

> Copland showed an uncommon flair for the lowlier arts of organization and publicity.
> 
> **8. Music for All: Music in FDR’s America** (Location 4901)

---

> According to polls, one quarter of the American people wanted a socialist government and another quarter had an “open mind” about the prospect.
> 
> **8. Music for All: Music in FDR’s America** (Location 4938)

---

> Many in the Harlem Renaissance intelligentsia, Duke Ellington included, committed themselves to Communism to a greater or lesser degree.
> 
> **8. Music for All: Music in FDR’s America** (Location 4941)

---

> After Shostakovich was denounced in 1936, the New Masses reporter Joshua Kunitz quoted the soothing words of a young Communist: “Don’t worry. There’ll be no blood, no prisons, no ruin and no darkness. The fellows who deserve it will be criticized— that’s all.” (Kunitz retailed these rationalizations in a lecture to New Yorkers that May: “The Truth About Shostakovich,” followed by refreshments and dancing.)
> 
> **8. Music for All: Music in FDR’s America** (Location 4953)

---

> The New Deal had a mighty impact on the arts for the simple reason that it had a mighty wad of money to spend.
> 
> **8. Music for All: Music in FDR’s America** (Location 5084)

---

> The rapid advance of Broadway composers set in relief the fact that their counterparts in the classical world were writing relatively few operas or music-theater pieces, preferring to concentrate on orchestral writing. The Broadway musical was splitting off as a separate genre of American music, with its own language, its own styles of singing, its own schools and subgenres. The distinction between “opera” and “Broadway” was hardening into fact-a missed opportunity for the populist generation.
> 
> **8. Music for All: Music in FDR’s America** (Location 5257)

---

> Hollywood may have been hazardous territory for composers, but they at least felt wanted there, as they never did in American concert halls.
> 
> **8. Music for All: Music in FDR’s America** (Location 5314)

---

> Like his idol Sergei Eisenstein, Welles possessed exceptional musical instincts. An opera maven in his youth, he understood how music could amplify stage action, draw out hidden moods and emotions, even expose a lie. Kane’s opening two-and-a-half-minute sequence, showing the protagonist’s last moments and death, is propelled entirely by Herrmann’s score, the only nonmusical sound being Kane’s whisper of “Rosebud!”
> 
> **8. Music for All: Music in FDR’s America** (Location 5356)

---

> The most surreal thing about the Los Angeles music scene was that Schoenberg and Stravinsky, the twin giants of modernism, now lived just eight miles apart, each on a side street north of Sunset Boulevard.
> 
> **8. Music for All: Music in FDR’s America** (Location 5385)

---

> The twelve-tone method finally reached the silver screen by way of Scott Bradley’s inventive scores for Tom and Jerry cartoons in the forties, notably Puttin’ on the Dog and The Cat That Hated People.
> 
> **8. Music for All: Music in FDR’s America** (Location 5426)

---

> The Symphony in Three Movements became another peak in a mountain range of an output. It is unusual among Stravinsky’s works in that it follows a quasi-Romantic narrative plan, one of struggle and resolution.
> 
> **8. Music for All: Music in FDR’s America** (Location 5467)

---

> Bartók, like Hindemith, apparently believed that Shostakovich was indulging in oversimplified writing for cheap effect. Neither composer seemed to realize that the first movement of the Leningrad was a complicated act of parody, or that Shostakovich had little to gain, financial or otherwise, from American success.
> 
> **8. Music for All: Music in FDR’s America** (Location 5487)

---

> “Thank God,” Richard Strauss said after Hitler came to power, “finally a Reich Chancellor who is interested in art!”
> 
> **9. Death Fugue: Music in Hitler’s Germany** (Location 5574)

---

> Precisely because of its inarticulate nature, it is all too easily imprinted with ideologies and deployed to political ends.
> 
> **9. Death Fugue: Music in Hitler’s Germany** (Location 5581)

---

> The melding of German music with reactionary politics goes back to Wagner. The composer’s 1850 pamphlet Das Judentum in der Musik, or Jewry in Music, decried the “Jewification” of German music and demanded that the Jews undergo Untergang and Selbstvernichtung— destruction and self-annihilation.
> 
> **9. Death Fugue: Music in Hitler’s Germany** (Location 5604)

---

> The protagonist of Alfred Döblin’s novel Berlin Alexanderplatz, Franz Biberkopf, is a stubborn, tough-minded, self-reliant man who finds himself transformed into a Nazi stooge. In much the same way, Strauss’s philosophy of self—“ The laws of my mind determine my life,” to quote Guntram— left him defenseless before Hitler’s seductions.
> 
> **9. Death Fugue: Music in Hitler’s Germany** (Location 5661)

---

> From the start, classical music blared in the background of Nazi life. Party rallies were so immaculately choreographed to Beethoven, Bruckner, and Wagner that the music seemed to have been written in support of the pageantry;
> 
> **9. Death Fugue: Music in Hitler’s Germany** (Location 5737)

---

> In contrast to Stalin, Hitler turned up his nose at sycophantic propaganda. In 1935, he directed that no more music should be dedicated to him, and three years later he complained that a group of works commissioned for the Reich Party Day paled in comparison to Bruckner.
> 
> **9. Death Fugue: Music in Hitler’s Germany** (Location 5746)

---

> Herbert von Karajan, for example, may have joined the Party early on, but Hitler disliked him. Karajan’s habit of conducting from memory was “arrogant,” Hitler thought— Furtwängler would never do such a thing.
> 
> **9. Death Fugue: Music in Hitler’s Germany** (Location 5759)

---

> Bruckner apparently represented for Hitler the revenge of the “little” man on an uncomprehending world.
> 
> **9. Death Fugue: Music in Hitler’s Germany** (Location 5767)

---

> Atonality and other modernist trends suffered an interesting fate in Nazi Germany. When an exhibition of Degenerate Music opened in Düsseldorf in May 1938, its organizer, Hans Severus Ziegler, decreed that atonal composition was a “product of the Jewish spirit” of Schoenberg. Yet, as Michael Kater points out, a committee led by Strauss had declared that “the Reich Music Chamber cannot forbid works of an atonal character, for it is up to the audience to judge such compositions.” In the end, Ziegler’s exhibition was poorly received, even in official circles. There was some embarrassment over the fact that Stravinsky had been included in the gallery of degenerates, and the German Foreign Affairs Office issued a quasi-apologetic explanation.
> 
> **9. Death Fugue: Music in Hitler’s Germany** (Location 5852)

---

> Although Schoenberg opposed the Nazis unstintingly, he was hardly free from authoritarian impulses, as his attack on the egalitarianism of the Weimar Republic shows. In 1931, as Germany was swinging politically rightward, Schoenberg described his music as “a living example of an art able most effectively to oppose Latin and Slav hopes of hegemony and derived through and through from the traditions of German music.”
> 
> **9. Death Fugue: Music in Hitler’s Germany** (Location 5872)

---

> Adorno advised Berg to advertise his pure Aryan origins to the Reich Music Chamber, and also to distance himself from any notion of Jewish solidarity, “about which one can have so few illusions.”
> 
> **9. Death Fugue: Music in Hitler’s Germany** (Location 5885)

---

> No composer more painfully exhibited the moral collapse of German art than Richard Strauss, who served as president of the Reich Music Chamber from 1933 to 1935.
> 
> **9. Death Fugue: Music in Hitler’s Germany** (Location 5891)

---

> The record is dismaying. Strauss appeared at Nazi functions and signed a meretricious denunciation of Thomas Mann. When the anti-fascist Toscanini canceled his Bayreuth engagements in 1933, Strauss replaced him, and in the same year he stepped in as a lastminute replacement for the racially unacceptable Bruno Walter in Berlin.
> 
> **9. Death Fugue: Music in Hitler’s Germany** (Location 5895)

---

> The Holocaust accomplished the murder not only of millions of individuals but of entire schools of composition. The energetically middle-of-the-road, eclectic style that had prospered in Berlin, Vienna, and Prague between the wars was effectively wiped out.
> 
> **9. Death Fugue: Music in Hitler’s Germany** (Location 6060)

---

> Psychological warfare meant the pursuit of military ends by nonmilitary means, and in the case of music it meant the promotion of jazz,
> 
> **German Music, 1945–1949** (Location 6237)

---

> “German musical life must be influenced by positive rather than by negative means, i.e., by encouraging the music which we think beneficial and crowding out that which we think dangerous.”
> 
> **German Music, 1945–1949** (Location 6268)

---

> The extroverted, jazz-tinged music of the Weimar era, as embodied in The Threepenny Opera, had been condemned by the Nazis on political and racial grounds.
> 
> **German Music, 1945–1949** (Location 6285)

---

> The Americans placed highest confidence in musical progressives who lacked either Nazi or Communist affiliations.
> 
> **German Music, 1945–1949** (Location 6293)

---

> So there was, on the one hand, a classical establishment that eluded denazification, and, on the other, an avant-garde establishment that opposed itself so determinedly to the aesthetics of the Nazi period that it came close to disavowing the idea of the public concert. The middlebrow ideal of a popular modernism withered away, caught between extremes of revolution and reaction.
> 
> **German Music, 1945–1949** (Location 6345)

---

> The process of politicization was already under way in the twenties, as composers competed to stay ahead of changing trends and accused one another of complicity in regressive tendencies. In the thirties and forties, the entire Romantic tradition was effectively annexed by the totalitarian state. But nothing could compare to what happened when the Second World War ended and the Cold War began. Music exploded into a pandemonium of revolutions, counterrevolutions, theories, polemics, alliances, and party splits.
> 
> **the Avant-Garde of the Fifties** (Location 6389)

---

> When Stravinsky shocked his colleagues by giving up neoclassicism in favor of twelve-tone composition, Leonard Bernstein said that “it was like the defection of a general to the enemy camp, taking all his faithful regiments with him.”
> 
> **the Avant-Garde of the Fifties** (Location 6401)

---

> The most formidable proponent of sweeping nothing under the rug was Theodor Adorno—
> 
> **the Avant-Garde of the Fifties** (Location 6408)

---

> the very act of preserving tonality in the modern era, Adorno proposed, betrayed symptoms of the Fascist personality.
> 
> **the Avant-Garde of the Fifties** (Location 6412)

---

> Schoenberg, having been denounced by Hitler and Stalin alike, carried no taint from totalitarianism either on the left or on the right, or so it seemed.
> 
> **the Avant-Garde of the Fifties** (Location 6424)

---

> “The second half of this century will spoil by overestimation, all the good of me that the first half, by underestimation, has left intact.”
> 
> **the Avant-Garde of the Fifties** (Location 6437)

---

> The avant-garde era may be said to have begun a few years early, on a cold winter night in 1941, when Olivier Messiaen’s Quartet for the End of Time had its first performance, at the prisoner-of-war camp Stalag VIII A.
> 
> **the Avant-Garde of the Fifties** (Location 6444)

---

> Pierre Boulez went on to become the perfect avatar of the postwar avant-garde, the one who permitted “no compromise, no concession, no half-way, no consideration of values,” to quote Mann’s story “At the Prophet’s.”
> 
> **the Avant-Garde of the Fifties** (Location 6474)

---

> When Schoenberg died in the summer of 1951, Boulez penned a breathtakingly pitiless obituary. “The Schoenberg ‘case’ is irritating,” he wrote. The old man had revolutionized the art of harmony while leaving rhythm, structure, and form untouched. He had displayed “the most ostentatious and obsolete romanticism.” It was time to “neutralize the setback,” to rectify the situation. “Therefore,” Boulez concluded, “I do not hesitate to write, not out of any desire to provoke a stupid scandal, but equally without bashful hypocrisy and pointless melancholy: SCHOENBERG IS DEAD.”
> 
> **the Avant-Garde of the Fifties** (Location 6521)

---

> A particular note is always assigned the same values. Thus, the high E-flat is always a thirty-second note, is always played ppp, and is (almost) always slurred.
> 
> **the Avant-Garde of the Fifties** (Location 6531)

---

> The divide that opened up between Cage and Boulez indicated sociological differences between the avant-garde cultures of America and Europe. Cage’s audience was essentially a bohemian one, including like-minded artists, Greenwich Village eccentrics, and outsiders of every description. Boulez’s audience, on the other hand, overlapped with traditional circles of connoisseurship and art appreciation.
> 
> **the Avant-Garde of the Fifties** (Location 6659)

---

> In this same period, New Deal-style art for the masses began to acquire a dubious reputation. Excesses of populism in the “serious” arts counted as evidence of a politically compromised mind. Modernists, on the other hand, garnered admiring buzzwords such as “unyielding” and “uncompromising,” their contrary stance imbued with political as well as aesthetic implications.
> 
> **the Avant-Garde of the Fifties** (Location 6690)

---

> In a March 1948 essay Greenberg announced that with the rise of Pollock and others “the main premises of Western art have at last migrated to the United States, along with the center of gravity of industrial production and political power.”
> 
> **the Avant-Garde of the Fifties** (Location 6695)

---

> It was not in Shostakovich’s nature to jump through the window. He read the speeches that were placed in front of him; he answered questions in accordance with instructions that were whispered in his ear. On the final night of the conference, he played a piano arrangement of the Scherzo of his Fifth Symphony at Madison Square Garden before an audience of eighteen thousand while two thousand picketers protested outside. All the while, Shostakovich maintained an indecipherable facade of nervous preoccupation. When Morton Gould sidled up to him in the hope of hearing some candid confession, Shostakovich muttered, “It’s hot in here.”
> 
> **the Avant-Garde of the Fifties** (Location 6725)

---

> The speech attacked Stravinsky for betraying his native Russia and joining the ranks of the reactionary modernists: “His beginnings were promising, but … his moral barrenness reveals itself in his openly nihilistic writings, proclaiming the meaninglessness and absence of content in his creations. Stravinsky has no fear of that gaping abyss which separates him from the spiritual life of the people.”
> 
> **the Avant-Garde of the Fifties** (Location 6748)

---

> Nabokov kept his gaze fixed on Shostakovich. The “culture generalissimo,” as Stravinsky called him, had for many years been nursing a hatred of his Soviet counterpart.
> 
> **the Avant-Garde of the Fifties** (Location 6766)

---

> The knowledge that Shostakovich lacked freedom of speech did not prevent Nabokov from forcing him to speak. The émigré rose from his seat to ask whether Shostakovich really endorsed Zhdanov’s condemnation of composers such as Stravinsky, Schoenberg, and Hindemith. Shostakovich had no choice but to say, “I fully agree with the statements made in Pravda.”
> 
> **the Avant-Garde of the Fifties** (Location 6775)

---

> Igor Stravinsky, who had long dismissed twelve-tone composition as so much Teutonic obscurantism, watched and brooded as Schoenberg’s method spread across Europe and America in the late forties and early fifties.
> 
> **the Avant-Garde of the Fifties** (Location 6891)

---

> Commentators have periodically proposed that the Stravinsky of the late forties had run creatively aground, that twelve-tone writing saved him from obsolescence. In fact, between 1945 and 1951, the composer was at the very height of his abilities.
> 
> **the Avant-Garde of the Fifties** (Location 6901)

---

> When Schoenberg died, Stravinsky’s attitude toward his old rival changed almost overnight.
> 
> **the Avant-Garde of the Fifties** (Location 6914)

---

> Nabokov was trying to counter the spread of Communism in Western Europe by producing model festivals of democratic culture.
> 
> **the Avant-Garde of the Fifties** (Location 6938)

---

> Once more the creator of the Rite was being booed on the avenue Montaigne, only now, instead of being too radical, he was considered not radical enough.
> 
> **the Avant-Garde of the Fifties** (Location 6956)

---

> Yet as the years went by Stravinsky found it increasingly difficult to ignore Boulez’s ill-concealed contempt for everything he had written after Les Noces, whether neoclassical or twelve-tone.
> 
> **the Avant-Garde of the Fifties** (Location 6981)

---

> Once the avatar of a primitivist-modernist Russia, Stravinsky ended up as the perfect cosmopolitan, everywhere and nowhere at home.
> 
> **the Avant-Garde of the Fifties** (Location 7030)

---

> By the time Stravinsky began writing twelve-tone music, most of the younger composers considered the method out of date. Yesterday’s revolt was today’s status quo: music had entered a state of perpetual revolution.
> 
> **the Avant-Garde of the Fifties** (Location 7037)

---

> The former Fascist nations could thus demonstrate how far they had evolved from the days when Schoenberg’s work had been labeled “degenerate music.”
> 
> **the Avant-Garde of the Fifties** (Location 7045)

---

> Composers dressed like scientists, wearing thick black glasses and short-sleeve button-down shirts with pens in the pocket.
> 
> **the Avant-Garde of the Fifties** (Location 7050)

---

> The advent of a pseudoscientific mentality is evident in the titles of works that were performed at Darmstadt from 1946 on.
> 
> **the Avant-Garde of the Fifties** (Location 7053)

---

> The watchword at Darmstadt, as at Nabokov’s festivals, was “freedom.” After centuries of subservience to the Church, the aristocracy, the bourgeoisie, and the mass public, composers could finally do as they pleased— even embrace styles that took away freedom of choice.
> 
> **the Avant-Garde of the Fifties** (Location 7059)

---

> As Adorno decreed, the job of a composer was to write music that would repel, shock, and be the vehicle for ‘unmitigated cruelty.’”
> 
> **the Avant-Garde of the Fifties** (Location 7070)

---

> By common consent, Stockhausen was the crown prince of the new-music kingdom. No composer was more tireless in inventing or appropriating new ideas, more ambitious in articulating the avant-garde’s historical and spiritual mission, more adept at assembling the latest sounds into jaw-dropping spectacles.
> 
> **the Avant-Garde of the Fifties** (Location 7076)

---

> Behind Darmstadt’s hypermodern facade lurked some thoroughly traditional twentieth-century or even nineteenth-century obsessions: the revolutionary impulse, the urge to overthrow the bourgeois order, the age-old longing for sublimity and transcendence.
> 
> **the Avant-Garde of the Fifties** (Location 7126)

---

> In the end, the notion of musical progress proved to be contingent and subjective, its definition changing with the seasons. The philosophy of modern music was unmasked as the rhetoric of taste. All the same, Boulez adroitly maintained the illusion of being out in front— the signature of a master politician.
> 
> **the Avant-Garde of the Fifties** (Location 7178)

---

> New music played a very limited role in the Cold War arts bonanza. All the same, many American composers found themselves in a relatively happy situation. Money was plentiful, whether in the form of grants, prizes, commissions, or faculty salaries.
> 
> **the Avant-Garde of the Fifties** (Location 7207)

---

> Of the multifarious strands of American music, one in particular began to prosper in the university environment: composition informed by twelve-tone technique.
> 
> **the Avant-Garde of the Fifties** (Location 7213)

---

> Milton Babbitt, the emblematic Cold War composer, produced music so byzantine in construction that one practically needed a security clearance to understand it.
> 
> **the Avant-Garde of the Fifties** (Location 7224)

---

> These composers thrived on campus because of the undeniable intellectual solidity of their project: behind the modernity of the language was a traditional emphasis on the arts of variation and counterpoint.
> 
> **the Avant-Garde of the Fifties** (Location 7296)

---

> In 1958, Babbitt enlivened the pages of High Fidelity magazine with an essay notoriously headlined “Who Cares If You Listen?”— the original title was “The Composer as Specialist”— that sounded the signal for strategic withdrawal:
> 
> **the Avant-Garde of the Fifties** (Location 7302)

---

> Bernstein lived to a relatively grand old age, an aura of disappointment settling around him. Experts agreed that he had frittered away his gift amid glitzy conducting dates, media appearances, and “radical chic” parties at his apartment in Manhattan.
> 
> **the Avant-Garde of the Fifties** (Location 7317)

---

> Bernstein’s most dazzling transmutation of tradition took place in “Somewhere,” from West Side Story, where the main theme of the slow movement of Beethoven’s Emperor Concerto becomes the love song of a white boy in love with a Puerto Rican girl in the gang-ridden neighborhoods of Manhattan’s West Side.
> 
> **the Avant-Garde of the Fifties** (Location 7335)

---

> Britten provocatively compared the regimentation of culture in totalitarian states to the self-imposed regimentation of the avant-garde in democratic countries.
> 
> **12. “Grimes! Grimes!”: The Passion of Benjamin Britten** (Location 7413)

---

> Everything about Britten’s style— his deliberate parochialism, his tonal orientation, his preference for classical forms— went against the grain of the postwar era.
> 
> **12. “Grimes! Grimes!”: The Passion of Benjamin Britten** (Location 7415)

---

> Intellectual precocity often goes hand in hand with emotional immaturity.
> 
> **12. “Grimes! Grimes!”: The Passion of Benjamin Britten** (Location 7464)

---

> Shostakovich met Britten only one week after he had experienced yet another in his seemingly endless series of political humiliations.
> 
> **12. “Grimes! Grimes!”: The Passion of Benjamin Britten** (Location 7826)

---

> Shostakovich had sworn to friends that he would never join an organization that used terror to carry out its aims. He now gave conflicting accounts of the train of events that led him to go back on this resolution, one being that he was drunk. “They’ve been pursuing me for years, hunting me down,” he told Glikman, tears streaming down his face. Lev Lebedinsky claimed to have heard him say such things as “I am scared to death of them,” “I’m a wretched alcoholic,” and “I’ve been a whore, I am and always will be a whore.”
> 
> **12. “Grimes! Grimes!”: The Passion of Benjamin Britten** (Location 7828)

---

> They were aghast at Shostakovich’s gesture of conformity. “Our disappointment knew no bounds,” said the young composer Sofia Gubaidulina. “We were left wondering why, just at the time when the political situation had relaxed somewhat, when at last it seemed possible to preserve one’s integrity, Shostakovich fell victim to official flattery.”
> 
> **12. “Grimes! Grimes!”: The Passion of Benjamin Britten** (Location 7834)

---

> This latest crisis prompted Shostakovich to write his scathing, self-punishing Eighth Quartet, one of the most extraordinary autobiographical pieces in musical history.
> 
> **12. “Grimes! Grimes!”: The Passion of Benjamin Britten** (Location 7837)

---

> Shostakovich’s boldest political statement of the Khrushchev Thaw came in the Thirteenth Symphony, based on anti-Stalinist poems by Yevgeny Yevtushenko. The first movement, “Babi Yar,” is ostensibly a lament for Jewish suffering under the Nazis, but it also remembers life under Stalin.
> 
> **12. “Grimes! Grimes!”: The Passion of Benjamin Britten** (Location 7859)

---

> Leverkühn’s aesthetic of denial and negation captures in somewhat exaggerated form one of the dominant strains of twentieth-century music.
> 
> **the Avant-Garde of the Sixties** (Location 7973)

---

> After the war, composers took up what might be called catastrophe style with a vengeance, history having justified their instinctive attraction to the dreadful and the dire.
> 
> **the Avant-Garde of the Sixties** (Location 7981)

---

> Georg Lukács, in a critique of Adorno, remarked that the philosopher resided in a “Grand Hotel Abyss,” from whose aestheticized security he gazed on the agony of man as if it were an Alpine vista.
> 
> **the Avant-Garde of the Sixties** (Location 7989)

---

> As the fearful fifties gave way to the antic sixties, many European composers looked for a way out of the labyrinth of progress.
> 
> **the Avant-Garde of the Sixties** (Location 7993)

---

> While Messiaen took on a markedly more aggressive, even at times abrasive voice in the Quartet for the End of Time, he did not lose his flair for the simple, astounding gesture.
> 
> **the Avant-Garde of the Sixties** (Location 8050)

---

> Messiaen’s early sacred pieces, the Quartet included, are like Christian surrealism. They have something in common with those later paintings of Salvador Dalí in which Christ floats above the earth like an astronaut or superhero.
> 
> **the Avant-Garde of the Sixties** (Location 8063)

---

> Messiaen served as a mentor to many of the chief innovators of the postwar era. Boulez, Xenakis, and Stockhausen all studied with him at one time or another.
> 
> **the Avant-Garde of the Sixties** (Location 8096)

---

> For the remainder of the fifties, Messiaen modeled nearly all of his instrumental lines on the contours of bird melodies, and they would reign over his music to the end.
> 
> **the Avant-Garde of the Sixties** (Location 8112)

---

> Messiaen, like his teacher Dukas, identified certain harmonies with certain colors; E major is red, and the final chords evoke not only the red-orange rock formations of Bryce Canyon but also the geology of the book of Revelation— the sardius, topaz, and amethyst stones embedded in the foundation of the celestial Jerusalem.
> 
> **the Avant-Garde of the Sixties** (Location 8175)

---

> a second wave of avant-gardists rejected the previous generation’s obsession with purity and abstraction. Chance, indeterminacy, graphic notation, and other forms of unconventionally notated music enjoyed a European vogue.
> 
> **the Avant-Garde of the Sixties** (Location 8189)

---

> Cage’s Darmstadt lectures had episodes of coherence, but chance operations progressively took over, and by the third lecture he was lighting cigarettes at intervals specified by the I Ching.
> 
> **the Avant-Garde of the Sixties** (Location 8200)

---

> By the early sixties, the fascination with behind-the-scenes process— whether twelve-tone or chance-produced— had given way to a new appreciation of surfaces. The most-talked-about works of the period resembled a bubbling flow of timbres and textures, a sonic stream of consciousness.
> 
> **the Avant-Garde of the Sixties** (Location 8233)

---

> When Penderecki produced a floridly experimental piece called 8’37”— an affair of shrieking cluster chords, sputtering streams of pizzicato, siren-like glissandos, and other Xenakis-like sounds— officialdom took a favorable view only when someone suggested that the work be retitled Threnody for the Victims of Hiroshima. It went on to have a successful career in the West.
> 
> **the Avant-Garde of the Sixties** (Location 8253)

---

> In the central scene of Doctor Faustus, Leverkühn conducts a hallucinatory dialogue with the devil, who keeps changing guises and at one point assumes the form of “an intellectualist, who writes of art, of music, for vulgar newspapers, a theorist and critic, who is himself a composer, in so far as thinking allows”— Mann’s wry portrait of Theodor Adorno. The critic-devil hands down judgments on the state of contemporary music, eliminating all possibilities except the Schoenbergian path, the one that follows “an implacable imperative of density.”
> 
> **the Avant-Garde of the Sixties** (Location 8277)

---

> in the sixties games of parody and play caught on everywhere.
> 
> **the Avant-Garde of the Sixties** (Location 8289)

---

> When you are accepted in a club, without willing or without noticing you take over certain habits of what is in and what is out. Tonality was definitely out. To write melodies, even non-tonal melodies, was absolutely taboo. Periodic rhythm, pulsation, was taboo, not possible. Music has to be a priori … It worked when it was new, but it became stale. Now there is no taboo; everything is allowed. But one cannot simply go back to tonality, it’s not the way. We must find a way of neither going back nor continuing the avant-garde. I am in a prison: one wall is the avant-garde, the other wall is the past, and I want to escape.
> 
> **the Avant-Garde of the Sixties** (Location 8351)

---

> Calculating the likelihood of his being either killed in action, shot by the SS, or sent to the camps, Ligeti deserted from the front line. He immediately fell into the hands of Soviet troops, but once again managed to slip away. After a long walk home, he found that the Russians were now in control and that strangers were living in his parents’ house. When the war ended, he learned of his family’s fate: his father had been killed in BergenBelsen, his brother in Mauthausen, and his aunt and uncle in Auschwitz. His mother somehow survived.
> 
> **the Avant-Garde of the Sixties** (Location 8364)

---

> an American friend wrote to Ligeti with the news that the film director Stanley Kubrick had released a science-fiction epic titled 2001: A Space Odyssey, in which no fewer than four Ligeti scores— Requiem, Lux aeterna, Atmosphères, and Aventures— were heard. Although the director had not asked permission, and paid a fee only after a protracted legal squabble, Ligeti expressed admiration for Kubrick’s achievement.
> 
> **the Avant-Garde of the Sixties** (Location 8421)

---

> Among other things, the film neatly brackets the entire arc of twentieth-century musical history. It begins with Strauss’s Thus Spake Zarathustra, the music of nature’s original majesty. In the final section, the movie is subsumed into Ligeti’s alternate universe, spiraling through the outer limits of expression before returning to the point of origin. As the august Zarathustra chords sound again at the end, the cycle is ready to begin anew.
> 
> **the Avant-Garde of the Sixties** (Location 8426)

---

> several younger Americans— Terry Riley, Steve Reich, and Philip Glass— made a different kind of breakthrough. They simplified their harmonic language and rediscovered the pleasure of a steady pulse, devising a modern tonality that had nothing nostalgic about it.
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 8512)

---

> Riley, Reich, and Glass came to be called minimalists, although they are better understood as the continuation of a circuitous, difficult-to-name development in American music that dated back to the early years of the century, and more often than not took root on the West Coast.
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 8515)

---

> Minimalist influence radiated outward in the eighties and nineties, to the point where you could walk into any hip boutique or hotel lounge and sooner or later hear some distant, burbling cousin of Reich’s Music for 18 Musicians.
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 8528)

---

> During the two-decade stretch from 1945 to 1965, when the minimalist composers were growing from childhood to maturity, American popular music exploded with creative energy. Jazz, blues, country, and gospel evolved into rhythm and blues, rock ‘n’ roll, soul, and funk.
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 8536)

---

> The history of minimalism can’t be written without a cursory look at postwar jazz.
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 8546)

---

> It was at the end of the Second World War that many young jazz players began to think of themselves as “serious musicians,”
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 8547)

---

> “We had some fundamental background training in European harmony and music theory superimposed on our own knowledge from Afro-American musical tradition,” Gillespie wrote. “We invented our own way of getting from one place to the next.”
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 8552)

---

> Miles Davis released Kind of Blue, which put the brakes on bop’s forward drive. “So What,” the nine-minute opening track, is a proto-minimalist piece, defined by the dreamlike slowness of the harmonic rhythm. As the melodies drift by and change color, the underlying harmony stays fixed on a D-minor seventh chord, with periodic sidesteps into E-flat minor.
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 8557)

---

> Jazz had entered its high-modern era, and assumed a modernist contempt for convention.
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 8563)

---

> Miles Davis, in performance, turned his back to the crowd in Schoenbergian fashion.
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 8565)

---

> He liked the idea that Coltrane could walk out with a saxophone, play freewheeling improvisations on just one or two harmonies, and then disappear into the night. “The music just comes out,” Reich later said. “There’s no argument. There it is. This presented me with a human choice, almost an ethical, moral choice.”
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 8574)

---

> instead of begging for assistance from patrons or the WPA bureaucracy, he dropped out of civilization entirely, and became a hobo. For several years he crisscrossed the country, riding trains, doing manual labor, sleeping in shelters or in the wild, contracting syphilis, working occasionally as a proofreader, and, all the while, rethinking every parameter of music.
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 8633)

---

> he scandalized a crowd at Black Mountain College by saying that Beethoven had misled generations of composers by structuring music in goal-oriented harmonic narratives instead of letting it unfold moment by moment.
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 8667)

---

> In the late sixties and early seventies, twelve-tone composers were reaching the height of their influence. By some accounts, they effectively took control of university composition departments across the country.
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 8775)

---

> No matter who was running the show, young composers with tonal yearnings found little happiness in academia, as colorful testimonials from composers and musicians in Michael Broyles’s book Mavericks and Other Traditions in American Music suggest.
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 8779)

---

> Gann lumps both “modernists” and “New Romantics” together in the “uptown” category, named for the Upper West Side of New York City, home of Lincoln Center, the Juilliard School, Carnegie Hall, Columbia University, and other richly endowed institutions. Downtown composers are those who, in Harry Partch’s words, look for “a way outside”— anti-European, anti-symphonic, anti-operatic. They descend from the free spirits who had long gone their own way on the West Coast. In New York such composers have tended to congregate in loft spaces, art galleries, and rock clubs below Fourteenth Street.
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 8799)

---

> Michael Nyman, in his book Experimental Music, dubbed minimalism a subspecies of “process” music, classifying it alongside the chance processes of Cage, the “people processes” of Frederic Rzewski (players going through their parts at their own speeds), and the electronic processes of Lucier and Ashley. But minimalism was a different kind of process from the start.
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 8974)

---

> This philosophy differs starkly from the thinking inherent in Boulez’s total serialism and Cage’s I Ching pieces, where process works behind the scenes, like a spy network employing front organizations.
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 8995)

---

> In the last years of the twentieth century, minimalism acquired a degree of popularity with mainstream audiences, saturating American music with its influence. But in the early years it caused a fair amount of distress.
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 9013)

---

> The European avant-garde did nothing for Glass. He later called it “a wasteland, dominated by these maniacs, these creeps, who were trying to make everyone write this crazy creepy music.”
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 9035)

---

> Glass introduced constant rhythmic change, adding or subtracting notes in the style of Indian music.
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 9042)

---

> Like Reich, Glass made his living outside academia, driving taxis and doing odd jobs.
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 9044)

---

> Glass also worked as a plumber, and one day installed a dishwasher in the apartment of the art critic Robert Hughes, who could not understand why SoHo’s composer laureate was crawling around the floor of his kitchen.
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 9046)

---

> Downtown music had entered a phase that might be called grand minimalism. Large-scale structures and modulatory schemes ascended toward moments of transcendence. Perhaps Beethoven wasn’t so wrong after all.
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 9077)

---

> In the seventies the downtown Manhattan scene reached an apex of cool. Composers from around the country converged on the city to take part in it. Loft apartments were cheap, alternative performance spaces imposed no creative restrictions, audiences sat through the most far-out occurrences with an attitude of jaded calm.
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 9095)

---

> Minimalism is the story not so much of a single sound as of a chain of connections. Schoenberg invented the twelve-tone row; Webern found a secret stillness in its patterns; Cage and Feldman abandoned the row and accentuated the stillness; Young slowed down the row and rendered it hypnotic; Riley pulled the long tones toward tonality; Reich systematized the process and gave it depth of field; Glass gave it motorized momentum.
> 
> **14. Beethoven Was Wrong: Bop, Rock, and the Minimalists** (Location 9109)

---

> One way to describe his work is to say that it sounds like Highway 1. It is a cut-up paradise, a stream of familiar sounds arranged in unfamiliar ways.
> 
> **15. Sunken Cathedrals: Music at Century’s End** (Location 9189)

---

> This has been a book about the fate of composition in the twentieth century. The temptation is strong to see the overall trajectory as one of steep decline. From 1900 to 2000, the art experienced what can only be described as a fall from a great height.
> 
> **15. Sunken Cathedrals: Music at Century’s End** (Location 9210)

---

> To the cynical onlooker, orchestras and opera houses are stuck in a museum culture, playing to a dwindling cohort of aging subscribers and would-be elitists who take satisfaction from technically expert if soulless renditions of Hitler’s favorite works.
> 
> **15. Sunken Cathedrals: Music at Century’s End** (Location 9219)

---

> Seen from a more sympathetic angle, the picture is quite different.Classical music is reaching far larger audiences than it has at any time in history.
> 
> **15. Sunken Cathedrals: Music at Century’s End** (Location 9223)

---

> Living composers such as Adams, Glass, Reich, and Arvo Pärt have acquired a semblance of a mass following.
> 
> **15. Sunken Cathedrals: Music at Century’s End** (Location 9229)

---

> There is little hope of giving a tidy account of composition in the second fin de siècle.
> 
> **15. Sunken Cathedrals: Music at Century’s End** (Location 9234)

---

> In retrospect, modernism, in the sense of a unified vanguard, never existed. The twentieth century was always a time of “many streams,” a “delta,” in the wise words of John Cage.
> 
> **15. Sunken Cathedrals: Music at Century’s End** (Location 9238)

---

> The majority make a living by teaching composition, and their students usually become teachers themselves.
> 
> **15. Sunken Cathedrals: Music at Century’s End** (Location 9244)

---

> For now, the art is like the “sunken cathedral” that Debussy depicts in his Preludes for Piano— a city that chants beneath the waves.
> 
> **15. Sunken Cathedrals: Music at Century’s End** (Location 9251)

---

> When Mao Zedong and the Communists took power in 1949, composers found themselves in a recognizable predicament. Like Hitler and Stalin, Mao fancied himself a patron of the arts, and he meddled incessantly in the cultural sphere, zigzagging between liberalization and repression.
> 
> **15. Sunken Cathedrals: Music at Century’s End** (Location 9281)

---

> To be “classical,” in this sense, is to protect tradition from the ravages of passing time, to perpetuate the musical past.
> 
> **15. Sunken Cathedrals: Music at Century’s End** (Location 9313)

---

> To track the disparate activities of downtown composers, Kyle Gann has coined the term “postminimalism.” He describes it as a tonal, steady-pulsing kind of music that avoids defining itself through a controlling process,
> 
> **15. Sunken Cathedrals: Music at Century’s End** (Location 9341)

---

> Downtown and midtown composers are alike in rejecting the prophet-in-the-wilderness, who-cares-if-you-listen mentality that prevailed after the Second World War.
> 
> **15. Sunken Cathedrals: Music at Century’s End** (Location 9363)

---

> Boulez’s recent music has a cool, silvery sheen.
> 
> **15. Sunken Cathedrals: Music at Century’s End** (Location 9394)

---

> When Terry Riley’s In C was played at Darmstadt in 1969, it elicited lusty boos from the rank and file of the avant-garde.
> 
> **15. Sunken Cathedrals: Music at Century’s End** (Location 9413)

---

> If minimalism made hardly a dent on mainstream European music— its reliance on consonances and steady pulses broke all the modernist taboos at once— the younger generation of composers, those who came of age in the era of the student revolutions of May 1968, did find their own direction, distinct from that of Boulez.
> 
> **15. Sunken Cathedrals: Music at Century’s End** (Location 9426)

---

> The Soviet era, for all its ravaging effects on the spirit, preserved prewar musical culture as if in amber. As late as the 1980s, composers were still lionized, opera houses and orchestras were generously funded, and an imposing music-education system funneled major talents from the provinces to the center.
> 
> **15. Sunken Cathedrals: Music at Century’s End** (Location 9470)

---

> Schnittke, a man of haunted, sallow visage, Russian-Jewish and Volga German in origin, was Shostakovich’s heir apparent.
> 
> **15. Sunken Cathedrals: Music at Century’s End** (Location 9484)

---

> Minimalism gave Adams his individual voice. His defining move was to combine Reich-Glass repetition with the sprawling forms and grandiose orchestration of Wagner, Mahler, and Sibelius. In 1985 he finished a forty-minute symphonic work called Harmonielehre, its title taken from the famous textbook in which Schoenberg first declared that tonality was dead.
> 
> **15. Sunken Cathedrals: Music at Century’s End** (Location 9613)

---

> At the beginning of the twenty-first century, the impulse to pit classical music against pop culture no longer makes intellectual or emotional sense.
> 
> **Epilogue** (Location 9680)

---

> Björk is a modern pop artist deeply affected by the twentieth-century classical repertory that she absorbed in music school— Stockhausen’s electronic pieces, the organ music of Messiaen, the spiritual minimalism of Arvo Pärt.
> 
> **Epilogue** (Location 9686)