---
title: "Um Defeito de Cor"
author: Ana Maria Gonçalves
date: 2024-03-28
Rating: 10 / 10
---

### Highlights
> Éramos pequenas e apenas os olhos ficavam ao alcance dos olhos, um par de cada lado do ombro da minha mãe, dois pares que pareciam ser apenas meus e que a Taiwo devia pensar que eram apenas dela.
> 
> **Capítulo um** (Location 210)

---

> Estou guardando comigo todas as cartas trocadas, para que você saiba de tudo que fiz na esperança de te encontrar, meu pequeno Omotunde.
> 
> **Capítulo seis** (Location 7155)

---

> Em muitas tribos do interior, os pais ficavam sabendo das boas condições de vida de muitos dos retornados e faziam muito gosto quando os tangomaus apareciam por lá, pois tinham oportunidade de fazer com que seus filhos também se tornassem brasileiros.
> 
> **Capítulo nove** (Location 13757)

---

> O José Joaquim me contou casos de pais que viajavam vários dias só para abandonarem os filhos na porta do forte, para que fossem capturados.
> 
> **Capítulo nove** (Location 13759)

---

> na verdade, o que nos fazia católicos era a lembrança do Brasil e a superioridade sobre os selvagens, e não a fé.
> 
> **Capítulo dez** (Location 15965)