---
title: "War and Peace"
author: Leo Tolstoy
date: 2024-11-11
Rating: 9 / 10
---

### Highlights
> The artificiality and mendacity characterizing human relations are underscored by Tolstoy’s use of the French language, spoken preferentially by his most superficial and manipulative characters.
> 
> **Introduction** (Location 189)

---

> predilection for speaking French is frequently an indictment of character,
> 
> **Introduction** (Location 199)

---

> insignificance of greatness,
> 
> **BOOK ONE** (Location 6708)

---

> Fallen man has retained a love of idleness, but the curse weighs on the race not only because we have to seek our bread in the sweat of our brows, but because our moral nature is such that we cannot be both idle and at ease.
> 
> **BOOK TWO** (Location 10740)

---

> If man could find a state in which he felt that though idle he was fulfilling his duty, he would have found one of the conditions of man’s primitive blessedness.
> 
> **BOOK TWO** (Location 10742)

---

> In historic events the so-called great men are labels giving names to events, and like labels they have but the smallest connection with the event itself.
> 
> **BOOK THREE** (Location 13215)

---

> Marshal Davout was one of those men who purposely put themselves in most depressing conditions to have a justification for being gloomy.
> 
> **BOOK THREE** (Location 13426)

---

> This reply of Balashov’s, which hinted at the recent defeats of the French in Spain,* was much appreciated when he related it at Alexander’s court,
> 
> **BOOK THREE** (Location 13603)

---

> The German’s self-assurance is worst of all, stronger and more repulsive than any other, because he imagines that he knows the truth— science— which he himself has invented but which is for him the absolute truth.
> 
> **BOOK THREE** (Location 13899)

---

> The best generals I have known were, on the contrary, stupid or absent-minded men.
> 
> **BOOK THREE** (Location 13988)

---

> they all were involuntary tools of history, carrying on a work concealed from them but comprehensible to us. Such is the inevitable fate of men of action, and the higher they stand in the social hierarchy the less are they free.
> 
> **BOOK THREE** (Location 14795)

---

> notes, projects, and letters, which contain hints of such a line of action. But all these hints at what happened, both from the French side and the Russian, are advanced only because they fit in with the event. Had that event not occurred these hints would have been forgotten, as we have forgotten the thousands and millions of hints and expectations to the contrary which were current then but have now been forgotten because the event falsified them.
> 
> **BOOK THREE** (Location 14812)

---

> During the whole period of the war not only was there no wish on the Russian side to draw the French into the heart of the country, but from their first entry into Russia, everything was done to stop them. And not only was Napoleon not afraid to extend his line, but he welcomed every step forward as a triumph, and did not seek battle as eagerly as in former campaigns, but very lazily.
> 
> **BOOK THREE** (Location 14819)

---

> The luring of Napoleon into the depths of the country was not the result of any plan, for no one believed it to be possible;
> 
> **BOOK THREE** (Location 14832)

---

> a battle is decided not by the orders of a commander-in-chief, nor the place where the troops are stationed, not by the number of cannon or of slaughtered men, but by that intangible force called the spirit of the army,
> 
> **BOOK THREE** (Location 17390)

---

> Only by taking an infinitesimally small unit for observation (the differential of history, that is, the individual tendencies of men) and attaining to the art of integrating them (that is, finding the sum of these infinitesimals) can we hope to arrive at the laws of history.
> 
> **BOOK THREE** (Location 17719)

---

> but this does not prove that the conquerors caused the wars and that it is possible to find the laws of a war in the personal activity of a single man.
> 
> **BOOK THREE** (Location 17732)

---

> To study the laws of history we must completely change the subject of our observation, must leave aside kings, ministers, and generals, and study the common, infinitesimally small elements by which the masses are moved.
> 
> **BOOK THREE** (Location 17743)

---

> THE human mind cannot grasp the causes of events in their completeness, but the desire to find those causes is implanted in the human soul.
> 
> **BOOK FOUR** (Location 21130)

---

> history is written by learned men and so it is natural and agreeable for them to think that the activity of their class supplies the basis of the movement of all humanity,
> 
> **EPILOGUE** (Location 25225)

---

> (2) The movement of nations is caused not by power, nor by intellectual activity, nor even by a combination of the two as historians have supposed, but by the activity of all the people who participate in the events, and who always combine in such a way that those taking the largest direct share in the event take on themselves the least responsibility and vice versa.
> 
> **EPILOGUE** (Location 25527)

---

> Or in other words, the conception of a cause is inapplicable to the phenomena we are examining.
> 
> **EPILOGUE** (Location 25532)

---

> Only by reducing this element of freewill to the infinitesimal, that is, by regarding it as an infinitely small quantity, can we convince ourselves of the absolute inaccessibility of the causes, and then instead of seeking causes, history will take the discovery of laws as its problem.
> 
> **EPILOGUE** (Location 25797)
