project:
  type: website

website:
  title: "Rafael N. Magalhães"
  favicon: assets/favicon.png
  twitter-card: true
  open-graph: true
  google-analytics: "G-V27VSXP3KH"
  search: false
  navbar:
    title: <i class="bi bi-house-fill"></i> # https://icons.getbootstrap.com/
    background: "#ffffff"
    foreground: "#495057" #primary 
    collapse: true
    pinned: false
    left:
      - text: about
        href: about.qmd
      - text: consulting
        href: consulting.qmd
      - text: code
        href: code.qmd
      - text: teaching
        href: teaching.qmd
      - text: motley
        menu:
          - text: reading
            href: motley/reading.qmd
          - text: riding
            href: motley/riding.qmd
          - text: colophon
            href: motley/colophon.qmd
    right:       
      - icon: github
        href: https://github.com/rnmag
      - icon: linkedin
        href: https://www.linkedin.com/in/rmagalhães
      - icon: envelope-fill
        href: mailto:rnunesmagalhaes@gmail.com


format:
  html:
    toc: false
    theme: [journal, assets/tema.scss] 
    highlight-style: gruvbox
    link-external-icon: true
    link-external-newwindow: true