---
title: "Projects"
---

This is a **Quarto** _website_ e  agora **_abcdefg_**.

To learn more about Quarto websites visit <https://quarto.org/docs/websites> and also [esse site](www.folha.com).

```{r}
a <- 1 + 1

a
```

As the armies advanced on one another, Hannibal gradually extended the center of his line, as Polybius described: "After thus drawing up his whole army in a straight line, he took the central companies of Hispanics and Celts and advanced with them, keeping the rest of them in contact with these companies, but gradually falling off, so as to produce a crescent-shaped formation, the line of the flanking companies growing thinner as it was prolonged, his object being to employ the Africans as a reserve force and to begin the action with the Hispanics and Celts." Polybius described the weak Carthaginian center as deployed in a crescent, curving out toward the Romans in the middle with the African troops on their flanks in echelon formation. It is believed that the purpose of this formation was to break the forward momentum of the Roman infantry, and delay its advance before other developments allowed Hannibal to deploy his African infantry most effectively. While the majority of historians feel that Hannibal's action was deliberate, some have called this account fanciful, and claim that the actions of the day represent either the natural curvature that occurs when a broad front of infantry marches forward, or the bending back of the Carthaginian center from the shock action of meeting the heavily massed Roman center.

The battle began with a fierce cavalry engagement on the flanks. Polybius described many of the Hispanic and Celtic horsemen facing the Romans dismounting due to the lack of space to fight on horseback, and called the struggle "barbaric" in the sense of its utter brutality. When the Carthaginian cavalry got the upper hand, they cut down their Roman opponents without giving quarter. On the other flank the Numidians engaged in a way that merely kept the Roman allied cavalry occupied. Hasdrubal kept his victorious Hispanic and Gallic cavalry under control and did not chase the retreating Roman right wing. Instead, he led them to the other side of the field to attack the socii cavalry still fighting the Numidians. Assailed from both sides, the allied cavalry broke before Hasdrubal could charge into contact and the Numidians pursued them off the field.

While the Carthaginian cavalry were in the process of defeating the Roman horsemen, the masses of infantry on both sides advanced towards each other in the center of the field. The wind from the east blew dust in the Romans' faces and obscured their vision. While the wind was not a major factor, the dust that both armies created would have been potentially debilitating to sight. Although it made seeing difficult, troops would still have been able to see others in the vicinity. The dust, however, was not the only psychological factor involved in battle. Because of the somewhat distant battle location, both sides were forced to fight on little sleep. Another Roman disadvantage was thirst caused by Hannibal's attack on the Roman encampment during the previous day. Furthermore, the massive number of troops would have led to an overwhelming amount of background noise. All of these psychological factors made battle especially difficult for the infantrymen.

The light infantry on both sides engaged in indecisive skirmishing, inflicting few casualties and quickly withdrawing through the ranks of their heavy infantry. As the Roman heavy infantry attacked, Hannibal stood with his men in the weak center and held them together in a controlled retreat. The crescent of Hispanic and Gallic troops buckled inwards as they gradually withdrew step by step. Knowing the superiority of the Roman infantry, Hannibal had instructed his infantry to withdraw deliberately, creating an even tighter semicircle around the attacking Roman forces. By doing so, he had turned the strength of the Roman infantry into a weakness. While the front ranks were gradually advancing, the bulk of the Roman troops began to lose their cohesion, as troops from the reserve lines advanced into the growing gaps. Soon they were compacted together so closely that they had little space to wield their weapons. In pressing so far forward in their desire to destroy the retreating and seemingly collapsing line of Hispanic and Gallic troops, the Romans had ignored (possibly due to the dust) the African troops that stood uncommitted on the projecting ends of this now-reversed crescent. This also gave the Carthaginian cavalry time to drive the Roman cavalry off on both flanks and attack the Roman center in the rear. The Roman infantry, now stripped of protection on both its flanks, formed a wedge that drove deeper and deeper into the Carthaginian semicircle, driving itself into an alley formed by the African infantry on the wings. At this decisive point, Hannibal ordered his African infantry to turn inwards and advance against the Roman flanks, creating an encirclement in one of the earliest known examples of a pincer movement.

This distinction between modernism and romanticism extends to their respective treatments of 'symbol'. The romantics at times see an essential relation (the 'ground') between the symbol (the 'vehicle', in I.A. Richards's terms)[22] and its 'tenor' (its meaning)—for example in Coleridge's description of nature as 'that eternal language which thy God / Utters'.[23] But while nature and its symbols may be God's language, for some romantic theorists it remains inscrutable. As Goethe (not quite a romantic) said, 'the idea [or meaning] remains eternally and infinitely active and inaccessible in the image'.[24] This was extended in modernist theory which, drawing on its Symbolist precursors, often emphasises the inscrutability and failure of symbol and metaphor—for example in Stevens who seeks and fails to find meaning in nature, even if he at times seems to sense such a meaning. As such, symbolists and modernists at times adopt a mystical approach to suggest a non-rational sense of meaning.[25]

For these reasons, modernist metaphors are often unnatural, as for instance in T.S. Eliot's description of an evening 'spread out against the sky / Like a patient etherized upon a table'.[26] Similarly, in many later modernist poets nature is unnaturalised and at times mechanised, as for example in Stephen Oliver's image of the moon busily 'hoisting' itself into consciousness.[27]