---
title: "A Hora da Estrela"
author: Clarice Lispector
date: 2025-04-21
Rating: 8 / 10
---

### Highlights
> numa rua do Rio de Janeiro peguei no ar de relance o sentimento de perdição no rosto de uma moça nordestina.
> 
> **A hora da estrela** (Location 50)

---

> Escrevo porque sou um desesperado e estou cansado, não suporto mais a rotina de me ser e se não fosse a sempre novidade que é escrever, eu me morreria simbolicamente todos os dias.
> 
> **A hora da estrela** (Location 154)

---

> ela era incompetente. Incompetente para a vida. Faltava-lhe o jeito de se ajeitar.
> 
> **A hora da estrela** (Location 192)

---

> As poucas conversas entre os namorados versavam sobre farinha, carne de sol, carne-seca, rapadura, melado.
> 
> **A hora da estrela** (Location 467)

---

> Para tal exígua criatura chamada Macabéa a grande natureza se dava apenas em forma de capim de sarjeta – se lhe fosse dado o mar grosso ou picos altos de montanhas, sua alma, ainda mais virgem que o corpo, se alucinaria e explodir-se-lhe-ia o organismo,
> 
> **A hora da estrela** (Location 862)