---
title: "Augustus"
author: John Williams
date: 2025-08-29
Rating: 8 / 10
---

### Highlights
> Cicero deplores the depraved Roman morality that worships wealth— and, himself a millionaire many times over, travels with a hundred slaves from one of his villas to another.
> 
> **Augustus** (Location 477)

---

> The boy is nothing, and we need have no fear.
> 
> **Augustus** (Location 675)

---

> suggested that however unfortunate the assassination (you will forgive me that hypocrisy, dear Brutus), there were many who thought that the act sprang from unselfish and patriotic motives. At no time did I detect in him any sign that he was distressed by these advances.
> 
> **Augustus** (Location 686)

---

> the witticism that Cicero made: “We shall do the boy honor, we shall do him praise, and we shall do him in.”
> 
> **Augustus** (Location 1139)

---

> . Out of Philippi, Antonius is the hero and you are the coward. Antonius’s pig of a wife and his vulture of a brother have spread the stories— while you cowered and quaked in fear in the salt marsh, Antonius bravely punished the enemies of Caesar.
> 
> **Augustus** (Location 1626)

---

> Her Greek is impeccable; her Latin is at least as good as mine; and she speaks casually to her servants in a dialect I cannot understand. She is widely and intelligently read —she even shares my admiration for our Aristotle, and assures me that she knows my own work upon his philosophy, and that her understanding has been enhanced by that knowledge.
> 
> **Augustus** (Location 2025)

---

> It is as if he never had a childhood, and did not want one;
> 
> **Augustus** (Location 2039)

---

> At the age of twenty-one I discovered that I was, except for Livia herself, the most powerful woman in the world. It is empty, the philosophers say; but they have not known power, as a eunuch has not known a woman, and thus can look upon her unmoved.
> 
> **Augustus** (Location 3335)

---

> “Father,” I asked, “has it been worth it? Your authority, this Rome that you have saved, this Rome that you have built? Has it been worth all that you have had to do?” My father looked at me for a long time, and then he looked away. “I must believe that it has,” he said. “We both must believe that it has.”
> 
> **Augustus** (Location 3807)

---

> when I read those books and wrote my words, I read and wrote of a man who bore my name but a man whom I hardly know.
> 
> **Augustus** (Location 4445)

---

> I have lived too long. All those who might have succeeded me and striven for the survival of Rome are dead. Marcellus, to whom I first betrothed my daughter, died at the age of nineteen; Marcus Agrippa died; and my grandsons, the sons of Agrippa and Julia, Gaius and Lucius, died in the service of Rome; and Tiberius’s brother, Drusus, who was both more able and equable than his brother, and whom I raised as my own son, died in Germany. Now only Tiberius remains.
> 
> **Augustus** (Location 4901)