---
title: "Disgrace"
author: J. M. Coetzee
date: 2025-11-24
Rating: 10 / 10
---

### Highlights
> Because he has no respect for the material he teaches, he makes no impression on his students.
> 
> **ONE** (Location 106)

---

> David. There is a difference between pleading guilty to a charge and admitting you were wrong, and you know that.'
> 
> **SIX** (Location 842)

---

> to me animal-welfare people are a bit like Christians of a certain kind. Everyone is so cheerful and well-intentioned that after a while you itch to go off and do some raping and pillaging. Or to kick a cat.'
> 
> **EIGHT** (Location 1136)

---

> One can punish a dog, it seems to me, for an offence like chewing a slipper. A dog will accept the justice of that: a beating for a chewing. But desire is another story. No animal will accept the justice of being punished for following its instincts.'
> 
> **ELEVEN** (Location 1374)

---

> Words are beginning to take shape that have been hovering since last night at the edges of memory.
> 
> **THIRTEEN** (Location 1659)

---

> Melanie the firstborn, the dark one, then Desiree, the desired one.
> 
> **NINETEEN** (Location 2493)

---

> You behave as if everything I do is part of the story of your life. You are the main character, I am a minor character who doesn't make an appearance until halfway through. Well, contrary to what you think, people are not divided into major and minor. I am not minor. I have a life of my own, just as important to me as yours is to you, and in my life I am the one who makes the decisions.'
> 
> **TWENTY-TWO** (Location 2992)

---

> Between Lucy's generation and mine a curtain seems to have fallen. I didn't even notice when it fell.'
> 
> **TWENTY-THREE** (Location 3177)

---

> here the soul is yanked out of the body; briefly it hangs about in the air, twisting and contorting; then it is sucked away and is gone. It will be beyond him, this room that is not a room but a hole where one leaks out of existence.
> 
> **TWENTY-FOUR** (Location 3304)