---
title: "El Amor en los Tiempos del Colera"
author: Gabriel García Marquez
date: 2025-03-25
Rating: 8 / 10
---

### Highlights
> Pero si algo habían aprendido juntos era que la sabiduría nos llega cuando ya no sirve para nada.
> 
> **El amor en los tiempos del cólera** (Location 439)

---

> En realidad eran cartas de distracción, destinadas a mantener las brasas vivas pero sin poner la mano en el fuego, mientras que Florentino Ariza se incineraba en cada línea.
> 
> **El amor en los tiempos del cólera** (Location 1151)

---

> los seres humanos no nacen para siempre el día en que sus madres los alumbran, sino que la vida los obliga otra vez y muchas veces a parirse a sí mismos.
> 
> **El amor en los tiempos del cólera** (Location 2717)

---

> sólo entonces había comprendido que un hombre sabe cuando empieza a envejecer porque empieza a parecerse a su padre.
> 
> **El amor en los tiempos del cólera** (Location 2794)

---

> “Es increíble cómo se puede ser tan feliz durante tantos años, en medio de tantas peloteras, de tantas vainas, carajo, sin saber en realidad si eso es amor o no”.
> 
> **El amor en los tiempos del cólera** (Location 5498)