---
title: "Hateship, Friendship, Courtship, Loveship, Marriage"
author: Alice Munro
date: 2025-12-7
Rating: 7 / 10
---

### Highlights
> For where, on the list of things she planned to achieve in her life, was there any mention of her being responsible for the existence on earth of a person named Omar?
> 
> **Hateship, Friendship, Courtship, Loveship, Marriage** (Location 777)

---

> The unspeakable excitement you feel when a galloping disaster promises to release you from all responsibility for your own life. Then for shame you must compose yourself and stay very quiet.
> 
> **Floating Bridge** (Location 851)

---

> What she felt was a lighthearted sort of compassion, almost like laughter. A swish of tender hilarity, getting the better of all her sores and hollows, for the time given.
> 
> **Floating Bridge** (Location 1231)

---

> When Grant first started teaching Anglo-Saxon and Nordic Literature he got the regular sort of students in his classes. But after a few years he noticed a change. Married women started going back to school. Not with the idea of qualifying for a better job or for any job but simply to give themselves something more interesting to think about than their usual housework and hobbies. To enrich their lives. And perhaps it followed naturally that the men who taught them these things would become part of the enrichment, that these men would seem to these women more mysterious and desirable than the men they still cooked for and slept with.
> 
> **The Bear Came Over the Mountain** (Location 4311)

---

> Academic parties, which used to be so predictable, became a minefield. An epidemic had broken out, it was spreading like the Spanish flu. Only this time people ran after contagion, and few between sixteen and sixty seemed willing to be left out.
> 
> **The Bear Came Over the Mountain** (Location 4333)

---

> Educated people, literary people, some rich people like Grant’s socialist inlaws had lost touch with reality. Due to an unmerited good fortune or an innate silliness.
> 
> **The Bear Came Over the Mountain** (Location 4559)

---

> And so it often happened with those practical people. In spite of their calculations, their survival instincts, they might not get as far as they had quite reasonably expected. No doubt it seemed unfair.
> 
> **The Bear Came Over the Mountain** (Location 4577)

---

> Her voice on the machine was different from the voice he’d heard a short time ago in her house. Just a little different in the first message, more so in the second. A tremor of nerves there, an affected nonchalance, a hurry to get through and a reluctance to let go.
> 
> **The Bear Came Over the Mountain** (Location 4588)