---
title: Infinite Jest
author: David Foster Wallace
date: 2025-01-22
Rating: 8 / 10
---

### Highlights
> Just do it. Forget about is there a point, of course there’s no point. The point of repetition is there is no point. Wait until it soaks into the hardware and then see the way this frees up your head. A whole shitload of head-space you don’t need for the mechanics anymore, after they’ve sunk in.
> 
> **30 APRIL—YEAR OF THE DEPEND ADULT UNDERGARMENT** (Location 2479)

---

> Video telephony rendered the fantasy insupportable. Callers now found they had to compose the same sort of earnest, slightly overintense listener’s expression they had to compose for in-person exchanges.
> 
> **3 NOVEMBER Y.D.A.U.** (Location 3054)

---

> a return to good old telephoning not only dictated by common consumer sense but actually after a while culturally approved as a kind of chic integrity, not Ludditism but a kind of retrograde transcendence of sci-fi-ish high-tech for its own sake, a transcendence of the vanity and the slavery to high-tech fashion that people view as so unattractive in one another.
> 
> **3 NOVEMBER Y.D.A.U.** (Location 3142)

---

> You can be at certain parties and not really be there. You can hear how certain parties have their own implied ends embedded in the choreography of the party itself.
> 
> **7 NOVEMBER YEAR OF THE DEPEND ADULT UNDERGARMENT** (Location 4585)

---

> ‘But you never know when the magic will descend on you. You never know when the grooves will open up. And once the magic descends you don’t want to change even the smallest detail. You don’t know what concordance of factors and variables yields that calibrated can’t-miss feeling, and you don’t want to soil the magic by trying to figure it out,
> 
> **ENFIELD MA…** (Location 5086)

---

> Eschaton takes eight to twelve people to play, w/ 400 tennis balls so dead and bald they can’t even be used for service drills anymore, plus an open expanse equal to the area of four contiguous tennis courts, plus a head for data-retrieval and coldly logical cognition, along with at least 40 megabytes of available RAM and wide array of tennis paraphernalia.
> 
> **8 NOVEMBER YEAR OF THE DEPEND ADULT UNDERGARMENT INTERDEPENDENCE DAY GAUDEAMUS IGITUR** (Location 6750)

---

> ‘The truth will set you free. But not until it is finished with you.’
> 
> **8 NOVEMBER YEAR OF THE DEPEND ADULT UNDERGARMENT GAUDEAMUS IGITUR** (Location 8183)

---

> It did what all ads are supposed to do: create an anxiety relievable by purchase.
> 
> **8 NOVEMBER YEAR OF THE DEPEND ADULT UNDERGARMENT GAUDEAMUS IGITUR** (Location 8733)

---

> Make no mistake about people who leap from burning windows. Their terror of falling from a great height is still just as great as it would be for you or me standing speculatively at the same window just checking out the view; i.e. the fear of falling remains a constant. The variable here is the other terror, the fire’s flames: when the flames get close enough, falling to death becomes the slightly less terrible of two terrors. It’s not desiring the fall; it’s terror of the flames.
> 
> **YEAR OF THE DEPEND…** (Location 14615)

---

> Pink being Microsoft Inc.’ s first post-Windows DOS, quickly upgraded to Pink2 when InterLace took everything 100% interactive and digital; by Y.D.A.U. it’s kind of a dinosaur, but it’s still the only DOS that’ll run a Mathpak\ EndStat tree without having to stop and recompile every few seconds.
> 
> **NOTES AND ERRATA** (Location 21385)

---

> the derivative’s going to be nx + xn-1 for any kind of first-order rate-of-increase thing they’re going to ask you.
> 
> **NOTES AND ERRATA** (Location 23192)