---
title: "La Ridícula Idea de no Volver a Verte"
author: Rosa Montero
date: 2025-04-17
Rating: 6 / 10
---

### Highlights
> Lo expresó muy bien Fernando Pessoa: «La literatura, como el arte en general, es la demostración de que la vida no basta».
> 
> **La ridícula idea de no volver a verte** (Location 276)

---

> (durante siglos, el amor ha sido la única pasión que se nos ha permitido a las mujeres, mientras que los hombres podían apasionarse por muchas otras cosas),
> 
> **Pájaros con las pechugas palpitantes** (Location 569)

---

> Para vivir tenemos que narrarnos; somos un producto de nuestra imaginación.
> 
> **Aplastando carbones con las manos desnudas** (Location 1132)

---

> Pero los Curie se tomaban estos percances no ya con estoicismo, sino con una especie de infantil jactancia: eran las cicatrices de su proeza. «En realidad estoy feliz, después de todo, con mis heridas. Mi mujer está tan satisfecha como yo»,
> 
> **Una cuestión de deditos** (Location 1205)

---

> La segunda cosa difícil de entender de Marie Curie es su completo silencio a la hora de hablar de los problemas añadidos a los que se tenía que enfrentar por ser mujer.
> 
> **Una cuestión de deditos** (Location 1243)

---

> en el Excelsior publicaron un estudio fisonómico y grafológico de Curie, al estilo de las fichas de los criminales, y concluían que Marie era «alguien peligroso, un espécimen de voluntad perversa e inapropiada ambición que podría resultar nocivo para la Academia».
> 
> **Una cuestión de deditos** (Location 1255)

---

> las mujeres con el anular más largo, como Marie o como yo (¡ qué maravilla tener algo en común con ella!), supuestamente poseen un cerebro más varonil,
> 
> **Una cuestión de deditos** (Location 1301)

---

> Vivía luchando contra el dolor del duelo y se drogaba con el trabajo.
> 
> **Una sonrisa ferozmente alentadora** (Location 1431)

---

> «Creí que estaba llegando al final de mi vida, pero ahora siento como si estuviera empezando. Es como si estuviera viviendo mi vida al revés»,
> 
> **La última vez que uno sube a una montaña** (Location 1803)