---
title: "Lavoura Arcaica"
author: Raduan Nassar
date: 2025-07-02
Rating: 10 / 10
---

### Highlights
> nos intervalos da angústia, se colhe, de um áspero caule, na palma da mão, a rosa branca do desespero, pois entre os objetos que o quarto consagra estão primeiro os objetos do corpo;
> 
> **A Partida** (Location 32)

---

> os olhos são a candeia do corpo, e que se eles eram bons é porque o corpo tinha luz,
> 
> **A Partida** (Location 59)

---

> ele falou ainda dos anseios isolados de cada um em casa, mas que era preciso refrear os maus impulsos, moderar prudentemente os bons, não perder de vista o equilíbrio, cultivando o autodomínio, precavendo-se contra o egoísmo e as paixões perigosas que o acompanham,
> 
> **A Partida** (Location 114)

---

> Ana, impaciente, impetuosa, o corpo de campônia, a flor vermelha feito um coalho de sangue prendendo de lado os cabelos negros e soltos, essa minha irmã que, como eu, mais que qualquer outro em casa, trazia a peste no corpo,
> 
> **A Partida** (Location 174)

---

> a boca um doce gomo, cheia de meiguice, mistério e veneno nos olhos de tâmara,
> 
> **A Partida** (Location 189)

---

> meus olhos cheios de amargura não desgrudavam de minha irmã que tinha as plantas dos pés em fogo imprimindo marcas que queimavam dentro de mim...;
> 
> **A Partida** (Location 199)

---

> não importava que eu, erguendo os olhos, alcançasse paisagens muito novas, quem sabe menos ásperas, não importava que eu, caminhando, me conduzisse para regiões cada vez mais afastadas, pois haveria de ouvir claramente de meus anseios um juízo rígido, era um cascalho, um osso rigoroso, desprovido de qualquer dúvida: "estamos indo sempre para casa".
> 
> **A Partida** (Location 208)

---

> e senti também, pensando nela, que estava por romper-se o fruto que me crescia na garganta, e não era um fruto qualquer, era um figo pingando em grossas gotas o mel que me entupia os pulmões e já me subia soberbamente aos olhos,
> 
> **A Partida** (Location 225)

---

> me escapava da corrente o cão sempre estirado na sombra sonolenta dos beirais,
> 
> **A Partida** (Location 238)

---

> sabendo que atirava numa suprema aventura ao chão, descarnando as palmas, o jarro da minha velha identidade elaborado com o barro das minhas próprias mãos,
> 
> **A Partida** (Location 242)

---

> tudo em nossa casa é morbidamente impregnado da palavra do pai;
> 
> **A Partida** (Location 261)

---

> era esse lavrador fibroso catando da terra a pedra amorfa que ele não sabia tão modelável nas mãos de cada um;
> 
> **A Partida** (Location 268)

---

> alguma vez te passou pela cabeça, um instante curto que fosse, suspender o tampo do cesto de roupas no banheiro?
> 
> **A Partida** (Location 271)

---

> sempre conduzida pela figura do nosso avô, esse velho esguio talhado com a madeira dos móveis da família; era ele, Pedro, era ele na verdade nosso veio ancestral,
> 
> **A Partida** (Location 283)

---

> nada naquele talo de osso brilhava além da corrente do seu terrível e oriental anzol de ouro"
> 
> **A Partida** (Location 292)

---

> eu já pudesse estar em comunhão com a saliva oleosa desse verbo,
> 
> **A Partida** (Location 302)

---

> "Pedro, meu irmão, eram inconsistentes os sermões do pai" eu disse de repente com a frivolidade de quem se rebela,
> 
> **A Partida** (Location 308)

---

> existe tempo, por exemplo, nesta mesa antiga: existiu primeiro uma terra propícia, existiu depois uma árvore secular feita de anos sossegados, e existiu finalmente uma prancha nodosa e dura trabalhada pelas mãos de um artesão dia após dia;
> 
> **A Partida** (Location 337)

---

> rico só é o homem que aprendeu, piedoso e humilde, a conviver com o tempo, aproximando-se dele com ternura, não contrariando suas disposições, não se rebelando contra o seu curso, não irritando sua corrente, estando atento para o seu fluxo, brindando-o antes com sabedoria para receber dele os favores e não a sua ira;
> 
> **A Partida** (Location 342)

---

> o mundo das paixões é o mundo do desequilíbrio, é contra ele que devemos esticar o arame das nossas cercas, e com as farpas de tantas fiadas tecer um crivo estreito, e sobre este crivo emaranhar uma sebe viva, cerrada e pujante, que divida e proteja a luz calma e clara da nossa casa, que cubra e esconda dos nossos olhos as trevas que ardem do outro lado;
> 
> **A Partida** (Location 358)

---

> a paciência é a virtude das virtudes, não é sábio quem se desespera, é insensato quem não se submete."
> 
> **A Partida** (Location 411)

---

> escondendo de vergonha meus pés brancos, minhas unhas limpas, meus dentes de giz, o asseio da minha roupa, minha cara imberbe de criança;
> 
> **A Partida** (Location 472)

---

> a prédica constante contra o desperdício, apontado sempre como ofensa grave ao trabalho;
> 
> **A Partida** (Location 512)

---

> e muita coisa estava acontecendo comigo pois me senti num momento profeta da minha própria história,
> 
> **A Partida** (Location 595)

---

> me recolhi na casa velha da fazenda, fiz dela o meu refúgio, o esconderijo lúdico da minha insônia e suas dores, tranquei ali, entre as páginas de um missal, minha libido mais escura;
> 
> **A Partida** (Location 613)

---

> descansando em palha o meu feto renascido, embalando-o na palma, espalhando as pétalas prematuras de uma rosa branca,
> 
> **A Partida** (Location 623)

---

> esquecer, projetada na terra, a grade da sua tela; era uma ciência de menino, mas era uma ciência complicada, nenhum grão de mais, nenhum instante de menos, para que a ave não encontrasse o desânimo na carência nem na fartura,
> 
> **A Partida** (Location 670)

---

> de um lado, os barros santos, de outro, legiões do demo; também eu, ainda menino, deixava à ingênua pomba uma escolha igual: de um lado, uma areia desprovida de alimento, de outro, promessas de abundância debaixo da peneira;
> 
> **A Partida** (Location 796)

---

> era preciso ali também aliciar os barros santos, as pedras lúcidas, as partes iluminadas daquela câmara, fazer como tentei na casa velha, aliciar e trazer para o meu lado toda a capela:
> 
> **A Partida** (Location 806)

---

> foi um milagre descobrirmos acima de tudo que nos bastamos dentro dos limites da nossa própria casa, confirmando a palavra do pai de que a felicidade só pode ser encontrada no seio da família;
> 
> **A Partida** (Location 811)

---

> e, quando já tivermos, debaixo de um céu arcaico, tingido nossos dentes com o sangue das amoras colhidas no caminho, só então nos entregaremos ao silêncio, vasto e circunspecto, habitado nessa hora por insetos misteriosos, pássaros de vôo alto e os sinos distantes dos cincerros;
> 
> **A Partida** (Location 893)

---

> é a minha advertência, vai no meu apelo, eu te asseguro, a clarividência de um presságio escuro: na quebra desta paixão, não serei piedoso, não tenho a tua fé, não reconheço os teus santos na adversidade"
> 
> **A Partida** (Location 915)

---

> não podemos nos permitir a pureza dos espíritos exigentes que, em nome do rigor, trocam uma situação precária por uma situação inexistente;
> 
> **A Partida** (Location 943)

---

> te exorto a reconhecer comigo o fio atávico desta paixão: se o pai, no seu gesto austero, quis fazer da casa um templo, a mãe, transbordando no seu afeto, só conseguiu fazer dela uma casa de perdição"
> 
> **A Partida** (Location 948)

---

> e fui largando minha baba com fervor, eu que vinha correndo as mãos na minha pele exasperada, devassando meu corpo adolescente, fazendo surgir da flora meiga do púbis, num ímpeto cheio de caprichos e de engenhos, o meu falo soberbo, resoluto, um pouco abaixo, entre a costura das virilhas, penso, me enchendo a palma, o saco tosco do meu escroto que protegia a fonte primordial de todos meus tormentos, enquanto ia oferecendo religiosamente para a irmã o alimento denso do seu avesso, mas Ana continuava impassível,
> 
> **A Partida** (Location 961)

---

> não tive o meu contento, o mundo não terá de mim a misericórdia; amar e ser amado era tudo o que eu queria, mas fui jogado à margem sem consulta,
> 
> **A Partida** (Location 973)

---

> pertenço como nunca desde agora a essa insólita confraria dos enjeitados, dos proibidos, dos recusados pelo afeto, dos sem-sossego, dos intranqüilos, dos inquietos, dos que se contorcem, dos aleijões com cara de assassino que descendem de Caim
> 
> **A Partida** (Location 976)

---

> a sabedoria está precisamente em não se fechar nesse mundo menor: humilde, o homem abandona sua individualidade para fazer parte de uma unidade maior, que é de onde retira sua grandeza;
> 
> **O Retorno** (Location 1019)

---

> O avô, enquanto viveu, ocupou a outra cabeceira; mesmo depois da sua morte, que quase coincidiu com nossa mudança da casa velha para a nova, seria exagero dizer que sua cadeira ficou vazia.
> 
> **O Retorno** (Location 1085)

---

> não reconheço mais os valores que me esmagam, acho um triste faz-de-conta viver na pele de terceiros, e nem entendo como se vê nobreza no arremedo dos desprovidos;
> 
> **O Retorno** (Location 1158)

---

> a larva só me parece sábia enquanto se guarda no seu núcleo, e não descubro de onde tira a sua força quando rompe a resistência do casulo; contorce-se com certeza, passa por metamorfoses, e tanto esforço só para expor ao mundo sua fragilidade.
> 
> **O Retorno** (Location 1178)

---

> o tempo é farto e generoso, mas não devolve a vida aos que não nasceram; aos derrotados de partida, ao fruto peco já na semente, aos arruinados sem terem sido erguidos, não resta outra alternativa: dar as costas para o mundo, ou alimentar a expectativa da destruição de tudo; de minha parte, a única coisa que sei é que todo meio é hostil, desde que negue direito à vida.
> 
> **O Retorno** (Location 1183)

---

> ninguém em nossa casa há de falar com presumida profundidade, mudando o lugar das palavras, embaralhando as idéias, desintegrando as coisas numa poeira, pois aqueles que abrem demais os olhos acabam só por ficar com a própria cegueira;
> 
> **O Retorno** (Location 1212)

---

> sem jamais ter suspeitado antes que se pudesse, de uma corda partida, arrancar ainda uma nota diferente
> 
> **O Retorno** (Location 1249)

---

> vou sair de casa para abraçar o mundo, vou partir para nunca mais voltar, não vou ceder a nenhum apelo, tenho coragem, André, não vou falhar como você...
> 
> **O Retorno** (Location 1308)

---

> seus olhos eram, sem a menor sombra de dúvida, os primitivos olhos de Ana!
> 
> **O Retorno** (Location 1317)

---

> eu tinha transferido só para a aurora o meu discernimento, sem contar que a madrugada haveria também de derramar o orvalho frio sobre os belos cabelos de Lula, quando ele percorresse o caminho que levava da casa para a capela.
> 
> **O Retorno** (Location 1323)

---

> a gargantilha de veludo roxo apertando-lhe o pescoço,
> 
> **O Retorno** (Location 1362)

---

> Ana, coberta com as quinquilharias mundanas da minha caixa,
> 
> **O Retorno** (Location 1363)

---

> provocando a ovação dos que a cercavam, era a voz surda de um coro ao mesmo tempo sacro e profano que subia, era a comunhão confusa de alegria, anseios e tormentos,
> 
> **O Retorno** (Location 1377)

---

> a boca um doce gomo, cheia de meiguice, mistério e veneno nos olhos de tâmara,
> 
> **O Retorno** (Location 1386)

---

> meu pai atingiu com um só golpe a dançarina oriental
> 
> **O Retorno** (Location 1398)

---

> essa matéria fibrosa, palpável, tão concreta, não era descarnada como eu pensava, tinha substância, corria nela um vinho tinto, era sangüínea, resinosa,
> 
> **O Retorno** (Location 1401)

---

> e com os mesmos olhos amenos assistir à manipulação misteriosa de outras ferramentas que o tempo habilmente emprega em suas transformações, não questionando jamais sobre seus desígnios insondáveis, sinuosos, como não se questionam nos puros planos das planícies as trilhas tortuosas, debaixo dos cascos, traçadas nos pastos pelos rebanhos: que o gado sempre vai ao poço.")
> 
> **O Retorno** (Location 1428)