---
title: "Livro do Desassossego"
author: Fernando Pessoa
date: 2025-12-29
Rating: 9 / 10
---

### Highlights
> Pertenço, porém, àquela espécie de homens que estão sempre na margem daquilo a que pertencem, nem vêem só a multidão de que são, senão também os grandes espaços que há ao lado.
> 
> **Início** (Location 638)

---

> Tudo em mim é a tendência para ser a seguir outra coisa; uma impaciência da alma consigo mesma, como com uma criança inoportuna; um desassossego sempre crescente e sempre igual. Tudo me interessa e nada me prende.
> 
> **Início** (Location 801)

---

> Nós nunca nos realizamos. Somos dois abismos1 — um poço fitando o céu.
> 
> **Início** (Location 811)

---

> Talvez o meu destino seja eternamente ser guarda-livros, e a poesia ou a literatura uma borboleta que, pousando-me na cabeça, me torne tanto mais ridículo quanto maior for a sua própria beleza.
> 
> **Início** (Location 883)

---

> Os críticos da casa pequena soem apontar que tal poema, longamente ritmado, não quer, afinal, dizer senão que o dia está bom. Mas dizer que o dia está bom é difícil, e o dia bom, ele mesmo, passa. Temos pois que conservar o dia bom em uma memória florida e prolixa, e assim constelar de novas flores ou de novos astros os campos ou os céus da exterioridade vazia e passageira.
> 
> **Início** (Location 986)

---

> Sou, neste momento de ver, um solitário súbito, que se reconhece desterrado onde se encontrou sempre cidadão. No mais íntimo do que pensei não fui eu.
> 
> **Início** (Location 1169)

---

> Para compreender, destruí-me. Compreender é esquecer de amar. Nada conheço mais ao mesmo tempo falso e significativo que aquele dito de Leonardo da Vinci de que se não pode amar ou odiar uma coisa senão depois de compreendê-la.
> 
> **Início** (Location 1323)

---

> O isolamento talhou-me à sua imagem e semelhança. A presença de outra pessoa — de uma só pessoa que seja — atrasa-me imediatamente o pensamento, e, ao passo que no homem normal o contacto com outrem é um estímulo para a expressão e para o dito, em mim esse contacto é um contra-estímulo,
> 
> **Início** (Location 1330)

---

> A personagem individual e imponente, que os românticos figuravam em si mesmos, várias vezes, em sonho, a tentei viver, e, tantas vezes, quantas a tentei viver, me encontrei a rir alto, da minha ideia de vivê-la.
> 
> **Início** (Location 1427)

---

> Cada vez que o meu propósito se ergueu, por influência de meus sonhos, acima do nível quotidiano da minha vida, e um momento me senti alto, como a criança num balouço, cada vez dessas tive que descer como ela ao jardim municipal, e conhecer a minha derrota sem bandeiras levadas para a guerra nem espada que houvesse força para desembainhar.
> 
> **Início** (Location 1537)

---

> É nobre ser tímido, ilustre não saber agir, grande não ter jeito para viver.
> 
> **Início** (Location 1587)

---

> Aquilo que, creio, produz em mim o sentimento profundo, em que vivo, de incongruência com os outros, é que a maioria pensa com a sensibilidade, e eu sinto com o pensamento.
> 
> **Início** (Location 1752)

---

> Entre mim e a vida há um vidro ténue. Por mais nitidamente que eu veja e compreenda a vida, eu não lhe posso tocar.
> 
> **Início** (Location 1894)

---

> Vejo tudo isto do alto de um telhado espiritual3. Estou só no mundo. Ver é estar distante. Ver claro é parar. Analisar é ser estrangeiro. Toda a gente passa sem roçar por mim. Tenho só ar à minha volta. Sinto-me tão isolado que sinto4 a distância entre mim e o meu fato.
> 
> **Início** (Location 1950)

---

> A única atitude digna de um homem superior é o persistir tenaz de uma actividade que se reconhece inútil, o hábito de uma disciplina que se sabe estéril, e o uso fixo de normas de pensamento filosófico e metafísico cuja importância se sente ser nula.
> 
> **Início** (Location 2050)

---

> A vida contemplativa, para sequer existir, tem que considerar os acidentes objectivos como premissas dispersas de uma conclusão inatingível; mas tem ao mesmo tempo que considerar as contingências do sonho como em certo modo dignas daquela atenção a elas, pela qual nos tornamos contemplativos.
> 
> **Início** (Location 2055)

---

> Houve tempo em que me irritavam aquelas coisas que hoje me fazem sorrir. E uma delas, que quase todos os dias me lembram, é a insistência com que os homens quotidianos e activos na vida sorriem dos poetas e dos artistas.
> 
> **Início** (Location 2074)

---

> Nunca pretendi ser senão um sonhador. A quem me falou de viver nunca prestei atenção. Pertenci sempre ao que não está onde estou e ao que nunca pude ser.
> 
> **Início** (Location 2100)

---

> Em mim foi sempre menor a intensidade das sensações que a intensidade da consciência1 delas. Sofri sempre mais com a consciência de estar sofrendo que com o sofrimento de que tinha2 consciência.
> 
> **Início** (Location 2152)

---

> Nunca fui senão um vestígio e um simulacro de mim. O meu passado é tudo quanto não consegui ser.
> 
> **Início** (Location 2258)

---

> o que se sente exige o momento; passado este, há um virar de página e a história continua, mas não o texto.
> 
> **Início** (Location 2259)

---

> ESTÉTICA DA ABDICAÇÃO Conformar-se é submeter-se e vencer é conformar-se, ser vencido. Por isso toda a vitória é uma grosseria. Os vencedores perdem sempre todas as qualidades de desalento com o presente que os levaram à luta que lhes deu a vitória. Ficam satisfeitos, e satisfeito só pode estar aquele que se conforma, que não tem a mentalidade do vencedor. Vence só quem nunca consegue. Só é forte quem desanima sempre.
> 
> **Início** (Location 2313)

---

> Não tenho uma ideia de mim próprio; nem aquela que consiste em uma falta de ideia de mim próprio. Sou um nómada da consciência de mim.
> 
> **Início** (Location 2341)

---

> Mas, quando há um intervalo, e não tenho que vigiar o curso da minha marcha, para evitar veículos ou não estorvar peões, quando não tenho que falar a alguém, nem me pesa a entrada para uma porta próxima, largo-me de novo nas águas do sonho,
> 
> **Início** (Location 2378)

---

> o onanista é a perfeita expressão lógica do amoroso. É o único que não disfarça nem se engana.
> 
> **Início** (Location 2403)

---

> Esculpi a minha vida como a uma estátua de matéria alheia a meu ser. Às vezes não me reconheço, tão exterior me pus a mim, e tão de modo puramente artístico empreguei a minha consciência de mim próprio.
> 
> **Início** (Location 2429)

---

> Um poema é a expressão de ideias ou de sentimentos em linguagem que ninguém emprega, pois que ninguém fala em verso.
> 
> **Início** (Location 2452)

---

> As crianças são muito literárias porque dizem como sentem e não como deve sentir quem sente segundo outra pessoa.
> 
> **Início** (Location 2465)

---

> Mais terrível de que qualquer muro, pus grades altíssimas a demarcar o jardim do meu ser, de modo que, vendo perfeitamente os outros, perfeitissimamente eu os excluo e mantenho outros.
> 
> **Início** (Location 2498)

---

> Como todo o indivíduo de grande mobilidade mental, tenho um amor orgânico e fatal à fixação. Abomino a vida nova e o lugar desconhecido.
> 
> **Início** (Location 2505)

---

> Os que sonham grandemente, ou são doidos e acreditam no que sonham e são felizes, ou são devaneadores simples, para quem o devaneio é uma música da alma, que os embala sem lhes dizer nada. Mas o que sonha o possível tem a possibilidade real da verdadeira desilusão. Não me pode pesar muito o ter deixado de1 ser imperador romano, mas pode doer-me o nunca ter sequer falado à costureira que, cerca das nove horas, volta sempre a esquina da direita.
> 
> **Início** (Location 2825)

---

> Tudo quanto o homem expõe ou exprime é uma nota à margem de um texto apagado de todo. Mais ou menos, pelo sentido da nota, tiramos o sentido que havia de ser o do texto; mas fica sempre uma dúvida, e os sentidos possíveis são muitos.
> 
> **Início** (Location 2919)

---

> Pasmo sempre quando acabo qualquer coisa. Pasmo e desolo-me. O meu instinto de perfeição deveria inibir-me de acabar; deveria inibir-me até de dar começo. Mas distraio-me e faço.
> 
> **Início** (Location 3002)

---

> Tenho assistido, incógnito, ao desfalecimento gradual da minha vida, ao soçobro lento de tudo quanto quis ser. Posso dizer, com aquela verdade que não precisa de flores para se saber que está morta, que não há coisa que eu tenha querido, ou em que tenha posto, um momento que fosse, o sonho só desse momento, que se me não tenha desfeito debaixo das janelas como pó parecendo pedra caído de um vaso de andar alto.
> 
> **Início** (Location 3587)

---

> Tem-me perseguido, como um ente maligno, o destino de não poder desejar sem saber que terei que não ter.
> 
> **Início** (Location 3596)

---

> Um romântico faria disto uma tragédia; um estranho sentiria isto como uma comédia: eu, porém, misturo as duas coisas, pois sou romântico em mim e estranho a mim, e viro a página para outra ironia.
> 
> **Início** (Location 3598)

---

> Uns dizem que sem esperança a vida é impossível, outros que com esperança é vazia. Para mim, que hoje não espero nem desespero, ela é um simples quadro externo, que me inclui a mim, e a que assisto como um espectáculo sem enredo,
> 
> **Início** (Location 3600)

---

> Tornei-me uma figura de livro, uma vida lida. O que sinto é (sem que eu queira) sentido para se escrever que se sentiu.
> 
> **Início** (Location 3613)

---

> De tanto recompor-me destruí-me. De tanto pensar-me, sou já meus pensamentos mas não eu. Sondei-me e deixei cair a sonda; vivo a pensar se sou fundo ou não, sem outra sonda agora senão o olhar que me mostra, claro a negro no espelho do poço alto, meu próprio rosto que me contempla contemplá-lo.
> 
> **Início** (Location 3615)

---

> Tenho sido sempre um sonhador irónico, infiel às promessas interiores. Gozei sempre, como outro e estrangeiro, as derrotas dos meus devaneios, assistente casual ao que pensei ser. Nunca dei crença àquilo em que acreditei.
> 
> **Início** (Location 4032)

---

> Considero o verso como uma coisa intermédia, uma passagem da música para a prosa. Como a música, o verso é limitado por leis rítmicas, que, ainda que não sejam as leis rígidas do verso regular, existem todavia como resguardos, coacções, dispositivos automáticos de opressão e castigo. Na prosa falamos livres. Podemos incluir ritmos musicais, e contudo pensar. Podemos incluir ritmos poéticos, e contudo estar fora deles. Um ritmo ocasional de verso não estorva a prosa; um ritmo ocasional de prosa faz tropeçar o verso.
> 
> **Início** (Location 4124)

---

> Ler é sonhar pela mão de outrem. Ler mal e por alto é libertarmo-nos da mão que nos conduz. A superficialidade na erudição é o melhor modo de ler bem e ser profundo.
> 
> **Início** (Location 4151)

---

> O horror à acção, por ter de ser vil numa sociedade vil, inundou os espíritos. A actividade superior da alma adoeceu; só a actividade inferior, porque mais vitalizada, não decaiu; inerte a outra, assumiu a regência do mundo. Assim nasceu uma literatura e uma arte feitas dos elementos secundários do pensamento — o romantismo; e uma vida social feita dos elementos secundários da actividade — a democracia moderna.
> 
> **Início** (Location 4402)

---

> Gosto de dizer. Direi melhor: gosto de palavrar. As palavras são para mim corpos tocáveis, sereias visíveis, sensualidades incorporadas.
> 
> **Início** (Location 4618)

---

> Não tenho sentimento nenhum político ou social. Tenho, porém, num sentido, um alto sentimento patriótico. Minha pátria é a língua portuguesa.
> 
> **Início** (Location 4635)

---

> A liberdade é a possibilidade do isolamento. És livre se podes afastar-te dos homens, sem que te obrigue a procurá-los a necessidade do dinheiro, ou a necessidade gregária, ou o amor, ou a glória, ou a curiosidade, que no silêncio e na solidão não podem ter alimento. Se te é impossível viver só, nasceste escravo.
> 
> **Início** (Location 4964)

---

> Pergunto então em mim próprio se valerá a pena todo o esforço que pus em me isolar e elevar, se o lento calvário que de mim fiz para a minha Glória Crucificada valerá religiosamente a pena? E, ainda que saiba que valeu, pesa-me nesse momento o sentimento de que não valeu, de que não valerá nunca.
> 
> **Início** (Location 5113)

---

> Para criar, destruí-me; tanto me exteriorizei dentro de mim, que dentro de mim não existo senão exteriormente. Sou a cena nua onde passam vários actores representando várias peças.
> 
> **Início** (Location 5176)

---

> O mundo é de quem não sente. A condição essencial para se ser um homem prático é a ausência de sensibilidade. A qualidade principal na prática da vida é aquela qualidade que conduz à acção, isto é, a vontade. Ora há duas coisas que estorvam a acção — a sensibilidade e o pensamento analítico, que não é, afinal, mais que o pensamento com sensibilidade.
> 
> **Início** (Location 5221)

---

> Para agir é, pois, preciso que nos não figuremos com facilidade as personalidades alheias, as suas dores e alegrias. Quem simpatiza pára.
> 
> **Início** (Location 5227)

---

> Todo o homem de acção é essencialmente animado e optimista porque quem não sente é feliz. Conhece-se um homem de acção por nunca estar mal disposto.
> 
> **Início** (Location 5235)

---

> Nas pequenas cavidades rugosas das pedras, por onde a água escolhia, havia segredos que tivéramos quando crianças, sonhos do tamanho parado dos nossos soldados de chumbo,
> 
> **Início** (Location 5481)

---

> Doem-me a cabeça e o universo.
> 
> **Início** (Location 5650)

---

> O calor, como uma roupa invisível, dá vontade de o tirar.
> 
> **Início** (Location 5945)

---

> Saber ser supersticioso ainda é uma das artes que, realizadas a auge, marcam o homem superior.
> 
> **Início** (Location 6444)

---

> Nunca tive a arte de estar vivo activamente. Errei sempre os gestos que ninguém erra; o que os outros nasceram para fazer, esforcei-me sempre para não deixar de fazer. Desejei sempre conseguir o que os outros conseguiram quase sem o desejar. Entre mim e a vida houve sempre vidros foscos: não soube deles pela vista, nem pelo tacto; nem a vivi essa vida ou esse plano, fui o devaneio do que quis ser, o meu sonho começou na minha vontade, o meu propósito foi sempre a primeira ficção do que nunca fui.
> 
> **Início** (Location 6604)

---

> Fabriquei-me a tintas falsas, resultei a império de trapeira. Meu coração, de quem fiei os grandes acontecimentos da prosa vivida, parece-me hoje, escrito na distância destas páginas relidas com outra alma,
> 
> **Início** (Location 7221)

---

> A criança sabe que a boneca não é real, e trata-a como real, até chorá-la e se desgostar quando se parte. A arte da criança é a de irrealizar.
> 
> **Início** (Location 7789)

---

> Nunca se deve fazer hoje o que se pode deixar de fazer também amanhã1.
> 
> **Início** (Location 8146)

---

> Ter opiniões definidas e certas, instintos, paixões e carácter fixo e conhecido — tudo isto monta ao horror de tornar a nossa alma um facto, de a materializar e tornar exterior. Viver num doce e fluido estado de desconhecimento das coisas e de si próprio é o único modo de vida que a um sábio convém e aquece.
> 
> **Início** (Location 8356)

---

> O homem de ciência reconhece que a única realidade para si é ele próprio, e o único mundo real o mundo como a sua sensação lho dá. Por isso, em lugar de seguir o falso caminho de procurar ajustar as suas sensações às dos outros, fazendo ciência objectiva, procura, antes, conhecer perfeitamente o seu mundo, e a sua personalidade. Nada mais objectivo do que os seus sonhos. Nada mais seu do que a sua consciência de si. Sobre essas duas realidades requinta ele a sua ciência. É muito diferente já da ciência dos antigos científicos, que, longe de buscarem as leis da sua própria personalidade e a organização dos seus sonhos, procuravam as leis do “exterior” e a organização daquilo a que chamavam “Natureza”.
> 
> **Início** (Location 9098)

---

> Por isso a ideia que faço de mim é uma ideia que a muitos parecerá errada. De certo modo é errada. Mas eu sonho-me a mim próprio e de mim escolho o que é sonhável, compondo-me e recompondo-me de todas as maneiras até estar bem perante o que exijo do que sou e não sou.
> 
> **Início** (Location 9145)

---

> esse livro chama-se Livro do Desassossego, por causa da inquietação e incerteza que é a sua nota predominante.
> 
> **Início** (Location 9369)

---

> Maria Aliete Galhoz descobriu, nas Vidas Paralelas de Plutarco, a fonte primitiva da frase “Navegar é preciso, viver não é preciso”. Foi dita por Pompeio quando, apesar de uma grande tormenta, ordenou que as suas naus partissem em direção a Roma, com o trigo que tinham carregado na Sicília, na Sardenha e em África.
> 
> **Início** (Location 9922)