---
title: "Never Let Me Go"
author: Kazuo Ishiguro
date: 2025-12-17
Rating: 10 / 10
---

### Highlights
> A lot of the time, how you were regarded at Hailsham, how much you were liked and respected, had to do with how good you were at “creating.”
> 
> **Chapter Two** (Location 194)

---

> We’d spend our precious tokens on an exercise book full of that stuff rather than on something really nice for around our beds.
> 
> **Chapter Two** (Location 201)

---

> we all felt it; it was like we’d walked from the sun right into chilly shade. Ruth had been right: Madame was afraid of us. But she was afraid of us in the same way someone might be afraid of spiders. We hadn’t been ready for that. It had never occurred to us to wonder how we would feel, being seen like that, being the spiders.
> 
> **Chapter Three** (Location 475)

---

> there are people out there, like Madame, who don’t hate you or wish you any harm, but who nevertheless shudder at the very thought of you— of how you were brought into this world and why— and who dread the idea of your hand brushing against theirs. The first time you glimpse yourself through the eyes of a person like that, it’s a cold moment. It’s like walking past a mirror you’ve walked past every day of your life, and suddenly it shows you something else, something troubling and strange.
> 
> **Chapter Three** (Location 491)

---

> When we were remembering these long speeches, Ruth remarked how odd it was they should have been so unfathomable, since Miss Emily, in a classroom, could be as clear as anything.
> 
> **Chapter Four** (Location 588)

---

> Sure enough, the guard was important to her. She’d known about the plot for much longer than the rest of us, and this gave her enormous authority; by hinting that the real evidence came from a time before people like me had joined— that there were things she’d yet to reveal even to us— she could justify almost any decision she made on behalf of the group.
> 
> **Chapter Five** (Location 704)

---

> What it was, I suppose, is that Moira was suggesting she and I cross some line together, and I wasn’t prepared for that yet. I think I sensed how beyond that line, there was something harder and darker and I didn’t want that. Not for me, not for any of us.
> 
> **Chapter Five** (Location 756)

---

> But after that morning in Room 5, I did go around in a bit of a trance. I’d drift off in the middle of conversations; whole lessons went by with me not knowing what was going on. I was determined Ruth shouldn’t get away with it this time, but for a long while I wasn’t doing anything constructive about it; just playing fantastic scenes in my head where I’d expose her and force her to admit she’d made it up. I even had one hazy fantasy where Miss Geraldine herself heard about it and gave Ruth a complete dressing-down in front of everyone.
> 
> **Chapter Five** (Location 793)

---

> Now I saw how upset Ruth was; how for once she was at a complete loss for words, and had turned away on the verge of tears. And suddenly my behaviour seemed to me utterly baffling. All this effort, all this planning, just to upset my dearest friend. So what if she’d fibbed a little about her pencil case?
> 
> **Chapter Five** (Location 822)

---

> So why had we stayed silent that day? I suppose it was because even at that age— we were nine or ten— we knew just enough to make us wary of that whole territory. It’s hard now to remember just how much we knew by then.
> 
> **Chapter Six** (Location 948)

---

> None of you will go to America, none of you will be film stars. And none of you will be working in supermarkets as I heard some of you planning the other day. Your lives are set out for you. You’ll become adults, then before you’re old, before you’re even middle-aged, you’ll start to donate your vital organs. That’s what each of you was created to do.
> 
> **Chapter Seven** (Location 1112)

---

> “It’s not so bad now,” she said, even though the rain was as steady as ever. “Let’s just go out there. Then maybe the sun will come out too.”
> 
> **Chapter Seven** (Location 1120)

---

> But from when we were thirteen, like I say, things started to change. We still didn’t discuss the donations and all that went with them; we still found the whole area awkward enough. But it became something we made jokes about, in much the way we joked about sex.
> 
> **Chapter Seven** (Location 1160)

---

> In other words, for all the talk of sex being beautiful, we had the distinct impression we’d be in trouble if the guardians caught us at it.
> 
> **Chapter Eight** (Location 1314)

---

> What I remember is that there was this discreet agreement among us all not to quiz each other too much about our claims. If, say, Hannah rolled her eyes when you were discussing another girl and murmured: “Virgin”— meaning “Of course we’re not, but she is, so what can you expect?”— then it definitely wasn’t on to ask her: “Who did you do it with? When? Where?” No, you just nodded knowingly. It was like there was some parallel universe we all vanished off to where we had all this sex.
> 
> **Chapter Eight** (Location 1343)

---

> ‘Tommy, I made a mistake, when I said what I did to you. And I should have put you right about it long before now.’ Then she’s saying I should forget everything she told me before. That she’d done me a big disservice telling me not to worry about being creative. That the other guardians had been right all along, and there was no excuse for my art being so rubbish…”
> 
> **Chapter Nine** (Location 1492)

---

> Because somewhere underneath, a part of us stayed like that: fearful of the world around us, and— no matter how much we despised ourselves for it— unable quite to let each other go.
> 
> **Chapter Ten** (Location 1627)

---

> Mind you, at first, Tommy didn’t have a clue what was going on, and would turn abruptly to Ruth and go: “What?,” so that she’d have to glare furiously at him, like they were in a play and he’d forgotten his lines.
> 
> **Chapter Ten** (Location 1650)

---

> She was the one always pretending to have finished anything anyone happened to be reading; and she was the only one with this notion that the way to demonstrate your superior reading was to go around telling people the plots of novels they were in the middle of.
> 
> **Chapter Ten** (Location 1674)

---

> And what made these heart-to-hearts possible— you might even say what made the whole friendship possible during that time— was this understanding we had that anything we told each other during these moments would be treated with careful respect: that we’d honour confidences, and that no matter how much we rowed, we wouldn’t use against each other anything we’d talked about during those sessions.
> 
> **Chapter Eleven** (Location 1712)

---

> Since each of us was copied at some point from a normal person, there must be, for each of us, somewhere out there, a model getting on with his or her life.
> 
> **Chapter Twelve** (Location 1889)

---

> “We all know it. We’re modelled from trash. Junkies, prostitutes, winos, tramps. Convicts, maybe, just so long as they aren’t psychos. That’s what we come from.
> 
> **Chapter Fourteen** (Location 2287)

---

> “Even if what Ruth says is right, and I don’t think it is, why are you looking through old porn mags for your possibles? Why would your model have to be one of those girls?”
> 
> **Chapter Fifteen** (Location 2507)

---

> But the fact was, I suppose, there were powerful tides tugging us apart by then, and it only needed something like that to finish the task. If we’d understood that back then— who knows?— maybe we’d have kept a tighter hold of one another.
> 
> **Chapter Seventeen** (Location 2728)

---

> It wasn’t until a few days later I came to see what a difference that trip had made. All the guardedness, all the suspicions between me and Ruth evaporated, and we seemed to remember everything we’d once meant to each other.
> 
> **Chapter Nineteen** (Location 3230)

---

> what occurs to me now is that she probably knew all along, even before I did, that I’d become Tommy’s carer, and that we’d “give it a try,” just as she’d told us to in the car that day.
> 
> **Chapter Nineteen** (Location 3256)

---

> right from that first time, there was something in Tommy’s manner that was tinged with sadness, that seemed to say: “Yes, we’re doing this now and I’m glad we’re doing it now. But what a pity we left it so late.”
> 
> **Chapter Twenty** (Location 3286)

---

> Okay, in many ways these frogs were a lot like what I’d seen back at the Cottages. But something was definitely gone, and they looked laboured, almost like they’d been copied. So that feeling came again, even though I tried to keep it out: that we were doing all of this too late; that there’d once been a time for it, but we’d let that go by, and there was something ridiculous, reprehensible even, about the way we were now thinking and planning.
> 
> **Chapter Twenty** (Location 3324)

---

> We took away your art because we thought it would reveal your souls. Or to put it more finely, we did it to prove you had souls at all.”
> 
> **Chapter Twenty-Two** (Location 3587)

---

> Most importantly, we demonstrated to the world that if students were reared in humane, cultivated environments, it was possible for them to grow to be as sensitive and intelligent as any ordinary human being.
> 
> **Chapter Twenty-Two** (Location 3604)

---

> It’s one thing to create students, such as yourselves, for the donation programme. But a generation of created children who’d take their place in society? Children demonstrably superior to the rest of us? Oh no. That frightened people. They recoiled from that.”
> 
> **Chapter Twenty-Two** (Location 3643)

---

> “I can see,” Miss Emily said, “that it might look as though you were simply pawns in a game. It can certainly be looked at like that. But think of it. You were lucky pawns. There was a certain climate and now it’s gone. You have to accept that sometimes that’s how things happen in this world. People’s opinions, their feelings, they go one way, then the other. It just so happens you grew up at a certain point in this process.” “It might be just some trend that came and went,” I said. “But for us, it’s our life.”
> 
> **Chapter Twenty-Two** (Location 3676)

---

> We’re all afraid of you. I myself had to fight back my dread of you all almost every day I was at Hailsham. There were times I’d look down at you all from my study window and I’d feel such revulsion…” She stopped, then something in her eyes flashed again. “But I was determined not to let such feelings stop me doing what was right. I fought those feelings and I won.
> 
> **Chapter Twenty-Two** (Location 3718)

---

> I was weeping for an altogether different reason. When I watched you dancing that day, I saw something else. I saw a new world coming rapidly. More scientific, efficient, yes. More cures for the old sicknesses. Very good. But a harsh, cruel world. And I saw a little girl, her eyes tightly closed, holding to her breast the old kind world, one that she knew in her heart could not remain, and she was holding it and pleading, never to let her go.
> 
> **Chapter Twenty-Two** (Location 3762)