---
title: "O Sistema Periódico"
author: Primo Levi
date: 2025-07-13
Rating: 8 / 10
---

### Highlights
> Poderia tornar - se deveras uma discussão essencial e fundamental , porque eu também era judeu e ela não : eu sou a impureza que faz reagir o zinco , sou o grão de sal e de mostarda .
> 
> **Zinco** (Location 554)

---

> Começava então a arranhar o alemão e seduzia - me o termo Urstoff ( que significa elemento ; à letra , substância primogénita ) e o prefixo Ur que nele aparecia exprime , efetivamente , origem antiga , distância remota no espaço e no tempo .
> 
> **Ferro** (Location 598)

---

> Hoje sei que é uma empresa sem esperança revestir um homem de palavras , fazê - lo reviver numa página escrita : um homem do tipo de Sandro . Não era homem de quem se podia falar ou a quem se podia erguer monumentos , ele que ria dos monumentos ; estava tudo nas ações , e , terminadas essas , nada sobrava dele ; nada de facto , senão , palavras .
> 
> **Ferro** (Location 758)

---

> Seria preciso recomeçar do nada , « inventar » um antifascismo nosso , acreditar nele desde o gérmen , desde a raiz , desde as nossas raízes . Procurávamos à nossa volta e sugeríamos estradas que não iam longe . A Bíblia , a Cruz , a Geometria , a Física pareciam - nos fontes de certeza .
> 
> **Potássio** (Location 791)

---

> Depois de ter sido devorado no liceu pelas verdades reveladas pela doutrina do fascismo , todas as verdades reveladas , mas não demonstradas , aborreciam - me e enchiam - me de desconfiança .
> 
> **Potássio** (Location 806)

---

> Se é verdade que não há dor maior do que recordarmos uma época feliz em tempo de miséria , também é verdade que relembrar a angústia de ânimo leve , serenamente sentados à escrivaninha , é fonte de profunda satisfação .
> 
> **Potássio** (Location 917)

---

> Segundo Alberto , uma pedra de isqueiro valia uma ração de pão , ou seja , um dia de vida ; eu roubara pelo menos quarenta cilindros , de cada um dos quais se podiam extrair três pedras completas . No total , cento e vinte pedras , dois meses de vida para mim e dois para Alberto e , dentro de dois meses , chegariam os Russos e libertar - nos - iam
> 
> **Cério** (Location 2167)

---

> De facto , tal como a Arquitetura , também com a Química acontece que os edifícios « bonitos » , ou seja , simétricos e simples , são igualmente os mais resistentes ; em suma , com as moléculas acontece o mesmo que com as cúpulas das catedrais ou as arcadas das pontes .
> 
> **Azoto** (Location 2677)

---

> Que a aloxana , destinada a embelezar os lábios das mulheres , fosse extraída dos excrementos das galinhas ou das serpentes era um pensamento que não me incomodava minimamente . O ofício de químico ( no meu caso reforçado pela experiência de Auschwitz ) ensina a ultrapassar , mesmo a ignorar , certos horrores que nada têm de necessários ou congénitos : a matéria é a matéria , nem nobre nem vil , infinitamente transformável , e efetivamente não interessa saber qual a sua origem mais próxima .
> 
> **Azoto** (Location 2703)

---

> a perfeição faz parte das histórias que se contam , e não das que se vivem .
> 
> **Vanádio** (Location 3221)

---

> Conheço - me : não possuo prontidão polémica , o adversário distrai - me , interessa - me mais como homem do que como adversário , oiço - o e arrisco - me a acreditar no que diz ; o desdém e o juízo correto vêm depois , aos poucos , quando já não são precisos .
> 
> **Vanádio** (Location 3266)

---

> falara em « ultrapassar o passado » , « Bewältigung der Vergangenheit » ; soube depois que isto é um estereótipo , um eufemismo da Alemanha de hoje , que é universalmente entendido como « redenção do nazismo » ; mas a raiz « walt » , aí existente , aparece também em palavras que significam « domínio » , « violência » e « estupro » e penso que traduzindo a expressão como « distorção do passado » ou « violência exercida no passado » , não se iria muito longe do seu sentido mais profundo .
> 
> **Vanádio** (Location 3330)