---
title: "Secondhand Time"
author: Svetlana Alexievich
date: 2025-12-13
Rating: 8 / 10
---

### Highlights
> In writing, I’m piecing together the history of “domestic,” “interior” socialism. As it existed in a person’s soul. I’ve always been drawn to this miniature expanse: one person, the individual. It’s where everything really happens.
> 
> **Remarks from an Accomplice** (Location 198)

---

> In “The Legend of the Grand Inquisitor,” Dostoevsky stages a debate about freedom. Namely, about the struggle, torment, and tragedy of freedom: “What’s the point of delving into that damn good and evil when the cost is so high?” People are constantly forced to choose between having freedom and having success and stability; freedom with suffering or happiness without freedom. The majority choose the latter.
> 
> **Remarks from an Accomplice** (Location 301)

---

> From a conversation with a university professor: “At the end of the nineties, my students would laugh when I told them stories about the Soviet Union. They were sure that a new future awaited them. Now it’s a different story… Today’s students have truly seen and felt capitalism: the inequality, the poverty, the shameless wealth. They’ve witnessed the lives of their parents, who never got anything out of the plundering of our country. And they’re oriented toward radicalism. They dream of their own revolution, they wear red T-shirts with pictures of Lenin and Che Guevara.”
> 
> **Remarks from an Accomplice** (Location 314)

---

> There’s a new demand for everything Soviet. For the cult of Stalin. Half of the people between the ages of nineteen and thirty consider Stalin an “unrivaled political figure.”
> 
> **Remarks from an Accomplice** (Location 318)

---

> Children were Little Octobrists from age seven to nine, when they would join the Young Pioneers. At fourteen, children could elect to join the Komsomol, the youth division of the Communist Party.
> 
> **Remarks from an Accomplice** (Location 351)

---

> Instead of lullabies, my mother would sing us songs of the Revolution. Now she sings them to her grandchildren. “Are you nuts?” I ask her. She replies, “I don’t know any other songs.”
> 
> **Snatches of Street Noise and Kitchen Conversations (1991–2001)** (Location 527)

---

> Russian novels don’t teach you how to become successful. How to get rich… Oblomov lies on his couch, Chekhov’s protagonists drink tea and complain about their lives…[
> 
> **Snatches of Street Noise and Kitchen Conversations (1991–2001)** (Location 599)

---

> They say that the Communists “lived in mansions and ate black caviar by the spoonful. They built communism for themselves.” My God! I’ve shown you around my “mansion”— a regular two-bedroom apartment, fifty-seven square meters. I haven’t hidden anything from you: my Soviet crystal, my Soviet gold… —But what about the special clinics and food rations, “internal queues” for apartments and government-issued dachas? The Party sanatoriums? —Honestly? All of that existed… it did… But mostly up there…[ Points up.] I was always at the bottom, on the lowest rung.
> 
> **Ten Stories in a Red Interior** (Location 1033)

---

> The people who’d called themselves communists suddenly started confessing that they’d hated communism from the day they were born.
> 
> **Ten Stories in a Red Interior** (Location 1264)

---

> —When our friends get together… Not a word about politics. Everyone came to this by their own path. We all live together: the gentlemen and the comrades. Reds and Whites. But no one wants any more shooting. There’s been enough blood.
> 
> **Ten Stories in a Red Interior** (Location 1476)

---

> Mstislav Rostropovich (1927– 2007) was a Soviet and Russian cellist and conductor. He left the Soviet Union in 1974 and did not return until 1990. In November 1989, Rostropovich famously played a Bach cello suite as the Berlin Wall collapsed around him.
> 
> **Ten Stories in a Red Interior** (Location 2732)

---

> The most important thing is spiritual labor… Books… You can wear the same suit for twenty years, two coats are enough to last a lifetime, but you can’t live without Pushkin or the complete works of Gorky. You’re part of the grand scheme of things, there’s a grand scheme…
> 
> **Ten Stories in a Red Interior** (Location 2862)

---

> …A boy from our class was about to move to Israel… They called an all-school assembly to try to talk him out of it: If your parents want to leave, they can go. We have good orphanages, you can finish school there and remain in the USSR. He was considered a traitor. They kicked him out of the Komsomol. The next day, our whole class was going on a trip to harvest potatoes at a collective farm. He showed up, and they led him off the bus. At assembly, the principal warned everyone that whoever corresponded with him would have a hard time graduating. After he left, we all started writing him letters as a group…
> 
> **Ten Stories in a Red Interior** (Location 3155)

---

> …I remember people walking around empty stores with bags full of Soviet currency…
> 
> **Ten Stories in a Red Interior** (Location 3163)

---

> There were kilometer-long queues outside of the first McDonald’s, stories about it on the news. Educated, intelligent adults saved boxes and napkins from there and would proudly show them off to guests.
> 
> **Ten Stories in a Red Interior** (Location 3202)

---

> “Keep your mouth shut, or else you’ll get a bullet in the back. No one will be held accountable for killing a Jew.”
> 
> **Ten Stories in a Red Interior** (Location 3892)

---

> Another Jewish saying: “When the wind is strong, the trash rises to the top.” Nazi propaganda had infected everyone, and the partisans were anti-Semitic, too.
> 
> **Ten Stories in a Red Interior** (Location 3893)

---

> had already come to terms with living without my mother, but how could I go on without Stalin?
> 
> **Ten Stories in a Red Interior** (Location 5003)

---

> By then, it was perestroika. Gorbachev, the rallies… Everybody was out in the streets. Celebrating. You can write about whatever you want, shout whatever you want wherever you want. Free-dom! Free-dom! No matter what awaited us, the past was finally over. We were waiting for something new to emerge… Impatience was in the air… then we’d get afraid again. For a long time, I was scared of turning on the radio in the morning: What if suddenly it was all over? Like they’d abruptly canceled the whole program? For a long time, I couldn’t believe it was real. I thought they were going to come in the middle of the night and take everyone down to the stadium like they did in Chile…
> 
> **Ten Stories in a Red Interior** (Location 5042)

---

> I wasn’t the one putting those people on the rack or blowing their brains out, that wasn’t me back there putting sharpened pencils through women’s nipples. It’s not me, it’s the system. Even Stalin… even he’d say, “I’m not the one who decides, it’s the Party.” He taught his son: You think that I’m Stalin— you’re wrong! That’s Stalin! And he’d point to the portrait of himself hanging on the wall.
> 
> **Ten Stories in a Red Interior** (Location 5422)

---

> Not a single one of my friends was a communist. For us, communism was inextricably linked with the Terror, the gulag. A cage. We thought it was dead. Gone forever. Twenty years have passed… I go into my son’s room, and what do I see but a copy of Marx’s Das Kapital on his desk, and Trotsky’s My Life on his bookshelf… I can’t believe my eyes! Is Marx making a comeback? Is this a nightmare? Am I awake or am I dreaming?
> 
> **Snatches of Street Noise and Kitchen Conversations (2002–2012)** (Location 5561)

---

> —I wasn’t born in the USSR. If I don’t like something, I go out on the street and protest. I don’t just run my mouth off in the kitchen before going to bed.
> 
> **Snatches of Street Noise and Kitchen Conversations (2002–2012)** (Location 5681)

---

> Revolution is long, hard work. In 1905, the first Russian revolution ended in failure and defeat. But twelve years later, in 1917, it took off so forcefully that it shattered the Tsarist regime to smithereens. We’re going to have our own revolution!
> 
> **Snatches of Street Noise and Kitchen Conversations (2002–2012)** (Location 5710)

---

> Until I was fourteen, we led a cloudless existence. Until perestroika… We did just fine until capitalism arrived, and they started talking about “the market” on TV. No one understood what it was exactly, and no one was explaining anything, either. It all started with being allowed to badmouth Lenin and Stalin.
> 
> **Ten Stories in the Absence of an Interior** (Location 6069)

---

> When I was left home alone, I would put on my mother’s dress and heels and sit on the couch reading Anna Karenina. Society balls, servants, aiguillettes… romantic trysts… I liked everything up to the part when Anna throws herself under the train: What did she do that for? She was beautiful and rich… for love? Not even Tolstoy could convince me… I liked Western novels better because of the bitches in them, the beautiful bitches that men would shoot themselves over and suffer for. Fall at their feet.
> 
> **Ten Stories in the Absence of an Interior** (Location 6395)

---

> A year later, she made another suicide attempt. This one was successful. I learned that her husband had soon found himself another woman. I called her. “I feel sorry for him,” she told me. “I don’t love him, but I pity him. The only trouble is, he started drinking again even though he promised he would quit.” Can you guess what she told me next?
> 
> **Ten Stories in the Absence of an Interior** (Location 7789)

---

> It’s such a Russian story! A woman who’s married with three kids falls in love with a prisoner— and a “lifer,” at that— sentenced to life in prison for a particularly brutal murder. And for him, she abandons everything: her husband, her kids, her home.
> 
> **Ten Stories in the Absence of an Interior** (Location 8192)

---

> Someone put it very accurately: In five years, everything can change in Russia, but in two hundred— nothing.
> 
> **Ten Stories in the Absence of an Interior** (Location 8218)

---

> The whole ride home, he lectured me on common sense: “It’s all bullshit! Nothing but idiocy! In 1991, I was a student in Moscow, I also ran around to demonstrations. There were more of us than there are of you. And we won. We dreamed that every one of us would start a business and get rich. And what do you think happened? When the Communists were in power, I was an engineer— now I’m a cabbie.
> 
> **Ten Stories in the Absence of an Interior** (Location 8749)