---
title: "Silence"
author: John Cage
date: 2025-11-6
Rating: 7 / 10
---

### Highlights
> “I’ve had more response from the book,” he said, “than I’ve ever had from the publication of a record, the publication of music, the giving of a concert, the giving of a lecture or anything.”
> 
> **Foreword to 50th Anniversary Edition** (Location 215)

---

> As I see it, poetry is not prose simply because poetry is in one way or another formalized. It is not poetry by reason of its content or ambiguity but by reason of its allowing musical elements (time, sound) to be introduced into the world of words.
> 
> **Foreword** (Location 503)

---

> There is no such thing as an empty space or an empty time. There is always something to see, something to hear. In fact, try as we may to make a silence, we cannot.
> 
> **Experimental Music** (Location 635)

---

> Which is more musical, a truck passing by a factory or a truck passing by a music school? Are the people inside the school musical and the ones outside unmusical? What if the ones inside can’t hear very well, would that change my question?
> 
> **Composition as Process** (Location 1420)