---
title: "Terra Sonâmbula"
author: Mia Couto
date: 2025-11-28
Rating: 9 / 10
---

### Highlights
> Disse que havia duas maneiras de partir: uma era ir embora, outra era enlouquecer. Meu pai escolhera os dois caminhos, um pé na doideira de partir, outro na loucura de ficar.
> 
> **Primeiro caderno de Kindzu** (Location 382)

---

> — O senhor está bem-disposto, não é, pai? — Sim, estou. Fez-me bem morrer.
> 
> **Segundo caderno de Kindzu** (Location 613)

---

> Então ele mete o dedo no ouvido, vai enfiando mais e mais fundo até que sentem o surdo som de qualquer coisa se estourando. O velho tira o dedo e um jorro de sangue repuxa da orelha. Ele se vai definhando, até se tornar do tamanho de uma semente.
> 
> **Quarto capítulo** (Location 945)

---

> Afinal, todos queremos no peito o nó de um outro peito, o devolver da metade que perdemos ao nascer.
> 
> **Quarto caderno de Kindzu** (Location 1051)

---

> A chuva redigia suas gordas gotas, hesitantes entre trovoar e tropousar. As nuvens se acotovelavam, sem gentileza. Podiam se tocar, pedirem desculpa e continuar caminho. Enquanto não: brigavam, cuspiam lumes, resmungos celestiais.
> 
> **Quinto caderno de Kindzu** (Location 1315)

---

> A riqueza é como o sal: só serve para temperar.
> 
> **Sexto caderno de Kindzu** (Location 1511)

---

> não somos nós que estamos a andar. É a estrada.
> 
> **Oitavo capítulo** (Location 1911)

---

> Tudo acontecera na vizinhança do autocarro. Era o país que desfilava por ali, sonhambulante.
> 
> **Oitavo capítulo** (Location 1915)

---

> Como sempre fizera, saudaria a locomotiva em solene continência. As carruagens arrastariam seu suspiro de ferros, as meninas correriam com seus cestos vendendo frutas e a vida se banharia de luzes e vozes.
> 
> **Oitavo capítulo** (Location 1