---
title: "The Brothers Karamazov"
author: Fyodor Dostoevsky
date: 2025-06-19
Rating: 10 / 10
---

### Highlights
> I am the kind of woman who works for a reward, and I want the reward at once, in the form of praise for myself and reciprocated love. I am incapable of loving anyone on any other terms!’
> 
> **The Brothers Karamazov** (Location 1841)

---

> “I love mankind,” he said, “but I marvel at myself: the more I love mankind in general, the less I love human beings in particular, separately, that is, as individual persons.
> 
> **The Brothers Karamazov** (Location 1846)

---

> If you do not reach happiness, always remember that you are on the right road, and try not to deviate from it. The main thing is to shun lies, all forms of lies, lies to yourself in particular. Keep a watch on your lies and study them every hour, every minute. Also shun disdain, both for others and for yourself: that which appears to you foul within yourself is cleansed by the very fact of your having noticed it in you. Also shun fear, although fear is only the consequence of any kind of lying. Never be daunted by your own lack of courage in the attainment of love, nor be over-daunted even by your bad actions in this regard.
> 
> **The Brothers Karamazov** (Location 1862)

---

> The horror of it is that beauty is not only a terrifying thing – it is also a mysterious one. In it the Devil struggles with God, and the field of battle is the hearts of men. And as a matter of fact, it’s natural that those who are in pain should talk about it.
> 
> **The Brothers Karamazov** (Location 3066)

---

> It isn’t God I don’t accept, you see; it’s the world created by Him, the world of God I don’t accept and cannot agree to accept.
> 
> **The Brothers Karamazov** (Location 6032)

---

> It isn’t God I don’t accept, Alyosha, it’s just his ticket that I most respectfully return to him.’
> 
> **The Brothers Karamazov** (Location 6273)

---

> That could have been one of the best bits in my poem – I mean, the question of why it is that everyone recognizes him.
> 
> **The Brothers Karamazov** (Location 6361)

---

> They will exclaim at last that the truth is not in you, for it would have been impossible to leave them in more confusion and torment than you did when you left them so many worries and unsolvable problems.
> 
> **The Brothers Karamazov** (Location 6507)

---

> Bear in mind particularly that you can be no man’s judge. For a criminal can have no judge upon the earth until that judge himself has perceived that he is every bit as much a criminal as the man who stands before him, and that for the crime of the man who stands before him he himself may well be more guilty than anyone else. Only when he grasps this may he become a judge.
> 
> **The Brothers Karamazov** (Location 8015)

---

> ‘Voltaire did believe in God, but I doubt if it was very much, and I doubt if he loved mankind very much either,’
> 
> **The Brothers Karamazov** (Location 13327)

---

> ‘A socialist?’ Alyosha began to laugh. ‘And where did you find time for that? After all, you are only thirteen, are you not?’
> 
> **The Brothers Karamazov** (Location 13336)