---
title: "The Age of Empire: 1875–1914"
author: Eric Hobsbawm
date: 2025-03-13
Rating: 7 / 10
---

### Highlights
> Essentially the central axis round which I have tried to organize the history of the century is the triumph and transformation of capitalism in the historically specific forms of bourgeois society in its liberal version.
> 
> **Overture** (Location 248)

---

> The first volume of this history, The Age of Revolution 1789– 1848, is structured round this concept of a ‘dual revolution’.
> 
> **Overture** (Location 254)

---

> This is the main theme of the second volume, which covers the brief period between the 1848 revolutions and the onset of the 1870s Depression,
> 
> **Overture** (Location 257)

---

> In short, the major obstacles to continued and presumably unlimited bourgeois progress seemed to have been removed. The possible difficulties arising from the inner contradictions of this progress did not yet seem to be cause for immediate anxiety.
> 
> **Overture** (Location 263)

---

> The Age of Empire, on the other hand, is penetrated and dominated by these contradictions.
> 
> **Overture** (Location 265)

---

> Indeed, its basic pattern, as seen in this book, is of the society and world of bourgeois liberalism advancing towards what has been called its ‘strange death’ as it reaches its apogee, victim of the very contradictions inherent in its advance.
> 
> **Overture** (Location 282)

---

> For better or worse, since 1914 the century of the bourgeoisie belongs to history.
> 
> **Overture** (Location 318)

---

> Perhaps nothing illustrates the identity crisis through which bourgeois society passed in this period better than the history of the arts from the 1870s to 1914.
> 
> **9 The Arts Transformed** (Location 4796)

---

> The real dividing-line runs through the period itself. It is the experimental avant garde of the last pre-war years which, outside a small community of the ‘advanced’ – intellectuals, artists and critics and the fashion-conscious – was never to find a genuine, spontaneous welcome among the broad public.
> 
> **9 The Arts Transformed** (Location 4827)

---

> But the crux of the crisis of the arts lay in the growing divergence between what was contemporary and what was ‘modern’.
> 
> **9 The Arts Transformed** (Location 4945)

---

> the visible break between the fin de siècle and the twentieth-century avant gardes occurred some time between 1900 and 1910. Amateurs of dates may choose between several, but the birth of Cubism in 1907 is as convenient as any.
> 
> **9 The Arts Transformed** (Location 5125)

---

> the avant garde henceforth found itself marching in directions the main army of the public was neither willing nor able to follow.
> 
> **9 The Arts Transformed** (Location 5128)

---

> A wide gap therefore opened between the main body of ‘cultured’ taste and the various small minorities who asserted their status as dissident anti-bourgeois rebels by demonstrating admiration for styles of artistic creation inaccessible and scandalous to the majority.
> 
> **9 The Arts Transformed** (Location 5132)

---

> It is therefore misleading to pay too much attention to the ‘modernist’ avant garde before 1914, except as ancestors.
> 
> **9 The Arts Transformed** (Location 5141)

---

> what they did not achieve was the actual cultural revolution of the twentieth century they aimed
> 
> **9 The Arts Transformed** (Location 5149)

---

> Few figures represent the old tradition, in its conventional and revolutionary versions, more obviously than two composers of pre-1914 Vienna: Erich Wolfgang Korngold, an infant prodigy of the middlebrow musical scene already launching himself into symphonies, operas and the rest; and Arnold Schönberg. The first ended his life as a highly successful composer of sound tracks for Hollywood motion pictures and musical director of Warner Brothers. The second, after revolutionizing nineteenth-century classical music, ended his life in the same city, still without a public, but admired and subsidized by more adaptable and vastly more prosperous musicians who earned money in the motion picture industry by not applying the lessons they had learned from him.
> 
> **9 The Arts Transformed** (Location 5271)

---

> The arts of the twentieth century were therefore revolutionized, but not by those who set themselves the task of doing so. In this respect they differed dramatically from the sciences.
> 
> **9 The Arts Transformed** (Location 5277)

---

> The process of divorcing science and intuition may perhaps be illustrated by the extreme example of mathematics. Some time in the middle of the nineteenth century the progress of mathematical thought began to generate not only (as it had already done earlier – see The Age of Revolution) results which conflicted with the real world as apprehended by the senses, such as non-Euclidean geometry, but results which appeared shocking even to mathematicians, who found, like the great Georg Cantor, that ‘je vois mais ne le crois pas’.
> 
> **10 Certainties Undermined: The Sciences** (Location 5333)

---

> Mathematics was henceforth based on a rigorous suspension of belief in anything except the rules of a game.
> 
> **10 Certainties Undermined: The Sciences** (Location 5345)

---

> Moreover, the rethinking of the foundations of mathematics itself was far from unproblematic, for the attempt to base it on rigorous definitions and non-contradiction itself (which also stimulated the development of mathematical logic) ran into difficulties which were to turn the period between 1900 and 1930 into the ‘great crisis of the foundations’ (Bourbaki).
> 
> **10 Certainties Undermined: The Sciences** (Location 5363)

---

> Eventually (in 1931) the Austrian mathematician Kurt Gödel proved that for certain fundamental purposes contradiction could not be eliminated at all: we cannot prove that the axioms of arithmetic are consistent by a finite number of steps which do not lead to contradictions.
> 
> **10 Certainties Undermined: The Sciences** (Location 5370)

---

> In short science henceforth became not only something which few people could understand, but something of which many disapproved while increasingly recognizing that they depended on it.
> 
> **10 Certainties Undermined: The Sciences** (Location 5385)

---

> But in a mechanically conceived physical universe waves had to be waves in something, just as seawaves were waves in water.
> 
> **10 Certainties Undermined: The Sciences** (Location 5393)

---

> In short, what made the revolution in physics so revolutionary was not the discovery of new facts, though this certainly look place, but the reluctance of physicists to reconsider their paradigms.
> 
> **10 Certainties Undermined: The Sciences** (Location 5437)

---

> biology was essential to a theoretically egalitarian bourgeois ideology, since it passed the blame for visible human inequalities from society to ‘nature’
> 
> **10 Certainties Undermined: The Sciences** (Location 5495)

---

> Hence biology was not only potentially the science of the political right, but the science of those who suspected science, reason and progress.
> 
> **10 Certainties Undermined: The Sciences** (Location 5498)

---

> Neither Planck nor Einstein was prepared to give up the rational, causal, determinist universe which their work did so much to destroy.
> 
> **10 Certainties Undermined: The Sciences** (Location 5585)

---

> Keynes is worth singling out because he formulated what was to be the most intellectually and politically influential way of saying that capitalist society could only survive if capitalist states controlled, managed and even planned much of the general shape of their economies, if necessary turning themselves into mixed public/ private economies.
> 
> **13 From Peace to War** (Location 7222)