---
title: "The Age of Revolution: 1789-1848"
author: Eric Hobsbawm
date: 2025-02-07
Rating: 9 / 10
---

### Highlights
> Our problem is thus to explain not the existence of these elements of a new economy and society, but their triumph;
> 
> **Início** (Location 143)

---

> the history of the dual revolution is not merely one of the triumph of the new bourgeois society. It is also the history of the emergence of the forces which were, within a century of 1848, to have turned expansion into contraction.
> 
> **Início** (Location 156)

---

> within Europe the forces and ideas which envisaged the supersession of the triumphant new society, were already emerging.
> 
> **Início** (Location 162)

---

> the world of 1789 was overwhelmingly rural, and nobody can understand it who has not absorbed this fundamental fact.
> 
> **Início** (Location 256)

---

> Economically, however, western rural society was very different.
> 
> **Início** (Location 379)

---

> The characteristic estate had long ceased to be a unit of economic enterprise and had become a system of collecting rents and other money incomes.
> 
> **Início** (Location 380)

---

> Only a few areas had pushed agrarian development one stage further towards a purely capitalist agriculture. England was the chief of these.
> 
> **Início** (Location 389)

---

> But the key controller of these decentralized forms of production, the one who linked the labour of lost villages or back streets with the world market, was some kind of merchant.
> 
> **Início** (Location 445)

---

> The sciences, not yet split by nineteenth-century academicism into a superior ‘pure’ and an inferior ‘applied’ branch, devoted themselves to the solution of productive problems: the most striking advances of the 1780s were those of chemistry, which was by tradition most closely linked to workshop practice and the needs of industry.
> 
> **Início** (Location 452)

---

> Yet in practice the leaders of the emancipation for which the enlightenment called were likely to be the middle ranks of society, the new, rational men of ability and merit rather than birth,
> 
> **Início** (Location 484)

---

> It is more accurate to call the ‘enlightenment’ a revolutionary ideology,
> 
> **Início** (Location 486)

---

> absolute monarchies ruled in all functioning states of the European continent;
> 
> **Início** (Location 493)

---

> What did abolish agrarian feudal relations all over Western and Central Europe was the French Revolution, by direct action, reaction or example, and the revolution of 1848.
> 
> **Início** (Location 521)

---

> This was the conflict between Britain and France, which was also, in a sense, that between the old and the new régimes.
> 
> **Início** (Location 541)

---

> In the late eighteenth century several of the great non-European powers and civilizations still confronted the white trader, sailor and soldier on apparently equal terms.
> 
> **Início** (Location 554)

---

> It is only in the 1830s that literature and the arts began to be overtly haunted by that rise of the capitalist society, that world in which all social bonds crumbled except the implacable gold and paper ones of the cash nexus
> 
> **Início** (Location 603)

---

> Not until the 1820s did English and French socialists— themselves an unprecedented group— invent it, probably by analogy with the political revolution of France.
> 
> **Início** (Location 611)

---

> some time in the 1780s, and for the first time in human history, the shackles were taken off the productive power of human societies,
> 
> **Início** (Location 617)

---

> By any reckoning this was probably the most important event in world history, at any rate since the invention of agriculture and cities.
> 
> **Início** (Location 640)

---

> Whatever the British advance was due to, it was not scientific and technological superiority.
> 
> **Início** (Location 648)

---

> But the right conditions were visibly present in Britain, where more than a century had passed since the first king had been formally tried and executed by his people, and since private profit and economic development had become accepted as the supreme objects of government policy.
> 
> **Início** (Location 674)

---

> Latin America came to depend virtually entirely on British imports during the Napoleonic Wars, and after it broke with Spain and Portugal (see pp. 109– 10, 239 below) it became an almost total economic dependency of Britain,
> 
> **Início** (Location 759)

---

> Cotton was the first industry to be revolutionized, and it is difficult to see what other could have pushed a host of private entrepreneurs into revolution.
> 
> **Início** (Location 803)

---

> In 1830 ‘industry’ and ‘factory’ in anything like the modern sense still meant almost exclusively the cotton areas of the United Kingdom.
> 
> **Início** (Location 810)

---

> Its most serious consequences were social: the transition to the new economy created misery and discontent, the materials of social revolution.
> 
> **Início** (Location 836)

---

> The industry was thus under immense pressure to mechanize (i.e. to lower costs by labour-saving) to rationalize and to expand its production and sales, thus making up by the mass of small profits per unit for the fall in the margins.
> 
> **Início** (Location 915)

---

> This immense industry, though probably not expanding fast enough for really massive industrialization on the modern scale, was sufficiently large to stimulate the basic invention which was to transform the capital goods industries: the railway.
> 
> **Início** (Location 950)

---

> The iron road, pushing its huge smoke-plumed snakes at the speed of wind across countries and continents, whose embankments and cuttings, bridges and stations, formed a body of public building beside which the pyramids and the Roman aqueducts and even the Great Wall of China paled into provincialism, was the very symbol of man’s triumph through technology.
> 
> **Início** (Location 966)

---

> the immense appetite of the railways for iron and steel, for coal, for heavy machinery, for labour, for capital investment, was at this stage more important. For it provided just that massive demand which was needed if the capital goods industries were to be transformed as profoundly as the cotton industry had been.
> 
> **Início** (Location 974)

---

> All these in turn were achieved by social rather than technological transformation: by the liquidation of medieval communal cultivation with its open field and common pasture (the ‘enclosure movement’), of self-sufficient peasant farming, and of old-fashioned uncommercial attitudes towards the land. Thanks to the preparatory evolution of the sixteenth to eighteenth centuries this uniquely radical solution of the agrarian problem, which made Britain a country of a few large landowners, a moderate number of commercial tenant farmers and a great number of hired labourers,
> 
> **Início** (Location 1049)

---

> In this rather haphazard, unplanned and empirical way the first major industrial economy was built.
> 
> **Início** (Location 1118)

---

> France provided the first great example, the concept and the vocabulary of nationalism.
> 
> **Início** (Location 1213)

---

> It is no accident that the American revolutionaries, and the British ‘Jacobins’ who migrated to France because of their political sympathies, found themselves moderates in France.
> 
> **Início** (Location 1230)

---

> alone of all the contemporary revolutions, the French was ecumenical. Its armies set out to revolutionize the world; its ideas actually did so.
> 
> **Início** (Location 1234)

---

> Its repercussions rather than those of the American revolution, occasioned the risings which led to the liberation of Latin America after 1808.
> 
> **Início** (Location 1237)

---

> Victory over England was gained at the cost of final bankruptcy, and thus the American Revolution can claim to be the direct cause of the French.
> 
> **Início** (Location 1305)

---

> The second, and decisive, was the desperate decision to call the States-General— the old feudal assembly of the realm, buried since 1614.
> 
> **Início** (Location 1312)

---

> ‘the philosophers’ can be justly made responsible for the Revolution. It would have occurred without them; but they probably made the difference between a mere breakdown of an old régime and the effective and rapid substitution of a new one.
> 
> **Início** (Location 1321)

---

> The most sensational result of their mobilization was the capture of the Bastille, a state prison symbolizing royal authority, where the revolutionaries expected to find arms. In times of revolution nothing is more powerful than the fall of symbols.
> 
> **Início** (Location 1376)

---

> The peculiarity of the French Revolution is that one section of the liberal middle class was prepared to remain revolutionary up to and indeed beyond the brink of anti-bourgeois revolution: these were the Jacobins,
> 
> **Início** (Location 1401)

---

> Most of the lasting institutional achievements of the Revolution date from this period, as do its most striking international results, the metric system and the pioneer emancipation of the Jews.
> 
> **Início** (Location 1431)

---

> every genuine revolution tends to be ecumenical.
> 
> **Início** (Location 1458)

---

> The iron and heroic age of the French Revolution began among the massacres of the political prisoners, the elections to the National Convention— probably the most remarkable assembly in the history of parliamentarism— and the call for total resistance to the invaders.
> 
> **Início** (Location 1476)

---

> the young French Republic discovered or invented total war: the total mobilization of a nation’s resources through conscription, rationing and a rigidly controlled war economy, and virtual abolition, at home or abroad, of the distinction between soldiers and civilians.
> 
> **Início** (Location 1487)

---

> The very names of the moderate revolutionaries who come between Mirabeau and Lafayette in 1789 and the Jacobin leaders in 1793, have lapsed from all but the memory of historians.
> 
> **Início** (Location 1507)

---

> In June 1793 sixty out of the eighty departments of France were in revolt against Paris; the armies of the German princes were invading France from the north and east; the British attacked from the south and west: the country was helpless and bankrupt. Fourteen months later all France was under firm control, the invaders had been expelled, the French armies in turn occupied Belgium and were about to enter on twenty years of almost unbroken and effortless military triumph.
> 
> **Início** (Location 1517)

---

> Within a few years France had a Civil Code, a concordat with the Church and even, most striking symbol of bourgeois stability, a National Bank. And the world had its first secular myth.
> 
> **Início** (Location 1641)

---

> Two very different kinds of belligerents confronted one another during those twenty-odd years: powers and systems.
> 
> **Início** (Location 1716)

---

> Broadly speaking, therefore, the military value of foreign philo-Jacobinism was chiefly that of an auxiliary to French conquest, and a source of politically reliable administrators of conquered territories.
> 
> **Início** (Location 1799)

---

> One foreign pro-French movement alone might have been decisive, had it been effectively exploited: the Irish. A combination of Irish revolution and French invasion, particularly in 1797– 8 when Britain was temporarily the only belligerent left in the field against France, might well have forced Britain to make peace.
> 
> **Início** (Location 1810)

---

> These advantages did not depend on any man’s military genius, for the military record of the French before Napoleon took charge was striking enough, and the average quality of French generalship was not exceptional.
> 
> **Início** (Location 1887)

---

> The French army’s methods as we have seen assumed rapid campaigns in areas sufficiently wealthy and densely peopled for it to live off the land. But what worked in Lombardy or the Rhineland, where such procedures had been first developed, and was still feasible in central Europe, failed utterly in the vast, empty and impoverished spaces of Poland and Russia.
> 
> **Início** (Location 1915)

---

> In terms of political geography, the French Revolution ended the European middle ages. The characteristic modern state, which had been evolving for several centuries, is a territorially coherent and unbroken area with sharply defined frontiers, governed by a single sovereign authority and according to a single fundamental system of administration and law.
> 
> **Início** (Location 1928)

---

> Feudalism, once officially abolished, was nowhere re-established.
> 
> **Início** (Location 1973)

---

> No area affected by the wars of 1792– 1815, not even in the Iberian peninsula, where military operations were more prolonged than anywhere else and popular resistance and reprisal made them more savage, was devastated as parts of Central and Eastern Europe were in the Thirty Years’ and Northern Wars of the seventeenth century,
> 
> **Início** (Location 2015)

---

> The economic requirements of war, and economic warfare, had more far-reaching consequences. By the standards of the eighteenth century, the revolutionary and Napoleonic wars were expensive beyond precedent; and indeed their cost in money impressed contemporaries perhaps even more than their cost in lives.
> 
> **Início** (Location 2060)

---

> In monetary terms the British carried by far the heaviest load during the war: it cost them between three and four times as much as it did the French.
> 
> **Início** (Location 2135)

---

> apart from the Crimean War, there was no war involving more than two great powers between 1815 and 1914.
> 
> **Início** (Location 2200)

---

> Our generation, which has failed so much more spectacularly in the fundamental task of international diplomacy, that of avoiding general wars, has therefore tended to look back upon the statesmen and methods of 1815– 48 with a respect that their immediate successors did not always feel.
> 
> **Início** (Location 2210)

---

> The map of Europe was redrawn without concern for either the aspirations of the peoples or the rights of the numerous princes dispossessed at one time or another by the French, but with considerable concern for the balance of the five great powers which emerged from the wars: Russia, Britain, France, Austria and Prussia.
> 
> **Início** (Location 2227)

---

> The British were satisfied. They had by 1815 gained the most complete victory of any power in the entire history of the world, having emerged from the twenty years of war against France as the only industrialized economy, the only naval power— the British navy in 1840 had almost as many ships as all other navies put together— and virtually the only colonial power in the world.
> 
> **Início** (Location 2331)

---

> The revolutionary wave of 1830 was therefore a much more serious affair than that of 1820. In effect, it marks the definitive defeat of aristocratic by bourgeois power in Western Europe.
> 
> **Início** (Location 2427)

---

> Whichever aspect of social life we survey, 1830 marks a turning-point in it; of all the dates between 1789 and 1848 it is the most obviously memorable. In the history of industrialization and urbanization on the continent and in the USA, in the history of human migrations, social and geographical, in that of the arts and of ideology, it appears with equal prominence.
> 
> **Início** (Location 2442)

---

> There has never been anything closer to the world-revolution of which the insurrectionaries of the period dreamed than this spontaneous and general conflagration, which concludes the era discussed in this volume.
> 
> **Início** (Location 2449)

---

> Unlike the revolutions of the late eighteenth century, those of the post-Napoleonic period were intended or even planned.
> 
> **Início** (Location 2452)

---

> All revolutionaries regarded themselves, with some justification, as small élites of the emancipated and progressive operating among, and for the eventual benefit of, a vast and inert mass of the ignorant and misled common people, which would no doubt welcome liberation when it came, but could not be expected to take much part in preparing
> 
> **Início** (Location 2506)

---

> The second result was that, with the progress of capitalism, ‘the people’ and ‘the labouring poor’— i.e. the men who built barricades— could be increasingly identified with the new industrial proletariat as ‘the working class’. A proletarian-socialist revolutionary movement therefore came into existence.
> 
> **Início** (Location 2549)

---

> small farmers, craftsmen and urban poor) for any purpose whatever. But in Western Europe where social revolution by the urban poor was a real possibility, and in the large European zone of agrarian revolution, the question whether or not to appeal to the masses was urgent and unavoidable.
> 
> **Início** (Location 2635)

---

> Marx and Engels’s Communist Manifesto is a declaration of future war against the bourgeoisie but— at least for Germany— of present alliance.
> 
> **Início** (Location 2791)

---

> But it was strong enough neither to inspire a revolution nor to safeguard against one.
> 
> **Início** (Location 5117)

---

> In its political thought classical liberalism thus swerved from the daring and rigour which made it so powerful a revolutionary force. In its economic thought, however, it was less inhibited;
> 
> **Início** (Location 5125)

---

> In the first place it broke radically with the liberal assumption that society was a mere aggregate or combination of its individual atoms, and that its motive force was their self-interest and competition. In doing so the socialists returned to the oldest of all human ideólogical traditions, the belief that man is naturally a communal being.
> 
> **Início** (Location 5255)

---

> For the classical liberals, and indeed the earliest modern socialists, their proposals were natural and rational, as distinct from the artificial and irrational society which ignorance and tyranny had hitherto imposed on the world.
> 
> **Início** (Location 5272)

---

> possibly of inevitable evolution through stages of historical development. But it was not until Karl Marx (1818– 83) transferred the centre of gravity of the argument for socialism from its rationality or desirability to its historic inevitability that socialism acquired its most formidable intellectual weapon, against which polemical defences are still being erected.
> 
> **Início** (Location 5284)

---

> In the first half of the nineteenth century Russian literature and music suddenly emerged as a world force,
> 
> **Início** (Location 5523)

---

> Probably no half-century contains a greater concentration of immortal novelists:
> 
> **Início** (Location 5529)

---

> Music is perhaps an even more striking case. The standard concert repertoire still rests largely on the composers active in this period—
> 
> **Início** (Location 5531)

---

> German painting came nowhere near the unique triumphs of German literature or music,
> 
> **Início** (Location 5541)

---

> If a single misleading sentence is to sum up the relations of artist and society in this era, we might say that the French Revolution inspired him by its example, the Industrial Revolution by its horror, and the bourgeois society, which emerged from both, transformed his very existence and modes of creation.
> 
> **Início** (Location 5546)

---

> Naturally enough, such nationalism found its most obvious cultural expression in literature and in music;
> 
> **Início** (Location 5563)

---

> It is equally understandable that the arts traditionally dependent on commissions from the established ruling classes, courts and governments, architecture and sculpture and to a lesser extent painting, reflected these national revivals less.iii
> 
> **Início** (Location 5564)

---

> However, though it is by no means clear what romanticism stood for, it is quite evident what it was against: the middle. Whatever its content, it was an extremist creed. Romantic artists or thinkers in the narrower sense are found on the extreme left, like the poet Shelley, on the extreme right, like Chateaubriand and Novalis, leaping from left to right like Wordsworth, Coleridge and numerous disappointed supporters of the French Revolution, leaping from royalism to the extreme left like Victor Hugo, but hardly ever among the moderates or whig-liberals in the rationalist centre, which indeed was the stronghold of’classicism’.
> 
> **Início** (Location 5612)

---

> The second generation of British romantics— that of Byron (1788– 1824), the unpolitical but fellow-travelling Keats (1795-1821) and above all Shelley (1792-1822)— was the first thus to combine romanticism and active revolutionism: the disappointments of the French Revolution, unforgotten by most of their elders, paled beside the visible horrors of the capitalist transformation in their own country.
> 
> **Início** (Location 5803)

---

> The most striking consequence of this junction of romanticism with vision of a new and higher French Revolution was the overwhelming victory of political art between 1830 and 1848.
> 
> **Início** (Location 5819)

---

> Nevertheless even the most passionate believer in the unsullied purity of pure science is aware that scientific thought may at least be influenced by matters outside the specific field of a discipline, if only because scientists, even the most unworldly of mathematicians, live in a wider world.
> 
> **Início** (Location 6048)

---

> The skills which revolutionized these were those of empirical— too empirical— men. The hero of the British railway revolution was George Stephenson, a scientific illiterate, but a man who could smell what would make a machine go: a super-craftsman rather than a technologist.
> 
> **Início** (Location 6063)

---

> The French Revolution transformed the scientific and technical education of its country, chiefly by setting up the Ecole Polytechnique (1795)— intended as a school for technicians of all sorts— and the first sketch of the Ecole Normale Supérieure (1794) which was firmly established as part of a general reform of secondary and higher education by Napoleon.
> 
> **Início** (Location 6068)

---

> Henceforth the scientist stayed within his linguistic area, except for shorter visits, communicating with his colleagues through the medium of the learned journals, which are so typical a product of this period:
> 
> **Início** (Location 6104)

---

> A revolution even more profound but, by the nature of the subject, less obvious than in chemistry took place in mathematics. Unlike physics, which remained within the seventeenth-century terms of reference, and chemistry, which fanned out on a broad front through the gap opened in the eighteenth, mathematics in our period entered an entirely new universe, far beyond the world of the Greeks, which still dominated arithmetic and plane geometry, and that of the seventeenth century, which dominated analysis.
> 
> **Início** (Location 6141)

---

> The mathematical revolution passed unperceived except by a few specialists in subjects notorious for their remoteness from everyday life. The revolution in the social sciences, on the other hand, could hardly fail to strike the layman, because it visibly affected him, generally, it was believed, for the worse.
> 
> **Início** (Location 6154)

---

> But philology was also fortunate, because of all the social sciences it dealt not directly with human beings, who always resent the suggestion that their actions are determined by anything except their free choice, but with words, which do not.
> 
> **Início** (Location 6230)

---

> The firm construction of scientific bases for the study of human society did not take place until the second half of the century.
> 
> **Início** (Location 6297)
