---
title: "The Age of Capital: 1848-1875"
author: Eric Hobsbawm
date: 2025-02-25
Rating: 9 / 10
---

### Highlights
> Political revolution retreated, industrial revolution advanced.
> 
> **Maps** (Location 151)

---

> The sudden, vast and apparently boundless expansion of the world capitalist economy provided political alternatives in the ‘advanced’ countries. The (British) industrial revolution had swallowed the (French) political revolution.
> 
> **Maps** (Location 159)

---

> It is the era of the triumphant bourgeois, though the European bourgeoisie still hesitated to commit itself to public political rule. To this – and perhaps only to this – extent the age of revolution was not dead. The middle classes of Europe were frightened and remained frightened of the people: ‘democracy’ was still believed to be the certain and rapid prelude to ‘socialism’.
> 
> **Maps** (Location 163)

---

> Within weeks, indeed in the case of the Manifesto within hours, the hopes and fears of the prophets seemed to be on the verge of realization. The French monarchy was overthrown by insurrection, the Republic proclaimed, and the European revolution had begun.
> 
> **PART ONE: REVOLUTIONARY PRELUDE** (Location 247)

---

> Moreover, 1848 was the first potentially global revolution, whose direct influence may be detected in the 1848 insurrection in Pernambuco (Brazil) and a few years later in remote Colombia.
> 
> **PART ONE: REVOLUTIONARY PRELUDE** (Location 258)

---

> Within six months of its outbreak its universal defeat was safely predictable,
> 
> **PART ONE: REVOLUTIONARY PRELUDE** (Location 262)

---

> During the first few months all governments in the revolutionary zone were swept away or reduced to impotence. All collapsed or retreated virtually without resistance. Yet within a relatively short period the revolution had lost the initiative almost everywhere:
> 
> **PART ONE: REVOLUTIONARY PRELUDE** (Location 327)

---

> All the revolutions had something else in common, which largely accounts for their failure. They were, in fact or immediate anticipation, social revolutions of the labouring poor.
> 
> **PART ONE: REVOLUTIONARY PRELUDE** (Location 357)

---

> Eighteen forty-eight failed because it turned out that the decisive confrontation was not that between the old regimes and the united ‘forces of progress’, but between ‘order’ and ‘social revolution’.
> 
> **PART ONE: REVOLUTIONARY PRELUDE** (Location 397)

---

> the bourgeoisie, as we have seen, discovered that it preferred order to the chance of implementing its full programme, when faced with the threat to property.
> 
> **PART ONE: REVOLUTIONARY PRELUDE** (Location 447)

---

> In 1848– 9 moderate liberals therefore made two important discoveries in western Europe: that revolution was dangerous and that some of their substantial demands (especially in economic matters) could be met without it. The bourgeoisie ceased to be a revolutionary force.
> 
> **PART ONE: REVOLUTIONARY PRELUDE** (Location 457)

---

> But, unlike Lenin in 1917, Marx did not conceive of the substitution of proletarian for bourgeois revolution until after the defeat of 1848;
> 
> **PART ONE: REVOLUTIONARY PRELUDE** (Location 534)

---

> Thus the revolutions of 1848 surged and broke like a great wave, leaving little behind except myth and promise. They ‘ought to have been’ bourgeois revolutions, but the bourgeoisie drew back from them.
> 
> **PART ONE: REVOLUTIONARY PRELUDE** (Location 538)

---

> Louis Napoleon’s election signified that even the democracy of universal suffrage, that institution identified with revolution, was compatible with the maintenance of social order.
> 
> **PART ONE: REVOLUTIONARY PRELUDE** (Location 584)

---

> The revolutions of 1848 made it clear that the middle classes, liberalism, political democracy, nationalism, even the working classes, were henceforth permanent features of the political landscape.
> 
> **PART ONE: REVOLUTIONARY PRELUDE** (Location 591)

---

> A bourgeois, a man of the moderate liberal left, and unquestionably ready to confront the forces of conservatism and religion from the late 1850s (though not before), he politely rejected the offer of Karl Marx to dedicate the second volume of Capital to him. He was not, after all, a revolutionary.
> 
> **PART THREE: RESULTS** (Location 5607)

---

> The first, and most apparently novel, was the emergence of independent working-class parties and movements, generally with a socialist (i.e. increasingly a Marxist) orientation, of which the German Social Democratic Party was both the pioneer and the most impressive example.
> 
> **PART THREE: RESULTS** (Location 6628)
