---
title: "Um Copo de Cólera"
author: Raduan Nassar
date: 2025-07-04
Rating: 9 / 10
---

### Highlights
> não que me metessem medo as unhas que ela punha nas palavras, eu também, além das caras amenas (aqui e ali quem sabe marota), sabia dar ao verbo o reverso das carrancas e das garras, sabia, incisivo como ela, morder certeiro com os dentes das idéias, já que era com esses cacos que se compunham de hábito nossas intrigas,
> 
> **Um copo de cólera** (Location 216)

---

> entenda, ô estratosférico, que essa escalada é muito fácil, o que conta mesmo na vida é a qualidade da descida;
> 
> **Um copo de cólera** (Location 349)

---

> deitado de lado, a cabeça quase tocando os joelhos recolhidos, ele dormia, não era a primeira vez que ele fingia esse sono de menino, e nem seria a primeira vez que me prestaria aos seus caprichos, pois fui tomada de repente por uma virulenta vertigem de ternura, tão súbita e insuspeitada, que eu mal continha o ímpeto de me abrir inteira e prematura pra receber de volta aquele enorme feto.
> 
> **Um copo de cólera** (Location 558)