---
title: "Wagnerism"
author: Alex Ross
date: 2025-09-21
Rating: 8 / 10
---

### Highlights
> He cast his strongest spell on the artists of silence— novelists, poets, and painters who envied the collective storms of feeling that he could unleash in sound.
> 
> **Prelude: Death in Venice** (Location 248)

---

> One danger inherent in the incessant linking of Wagner to Hitler is that it hands the Führer a belated cultural victory— exclusive possession of the composer he loved.
> 
> **Prelude: Death in Venice** (Location 279)

---

> When, in the wake of the Ring, Nietzsche broke with Wagner, he thought of himself as a fugitive slave.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 337)

---

> The revolutionary year 1848, which gave rise to the Ring, shook the old European order but failed to bring it down.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 346)

---

> Over the course of his Dresden tenure, Wagner became increasingly attuned to leftist politics.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 355)

---

> Wagner’s subsequent interweaving of mythic stories in operatic form caused him to be described— by none other than the anthropologist Claude Lévi-Strauss— as “the incontestable father of the structural analysis of myths.”
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 367)

---

> He then set the project aside and engaged in the most intense political activity of his life.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 391)

---

> For several years, he all but stopped composing and threw himself into the writing of essays,
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 400)

---

> That essay contends that Jews have no culture of their own and that leading Jewish composers like Felix Mendelssohn and Giacomo Meyerbeer are stale imitators of tradition and/ or agents of capitalist greed.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 407)

---

> He tells Liszt, his most steadfast musical ally, that he has an “enormous desire to commit acts of artistic terrorism.”
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 414)

---

> Kant had enshrined the principle of autonomous reason, of “always thinking for oneself,” as the essence of the Enlightenment. G. W. F. Hegel, Kant’s commanding successor, unveiled a grandiose theory of progress, in which a World Spirit guides history toward a utopian future.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 433)

---

> Wagner also absorbed the Romantic precept that art should fill the void left by the retreat of traditional religion.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 443)

---

> the Wagnerian synthesis: Romantic art-religion is bound to Hegel’s dialectic of progress, creating an aesthetic juggernaut.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 451)

---

> The metaphysical bravado of German philosophy masked a host of insecurities and fears. Why had the “land of poets and thinkers” failed to form a nation in the political sense? Was Germany’s backwardness a condition to be overcome, or did it preserve premodern values amid dizzying change?
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 461)

---

> In the years when Hegel’s vision of historical progress held sway, Schopenhauer offered a far darker picture of a pain-filled world spinning toward no definite goal.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 553)

---

> The World as Will appealed to Wagner not least because it elevated music to a place of preeminence among the arts.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 557)

---

> Music, Schopenhauer says, is the one art form that, rather than copying the outer shell of representation, mimics the operation of the Will itself.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 559)

---

> Wagner’s apparent conservative turn resulted from this deeper philosophical transformation: “His significant movement was not from left to right but from politics to metaphysics.” Music itself becomes the metaphysical agent, the way to a “trusty and true” world beyond the veil.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 580)

---

> Indeed, Siegfried is the most problematic character in the cycle. By design, he lacks complexity: he can seem like an action-movie figure barging into a psychological novel. Stupidity is his tragic flaw. Nonetheless, the entire drama hinges on him.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 600)

---

> The word “leitmotif” has sown much confusion over the years. Hans von Wolzogen, one of Wagner’s most militant young followers, popularized the term, against the composer’s own wishes. Although Wagner referred to “melodic moments” and “basic motifs” in his work, he criticized Wolzogen for treating such motifs purely as dramatic devices, overlooking their musical logic.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 617)

---

> They not only illustrate the action but indicate what characters are thinking or sensing— or even what they are unable to perceive.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 622)

---

> Because of its literary nature, the leitmotif has affected literature in turn. Wagnerian authors create networks of phrases that recur across a wide span. Visual artists and filmmakers, likewise, introduce motifs of pattern and color.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 634)

---

> Although she performed the role of helpmate, Cosima was a woman of high intelligence and broad culture, anything but meek in her opinions. That the Bayreuth Festival survived Wagner’s death and became a permanent institution owed everything to Cosima’s skill as a theatrical director, her flair for administration, and her half-ethereal, half-steely charisma. Few women of the period achieved comparable authority. She was also politically reactionary, and, if anything, even more antisemitic than her husband.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 645)

---

> Nietzsche grew up in a Lutheran household that cherished the German musical tradition.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 672)

---

> There was an element of calculation on both sides. Nietzsche seized the chance to align himself with a star of European culture. Wagner, who lacked strong support in the academic world, knew the value of having a gifted and impassioned young scholar as an ally.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 688)

---

> At almost every turn, however, Nietzsche pushes Wagnerian thought to new rhetorical extremes.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 704)

---

> Master and follower diverge most conspicuously on the question of slavery. For Wagner, slavery was a flagrant flaw of Hellenic culture; a Greek revival would require a different social structure, one that would make beauty available to all. Nietzsche repeats certain of these sentiments but never strongly affirms them.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 707)

---

> Traditional opera houses conform to a horseshoe shape, with many of the boxes facing one another— an arrangement conducive to social display. Bayreuth has a fan-shaped array of steeply raked rows, like a section lifted from a Greek amphitheater, so that every seat is angled toward the stage.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 772)

---

> In all, Bayreuth was intended to foster a new level of seriousness in the theater public. Spectators should feel themselves disappearing into the work at hand. To assist in that illusion, Wagner planned to have the lights in the auditorium dimmed— again defying an operagoing culture that saw its own finery as part of the spectacle.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 788)

---

> At a later performance, someone shouted, “Bravo!” during the chorus of the Flower Maidens, and was hissed. That someone turned out to be the composer. Here was an early sign that Wagnerism was taking on a life independent of its creator.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 796)

---

> Two of the biggest donors were, reputedly, Abdülaziz, the sultan of the Ottoman Empire, and Isma’il Pasha, the khedive of Egypt.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 804)

---

> Dom Pedro II of Brazil, who once expressed interest in becoming Wagner’s patron, made the long journey from Rio de Janeiro.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 828)

---

> In the end, a festival that professed to shun consumerism all but wallowed in commercial values.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 838)

---

> Nietzsche was appalled. “I no longer recognized anything, I scarcely recognized Wagner,” he wrote in Ecce Homo, remembering the “profound alienation” he felt when he arrived for the final rehearsals of the Ring.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 846)

---

> To Otto Eiser, Nietzsche’s doctor, Wagner later offered the observation that he had seen other “young men of great intellectual ability” cut down by similar problems, and that these were often the result of masturbation.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 874)

---

> The immediate cause of the break, however, was a brazen display of independence on Nietzsche’s part. During his stay in Klingenbrunn, in the summer of 1876, he had begun making notes for the book that became Human, All Too Human. The style departs markedly from his earlier published writing. In place of spacious paragraphs and ornate sentences, it proceeds by way of aphorisms and polemics, pithy strikes and sudden swerves.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 877)

---

> Wagner goes unnamed in Human, All Too Human, but a number of passages take clear shots at him. “Any degree of levity or melancholy is better than a romantic turn to the past and desertion, an accommodation with any form of Christianity whatsoever”: this is a preemptive critique of Parsifal.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 895)

---

> In the end, both men harbored impulses that look ominous from the vantage point of the post-Holocaust era. What Wagner disliked in Nietzsche— the pitilessness, the exaltation of power— and what Nietzsche disliked in Wagner— the Teutonic chauvinism, the antisemitism— added up to an approximation of the fascist mentality.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 926)

---

> Nietzsche accuses Wagner of having misunderstood the philosophy implicit in his own art. Schopenhauer has beguiled him into anti-Jewish blather, into a dubious conflation of Christianity and Buddhism, into an overweening concern for the well-being of animals.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 940)

---

> The Übermensch makes a formal entrance in Thus Spoke Zarathustra, which Nietzsche was writing at the time of Wagner’s death. Zarathustra, the Übermensch’s prophet, appears toward the end of The Joyful Science, preparing to descend from his mountain and undertake his Untergang, his “going under.”
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 954)

---

> In the last book of Zarathustra, the protagonist meets the Zauberer, the Sorcerer, one of several tempters who try to lure him from his path. Even if we hadn’t read Nietzsche’s prior references to the “old sorcerer,” we would recognize Wagner’s personality in this restless, twitching, frantically gesturing figure, who babbles self-pitying monologues and dubs himself “the greatest person living today.”
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 975)

---

> of Wagner, written in the spring of 1888, promises to be the ultimate act of apostasy.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 1016)

---

> Toward the end of his career, Nietzsche drops the pretense of being anti-Wagnerian and confesses his vestigial adoration.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 1035)

---

> One project of the later writings is to separate Wagner from bad national mythologies and guide him toward the Nietzschean ideal of the “good European,”
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 1054)

---

> Having become himself in the course of his agon with Wagner, Nietzsche fell back under the sorcerer’s spell in the end.
> 
> **1. Rheingold: Wagner, Nietzsche, and the Ring** (Location 1079)

---

> Powerless, the heart sinks back to languish in longing, in longing without attainment, since each attainment leads only to renewed desire, until in final exhaustion the breaking glance catches a glimpse of the attainment of the highest rapture: it is the rapture of dying, of ceasing to be, of the final deliverance into that wondrous realm from which we stray farthest when we try to penetrate it with the stormiest force.
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1165)

---

> That first chord, named the “Tristan chord,” is a nebulous, ambiguous half-diminished seventh. In a well-defined harmonic context, it would be unremarkable, but in the hazy space delineated by the cellos it assumes an identity at once sensuous and unstable.
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1175)

---

> Originally, the Liebestod was a seeming death that turns into love. It became almost the opposite— love that turns into death.
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1204)

---

> Wagnérisme, the French cult of Wagner, was an astonishing development, as those who lived through it knew.
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1226)

---

> The fervor was all the more notable given the mutual distrust that festered between France and Germany in the decades after the Franco-Prussian War.
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1232)

---

> decadent style as “one in which the unity of the book breaks down and gives way to the independence of the page, in which the page breaks down and gives way to the independence of the sentence, and in which the sentence breaks down and gives way to the independence of the word.”
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1255)

---

> Wagner was modern; he was decadent; and he was dangerous. Riots and brawls accompanied French performances of his works until the end of the century, when the torch of scandal passed to the modernists.
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1260)

---

> Mallarmé directed writers to “take back what is ours” from the rival domain of music drama. “What a singular challenge Richard Wagner imposes on poets, whose duty he usurps with the most candid and splendid bravura!”
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1271)

---

> Interest in Wagner quickened after 1848. The failure of revolutionary hopes impelled a turn away from politics and toward the otherworldly, the bizarre, the visceral, the voluptuous— a distinctively French counterpart to Wagner’s turn to metaphysics.
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1285)

---

> The political backdrop helps to explain the ensuing battle over Wagner in Paris. Louis-Napoléon was crowned Napoleon III in 1852, and in the early years of his regime he exercised an authoritarian grip, effectively suppressing opposition at both ends of the political spectrum— the republican left, adhering to the ideals of the Revolution; and the legitimist right, dedicated to restoring the Bourbon monarchy. By the end of the fifties, though, the left was gathering strength, and the emperor responded with a strategy of partial liberalization.
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1321)

---

> Even if Wagner had retreated from politics, his reputation rested in large measure on his revolutionary pamphlets, and he had many fans on the left.
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1326)

---

> In March 1860, Napoleon III commanded a performance of Tannhäuser at the Opéra. The historian Gerald Turbow diagrams the politics behind the move: the emperor wished to improve relations with Austria, and Princess Pauline von Metternich, the wife of the Austrian ambassador, was a Wagner champion. At the same time, the gesture seemed intended to win allies among domestic progressives.
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1355)

---

> The Jockeys, who had ties to the legitimist camp and no great love for Napoleon III, had already decided to ruin the show. They came equipped with hunting whistles and made a mighty noise. The entrance onstage of ten hunting dogs, loaned by the emperor, caused merriment, eliciting cries of “Bravo les chiens! Bis les chiens!” The Wagnerites fought back, shouting, “À bas les Jockeys!” Fistfights broke out;
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1379)

---

> While the composer came from relatively humble origins, the poet grew up in comfortable bourgeois circumstances, and assumed, with a certain pride, a downward trajectory.
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1394)

---

> I often experienced a sensation of a rather bizarre nature, and this was the pride and pleasure of comprehending, of letting myself be penetrated and invaded, a truly sensual enjoyment,
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1414)

---

> After the conflict, the composer’s reputation in France slumped again, thanks in part to his genius for insult. In 1873, he dismayed even his most die-hard French fans by publishing a would-be Aristophanic farce titled A Capitulation, which made light of the siege of Paris in the fall and winter of 1870.
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1613)

---

> If the war had dampened French Wagnerism, the composer’s death seemed to ignite it again. “Curious people!” Tchaikovsky wrote from Paris. “It is necessary to die in order to attract their attention.” At the Bayreuth Festival of 1886, the number of French visitors exploded, from a few dozen to well over a hundred.
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1634)

---

> Partisans of Impressionist and Post-Impressionist painting often used Wagner as a reference point.
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1668)

---

> The composer himself had conservative taste in the visual arts, and late in life he scoffed at Impressionists who “paint nocturne-symphonies in ten minutes.”
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1671)

---

> Where Cézanne reacted to Wagner in muted hues, Vincent van Gogh, a Dutchman who reached his vertiginous zenith in France, associated the composer with explosions of color.
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1699)

---

> These encounters left the painter with the sense that music had pulled ahead of the other arts.
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1703)

---

> his unstoppable march from the fringe to the center served as the greatest extant demonstration of a successful avant-garde— the victory for which even the most anticommercial artists yearned.
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1722)

---

> The Symbolists gave much thought to the innate musicality of the raw materials of language.
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1781)

---

> Just as Wagner’s music consists of a succession of motifs that suggest psychological states, the interior monologue is a “succession of short sentences, each of which also expresses a movement of the soul, the similarity being that they are related to each other not according to a rational order but according to a purely emotional order, outside of any intellectualized arrangement.”
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1812)

---

> James Joyce cited Les Lauriers as a precedent for Ulysses.
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1816)

---

> The poet had recently served his second prison term, after threatening to strangle his mother; the first was for shooting Rimbaud.
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1825)

---

> Like van Gogh, Mallarmé felt that music had moved ahead of other art forms.
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1851)

---

> praises the art of music for holding fast to its secrets.
> 
> **2. Tristan Chord: Baudelaire and the Symbolists** (Location 1853)

---

> The custom is a little strange, because in its original context the music is a prelude to catastrophe.
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 1939)

---

> The British royal family, arbiters of wedding fashion across the ages, promoted the Bridal Chorus as a marriage anthem.
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 1957)

---

> Victoria’s willingness to associate with a “politically disreputable person wanted for high treason”— Wagner’s self-characterization— flattered him deeply.
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 1965)

---

> It is a historical curiosity that the British royals chose to pair Wagner with the two Jewish composers whom he insults in “Jewishness in Music.”
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 1971)

---

> The incorporation of Lohengrin into the royal wedding protocol exposes a gap between French- and English-speaking responses to Wagner. In France, he was a scandal, an incitement, a field of battle. In Britain and the United States, he was a somewhat tamer product— a “treat,” in Victoria’s graciously belittling formulation.
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 1985)

---

> At the end of the nineteenth century, American orchestras were largely German-speaking ensembles.
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 1998)

---

> Even as evocations of a mythic past served an imperial agenda, the anticapitalist allegory of the Ring warned against the industrial modernization that fueled the mid-century might of the British Empire and the gathering strength of the United States. Wagner’s own vision of London was nightmarish:
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 2006)

---

> Wagner’s British reception was further complicated by awareness of his anti-Jewish feelings. Thanks to a maladroit article by a supporter, Ferdinand Praeger, the English-speaking music world had recently learned of Wagner’s authorship of “Jewishness in Music,” which otherwise received almost no international notice.
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 2032)

---

> Mary Ann Evans, who wrote under the pen name George Eliot, was one of the first major English-speaking figures to take Wagner seriously.
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 2037)

---

> Eliot endorses Wagner’s progressive ideas, but the music itself gives her trouble. Accustomed to clean-cut classical forms, she finds the endlessness of Wagnerian discourse bewildering.
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 2054)

---

> “The Teutonic element in the house had a marvellous effect in teaching the audience that ‘Lohengrin’ was not to be judged by the ordinary standard; so when the usual round of applause was given for the favourite singers on their entrance … a very decided ‘hush’ convinced the astonished Opera habitués that the vocalists must be considered as secondary to the work they were interpreting.”
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 2117)

---

> The Pre-Raphaelite Brotherhood, which sought to revive the handcrafted aesthetic of the Middle Ages in anticipation of a better world, formed in 1848, in the midst of the pan-European wave of revolutionary agitation that also spawned the Ring.
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 2161)

---

> The tale of Tristram and Iseult is indisputably a property of the British Isles, even if the earliest surviving versions come from twelfth-century France. Iseult the Fair is an Irish princess, her castle thought to lie on the outskirts of Dublin.
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 2259)

---

> Later in the decade, the physician and Theosophist William Ashton Ellis launched a journal called The Meister, dedicated to the “regenerative life-force of the Spring of Richard Wagner’s genius.”
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 2321)

---

> In his final years, Wagner flirted with the notion of immigrating to the United States, a place he never saw. Reeling from the financial disaster of the first Bayreuth Festival, he spoke of selling Wahnfried and moving with his family to the New World.
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 2369)

---

> By 1880, the American plan had become an idée fixe. Cosima wrote: “Again and again he keeps coming back to America, says it is the only place on the whole map which he can gaze upon with any pleasure.”
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 2377)

---

> Around a million Germans had immigrated to the United States between 1846 and 1855. They were often called Forty-Eighters, because many had fled after the failed 1848 revolutions, and they played a pivotal role in American politics before the Civil War.
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 2384)

---

> For the French, he was a torchbearer of the modern; for the British, a messenger of Arthuriana. In the United States, Wagner harmonized with a national love of wilderness sagas, frontier lore,
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 2398)

---

> The American quest for heroic self-definition was caught up in questions of gender and race. Theodore Roosevelt, with his “Rough Rider” persona, epitomized an American masculinity that resisted a supposed European tendency toward effeminacy and degeneracy.
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 2415)

---

> The convention of the nameless Western hero would later find its apotheosis in Sergio Leone’s trilogy of spaghetti Westerns, in which Clint Eastwood plays the Man with No Name.
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 2630)

---

> Root led the Chicago architects in embracing Wagner. A sometime church organist, he thrilled friends with his lively rendition of “The Ride of the Valkyries.”
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 2653)

---

> In 1884 and 1885, the Met brought its Wagner to Chicago, setting off the usual hysteria. It was decided that Chicago should have its own major opera house.
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 2669)

---

> By the turn of the century, Wagner loomed large in American life, his operas laden with the neo-Gothic trappings that informed so much American architecture of the period.
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 2696)

---

> The nation’s aspiration toward European grandeur, Parsifal Entertainments included, clashed with a contrary impulse to shrug off an effete, unmanly European inheritance.
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 2705)

---

> In 1891, Twain trained his gaze on the juiciest high-culture target of all, undertaking a ten-day visit to Bayreuth. He reported on the experience in a rippingly funny newspaper article that first appeared under the title “Mark Twain at Bayreuth” and was later republished as “At the Shrine of St. Wagner.” Selective quotations of its sharpest jabs have made it seem a merciless takedown. It is, in fact, an oblique expression of embarrassed fandom, nearly as conflicted as Nietzsche’s The Case of Wagner.
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 2722)

---

> Twain wishes that he could listen to Wagner with the vocal parts omitted, so that he could bask in the orchestration.
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 2731)

---

> “So many of my friends say Wagner is Leaves of Grass done into music that I begin to suspect there must be something in it.”
> 
> **3. Swan Knight: Victorian Britain and Gilded Age America** (Location 2762)

---

> Parsifal is certainly a Mass of a different color. It is a religious work— Wagner called it his “stage consecration festival play”— yet it belongs to no one religion.
> 
> **4. Grail Temple: Esoteric, Decadent, and Satanic Wagner** (Location 2824)

---

> By the time he began composing Parsifal, he was no longer remotely a revolutionary, but his antimaterialist slant remained.
> 
> **4. Grail Temple: Esoteric, Decadent, and Satanic Wagner** (Location 2827)

---

> Although the later Nietzsche considered Parsifal a capitulation to Christianity, he better explained the composer’s stance in an 1875 note: “If Wagner takes up Germanic-Christian myth one moment, seafaring legends another, then Buddhistic myths, then pagan-German ones, then the Protestant bourgeoisie, it is clear that he stands free of the religious meaning of these myths, and requires the same of his listeners.”
> 
> **4. Grail Temple: Esoteric, Decadent, and Satanic Wagner** (Location 2833)

---

> It was the age of esotericism, occultism, Satanism, Spiritism, Theosophy, Swedenborgism, Mesmerism, Martinism, and Kabbalism. Reinventions or fabrications of medieval sects multiplied:
> 
> **4. Grail Temple: Esoteric, Decadent, and Satanic Wagner** (Location 2856)

---

> A large number of writers, artists, and musicians took an interest in one or another of these movements;
> 
> **4. Grail Temple: Esoteric, Decadent, and Satanic Wagner** (Location 2860)

---

> Holbrook Jackson, writing in 1913, associated the mystical revival with a “revolt against rationalism” and a “salvation by sin”— ideas implicit in Parsifal.
> 
> **4. Grail Temple: Esoteric, Decadent, and Satanic Wagner** (Location 2862)

---

> The advent of positivism, social Darwinism, and other mechanistic explanations for human behavior brought a countervailing urge to restore the dimension of the miraculous. The occultists also rejected dualities of good and evil, seeking a more complex
> 
> **4. Grail Temple: Esoteric, Decadent, and Satanic Wagner** (Location 2865)

---

> Cosima, an Italian-born French-Hungarian who spoke fluent German and English, knew that Bayreuth’s future depended on an international audience, and she proved adept at obtaining one.
> 
> **4. Grail Temple: Esoteric, Decadent, and Satanic Wagner** (Location 2890)

---

> The leading Belgian art journals, like their French counterparts, named Wagner as a fellow combatant in the war against bourgeois taste.
> 
> **4. Grail Temple: Esoteric, Decadent, and Satanic Wagner** (Location 3011)

---

> “The destiny of the Wagnerian work,” he wrote, “will be to annihilate once and for all the naturalist muck where Zola has sat for nearly a half-century.”
> 
> **4. Grail Temple: Esoteric, Decadent, and Satanic Wagner** (Location 3043)

---

> The Symbolists ran up against a quandary that was not unfamiliar to the man who founded the Bayreuth Festival: their excoriation of bourgeois mediocrity did not prevent the bourgeoisie from consuming their art.
> 
> **4. Grail Temple: Esoteric, Decadent, and Satanic Wagner** (Location 3072)

---

> The idea that Wagner’s music tapped into devilish forces had wide purchase, both among the composer’s detractors and among his wilder-eyed disciples. Fin-de-siècle culture granted mighty powers to artists, and by some accounts Wagner was capable of administering a sort of aural potion of death or derangement.
> 
> **4. Grail Temple: Esoteric, Decadent, and Satanic Wagner** (Location 3098)

---

> Wagner saw himself as an affirmative artist, preparing humanity for a better world. Yet he, too, sensed danger in his music. While composing Tristan, he worried that it would drive people insane.
> 
> **4. Grail Temple: Esoteric, Decadent, and Satanic Wagner** (Location 3109)

---

> As the eighties gave way to the nineties, vampiric, necromantic, and satanic themes proliferated in post-Wagnerian, post-Symbolist literature.
> 
> **4. Grail Temple: Esoteric, Decadent, and Satanic Wagner** (Location 3126)

---

> In Latin America, the Modernismo movement, led by the Nicaraguan poet Rubén Darío, mixed Symbolist, Decadent, and Wagnerian strains, to sometimes creepy effect.
> 
> **4. Grail Temple: Esoteric, Decadent, and Satanic Wagner** (Location 3142)

---

> Hundreds of Waldorf schools around the world follow Steiner’s philosophy of holistic education, fostering creativity and independence in children.
> 
> **4. Grail Temple: Esoteric, Decadent, and Satanic Wagner** (Location 3226)

---

> The period of Wagner’s ascendancy coincided with the cresting of ​ Irish nationalism. More than a few artists and impresarios looked to the composer as they pondered how to forge their own political identity.
> 
> **4. Grail Temple: Esoteric, Decadent, and Satanic Wagner** (Location 3252)

---

> For Yeats, as for many others, Wagner showed how folk sources could shape a national consciousness. In his 1898 essay “The Celtic Element in Literature,” he wrote of Ireland’s connection to the “ancient religion of the world, the ancient worship of Nature.” The Celts, he said, were “nearer to ancient chaos.”
> 
> **4. Grail Temple: Esoteric, Decadent, and Satanic Wagner** (Location 3293)

---

> If Wagner had left it at that, Meistersinger might not have become the most politically charged of his operas,
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3381)

---

> We can no longer hear these lines as nineteenth-century audiences heard them. Echoes of their future, which is now our past, intrude. We think of the young Hitler copying out Sachs’s closing speech; of an audience in Bayreuth in 1924 rising to its feet during the monologue and breaking into the Deutschlandlied afterward; of the chorus “Wach auf, es nahet gen den Tag” (“ Awake, the dawn is drawing near”) resounding as a salute to Hitler in 1933; of Meistersinger being staged during Nazi Party rallies in Nuremberg; of Joseph Goebbels calling the opera “the incarnation of our folk character”; of the Act III prelude appearing on the soundtrack of Leni Riefenstahl’s film Triumph of the Will. All of Wagner’s operas have political dimensions, but Meistersinger is the only one that makes its politics unavoidable. Karol Berger, in his book Beyond Reason: Wagner contra Nietzsche, has written: “I can think of no other example of a masterpiece so profoundly wounded by its ending.”
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3402)

---

> Wagner’s Germanness has never been in doubt, whatever Nietzsche said. Rather, the question is: which Germany do we mean? The Kaiserreich, the unified German empire that formed under Wilhelm I in 1871, has been subject to a barrage of competing interpretations.
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3421)

---

> Germany had failed to undergo a bourgeois revolution of the kind that modernized other European states. Instead, much of the old feudal order remained, and parliamentary democracy never put down healthy roots.
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3424)

---

> The odd thing about Wagnerism in German-speaking lands is how limited it was, especially in comparison with developments in France.
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3436)

---

> Only in the Germany of the Kaiserreich did Wagner become a predominantly conservative cultural phenomenon— not just an official artist but also a mass-market commodity.
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3444)

---

> At first glance, Neuschwanstein, Ludwig II’s castle in the foothills of the Bavarian Alps, would seem to be the most Wagnerian place on earth. When the young king began planning it, in the late 1860s, he told Wagner that “the spot is one of the most beautiful to be found, sacred and inaccessible, a worthy temple for the divine friend”— the friend being, of course, the composer.
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3455)

---

> This strange and lonely man did as much as anyone to give Wagner semi-godlike status in German culture.
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3465)

---

> if I am ‘German,’ then be assured I carry my Germany within me.”
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3470)

---

> the new king, just eighteen years old, adored Wagner, had memorized his writings, and wished to place the resources of the court at the composer’s disposal, with an eye toward a production of the Ring. This implausible sequence of events is, in fact, one of the better-documented episodes in Wagner’s life. It is a fairy tale that Ludwig had the power to make real.
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3476)

---

> The landmark premieres of the composer’s final period— Tristan in 1865, Meistersinger in 1868, Rheingold in 1869, Walküre in 1870, the entire Ring in 1876, and Parsifal in 1882— relied on Ludwig’s support. The Bayreuth Festival stayed afloat on the strength of royal loans.
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3483)

---

> For the time being, though, purely nationalist definitions of Germanness remained foreign to him.
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3486)

---

> The desire to conquer other lands is “un-German.” So is any system of standing armies, which creates a useless military class. The German nature is “defensive-conservative,” he says, inclined toward contemplation rather than domination. It was, in fact, in the absence of political power that German art rose to greatness. Imperialism and militarism are blamed on Austrians, Junkers, and Jews.
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3491)

---

> When Wagner came under Ludwig’s protection, Bavaria was a prosperous independent kingdom with strong ties to Austria. In 1866, Prussia defeated Austria in the Seven Weeks’ War, establishing itself as the chief German power. As a result, Wagner took a new tack. Although Bavaria had fought alongside Austria, he was impressed by the ruthlessness of Bismarck, the Prussian minister-president. Bismarck, for his part, made oblique overtures toward Wagner, hoping to use him to coax Ludwig away from the Austrians.
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3497)

---

> During the Franco-Prussian War of 1870– 71, Wagner indulged in the kind of bellicosity he had warned against just a few years earlier.
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3503)

---

> Although he devoted many pages of his late writings to obnoxious claims of Germanic superiority, he was again recoiling from militarism and making noises of sympathy for the left.
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3508)

---

> just before his death, Wagner shuddered at a news item about Neuschwanstein under construction: “The description of the King’s castle in L’Italie annoys R., making him feel ashamed of the whole relationship.”
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3516)

---

> His still unexplained death— he was found floating in Lake Starnberg, next to the body of his psychiatrist— took place three days after Bavarian ministers had arranged for him to be declared unfit to rule.
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3522)

---

> The spread of such stories, both at home and abroad, marked a turning point in Wagner’s public image: his music now signified the military might of the new German nation.
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3536)

---

> The Kaisers were not alone in resisting the deification of Wagner. Until 1900, and even after, the composer remained a contentious figure in Germany, his status disputed on musical, personal, and political grounds.
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3591)

---

> Vienna, the other glittering showplace of the German-speaking art world, was long divided on the Wagner question. At first, the “music of the future” seemed like an assault on the city’s classical tradition, the legacy of Haydn, Mozart, Beethoven.
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3762)

---

> For the cultured youth of Vienna, Wagner productions blended with the general dream-consciousness of the city, which promised a realization of Schiller’s “aesthetic state.”
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3808)

---

> In 1871, the year of the founding of the German Empire, the Risorgimento, the unification of Italy, reached its final stage with the incorporation of Rome. As in Germany, a composer symbolized the new order: Giuseppe Verdi, whose music had served an anthemic role during the drive toward unification, became a national hero, his name read as a cipher of the sovereign (Vittorio Emanuele, Re d’Italia).
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3825)

---

> The brothers grew up in the Baltic Sea port of Lübeck, sons of the grain merchant Thomas Johann Heinrich Mann and of the Brazilian-born immigrant Júlia da Silva Bruhns.
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 3894)

---

> In the years before the First World War, a rift opened between the brothers Mann. Heinrich’s leftist convictions became more pronounced, as did his allegiance to French culture. Thomas drifted to the right.
> 
> **5. Holy German Art: The Kaiserreich and Fin-de-Siècle Vienna** (Location 4010)

---

> Wagner was a bigot who expended thousands of words vilifying Jews and other races. Still, Lohengrin represented an ideal in Du Bois’s mind, one that floated above the bloodland of American racism.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4076)

---

> David responds, “I do hate myself, but it has nothing to do with being Jewish.”
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4089)

---

> Complicating matters further is the fact that two towering figures in modern African-American and Jewish history— Du Bois and Theodor Herzl— held Wagner’s art in high esteem.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4095)

---

> Murderous hostility toward Jews had existed in Germany for centuries before Wagner was born.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4105)

---

> In the nineteenth century, though, anti-Jewish rhetoric underwent a fateful transformation. Formerly, it had had a religious basis, or was tied to critiques of capitalism. When scientific-sounding theories of race took hold, in the final years of Wagner’s life, Jews were categorized as biologically different from the rest of humanity. Wagner helped to propagate this racialized hatred, which came to be known as antisemitism.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4109)

---

> Anti-Jewish remarks crept into Wagner’s writings in the 1830s, as he began to hold Jews responsible for the cultural marketplace that had failed to capitulate instantly to his genius.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4113)

---

> Karl Marx’s 1843 essay “On the Jewish Question,” responding to a similarly titled work by Bruno Bauer, states that Jewish political activities are founded on egoism and the pursuit of material gain; that the Jewish mentality pervades society; and that liberation from Jewishness will be achieved only through the abolition of capitalism.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4116)

---

> The Wagner scholar Udo Bermbach notes that the closing argument of “On the Jewish Question”—“ The social emancipation of the Jew is the emancipation of society from Judaism”— anticipates the thrust of “Jewishness in Music,” though the tone is far milder.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4120)

---

> In language of still shocking crudity, he charges Jews with being cultural parasites, feeding off of the healthy artistic material of other peoples.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4139)

---

> In that same year, Wagner made the enormously consequential decision to reprint “Jewishness in Music” under his own name. His authorship of the essay had been exposed as early as 1851, but memories of it had faded. The 1869 publication, as a freestanding pamphlet, touched off an uproar.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4173)

---

> The essay also elicited much ridicule— evidence that Wagner’s anti-Judaism was misaligned with elements of German and Austrian opinion circa 1870.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4182)

---

> Cosima’s diaries, which began in 1869, record a daily barrage of hateful antisemitic language.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4197)

---

> It is not enough to get rid of Jews, he writes, since society is afflicted by a general disease of which Jews are merely the symptom.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4224)

---

> Wagner again approaches Marx’s formulation in “On the Jewish Question.”
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4228)

---

> There are no Jews in Wagner’s operas— or, at least, no characters identified as Jews. Blatant stereotypes on the order of Fagin in Dickens’s Oliver Twist, Svengali in George du Maurier’s Trilby, or the hook-nosed financier in Degas’s painting At the Bourse do not appear. That absence once enabled liberal Wagnerites to create a kind of firewall between the composer’s despicable views and the ostensibly humane content of his works. After the rise of the Wagner-loving Hitler, that barrier broke down.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4238)

---

> de-Judaized Christianity. That article received Wagner’s approval. Some of Wagner’s adversaries tried to turn the tables, spreading rumors to the effect that the composer was Jewish or that he displayed Jewish mannerisms.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4302)

---

> Toward the end of the 1870s, anti-Jewish feeling in Germany coalesced into a political movement. In 1879, Wilhelm Marr, an enthusiastic Wagnerite, founded an organization called the League of Anti-Semites, helping to standardize the term “antisemitism.”
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4319)

---

> The transition to so-called scientific antisemitism— a mind-set that relied on deep-seated biological definitions of race, and that ruled out the possibility of assimilation— was fitful and incomplete. Several leaders of the new antisemitic politics were inconsistent in their doctrine;
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4326)

---

> Few publications were more implacably racist than the Bayreuther Blätter, which, under the leadership of Hans von Wolzogen, dedicated itself to the “purification and re-establishment of the true German culture.” To all appearances, the newsletter operated with Wagner’s blessing, although the composer sometimes questioned its more dogmatic utterances. He declined to sign Förster’s petition against Jewish rights, despite the fact that it had evidently originated at Bayreuth. Cosima gives three reasons for his refusal: “he has already done what he can”; “he dislikes appealing to Bismarck”; and “nothing more can be done in the matter.”
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4333)

---

> Wagner did not approve of all antisemites, nor did all antisemites approve of him.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4352)

---

> The socialist Eugen Dühring, one of the most vituperative antisemites of the period, was also anti-Wagnerian.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4355)

---

> In France, Wagnerites fell on both sides of the Dreyfus Affair— the national furor over the conviction and imprisonment of the French-Jewish army officer Alfred Dreyfus, falsely accused of treason.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4360)

---

> This remarkable and repellent man, in whom superficial erudition mingled with profound intolerance, is essential to understanding Wagner’s fate in the twentieth century. More than any other figure, he forms the bridge between Bayreuth and Nazi Germany.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4393)

---

> Indeed, Levi endured humiliation in Wagner’s service, but he kept faith in the man and his music.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4451)

---

> The Jews who surrounded Wagner have long been considered paragons of self-loathing.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4466)

---

> The existence of Jewish Wagnerites first drew wide notice amid the controversy over the reprinting of “Jewishness in Music,” when a fair number of Jews remained steadfast in their support of the composer.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4475)

---

> His suicide, which happened in the house where Beethoven died, won him the darkest imaginable praise. In 1941, Hitler recalled his mentor Dietrich Eckart saying that Weininger was the one “decent Jew,” because “he took his own life when he realized that the Jew thrives on the corrosion of other peoples.”
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4584)

---

> For some years, Herzl remained convinced that assimilation was the only way forward.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4603)

---

> This criticism might have played a role in Herzl’s about-face in 1895, when he rejected assimilation and championed the Zionist idea.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4612)

---

> Herzl made no secret of his Wagnerism.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4623)

---

> Lohengrin had a special appeal for Jewish listeners, as Jütte observes. The opera romanticizes the figure of the itinerant outsider who stands apart from the “normal” community, much as many Jews perceived themselves within German society.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4670)

---

> Much of the time, Wagner echoed the common prejudice. According to Cosima’s diaries, he used “Negro” or “mulatto” as a metaphor for dim-wittedness;
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4684)

---

> Yet Wagner could also be sympathetic to black people.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4687)

---

> He says that the American Civil War was “the only war whose aim was humane”— presumably meaning the abolition of slavery.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4689)

---

> Although her assignment at Bayreuth was small, Luranah received unusual treatment. The nineteen-year-old Eva Wagner, the future wife of Houston Stewart Chamberlain, befriended her, and Cosima apparently invited the young singer to stay at Wahnfried in the months before the festival.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4724)

---

> Just as Herzl looked to Tannhäuser to fortify his Zionist vision, Du Bois took Wagnerian myth as a model for a heroic new African-American spirit, one that would make use of its own legends.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4771)

---

> This ideal of a transnational black identity is not unlike the “holy German art” that preoccupied Wagner while he was writing Meistersinger.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4776)

---

> German theories of racial superiority horrified Du Bois, but they led him to think about how African-Americans could cultivate their own inheritance.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4799)

---

> Decades after he wrote “Of the Coming of John,” Du Bois fulfilled a long-standing dream of going to Bayreuth. He chose a curious time to make his visit: 1936.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4805)

---

> he felt less conscious of his race than he did at home. He wrote: “I have not suffered from race prejudice … I can go to any hotel which I can afford; I can dine where I please and have the head-waiter bow me welcome.” That he felt less open hostility in Hitler’s Germany than in Roosevelt’s America is a devastating verdict on American race relations.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4809)

---

> The conceit of self-hatred would imply that these black Wagnerians were in some way ashamed of their heritage. Such condescension is just as dubious in the case of civil-rights stalwarts like Du Bois and Graham as it is for Theodor Herzl.
> 
> **6. Nibelheim: Jewish and Black Wagner** (Location 4836)

---

> Warthin’s paper is one of a number of turn-of-the-century medical studies that purport to document cases of erotomania, or excessive sexual desire, induced by the music of Wagner.
> 
> **7. Venusberg: Feminist and Gay Wagner** (Location 4868)

---

> “Music can vicariously stand in for sexual intercourse— Wagnerizing [Wagnerei] especially is often just a better surrogate for coitus.”
> 
> **7. Venusberg: Feminist and Gay Wagner** (Location 4872)

---

> The word “degeneration,” suggesting a devolution to a primitive mental or moral condition, is a staple of fin-de-siècle discussions of Wagner. The historian Daniel Pick has shown how concepts of a society-wide epidemic of degeneration caught on in the wake of the revolutions of 1848, as liberal thinkers struggled to explain the apparent halt of the march of social progress.
> 
> **7. Venusberg: Feminist and Gay Wagner** (Location 4888)

---

> the composer was hardly conventionally masculine in his habits. He fetishized silk and satin, especially in shades of pink, and spent lavishly on the finest fabrics.
> 
> **7. Venusberg: Feminist and Gay Wagner** (Location 4932)

---

> Throughout his life, Wagner pursued an ideal of androgyny, a spiritual merger of the sexes.
> 
> **7. Venusberg: Feminist and Gay Wagner** (Location 4944)

---

> Feminists in the German-speaking world were less inclined to idealize Wagner, perhaps because he was so embedded in the strutting military culture of the Kaiserreich.
> 
> **7. Venusberg: Feminist and Gay Wagner** (Location 5100)

---

> By the end of the nineteenth century, campaigners for gay rights had made Wagner part of a self-fashioned cultural genealogy— if not gay himself, then an exceptionally friendly kind of ally.
> 
> **7. Venusberg: Feminist and Gay Wagner** (Location 5134)

---

> Modern homosexuality was, to some extent, a German invention.
> 
> **7. Venusberg: Feminist and Gay Wagner** (Location 5137)

---

> In 1869, an Austrian littérateur named Karl Maria Kertbeny, also opposed to sodomy laws, coined the term “homosexuality.”
> 
> **7. Venusberg: Feminist and Gay Wagner** (Location 5140)

---

> The German gay-rights movement grew out of the ethos of Romanticism, with its respect for heroic individuals who vanquish “age-old custom” and live according to their own laws.
> 
> **7. Venusberg: Feminist and Gay Wagner** (Location 5145)

---

> The romantic tinge of the Ludwig-Wagner friendship caused chatter when both men were still alive. When the composer entered Ludwig’s circle and began causing trouble in Munich, wits compared him to Lola Montez, the Irish actor whose affair with Ludwig’s grandfather Ludwig I had led to the latter’s abdication.
> 
> **7. Venusberg: Feminist and Gay Wagner** (Location 5192)

---

> Wagner became part of the syllabus of gay taste.
> 
> **7. Venusberg: Feminist and Gay Wagner** (Location 5242)

---

> Wagner and same-sex desire intermingle in Mann’s writing almost from the start.
> 
> **7. Venusberg: Feminist and Gay Wagner** (Location 5295)

---

> Novelists both gay and straight feasted on the divine friendship of Wagner and Ludwig.
> 
> **7. Venusberg: Feminist and Gay Wagner** (Location 5304)

---

> Oscar Wilde, a connoisseur of disgraceful and improbable situations, had too little patience for unreflective grandiosity to count himself among the Wagnerites.
> 
> **7. Venusberg: Feminist and Gay Wagner** (Location 5320)

---

> Death in Venice was a great success. Far from causing scandal, its gay content became a selling point in the sexually jaded Kaiserreich. “Pederasty is made acceptable for the cultured middle classes,” sneered the critic Alfred Kerr.
> 
> **7. Venusberg: Feminist and Gay Wagner** (Location 5528)

---

> Mann, as a loyal Wagnerite, emphasized the degree to which the composer of the Ring and Parsifal had anticipated psychoanalytic theory.
> 
> **7. Venusberg: Feminist and Gay Wagner** (Location 5546)

---

> In the annals of literary Wagnerism, Willa Cather occupies a category of her own. Among major authors, only Thomas Mann knew his Wagner better, and he lacked Cather’s acumen on the subject of singers.
> 
> **8. Brünnhilde’s Rock: Willa Cather and the Singer-Novel** (Location 5670)

---

> The Wagner singer, emitting ear-splitting sounds while inhabiting superhuman roles, was irresistible to writers of fin-de-siècle fiction.
> 
> **8. Brünnhilde’s Rock: Willa Cather and the Singer-Novel** (Location 5976)

---

> The First World War marked an absolute historical rift— and, more or less, the end of Wagnerism as an intellectual phenomenon.
> 
> **9. Magic Fire: Modernism, 1900 to 1914** (Location 6193)

---

> The art historian T. J. Clark has explicated modernism in relation to Max Weber’s thesis about the “disenchantment of the world”— the banishing of ancestor worship and ritual, the founding of a secular, technocratic, materialist order.
> 
> **9. Magic Fire: Modernism, 1900 to 1914** (Location 6224)

---

> Three legacies stand out: the Gesamtkunstwerk; the stream of consciousness; and the juxtaposition of myth and modernity.
> 
> **9. Magic Fire: Modernism, 1900 to 1914** (Location 6227)

---

> In many ways, the Gesamtkunstwerk is a projection of twentieth-century concerns back onto Wagner.
> 
> **9. Magic Fire: Modernism, 1900 to 1914** (Location 6230)

---

> “The Wagnerian contradiction,” Appia called it— the disparity between the limitless expressiveness of the music and the confined world of the bourgeois stage.
> 
> **9. Magic Fire: Modernism, 1900 to 1914** (Location 6338)

---

> The classic chronicle of modernism leaned heavily on rhetoric of purity, autonomy, and freedom. Whether in music, theater, literature, or the visual arts, a quasi-Hegelian spirit of progress guides the artist into uncharted realms.
> 
> **9. Magic Fire: Modernism, 1900 to 1914** (Location 6414)

---

> It was primarily through this mystical channel that Wagner—“ the greatest unconscious occultist who has ever lived,” in Édouard Schuré’s words— influenced modernist painters.
> 
> **9. Magic Fire: Modernism, 1900 to 1914** (Location 6426)

---

> Inner necessity was just as much a byword of the composer Arnold Schoenberg, who saw his hugely controversial exploration of nontonal harmony— atonality, it came to be called— as a natural extension of the chromaticism of Tristan.
> 
> **9. Magic Fire: Modernism, 1900 to 1914** (Location 6463)

---

> Joseph Conrad, né Józef Korzeniowski, a retired Polish sea captain who was now improbably making his way as an English-language novelist.
> 
> **9. Magic Fire: Modernism, 1900 to 1914** (Location 6528)

---

> In Search of Lost Time is one of the supreme Wagnerian creations, yet it is free of bombast, maintaining an intimate mode of address.
> 
> **9. Magic Fire: Modernism, 1900 to 1914** (Location 6848)

---

> Wagnerism reached its zenith in early 1914, on the eve of the First World War.
> 
> **10. Nothung: The First World War and Hitler’s Youth** (Location 6994)

---

> “Gaudí’s love of extremes, his belief that architecture should deal in ambiguity and gloom, exaltation and anxiety, and theatrically primal spaces— the peak and the cavern— is entirely Wagnerian.”
> 
> **10. Nothung: The First World War and Hitler’s Youth** (Location 7023)

---

> Bayreuth’s unsuccessful effort to prevent the expiration of the Parsifal copyright also dented its image. That campaign took on hyper-nationalist, xenophobic, and antisemitic overtones.
> 
> **10. Nothung: The First World War and Hitler’s Youth** (Location 7039)

---

> When Parsifal ended that night, the festival fell silent for ten years.
> 
> **10. Nothung: The First World War and Hitler’s Youth** (Location 7057)

---

> Despite the composer’s intermittent hostility to the state and his late-period drift toward pacifism, his music often fueled a bellicose mood and, especially in Germany, became a psychological weapon.
> 
> **10. Nothung: The First World War and Hitler’s Youth** (Location 7064)

---

> Eventually, Wagner became part of military lingo. A defensive bulwark on the Western Front, constructed in 1916, was known as the Siegfried Line; another fortification was called the Wotan Line.
> 
> **10. Nothung: The First World War and Hitler’s Youth** (Location 7079)

---

> Many Wagnerites on the Entente side believed that the composer not only stood apart from contemporary Germany but could be seen as actively opposing it.
> 
> **10. Nothung: The First World War and Hitler’s Youth** (Location 7142)

---

> If, as Thomas Mann said, Wagner epitomized the nineteenth century— its grandeur, its splendor, its faith in progress, its bourgeois materialism, its nationalist mythologies, its moral arrogance, its spiritual longing, and, above all, its veneration of art and artists— then the Great War indeed killed him off, as it did large tracts of the nineteenth-century cultural legacy.
> 
> **10. Nothung: The First World War and Hitler’s Youth** (Location 7153)

---

> Speed, flight, noise, war, chaos, cut-up, collage, the overturning of all artistic norms: these were the values, to different degrees, of Futurism and Dada.
> 
> **10. Nothung: The First World War and Hitler’s Youth** (Location 7329)

---

> Guillaume Apollinaire, coiner of the word “surrealism,” consigned Wagner to the category “shit,” though Dante, Shakespeare, Goethe, and Tolstoy made for good company.
> 
> **10. Nothung: The First World War and Hitler’s Youth** (Location 7344)

---

> The reintegration of art and life is, after all, a Wagnerian project. Futurists seized on the Gesamtkunstwerk, making it newer and louder.
> 
> **10. Nothung: The First World War and Hitler’s Youth** (Location 7384)

---

> Götterdämmerung—“ He thrusts his spear in Siegfried’s back.” In the medieval Nibelungenlied, Siegfried’s only vulnerability is a spot between his shoulder blades: when the hero bathed in the blood of the dragon, a leaf of a linden tree landed on his back, and that area was untouched by the liquid that otherwise made him invincible. There Hagen pierces him. Hence the expression “stab in the back,” the byword for betrayal by a seeming friend.
> 
> **10. Nothung: The First World War and Hitler’s Youth** (Location 7410)

---

> Decades of Wilhelmine triumphalism made the events of 1918 incomprehensible for many Germans. In the spring of that year, as Krupp guns moved within reach of Paris, victory seemed at hand. The rapid reversals of the summer, leading to the Armistice of November 1918, almost required a conspiratorial explanation. Thus arose the “stab-in-the-back legend”—
> 
> **10. Nothung: The First World War and Hitler’s Youth** (Location 7414)

---

> The metaphor of a Dolchstoß, or dagger thrust, originated with military leaders like Erich Ludendorff and Paul Hindenburg, who adopted a mendacious strategy of blaming the political class for a loss they knew to be inevitable.
> 
> **10. Nothung: The First World War and Hitler’s Youth** (Location 7417)

---

> The point was that something had gone terribly wrong in the march toward German victory, something that had to be avenged.
> 
> **10. Nothung: The First World War and Hitler’s Youth** (Location 7429)

---

> The swiftness of the collapse encouraged the stab-in-the-back fiction. Soldiers returning from the front were especially prone to conspiracy theories, because they were confronted with a world that had changed beyond recognition.
> 
> **10. Nothung: The First World War and Hitler’s Youth** (Location 7435)

---

> Young men who had indulged in Wagnerian fantasies in the last years of empire now found themselves members of a socialist democracy.
> 
> **10. Nothung: The First World War and Hitler’s Youth** (Location 7436)

---

> When the war began, Adolf Hitler was a twenty-five-year-old bohemian painter in Munich, steeped in Wagner, solitary in his habits. Within two years of its end, he had become a rabble-rousing far-right fanatic with a flair for hysterical antisemitic rhetoric.
> 
> **10. Nothung: The First World War and Hitler’s Youth** (Location 7438)

---

> On such questions the latter-day reputation of Richard Wagner also hangs, since the composer is suspected of having nurtured Hitler’s politics of domination and destruction.
> 
> **10. Nothung: The First World War and Hitler’s Youth** (Location 7442)

---

> The most significant of Hitler’s Wagner experiences is said to have taken place a few years earlier, in 1905, at a performance of Rienzi in Linz.
> 
> **10. Nothung: The First World War and Hitler’s Youth** (Location 7461)

---

> The military state that devised Operation Alberich and Plan Hagen was internalizing the ethos of hardness that Wagner’s philosophy of compassion strove to overcome.
> 
> **10. Nothung: The First World War and Hitler’s Youth** (Location 7510)

---

> The 1848 dream of the overthrow of worldly power gave way to a cult of force:
> 
> **10. Nothung: The First World War and Hitler’s Youth** (Location 7512)

---

> Shaw’s perusal of Wagner and Marx must have raised eyebrows in 1883. It seems even more surprising now, given Hitler’s success in convincing posterity that the composer belongs exclusively to the extreme right.
> 
> **11. Ring of Power: Revolution and Russia** (Location 7527)

---

> After the Bolshevik Revolution of 1917, Wagner had a brief vogue as a figurehead of proletarian culture.
> 
> **11. Ring of Power: Revolution and Russia** (Location 7533)

---

> The younger Wagner fascinated the left in large measure because of the emphatic vagueness of his convictions. As he dabbled in various ideologies— socialism, communism, anarchism, democratic liberalism— he created a kind of potpourri of leftist possibilities, which adherents of one camp or another sampled at will.
> 
> **11. Ring of Power: Revolution and Russia** (Location 7546)

---

> Although Wagner never mentioned Marx by name, he made scattered references to communism— occasionally positive, more often dismissive.
> 
> **11. Ring of Power: Revolution and Russia** (Location 7552)

---

> In his last years, after his stint as a Reich nationalist, Wagner again drifted leftward.
> 
> **11. Ring of Power: Revolution and Russia** (Location 7567)

---

> By a sublime historical coincidence, Marx was traveling through Nuremberg at the time of the first Bayreuth Festival.
> 
> **11. Ring of Power: Revolution and Russia** (Location 7575)

---

> In defiance of Marx, Lassalle believed that revolutionaries should engage in parliamentary politics rather than wait for capitalism to collapse from its own contradictions. The Social Democratic Workers’ Party (SDAP), the ancestor of the modern Social Democratic Party in Germany, arose from his efforts.
> 
> **11. Ring of Power: Revolution and Russia** (Location 7591)

---

> W. B. Yeats quoted Victor Hugo to the effect that the theater is the place where “the mob becomes a people.”
> 
> **11. Ring of Power: Revolution and Russia** (Location 7646)

---

> Stravinsky, in later years, insisted that his experience of Bayreuth had been one of extreme discomfort, that he had gone away revolted by the “unseemly and sacrilegious conception of art as religion.”
> 
> **11. Ring of Power: Revolution and Russia** (Location 7790)

---

> More than their counterparts to their west, Russian theorists understood Gesamt to mean “communal” or “collective.”
> 
> **11. Ring of Power: Revolution and Russia** (Location 7927)

---

> The Bolshevik arts scene changed drastically after 1921. The governing apparatus was reorganized, and Lunacharsky began to lose his authority. The state was exerting ever greater control over the arts, and a backlash against avant-gardism began.
> 
> **11. Ring of Power: Revolution and Russia** (Location 8006)

---

> The brutal killing of the Communist leaders Karl Liebknecht and Rosa Luxemburg created a deep rift in the German left, one that may have sealed the fate of the Weimar Republic.
> 
> **11. Ring of Power: Revolution and Russia** (Location 8027)

---

> Younger German and Austrian authors, especially those aligned with the left, had difficulty seeing Wagner as anything but a decrepit relic of a national culture that had descended from imperial pomposity into tribal savagery.
> 
> **11. Ring of Power: Revolution and Russia** (Location 8081)

---

> Perhaps the most pitiless of all Wagner Scenes occurs in The Man Without Qualities, Robert Musil’s satirical epic of Austria-Hungary on the brink of extinction.
> 
> **11. Ring of Power: Revolution and Russia** (Location 8100)

---

> Of the various distortions of the Gesamtkunstwerk that circulated in the early twentieth century, Brecht’s was the most influential.
> 
> **11. Ring of Power: Revolution and Russia** (Location 8125)

---

> The Gesamtkunstwerk charade, Brecht goes on, hypnotizes spectators and renders them passive. Such “sordid intoxication” must stop. Wagner makes clear, however, that the arts should not dissolve into one another.
> 
> **11. Ring of Power: Revolution and Russia** (Location 8129)

---

> The dialectic of emulation and rejection that governs early modernist responses to Wagner is redoubled in Ulysses and The Waste Land.
> 
> **12. Flying Dutchman: Ulysses, The Waste Land, The Waves** (Location 8218)

---

> Both Ulysses and The Waste Land depict a society that existed before the world war and revolution;
> 
> **12. Flying Dutchman: Ulysses, The Waste Land, The Waves** (Location 8224)

---

> As Joyce grew older, his relationship with Wagner oscillated between passion and boredom.
> 
> **12. Flying Dutchman: Ulysses, The Waste Land, The Waves** (Location 8315)

---

> The first books of the Odyssey center on Telemachus, the hero’s son, who is searching for news of his father’s fate. Likewise, Stephen dominates the early part of Ulysses, unconsciously seeking a figurative father he does not yet know.
> 
> **12. Flying Dutchman: Ulysses, The Waste Land, The Waves** (Location 8366)

---

> The recurrence of verbal motifs such as the vampire, the panther, and the drowned man suggests that Joyce is using a leitmotif system— much as Andrey Bely does in Petersburg, a novel similarly rich in Dutchman lore. The method attains dizzying complexity in the “Sirens” chapter, the one that Joyce considered an improvement on Wagner. Around sixty verbal fragments are laid out at the outset. Matthew Hodgart compares them to the catalogue of leitmotifs that appears at the head of Wagner scores and librettos. “Sirens” is set in the concert room of the Ormond Hotel, where Stephen’s father and his friends sing around a piano. Joyce described it as a fugue of many voices, and advised one of his Zurich pupils that it contains a quintet, “as in Die Meistersinger, my favorite Wagnerian opera.” Gossipy barmaids are like Rhinemaidens, seen in watery light: “By bronze, by gold, in oceangreen of shadow.”
> 
> **12. Flying Dutchman: Ulysses, The Waste Land, The Waves** (Location 8482)

---

> Wagner and Wagnerism have effectively been exorcized. The very fact that Bloom mixes up the composers’ names undermines the Romantic cult of the genius.
> 
> **12. Flying Dutchman: Ulysses, The Waste Land, The Waves** (Location 8528)

---

> Eliot later claimed that the footnotes published with the poem were in large part a comedic exercise in “bogus scholarship.”
> 
> **12. Flying Dutchman: Ulysses, The Waste Land, The Waves** (Location 8725)

---

> she recalled reading the book “with spasms of wonder, of discovery, & then again with long lapses of intense boredom”— an ambivalence not unlike her response to Wagner.
> 
> **12. Flying Dutchman: Ulysses, The Waste Land, The Waves** (Location 8785)

---

> What she admired in Joyce, despite his egotism and vulgarity, was his urge to subdue the machine and expose the disorderly flux of being. Joyce never met Woolf, but he was aware of her.
> 
> **12. Flying Dutchman: Ulysses, The Waste Land, The Waves** (Location 8911)

---

> The Wake is his novel of night and dream, a transcript not of the stream of consciousness but of the stream of existence itself. It is suffused with references to Wagner, arguably from the first page to the last.
> 
> **12. Flying Dutchman: Ulysses, The Waste Land, The Waves** (Location 8916)

---

> Why did Joyce return to Wagner at a time when Bach, Stravinsky, and Duke Ellington were the rage? Nora Joyce may have been partly responsible: she went through a phase of listening constantly to Wagner records.
> 
> **12. Flying Dutchman: Ulysses, The Waste Land, The Waves** (Location 8936)

---

> Joyce’s evolving relationship with Wagner “is exactly the behavior, in exactly the pattern, that one would expect the developing Stephen Dedalus to exhibit towards an ‘artist-father’: first reverence, then imitation, then competition, then repudiation, finally peaceful coexistence.”
> 
> **12. Flying Dutchman: Ulysses, The Waste Land, The Waves** (Location 8939)

---

> When Joyce was asked whether the Wake was an attempt at combining music and literature, he responded, “No, it’s pure music.”
> 
> **12. Flying Dutchman: Ulysses, The Waste Land, The Waves** (Location 8951)

---

> Only when we see clusters of verbal motifs associated with particular characters do we realize that those characters are present.
> 
> **12. Flying Dutchman: Ulysses, The Waste Land, The Waves** (Location 8954)

---

> Wagner would now become the chief cultural ornament of the most destructive political regime in history.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9022)

---

> Wagner was a malignant antisemite, but antisemitism does not amount to a political philosophy. Much about his erratic ideology— the anarchist tendencies, the disapproval of standing armies, the dislike of organized power— is antithetical to the totalitarian mind-set.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9037)

---

> Carl Schmitt, whose rationalization of dictatorial measures helped to justify Hitler’s takeover, was acutely aware of myth’s political usefulness— its capacity to direct feeling against real or imaginary adversaries.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9049)

---

> Hostile to the Weimar Republic from the moment of its inception, the Wagners welcomed various attempts to overthrow it.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9080)

---

> Circa 1918, the author of Death in Venice appeared to be heading down the same path that beguiled so many Wagnerites of his generation— the path that led, by so many twists and turns, to Fascism.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9130)

---

> He begins with the startling announcement that he is “not a very proper German”— on account of his mother’s Latin American heritage.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9145)

---

> When Hitler first attended performances at Bayreuth, in 1925, he kept a low profile, stealing into the Wagners’ box just before the music started. He did not return to the festival until 1933, partly in order to avoid causing a political disruption, although he also objected to the continued presence of Jewish singers.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9318)

---

> Hitler deploys the vile word that the composer popularized—“ Verjudung,” Jewification. As Wagner spoke of the Jewification of art, Hitler speaks of the “inner Jewification of our people.”
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9327)

---

> Somewhat astonishingly, though, he never directly quoted Wagner on the subject of the Jews.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9338)

---

> Hitler’s relationship with Wagner remained one of musical fandom rather than of ideological fanaticism. His knowledge of the operas was pedantically acute: he impressed artists and fellow music lovers with detailed commentary on tempos, cuts, and matters of interpretation. But he gave no sign of having absorbed Wagner’s grander themes— the critique of power in the Ring, the consecration of compassion in Parsifal.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9344)

---

> In a paradoxical way, Hitler’s uncomplicated, seemingly apolitical devotion to Wagner assisted in the politicization of the composer in the Third Reich.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9350)

---

> Walter Legge, reporting for the Manchester Guardian, wrote that one could easily have “mistaken this year’s Wagner festival for a Hitler festival.”
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9372)

---

> the composer’s complexities caused trouble. He was too strange, too eccentric, to serve as a reliable ideological bulwark. Nor was his work popular enough, in the mass-market sense, to operate as a unifying force.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9411)

---

> Parsifal, with its ethos of compassion, caused the most trouble. Goebbels, Rosenberg, and Himmler all thought that it should be removed from the repertory because its quasi-Christian message was irreconcilable with Nazi ideology.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9431)

---

> Parsifal’s overriding message of “knowing through compassion”—“ durch Mitleid wissend”— diverged from a Nazi culture that all but outlawed sentimental weakness.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9439)

---

> Hitler wished to foster a culture in which Wagner and the rest of the classical-music legacy would no longer be limited to the elites. Opera houses should hold more people, and tickets should be cheaper. Nonetheless, Wagner’s popularity on German stages actually declined during the Nazi era.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9460)

---

> As Goebbels knew, the general public was most avid for hit songs, dance music, operetta melodies, and light classics.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9469)

---

> Although the Nazis denounced jazz at every opportunity, they never formally banned it nationwide, and later found it expedient to give the public what it wanted.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9474)

---

> This popular orientation, which was the core of the Goebbels strategy, displaced Hitler’s Wagnerism in the later years of the regime.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9482)

---

> Hitler adopted the Wagners as a surrogate family, showering favors on Wieland, the heir apparent.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9487)

---

> Ironically, though, Hitler’s assumption of power sent Bayreuth into financial crisis. Foreign and Jewish visitors, who had remained a crucial part of the festival’s audience even after the hyper-nationalist debacle of 1924, grew scarce:
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9500)

---

> Increasingly, Bayreuth played to a fictitious audience, assembled to validate Hitler’s belief that he was bringing Wagner to the masses.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9504)

---

> Four years later, the literary world was confronted with Doctor Faustus: The Life of the German Composer Adrian Leverkühn, Told by a Friend. It was the book Mann had been preparing all his life to write: the biography of a Faustian artist as an allegory of Germany’s spiritual crisis.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9572)

---

> In The Magic Mountain, Mann advocated Nietzschean values as a way beyond Wagnerian “sympathy for death.” By the forties, he was losing faith in that philosophy. Leverkühn’s modernism begins to seem less humane than the creaky Wagnerian apparatus that it wishes to supplant.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9613)

---

> During the First World War, everything German had been demonized. This time, the Allied countries made a point of extolling the “good Germany”— an intellectual and artistic community that could reconstitute itself abroad.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9629)

---

> For most cultural arbiters, the “good Germany” still included Wagner, who kept his place in the opera and concert repertories of Allied countries.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9632)

---

> Arturo Toscanini, the most widely acclaimed classical musician of the era, managed to make Wagner a symbol of the anti-Fascist struggle.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9641)

---

> Most conspicuously, in 1938 Toscanini went to Lucerne, Wagner’s former place of exile, to lead an orchestra that included refugees from Germany and Austria— an early edition of what would become the Lucerne Festival.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9652)

---

> As the thirties gave way to the forties, a very different perspective began to take hold: one that saw Wagner not as a victim of Nazism but as an agent of it.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9666)

---

> During the war, Wagner’s popularity in America actually surged.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9694)

---

> Toscanini mounted a series of wartime Wagner concerts, effectively conscripting the composer to the Allied cause.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9703)

---

> Winifred Wagner had assumed that the Bayreuth Festival would be shut down in wartime, as had happened in 1914, but Hitler insisted that it proceed.
> 
> **13. Siegfried’s Death: Nazi Germany and Thomas Mann** (Location 9745)

---

> From the Festspielhaus, the media theorist Friedrich Kittler writes, “the darkness of all our cinemas derives.”
> 
> **14. Ride of the Valkyries: Film from The Birth of a Nation to Apocalypse Now** (Location 9913)

---

> In film, by contrast, music almost always plays a subordinate role. That reversal of priorities makes Hollywood almost the opposite of Bayreuth.
> 
> **14. Ride of the Valkyries: Film from The Birth of a Nation to Apocalypse Now** (Location 9946)

---

> That this foundational work of cinema history is racist to the core recapitulates the Wagner problem in an American context. Infamously, President Woodrow Wilson hosted a screening of the film at the White House, giving it an official imprimatur.
> 
> **14. Ride of the Valkyries: Film from The Birth of a Nation to Apocalypse Now** (Location 9984)

---

> The insertion of “The Ride of the Valkyries” into The Birth of a Nation tells us more about the cultural arrogance of American white supremacism than it does about the nefarious influence of Wagner.
> 
> **14. Ride of the Valkyries: Film from The Birth of a Nation to Apocalypse Now** (Location 10003)

---

> In August 1939, the signing of the Nazi-Soviet non-aggression pact temporarily returned Wagner to favor in the Soviet Union.
> 
> **14. Ride of the Valkyries: Film from The Birth of a Nation to Apocalypse Now** (Location 10169)

---

> The Hitlerizing of Wagner in Hollywood began with the onset of the Second World War.
> 
> **14. Ride of the Valkyries: Film from The Birth of a Nation to Apocalypse Now** (Location 10210)

---

> Many people had the impression that Triumph of the Will is awash in Wagner.
> 
> **14. Ride of the Valkyries: Film from The Birth of a Nation to Apocalypse Now** (Location 10226)

---

> listeners imagine more Wagner than there is, because he seems to belong in an ode to Hitler.
> 
> **14. Ride of the Valkyries: Film from The Birth of a Nation to Apocalypse Now** (Location 10232)

---

> During the Cold War, the instinct to vilify the Germans ran up against a rival agenda. Because West Germany had become an ally in the effort to contain the Soviets, Realpolitik required a measure of forgiveness.
> 
> **14. Ride of the Valkyries: Film from The Birth of a Nation to Apocalypse Now** (Location 10318)

---

> For decades, aerial warfare had been stirring thoughts of the Valkyries and their “air-horses,” as Wagner called them.
> 
> **14. Ride of the Valkyries: Film from The Birth of a Nation to Apocalypse Now** (Location 10573)

---

> Apocalypse soon became a military fetish object, its Wagner Scene influencing real-life behavior. Black Hawk helicopters blared the “Ride” during the American invasion of Grenada in 1983. In 1991, a psy-ops unit played it at the Battle of 73 Easting, in the Iraqi desert, during the First Gulf War. Loudspeakers mounted on Humvees boomed out the “Ride” at Fallujah in 2004, during the second American invasion of Iraq.
> 
> **14. Ride of the Valkyries: Film from The Birth of a Nation to Apocalypse Now** (Location 10640)

---

> Part of the outrage in 1976 stemmed from Chéreau’s challenge to the elite audience: Wagner’s critique of bourgeois society is turned on Bayreuth itself.
> 
> **15. The Wound: Wagnerism After 1945** (Location 10678)

---

> The thoroughgoing Hitlerization of the composer made him Exhibit A for the supposition that German culture had been complicit in the Holocaust. The virtual ban on playing Wagner in Israel has given him a singularly baleful aura.
> 
> **15. The Wound: Wagnerism After 1945** (Location 10692)

---

> Bayreuth’s renaissance in the 1950s was a spectacular and unexpected development.
> 
> **15. The Wound: Wagnerism After 1945** (Location 10702)

---

> The New Bayreuth, as it was called, transformed Wagner’s image. In a feat of sorcery worthy of their grandfather, the brothers convinced the world that they had decisively broken with the Nazi past.
> 
> **15. The Wound: Wagnerism After 1945** (Location 10712)

---

> However intractable the family’s attitudes, the metamorphosis of the Bayreuth stage was real and profound.
> 
> **15. The Wound: Wagnerism After 1945** (Location 10720)

---

> His persistence as an object of philosophical scrutiny has much to do with Nietzsche’s own ascendancy, which began in the 1890s and accelerated as the twentieth century went on.
> 
> **15. The Wound: Wagnerism After 1945** (Location 10787)

---

> Having endorsed the Nazi takeover in 1933, Heidegger sided with those who saw Wagner as a decadent detour of the German spirit.
> 
> **15. The Wound: Wagnerism After 1945** (Location 10795)

---

> Adorno says that the composer never needed to renounce his revolutionary phase because he was never a revolutionary to begin with.
> 
> **15. The Wound: Wagnerism After 1945** (Location 10809)

---

> Lévi-Strauss saw universal patterns undergirding the social norms and the mythic narratives of diverse cultures. Appropriating terminology from linguistics, he began to speak of generalizable “structures” that impose order on the world. This insight animated the new philosophical discipline of structuralism.
> 
> **15. The Wound: Wagnerism After 1945** (Location 10856)

---

> Lévi-Strauss crowned Wagner the godfather of the structural analysis of myth.
> 
> **15. The Wound: Wagnerism After 1945** (Location 10866)

---

> For many German-speaking artists and writers who came to the fore in the postwar decades, Wagner was the god that failed.
> 
> **15. The Wound: Wagnerism After 1945** (Location 10946)

---

> Dalí’s reworking of Wagner, at once subversive and adoring, has much in common with that of his sometime collaborator Buñuel. At times, the composer is deposited like a kitsch object in pristine landscapes of juxtaposition and dissociation.
> 
> **15. The Wound: Wagnerism After 1945** (Location 11079)

---

> Dalí’s proclivities took a baroque turn when he developed an erotic interest in Hitler, disclosing that a rear view of the Führer gave him a “delicious gustatory thrill,” a “Wagnerian ecstasy.”
> 
> **15. The Wound: Wagnerism After 1945** (Location 11092)

---

> The dystopias of Dick’s classic sci-fi novels, often involving authoritarian regimes on American soil, frequently include the Nazi Wagner.
> 
> **15. The Wound: Wagnerism After 1945** (Location 11154)

---

> At a time when consciousness of the enormity of the Holocaust was deepening, both in Germany and abroad, the conversation around Wagner increasingly focused on his antisemitism and his effect on Hitler. The publication of Cosima Wagner’s diaries, in 1976 and 1977, revealed that the composer was even more bigoted than his published writings let on.
> 
> **15. The Wound: Wagnerism After 1945** (Location 11180)

---

> just as the focus on Wagner’s antisemitism was intensifying, Zubin Mehta, the music director of the Israel Philharmonic, tried to break the unofficial Israeli ban on performances of the composer.
> 
> **15. The Wound: Wagnerism After 1945** (Location 11185)

---

> The Wagner moratorium had begun in 1938, when Toscanini agreed to remove the Meistersinger prelude from a Palestine Symphony program.
> 
> **15. The Wound: Wagnerism After 1945** (Location 11193)

---

> In 1991, Barenboim announced a Wagner concert in Tel Aviv, then canceled it. He tried again in 2001, asking an audience in Jerusalem whether they wished to hear the Tristan prelude as an encore. During the prolonged debate that followed, protesters shouted “Fascist!” and “Concentration camp music!” The cheers won out, and Barenboim went ahead.
> 
> **15. The Wound: Wagnerism After 1945** (Location 11198)

---

> Na’ama Sheffi, in a study of the Israeli Wagner controversy, finds that the discussion has been driven largely by people who do not attend concerts regularly. (At the time of Mehta’s 1981 action, a majority of concertgoers favored playing Wagner.)
> 
> **15. The Wound: Wagnerism After 1945** (Location 11203)

---

> Woody Allen made an often-quoted crack about Wagner in his 1993 film Manhattan Murder Mystery. As his character walks out of a performance of The Flying Dutchman at the Met, he says, “I can’t listen to that much Wagner, ya know? I start to get the urge to conquer Poland.”
> 
> **15. The Wound: Wagnerism After 1945** (Location 11216)

---

> In Russia, where the neo-fascist guru Aleksandr Dugin drops Nietzsche and Wagner allusions, a mercenary unit known as the Wagner Group appears to have been named after the composer.
> 
> **15. The Wound: Wagnerism After 1945** (Location 11234)

---

> The author of The Lord of the Rings knew the composer’s work and evidently found some enjoyment in it, but he resisted comparisons between his novels of Middle-earth and the operatic Ring.
> 
> **15. The Wound: Wagnerism After 1945** (Location 11257)

---

> As totalitarian regimes overran Europe and Russia in the twenties and thirties, American comic-book culture countered with the superhero.
> 
> **15. The Wound: Wagnerism After 1945** (Location 11300)

---

> Democratic mass culture prefers to consider itself exempt from the forces that made Wagner vulnerable to exploitation by the Nazis. Fantasy artists like to believe they are creating allegories of liberal good versus reactionary evil.
> 
> **15. The Wound: Wagnerism After 1945** (Location 11367)

---

> In Fitzcarraldo— the tale of a mad Irish businessman who tries to build an opera house in the Amazonian jungle— Herzog had a steamship dragged over a hill.
> 
> **15. The Wound: Wagnerism After 1945** (Location 11431)