---
title: "Why Bother with Elections?"
author: Adam Przeworski
date: 2025-07-26
Rating: 9 / 10
---

### Highlights
> This is a minimalist , “ Churchillian , ” perspective , a view that admits that elections are not pretty , that they are never quite “ fair , ” that they are impotent against some barriers they face in particular societies , and that they are far from realizing the ideals that led to their emergence and are still held by some people as the criteria to evaluate them . But no other method of selecting our rulers , I believe , can do better .
> 
> **1 Introduction** (Location 251)

---

> between 1788 and 2008 political power changed hands as a result of 544 elections and 577 coups . The very idea of selecting governments by elections is quite recent and still quite rare . The first national - level election based on individual suffrage , in which representatives were chosen for a limited term , dates only from 1788 ; the first time in history that the helm of the government changed as a result of an election was in 1801 ; both events took place in the United States .
> 
> **1 Introduction** (Location 281)

---

> Still , as of 2008 , 68 countries , including the two behemoths , China and Russia , had never experienced a change in office between parties as a result of an election .
> 
> **1 Introduction** (Location 287)

---

> Those who see such elections as mere “ window dressing ” must ask themselves why some rulers , say those in Russia , care to dress their windows ,
> 
> **1 Introduction** (Location 293)

---

> Holding non - competitive elections is a trick , but it is based on the ideal that the ultimate source of power resides in the people ,
> 
> **1 Introduction** (Location 295)

---

> Systems of representative government were born under a fear of participation by the broad masses . One would not err much in thinking that the strategic problem of “ founders , ” pretty much everywhere , was how to construct representative government for the rich while protecting it from the poor .
> 
> **1 Introduction** (Location 303)

---

> The relation between property and power has been the axis organizing political conflicts over the past 200 years , with outcomes varying across periods and countries .
> 
> **1 Introduction** (Location 311)

---

> Elections are competitive – incumbents expose themselves to the possibility of losing – only when their stakes in the outcomes of elections are not too high , when all that is at play is who would govern for some fixed period of time , perhaps promoting the interests of those who elected them but not threatening vital interests or values of those who opposed them .
> 
> **1 Introduction** (Location 322)

---

> Carl Schmitt , an influential German twentieth - century political philosopher , claimed that the rule of the people is sustained whenever rulers act in the common good of everyone , regardless of how they are selected .
> 
> **Part I: How Elections Work** (Location 371)

---

> The principle that only those who were elected could be considered as representing the people was revolutionary .
> 
> **Part I: How Elections Work** (Location 388)

---

> Elections are supposed to convey instructions to those elected to do what citizens would have done themselves in their place .
> 
> **Part I: How Elections Work** (Location 439)

---

> The relation between property and power was intimate and often unabashed . This is why some voices are so revealing : they only bare the true beliefs , real intentions . The people cannot be trusted because it can “ err ” : James Madison said it , Simón Bolvar said it , and so did Henry Kissinger .
> 
> **Part I: How Elections Work** (Location 467)

---

> parliaments can remove governments without accusing them of anything ,
> 
> **Part I: How Elections Work** (Location 520)