---
title: "Austerlitz"
author: W. G. Sebald
date: 2026-01-25
Rating: 9 / 10
---

### Highlights

> Sebald borrowed this habit of repetitive attribution from the Austrian writer Thomas Bernhard, who also influenced Sebald’s diction of extremism. Almost every sentence in this book is a cunning combination of the quiet and the loud:
> 
> **Introduction** (Location 85)

---

> In Thomas Bernhard’s work, extremity of expression is indistinguishable from the Austrian author’s comic, ranting rage, and his tendency to circle obsessively around madness and suicide.
> 
> **Introduction** (Location 89)

---

> There is also guilt at the idea that the dead are at our mercy, that we can choose to remember or forget them. This is finely caught by Theodor Adorno, in an essay on Mahler, written in 1936: “So the memory is the only help that is left to them [the dead]. They pass away into it, and if every deceased person is like someone who was murdered by the living, so he is also like someone whose life they must save, without knowing whether the effort will succeed.”
> 
> **Introduction** (Location 114)

---

> Of all the rescues that the novel poses, the most difficult may be this one: to restore to Jacques Austerlitz the individuality of his name and experience, to rescue the living privacy of the surname “Austerlitz” from the dead, irrelevant publicity of the place name “Austerlitz.” Jacques should not be a battle, nor a railway station, nor a thing.
> 
> **Introduction** (Location 205)

---

> Evan told tales of the dead who had been struck down by fate untimely, who knew they had been cheated of what was due to them and tried to return to life. If you had an eye for them they were to be seen quite often, said Evan. At first glance they seemed to be normal people, but when you looked more closely their faces would blur or flicker slightly at the edges.
> 
> **First Page** (Location 785)

---

> think you will find it is a small place in Moravia, site of a famous battle, you know. And sure enough, the Moravian village of Austerlitz was discussed at great length during the next school year,
> 
> **First Page** (Location 948)

---

> His undoubted pièce de résistance was the battle of Austerlitz. He spoke on it at length, describing the terrain, the highway leading east from Brünn to Olmütz, with the hilly Moravian countryside on its left and the Pratzen heights on its right,
> 
> **First Page** (Location 965)

---

> The Russian and Austrian troops had come down from the mountainsides like a slow avalanche, and soon, increasingly unsure where they were going, were wandering around on the slopes and in the meadows below, while the French, in a single onslaught, captured the now half-abandoned positions on the Pratzen heights and then proceeded to attack the enemy in the rear from that vantage point.
> 
> **First Page** (Location 971)

---

> for the first time in as far back as I can remember I recollected myself as a small child, at the moment when I realized that it must have been to this same waiting room I had come on my arrival in England over half a century ago.
> 
> **First Page** (Location 1670)

---

> I realized then, he said, how little practice I had in using my memory, and conversely how hard I must always have tried to recollect as little as possible, avoiding everything which related in any way to my unknown past.
> 
> **First Page** (Location 1699)

---

> and at the end there was an Austerlitzová Agáta, evidently a single woman. The names were followed by the professions of their bearers— dealer in textiles en gros, rabbi, bandages manufacturer, principal clerk, silversmith, printing works proprietor, and finally opera singer—
> 
> **First Page** (Location 1816)

---

> And so, said Austerlitz, no sooner had I arrived in Prague than I found myself back among the scenes of my early childhood, every trace of which had been expunged from my memory for as long as I could recollect.
> 
> **First Page** (Location 1821)

---

> it was as if I had already been this way before and memories were revealing themselves to me not by means of any mental effort but through my senses, so long numbed and now coming back to life.
> 
> **First Page** (Location 1824)

---

> I found myself facing Vera Ryšanová, who— as she was soon to tell me— had been my mother Agáta’s neighbor and my nurserymaid in the thirties when she, Vera, had been studying Romance languages at Prague University.
> 
> **First Page** (Location 1837)

---

> we spoke first about my lost parents, Agáta and Maximilian. Maximilian Aychenwald, who had come to Prague from St. Petersburg where his father traded in spices until the year of the revolution, soon established himself as one of the most prominent officials of the Czech Social Democratic Party, said Vera.
> 
> **First Page** (Location 1853)

---

> Despite her dark and rather melancholy appearance, so I think Vera began, said Austerlitz, your mother Agáta was a very genial, on occasion even lighthearted woman.
> 
> **First Page** (Location 2002)

---

> But from that day on Agáta was a changed woman, Vera continued, said Austerlitz. What she had preserved of her cheerfulness and confidence, in defiance of all difficulties, was now overcast by a depression which she was clearly unable to dispel.
> 
> **First Page** (Location 2095)

---

> Yes, and the small boy in the other photograph, said Vera after a while, this is you, Jacquot, in February 1939, about six months before you left Prague.
> 
> **First Page** (Location 2198)

---

> I feel more and more as if time did not exist at all, only various spaces interlocking according to the rules of a higher form of stereometry, between which the living and the dead can move back and forth as they like,
> 
> **First Page** (Location 2221)

---

> we who are still alive are unreal in the eyes of the dead, that only occasionally, in certain lights and atmospheric conditions, do we appear in their field of vision.
> 
> **First Page** (Location 2222)

---

> I have always felt as if I had no place in reality, as if I were not there at all, and I never had this impression more strongly than on that evening in the šporkova when the eyes of the Rose Queen’s page looked through me.
> 
> **First Page** (Location 2224)

---

> What I found most uncanny of all, however, were the gates and doorways of Terezín, all of them, as I thought I sensed, obstructing access to a darkness never yet penetrated,
> 
> **First Page** (Location 2262)

---

> the endless landscape painted round a lampshade in fine brushstrokes, showing a river running quietly through perhaps Bohemia or perhaps Brazil?
> 
> **First Page** (Location 2288)

---

> I understood it all now, yet I did not understand it, for every detail that was revealed to me as I went through the museum from room to room and back again, ignorant as I feared I had been through my own fault, far exceeded my comprehension.
> 
> **First Page** (Location 2317)

---

> I had just been reading, several times over, a note on one of the display panels, to the effect that in the middle of December 1942, and thus at the very time when Agáta came to Terezín, some sixty thousand people were shut up together in the ghetto, a built-up area of one square kilometer at the most, and a little later, when I was out in the deserted town square again, it suddenly seemed to me, with the greatest clarity, that they had never been taken away after all, but were still living crammed into those buildings and basements and attics,
> 
> **First Page** (Location 2332)

---

> At some time in the past, I thought, I must have made a mistake, and now I am living the wrong life. Later, on a walk through the deserted town and up to the fountain colonnade, I kept feeling as if someone else were walking beside me, or as if something had brushed against me. Every new view that opened out before us as we turned a corner, every façade, every flight of steps looked to me both familiar and utterly alien. I felt that the decrepit state of these once magnificent buildings, with their broken gutters, walls blackened by rainwater, crumbling plaster revealing the coarse masonry beneath it, windows boarded up or clad with corrugated iron, precisely reflected my own state of mind,
> 
> **First Page** (Location 2482)

---

> On the way back to the hotel Marie spoke, almost as a warning, so it seemed to me, said Austerlitz, of the clouding of Schumann’s mind as his madness came on and how at last, in the middle of carnival crowds in Düsseldorf, he took a leap over the parapet of the bridge into the icy waters of the Rhine, from which he was pulled out by two fishermen. He lived for a number of years after that, said Marie, in a private asylum for the mentally deranged near Bonn or Bad Godesberg, where he was visited by Clara and the young Brahms at intervals, and since it was impossible to converse with him anymore, withdrawn from the world as he was and humming tunelessly to himself, they generally contented themselves with looking into his room for a while through a small trap in the door.
> 
> **First Page** (Location 2504)

---

> I could not admit to myself how right everything Marie said was, but today I know why I felt obliged to turn away when anyone came too close to me, I know that I thought this turning away made me safe, and that at the same time I saw myself transformed into a frightful and hideous creature, a man beyond the pale.
> 
> **First Page** (Location 2531)

---

> what was described as a Verschönerungsaktion or general improvement campaign was undertaken, with an eye to the imminent visit in the early summer of 1944 of a Red Cross commission, an event regarded by those authorities of the Reich responsible as a good opportunity to dissimulate the true nature of their deportation policy,
> 
> **First Page** (Location 2775)

---

> despite Adler’s meticulous account, which I had read down to the last footnote with the greatest attention, I found myself unable to cast my mind back to the ghetto and picture my mother Agáta there at the time.
> 
> **First Page** (Location 2805)

---

> And then, Austerlitz continued, towards the end of the film there was the comparatively long sequence showing the first performance of a piece of music composed in Theresienstadt, Pavel Haas’s study for string orchestra, if I am not mistaken.
> 
> **First Page** (Location 2854)