---
title: "Blood Meridian"
author: Cormac McCarthy
date: 2026-05-10
Rating: 9 / 10
---

### Highlights

> A legion of horribles, hundreds in number, half naked or clad in costumes attic or biblical or wardrobed out of a fevered dream with the skins of animals and silk finery and pieces of uniform still tracked with the blood of prior owners, coats of slain dragoons, frogged and braided cavalry jackets, one in a stovepipe hat and one with an umbrella and one in white stockings and a bloodstained wedding veil and some in headgear or cranefeathers or rawhide helmets that bore the horns of bull or buffalo and one in a pigeontailed coat worn backwards and otherwise naked and one in the armor of a Spanish conquistador, the breastplate and pauldrons deeply dented with old blows of mace or sabre done in another country by men whose very bones were dust and many with their braids spliced up with the hair of other beasts until they trailed upon the ground and their horses' ears and tails worked with bits of brightly colored cloth and one whose horse's whole head was painted crimson red and all the horsemen's faces gaudy and grotesque with daubings like a company of mounted clowns, death hilarious, all howling in a barbarous tongue and riding down upon them like a horde from a hell more horrible yet than the brimstone land of Christian reckoning, screeching and yammering and clothed in smoke like those vaporous beings in regions beyond right knowing where the eye wanders and the lip jerks and drools.
>
> **IV**

---

> He was wounded in a country far from home and although his eyes took in the alien stones about yet the greater void beyond seemed to swallow up his soul.
>
> **V**

---

> I know your kind, he said. What's wrong with you is wrong all the way through you.
> 
> **V**

---

> The jagged mountains were pure blue in the dawn and everywhere birds twittered and the sun when it rose caught the moon in the west so that they lay opposed to each other across the earth, the sun whitehot and the moon a pale replica, as if they were the ends of a common bore beyond whose terminals burned worlds past all reckoning.
>
> **VII**

---

> They crossed before the sun and vanished one by one and reappeared again and they were black in the sun and they rode out of that vanished sea like burnt phantoms with the legs of the animals kicking up the spume that was not real and they were lost in the sun and lost in the lake and they shimmered and slurred together and separated again and they were augmented by planes in lurid avatars and began to coalesce and there began to appear above them in the dawn-broached sky a hellish likeness of their ranks riding huge and inverted and the horses' legs incredibly elongate trampling down the high thin cirrus and the howling antiwarriors pendant from their mounts immense and chimeric and the high wild cries carrying that flat and barren pan like the cries of souls broke through some misweave in the weft of things into the world below.
>
> **IX**

---

> They rode in a narrow enfilade along a trail strewn with the dry round turds of goats and they rode with their faces averted from the rock wall and the bake-oven air which it rebated, the slant black shapes of the mounted men stenciled across the stone with a definition austere and implacable like shapes capable of violating their covenant with the flesh that authored them and continuing autonomous across the naked rock without reference to sun or man or god.
>
> **XI**

---

> If God meant to interfere in the degeneracy of mankind would he not have done so by now? Wolves cull themselves, man. What other creature could? And is the race of man not more predacious yet? The way of the world is to bloom and to flower and die but in the affairs of men there is no waning and the noon of his expression signals the onset of night. His spirit is exhausted at the peak of its achievement. His meridian is at once his darkening and the evening of his day. He loves games? Let him play for stakes.
>
> **XI**

---

> Whatever in creation exists without my knowledge exists without my consent.
> 
> **XIV**

---

> The man who believes that the secrets of the world are forever hidden lives in mystery and fear. Superstition will drag him down. The rain will erode the deeds of his life. But that man who sets himself the task of singling out the thread of order from the tapestry will by the decision alone have taken charge of the world and it is only by such taking charge that he will effect a way to dictate the terms of his own fate.
>
> **XIV**

---

> The flames sawed in the wind and the embers paled and deepened and paled and deepened like the bloodbeat of some living thing eviscerate upon the ground before them and they watched the fire which does contain within it something of men themselves inasmuch as they are less without it and are divided from their origins and are exiles. For each fire is all fires, and the first fire and the last ever to be.
>
> **XVII**

---

> The truth about the world, he said, is that anything is possible. Had you not seen it all from birth and thereby bled it of its strangeness it would appear to you for what it is, a hat trick in a medicine show, a fevered dream, a trance bepopulate with chimeras having neither analogue nor precedent, an itinerant carnival, a migratory tentshow whose ultimate destination after many a pitch in many a mudded field is unspeakable and calamitous beyond reckoning.
>
> **XVII**

---

> Even in this world more things exist without our knowledge than with it and the order in creation which you see is that which you have put there, like a string in a maze, so that you shall not lose your way. For existence has its own order and that no man's mind can compass, that mind itself being but a fact among others.
>
> **XVII**

---

> It makes no difference what men think of war, said the judge. War endures. As well ask men what they think of stone. War was always here. Before man was, war waited for him. The ultimate trade awaiting its ultimate practitioner.
>
> **XVII**
