---
title: "El Hombre que Amaba a los Perros"
author: Leonardo Padura
date: 2026-03-19
Rating: 9 / 10
---

### Highlights
> los nativos de aquellos desiertos remotos han glorificado las piedras, pues aseguran que en su capacidad de resistencia se expresa una fuerza, encerrada para siempre en su interior, como fruto de una voluntad eterna.
> 
> **Primera parte** (Location 192)

---

> En medio de la tormenta de amor y de odio en que vivieron por tantos años, Caridad nunca sabría, pues Ramón tampoco le regaló jamás el placer de confesárselo, que en aquel momento, viéndola partir rescatada por la encarnación misma de lo que ella más despreciaba, él dejó de ser un niño, pues se convenció de que su madre tenía razón: si uno quería saberse realmente libre, tenía que hacer algo para cambiar aquel mundo de mierda que laceraba la dignidad de las personas.
> 
> **Primera parte** (Location 717)

---

> —Prepárate, socio: aquí te vas a hacer un cínico o te van a hacer mierda… Bienvenido a la realidad real.
> 
> **Primera parte** (Location 1264)

---

> a partir del 20 de febrero de 1932 Liev Trotski y los miembros de su familia que se encontraban fuera del territorio de la Unión de los Soviets dejaban de ser ciudadanos del país y perdían todos los derechos constitucionales y la protección del Estado.
> 
> **Primera parte** (Location 1627)

---

> Sin duda la primera intención de Stalin era la de convertirle en un proscrito, sin un Estado a sus espaldas, totalmente a merced de sus enemigos, entre los que ahora se alzaba el propio pueblo soviético. Pero detrás estaba la consecuencia lógica que convertía a sus partidarios dentro del país no ya en opositores políticos, sino en colaboradores de un agente «extranjero» y, por tanto, acusables del delito de traición, el más temido en días de fervor patriótico y nacionalista.
> 
> **Primera parte** (Location 1636)

---

> Ante el precipicio al que se asomaban él y su familia, Liev Davídovich lamentó como nunca la falta de realismo y el exceso de confianza que lo habían cegado durante años, hasta el punto de permitir que engendrara y creciera, ante sus propios ojos, aquel tumor maligno adherido a las murallas del Kremlin llamado Iósif Stalin.
> 
> **Primera parte** (Location 1639)

---

> «La principal cualidad que distingue a Stalin», le había dicho un día Bujarin, «es la pereza; la segunda, la envidia sin límites contra todos los que saben o pueden saber más que él. Hasta contra Lenin ha hecho labor de zapa».
> 
> **Primera parte** (Location 1658)

---

> La coalición que había llevado a Hitler al poder era demasiado heterogénea, y la izquierda y el centro tendrían que explotar esa debilidad antes de que el líder fascista consolidara sus posiciones. Pero los días habían pasado sin que los comunistas lanzaran siquiera un quejido, como si su destino no estuviese en juego.
> 
> **Primera parte** (Location 2258)

---

> La indignación de Liev Davídovich explotó cuando supo que el ejecutivo de la Internacional comunista había emitido una desvergonzada declaración de apoyo al Partido alemán, cuya estrategia política calificaba de impecable, mientras repetía que la victoria de los nazis era solo una coyuntura transitoria, de la cual las fuerzas progresistas saldrían victoriosas.
> 
> **Primera parte** (Location 2267)

---

> Ellos, los vencedores, habían administrado sin piedad la derrota de sus adversarios, y el Partido tuvo que funcionar como el instrumento de la Historia y de su inevitable venganza masiva, aunque impersonal. Había sido una violencia despiadada, seguramente excesiva, pero necesaria: la de la clase vencedora sobre la vencida, la disyuntiva del «nosotros o ellos»…
> 
> **Primera parte** (Location 2660)

---

> el presidente norteamericano Roosevelt había vuelto a rechazar la petición de asilo que Liev Davídovich le dirigiera.
> 
> **Primera parte** (Location 3434)

---

> Para Liev Davídovich la posibilidad de ir a México, quizás la más realista en ese momento, lo desasosegaba: sabía que en ese país su vida peligraría tanto como si se acostara a dormir desnudo en la costa del fiordo helado de Hurum.
> 
> **Primera parte** (Location 3437)

---

> Aunque la perspectiva de marchar a México seguía pareciéndole peligrosa, el exiliado trató de convencerse de que era preferible morir a manos de cualquier asesino que vivir en ese cautiverio que amenazaba endurecerse hasta aplastarlo.
> 
> **Primera parte** (Location 3461)

---

> —El camarada Stalin piensa que ha llegado el momento… Vamos a preparar la salida de Trotski del mundo. Ramón no pudo evitar la sacudida. Quiso pensar que había oído mal, pero sabía que había entendido perfectamente y que en ese mismo instante, solo por haber escuchado aquellas palabras de Kótov, su vida había caído en una dimensión extraordinaria. —¿ Qué quieres decir con preparar? —logró preguntar. —Empezar a trabajar para ello. Montar un golpe maestro. Por eso tú y otros comunistas españoles estáis aquí. —¿ Nos vais a preparar para matarlo? —Los vamos a preparar para muchas cosas. —¿ Y por qué coño tenemos que ser españoles?
> 
> **Primera parte** (Location 3574)

---

> En esos meses fue cuando realmente Ramón empezó a dejar de ser Ramón, y solo volvería a serlo cuando el hombre en que lo convertirían se asfixiaba y, para salvarlo, debía salir a flote el viejo Ramón Mercader. O siempre que le ordenaban sacarlo a tomar sol. Pero ya nunca volvió a ser el mismo Ramón Mercader del Río…
> 
> **Primera parte** (Location 3654)

---

> Cuando a finales de noviembre Grigóriev reapareció en la base, el Soldado 13 ya era, hasta donde los entrenadores podían garantizarlo, un hombre de mármol, convencido de la necesidad de cumplir cualquier misión que se le ordenase, forjado para resistir en silencio diversos asedios, dotado de un odio visceral contra los enemigos trotskistas y apto para ser convertido en la persona que le asignaran.
> 
> **Primera parte** (Location 3684)

---

> El plan, que debía prepararse con sumo cuidado, tendría que cumplir algunas condiciones importantes: la primera, que no fuese posible encontrar una pista capaz de ligar a cualquier organismo soviético con la operación; la segunda, que la acción final solo se ejecutase cuando él, personalmente, él, recalcó, diera la orden;
> 
> **Primera parte** (Location 3820)

---

> ¿cómo era posible que López tuviera una información tan precisa de la vida y sentimientos de su amigo?
> 
> **Primera parte** (Location 4128)

---

> ¿Jaime López no sería el mismísimo Ramón Mercader?
> 
> **Primera parte** (Location 4134)

---

> Si escuchar cierta música occidental, creer en cualquier dios, practicar yoga, leer determinadas novelas consideradas ideológicamente dañinas o escribir un cuento de mierda sobre un pobre tipo que siente miedo podía significar un estigma y hasta implicar una condena, meterse con el trotskismo hubiera sido como colgarse una soga al cuello, sobre todo para los que se movían en el mundo de la cultura, la enseñanza y las ciencias sociales.
> 
> **Primera parte** (Location 4176)

---

> Ésta es una historia repulsiva, que devalúa ella sola millones de discursos que se han hecho durante sesenta años…
> 
> **Primera parte** (Location 4229)

---

> Aquella sórdida jugada le permitió a Liev Davídovich ver algo que se le había escapado durante los juicios anteriores: Stalin también se había propuesto convertir a las pocas figuras del pasado que aún lo acompañaban no ya en sumisos comparsas de sus mentiras, sino en cómplices directos de su furia criminal: quien no fuese víctima, sería cómplice y, más aún, sería verdugo.
> 
> **Segunda parte** (Location 4470)

---

> Desde que Yezhov había sustituido a Yagoda, la ola de terror desatada diez años antes con la colectivización forzosa de la tierra y la lucha contra los campesinos dueños de tierras había alcanzado unos niveles de insania que parecían dispuestos a devorar un país postrado por el miedo y la práctica de la delación.
> 
> **Segunda parte** (Location 5325)

---

> —Iván, el problema es que te has pasado la vida lanzando las culpas hacia los blancos más fáciles. Y casi siempre te escoges a ti mismo, porque es más sencillo y porque así puedes rebelarte, aunque lo que estás haciendo es autoflagelarte. Saca la cuenta y vas a ver: dejaste de escribir, te volviste alcohólico, te hundiste en esa revista de mierda y ni siquiera intentaste probar en un trabajo que te merezca. Cuando te conocí eras un tipo ambicioso, la gente hablaba de ti como de una promesa, pusieron tus cuentos en todas las antologías de jóvenes escritores que se publicaron…
> 
> **Segunda parte** (Location 5511)

---

> Pero cuando leí la carta de Jaime López no podía sospechar que tendrían que pasar otros diez años —casi dieciséis desde mi último encuentro con él— para que yo diera con las claves que al fin me permitieron encajar en su sitio revelador todas las piezas de aquel rompecabezas hecho con fichas de sordidez y toneladas de manipulación y ocultamiento: los componentes que conformaron el tiempo y moldearon la obra de Ramón Mercader.
> 
> **Segunda parte** (Location 5613)

---

> En esos años se atravesó el puente que iba del entusiasmo de lo mejorable a la decepción de comprobar que el gran sueño estaba enfermo de muerte y que en su nombre se habían cometido hasta genocidios como el de la Camboya de Pol Pot. Por eso, al final, lo que parecía indestructible terminó deshecho, y lo que considerábamos increíble o falso resultó ser la punta de un iceberg que ocultaba en las profundidades las más macabras verdades de lo que había ocurrido en el mundo por el que había luchado Ramón Mercader.
> 
> **Segunda parte** (Location 5621)

---

> Aquéllos fueron los tiempos en los que se concretó el gran desencanto.
> 
> **Segunda parte** (Location 5626)

---

> Por eso estamos trabajando con el personal mexicano, para que parezca una cosa de política y rencillas locales. Los mexicanos no tendrán información ninguna de la conexión de Griguliévich conmigo y menos de la mía con Moscú.
> 
> **Segunda parte** (Location 5745)

---

> A Liev Davídovich le parecía evidente que en los procesos Stalin exigía, más que una verdad, la destrucción humana y política a los acusados.
> 
> **Segunda parte** (Location 6082)

---

> Liev Davídovich podía imaginar la satisfacción de Stalin al recibir mensajes como aquél, que lo convertían en uno de los pocos verdugos en la historia que recibían la veneración de sus víctimas mientras las empujaba hacia la muerte…
> 
> **Segunda parte** (Location 6088)

---

> El otro gran propósito era hacer extensivo y omnipresente el miedo, sobre todo el miedo de los que tenían algo que perder. Por eso los primeros destinatarios de aquellas purgas habían sido, en realidad, los burócratas:
> 
> **Segunda parte** (Location 6097)

---

> El terror había generado el efecto de estimular la envidia y la venganza, había creado una atmósfera de histeria colectiva y, peor aún, de indiferencia ante el destino de los demás. La depuración se alimentaba de sí misma y, una vez desatada, liberaba fuerzas infernales que la obligaban a seguir hacia delante y a crecer…
> 
> **Segunda parte** (Location 6106)

---

> Guiados por Diego, los Bretón y los Trotski pasearon por las ruinas precolombinas, visitaron museos y a los artistas locales que aceptaron la presencia del exiliado. El sumo pontífice del surrealismo se confesó atónito ante los abigarrados mercados, los cementerios y las manifestaciones de religiosidad popular, en los que solía encontrar un «surrealismo en estado puro», más revelador que el choque del paraguas y la máquina de coser en la mesa de disecciones, y por eso consideró a México «la tierra electa del surrealismo».
> 
> **Segunda parte** (Location 6136)

---

> Por aceptar condiciones políticas que él mismo había defendido (a esas alturas mucho lamentaba haberlo hecho), en el presente no se podían leer sin repugnancia y horror los poemas y novelas soviéticas, ni ver las pinturas de los obedientes: el arte en la URSS se había convertido en una pantomima en la que funcionarios armados de pluma o pincel, y vigilados por funcionarios armados de pistolas, solo tenían la posibilidad de glorificar a los grandes jefes geniales.
> 
> **Segunda parte** (Location 6163)

---

> El poeta le dijo que lo entendía y le aclaró que él también amaba a los perros, pero el sentimiento partía de él, el humano. El perro, si acaso, expresaba de manera primaria que sabía distinguir los efectos de su relación con los hombres: miedo al humano que puede provocarle dolor, por ejemplo.
> 
> **Segunda parte** (Location 6181)

---

> En esa cacería, Stalin había liquidado a más dirigentes del PC alemán de antes de 1933 que el mismo Hitler: de los sesenta y ocho líderes que, luego de obedecer su política y permitir el ascenso del fascismo huyeron a refugiarse en la patria del comunismo, más de cuarenta habían muerto ejecutados o internados en los campos; los polacos liquidados, por su lado, fueron tantos, que se debió desintegrar el partido en ese país.
> 
> **Segunda parte** (Location 6314)

---

> Desde muy joven él había pensado que la peor de las agresiones a la condición humana es la humillación, porque desarma al individuo, agrede lo esencial de su dignidad. Él, que a lo largo de su vida había sufrido todos los insultos y calumnias posibles, nunca se había sentido tan al borde de la humillación como cuando Natalia y Jean van Heijenoort le impidieron, después de su último cumpleaños, abandonar la Casa Azul y gritarle a Rivera la repugnancia que le provocaban su exhibicionismo, sus poses de macho mexicano, su inconsistencia de payaso político.
> 
> **Segunda parte** (Location 6702)

---

> Lo más triste había sido ver cómo un país valiente, que tuvo la Revolución al alcance de sus dedos, había sido sacrificado por los dueños de la Revolución y el socialismo, tal como años atrás hicieran con los comunistas chinos o con los obreros alemanes.
> 
> **Segunda parte** (Location 6781)

---

> como le ocurriera al también deificado Nerón, después de su muerte las estatuas de Stalin serían derribadas y su nombre borrado de todas partes: porque la venganza de la historia suele ser más poderosa que la del más poderoso emperador que jamás hubiese existido.
> 
> **Segunda parte** (Location 6816)

---

> La consumación de un tratado que dejaba a Hitler las manos libres para lanzarse sobre Occidente resultaba incomprensible para las mentes de buena y hasta de mala voluntad que, a pesar del terror y los procesos criminales, habían seguido defendiendo a Stalin como el Gran Conductor de la clase obrera.
> 
> **Segunda parte** (Location 6855)

---

> Liev Davídovich sentía como un peso abrumador la contradicción de no saber hasta qué punto resultaba posible oponerse al estalinismo sin dejar de defender a la URSS. Le atormentaba no poder discernir del todo si la burocracia era ya una nueva clase, incubada por la revolución, o solo la excrecencia que siempre había pensado.
> 
> **Segunda parte** (Location 6879)

---

> ¿era el marxismo apenas una «ideología» más, una forma de falsa conciencia que llevaba a las clases oprimidas y a sus partidos a creer que luchaban por sus propios fines cuando en realidad estaban beneficiando los intereses de una nueva clase gobernante?…
> 
> **Segunda parte** (Location 6886)

---

> Habría que admitir también que la URSS no había sido más que la precursora de un nuevo sistema de explotación y que su estructura política tenía que engendrar, inevitablemente, una nueva dictadura, si acaso adornada con otra retórica…
> 
> **Segunda parte** (Location 6891)

---

> En medio de esas purgas celebraron el Día de los Trabajadores con un desfile demasiado parecido a los que nazis y fascistas organizaban en Berlín y Roma: veinte mil comunistas, iracundos, convocados por el Partido Comunista y la Central de Trabajadores, que en lugar de gritar consignas contra la guerra, habían inscrito en sus banderas ¡Fuera Trotski!, ¡Trotski fascista!, ¡Trotski traidor!, y quizás por un remoto pudor no habían escrito lo que gritaron con más ardor: ¡Muerte a Trotski!…
> 
> **Segunda parte** (Location 6972)

---

> Creo que yo había tenido la mayor sospecha de que Jaime López no era Jaime López en el instante en que éste me confirmó que Ramón siempre había oído el grito de Trotski: el tono de su voz y la humedad de su mirada me advirtieron que hablaba de algo demasiado íntimo y doloroso.
> 
> **Segunda parte** (Location 7012)

---

> el asedio al que me había sometido en vida —y hasta después de su muerte— el hombre que amaba a los perros, solo podía tener una razón calculada por una mente de ajedrecista: empujarme silenciosa pero inexorablemente a que yo escribiera el relato que él me había contado, mientras me hacía prometerle lo contrario.
> 
> **Segunda parte** (Location 7042)

---

> ¿cómo que deje de pensar como un escritor? ¿Cómo es que en todo este tiempo no te atreviste a escribir nada? ¿No se te ocurrió pensar que a los veintiocho años Dios te había puesto en las manos la historia que se podía convertir en tu novela, la grande?…
> 
> **Segunda parte** (Location 7054)

---

> ¿O es que tú no sabes en qué país vivíamos en ese momento? ¿Tienes idea de cuántos escritores dejaron de escribir y se convirtieron en nada, o, peor todavía, en antiescritores, y nunca más pudieron levantar el vuelo? ¿Quién podía apostar por que las cosas cambiarían alguna vez? ¿Sabes lo que es sentir que estás marginado, prohibido, sepultado en vida a los treinta, treinta y cinco años, cuando de verdad puedes empezar a ser un escritor en serio, y creyendo que esa marginación es para siempre, hasta el fin de los tiempos, o por lo menos hasta el fin de tu puta vida?
> 
> **Segunda parte** (Location 7059)

---

> ¿Sabes lo que es convertirte en nada? Porque yo sí lo sé, porque yo mismo me convertí en nada… Y también sé lo que es sentir miedo.
> 
> **Segunda parte** (Location 7066)

---

> Y le hablé de los que, como yo, inocentes y crédulos, nos ganamos un «correctivo» por sacar apenas la punta de un pie, y de los que, tras una estancia en el infierno de la nada, trataron de regresar y lo hicieron con libros lamentables, también vacíos y complacientes, con los que lograban un perdón siempre condicional y la sensación mutilada de que otra vez eran escritores porque volvían a ver sus nombres impresos.
> 
> **Segunda parte** (Location 7070)

---

> la verdadera grandeza humana está en la práctica de la bondad sin condiciones, en la capacidad de dar a los que nada tienen, pero no lo que nos sobra, sino una parte de lo poco que tenemos.
> 
> **Segunda parte** (Location 7123)

---

> El sueño estrictamente teórico y tan atractivo de la igualdad posible se había trocado en la mayor pesadilla autoritaria de la historia, cuando se aplicó a la realidad, entendida, con razón (más en este caso), como el único criterio de la verdad. Marx dixit.
> 
> **Segunda parte** (Location 7242)

---

> Mi odio nunca me permitirá trabajar para construir la nueva sociedad. Pero es la mejor arma para destruir esta otra sociedad, y por eso os he convertido a todos vosotros, mis hijos, en lo que sois: los hijos del odio.
> 
> **Segunda parte** (Location 7707)

---

> Liev Davídovich leería con asombro que las primeras sospechas manejadas por la prensa recaían sobre Diego Rivera como posible conductor del ataque.
> 
> **Segunda parte** (Location 7775)

---

> unos seguidores norteamericanos le propusieron a Liev Davídovich que viajase clandestinamente a Estados Unidos, donde se encargarían de esconderlo. Sin pensarlo apenas, él se negó: sus tiempos de luchador clandestino habían pasado hacía muchos años y ahora no tenía derecho a desaparecer para salvar su vida, y menos en un momento en que se decidía el futuro de la civilización humana:
> 
> **Segunda parte** (Location 7843)

---

> Porque la lucha mayor, la de la historia, no terminaría con su muerte y con la victoria personal de Stalin: comenzará dentro de unos años, cuando las estatuas del Gran Líder sean derribadas de sus pedestales, escribió.
> 
> **Segunda parte** (Location 7948)

---

> En ese instante se convenció de que la historia de las humillaciones de Caridad, mencionadas de pasada por Tom, en realidad formaban parte de una estrategia urdida por su madre y por el agente para apuntalar su odio: solo así se explicaba que Tom hubiese tenido noticias de la conversación en el Gillow.
> 
> **Segunda parte** (Location 8184)

---

> su mentor había diseñado aquel montaje con tal maestría que, en el desenlace, el propio condenado se encargaría de fijar la fecha de su muerte y, para alcanzar la máxima perfección, también la de su victimario.
> 
> **Segunda parte** (Location 8323)

---

> la historia y la vida se ensañaron alevosamente con nosotros, con mi generación, y, sobre todo, con nuestros sueños y voluntades individuales, sometidas por los arreos de las decisiones inapelables. Las promesas que nos habían alimentado en nuestra juventud y nos llenaron de fe, romanticismo participativo y espíritu de sacrificio, se hicieron agua y sal mientras nos asediaban la pobreza, el cansancio, la confusión, las decepciones, los fracasos, las fugas y los desgarramientos.
> 
> **Segunda parte** (Location 8640)

---

> era evidente que estábamos hundidos en el fondo de una atrofiada escala social donde inteligencia, decencia, conocimiento y capacidad de trabajo cedían el paso ante la habilidad, la cercanía al dólar, la ubicación política, el ser hijo, sobrino o primo de Alguien, el arte de resolver, inventar, medrar, escapar, fingir, robar todo lo que fuese robable. Y del cinismo, el cabrón cinismo.
> 
> **Segunda parte** (Location 8676)

---

> éramos la generación de los crédulos, la de los que románticamente aceptamos y justificamos todo con la vista puesta en el futuro,
> 
> **Segunda parte** (Location 8680)

---

> Habíamos crecido viendo (así éramos de miopes) en cada soviético, búlgaro o checoslovaco un amigo sincero, como decía Martí, un hermano proletario, y habíamos vivido bajo el lema, tantas veces repetido en matutinos escolares, de que el futuro de la humanidad pertenecía por completo al socialismo
> 
> **Segunda parte** (Location 8686)

---

> Atravesamos la vida ajenos, del modo más hermético, al conocimiento de las traiciones que, como la de la España republicana o la de la Polonia invadida, se habían cometido en nombre de aquel mismo socialismo. Nada habíamos sabido de las represiones y genocidios de pueblos, etnias, partidos políticos enteros, de las persecuciones mortales de inconformes y religiosos, de la furia homicida de los campos de trabajo, del asesinato de la legalidad y la credulidad antes, durante y después de los procesos de Moscú.
> 
> **Segunda parte** (Location 8690)

---

> Ahora, a duras penas, conseguíamos entender cómo y por qué toda aquella perfección se había desmerengado cuando se movieron solo dos de los ladrillos de la fortaleza: un mínimo acceso a la información y una leve pero decisiva pérdida del miedo (siempre el dichoso miedo, siempre, siempre, siempre) con el que se había condensado aquella estructura.
> 
> **Segunda parte** (Location 8699)

---

> su víctima, ya herida de muerte, le había salvado la vida al exigirles a los guardaespaldas que dejaran de golpearlo, pues era preciso obligarlo a hablar.
> 
> **Tercera parte** (Location 8949)

---

> entre los impíos de siempre, no saber es el mejor modo de estar protegido.
> 
> **Tercera parte** (Location 9021)

---

> En esa época entendí que la crueldad de Stalin no solo obedecía a la necesidad política o al deseo de poder: también se debía a su odio a los hombres, peor todavía, a su odio a la memoria de los hombres que lo habían ayudado a crear sus mentiras, a putear y reescribir la historia.
> 
> **Tercera parte** (Location 9160)

---

> Y me dije que iba a aguantarlo todo: y aguanté, sin hablar. ¿Sabes cómo? Pues dejándome morir poco a poco, convirtiéndome en un esqueleto que se les podía desarmar en las manos. Era la única manera de evitar que me torturaran…
> 
> **Tercera parte** (Location 9179)

---

> Ése fue mi penúltimo acto de fe. Estaba convencido de que, sin Stalin y su odio, el Partido haría justicia y la lucha recobraría su sentido… Nada, me equivoqué otra vez.
> 
> **Tercera parte** (Location 9204)

---

> El plan era que tú mataras a Trotski y que los guardaespaldas te mataran a ti, como debió haber ocurrido. Así todo iba a ser más fácil. Así lo había pedido Stalin. Él no quería que quedara ningún cabo suelto y tu vida le importaba un carajo. Pero Trotski te salvó…
> 
> **Tercera parte** (Location 9384)

---

> —Y tú, ¿por qué luchaste? —Al principio porque tenía fe, quería cambiar el mundo, y porque necesitaba el par de botas que les daban a los agentes de la Cheka. Después… ya hablamos del miedo, ¿no?: una vez que entras en el sistema, nunca puedes salir. Y seguí luchando porque me volví un cínico, yo también.
> 
> **Tercera parte** (Location 9421)

---

> El día en que mataste a Trotski sabías por qué lo hacías, sabías que eras parte de una mentira, que luchabas por un sistema que dependía del miedo y de la muerte. ¡A mí no puedes engañarme!… Por eso entraste en aquella casa con las piernas temblándote, pero dispuesto a hacerlo, porque sabías bien que no había retroceso posible.
> 
> **Tercera parte** (Location 9425)

---

> él se había envuelto en la fe, en la convicción de que luchaba por un mundo mejor, para tapar con aquellos mantos las verdades en las que no quería pensar: los asesinatos, entre otros, de Nin y de Robles, las manipulaciones del Partido antes y durante la guerra civil, las turbias historias en torno a Liev Sedov, Sheldon Harte o Rudolf Klement, la extraña confesión de Yagoda que él mismo había presenciado, la manipulación de los sucesos de mayo de 1937 en Barcelona, el vagabundo al que había tenido que matar como a un cerdo en Malájovka, las mentiras sobre Trotski y su colaboración con los fascistas, la malévola utilización de Sylvia Ageloff… Una sola de esas verdades habría bastado para que se reconociera no solo como un ser despiadado, sino también como el cínico en que se había convertido.
> 
> **Tercera parte** (Location 9432)

---

> —Con las estatuas y bustos de Stalin ya tuvieron bastante trabajo. Eran millones en todo el país. En Georgia, donde Stalin fue más sanguinario, pues era donde mejor lo conocían, hubo motines cuando trataron de retirar las más grandes. La gente ya estaba tan acostumbrada a vivir bajo Stalin, a jugar con sus reglas, que tuvieron miedo: ¡alguien podía pensar que ellos aprobaban el derribo de las estatuas! ¿Te das cuenta de lo que puede provocar el miedo cuando se convierte en forma de vida?
> 
> **Tercera parte** (Location 9576)

---

> Aquellas huellas en su piel, un grito en sus oídos y la sombra de Caridad eran como cadenas que lo ataban a su pasado, y las tres podían ser terriblemente pesadas si pretendía moverlas juntas. La cicatriz y el grito eran indelebles, pero al menos a su madre podía mantenerla lejos.
> 
> **Tercera parte** (Location 9894)

---

> otra vez aquel espectro que alguna vez se había llamado Ramón Mercader del Río imaginó cómo habría sido su vida si aquella madrugada remota, en una ladera de la Sierra de Guadarrama, hubiese dicho que no.
> 
> **Tercera parte** (Location 9945)

---

> Ramón había abierto todas las ventanas de su espíritu hacia las mentalidades colectivas, hacia la lucha por un mundo de justicia e igualdad, y si hubiera muerto peleando por ese mundo mejor, se habría ganado un espacio eterno en el paraíso de los héroes puros. Ramón pensó en ese instante cuánto le habría gustado ver llegar a su lado a ese otro Ramón, el verdadero, el héroe, el puro, y poder contarle la historia del hombre que él mismo había sido durante todos esos años en que había vivido la más larga y sórdida de las pesadillas.
> 
> **Tercera parte** (Location 9948)

---

> Cuando leí esos papeles y tuve una idea cabal de lo que había hecho Ramón Mercader, sentí asco. Pero también sentí compasión por él, por el modo en que lo habían usado, por la vergüenza que le provocaba ser él mismo.
> 
> **Tercera parte** (Location 10076)

---

> A lo mejor es verdad que su misma gente le metió radiactividad en la sangre para matarlo, como dice Eitingon, pero no hacía falta, porque ya lo habían matado muchas veces. Se lo habían quitado todo, su nombre, su pasado, su voluntad, su dignidad. ¿Y al final para qué? Desde que le dijo que sí a Caridad, Ramón vivió en una cárcel que lo persiguió hasta el mismo día de su muerte.
> 
> **Tercera parte** (Location 10078)

---

> a él le tocara recibir cada uno de los golpes que le han correspondido a una generación de crédulos por obligación.
> 
> **Tercera parte** (Location 10088)