---
title: "El Proceso"
author: Franz Kafka
date: 2026-02-28
Rating: 10 / 10
---

### Highlights
> «Ya ves, Willem, admite que no conoce la Ley, y al mismo tiempo afirma que es inocente».
> 
> **El proceso** (Location 194)

---

> La presencia de esos empleados tenía naturalmente otro objetivo más: ellos debían, lo mismo que mi patrona y su criado, difundir la noticia de mi detención, perjudicar mi reputación y, especialmente, debilitar mi posición en el banco.
> 
> **El proceso** (Location 680)

---

> «esos libros son sin duda libros de leyes, y es propio de esta clase de justicia sufrir condena no solo siendo inocente, sino permaneciendo además ignorante.»
> 
> **El proceso** (Location 751)

---

> también mi marido ha tenido que conformarse; si quiere conservar su puesto, tiene que tolerarlo, porque ese hombre es estudiante y probablemente llegará a tener mucho poder.
> 
> **El proceso** (Location 761)

---

> solo había sufrido la derrota porque había buscado la lucha.
> 
> **El proceso** (Location 867)

---

> “Tener un proceso significa haberlo perdido ya”.»
> 
> **El proceso** (Location 1240)

---

> Verdadero valor tienen solo unas honradas relaciones personales, concretamente con funcionarios superiores, con lo cual, naturalmente, se quiere decir solo funcionarios superiores de la categoría más baja. Solo de esa forma se puede influir en el curso del proceso: aunque al principio de forma únicamente imperceptible, luego de un modo cada vez más claro.
> 
> **El proceso** (Location 1505)

---

> Eso es sin duda lo peor que puede ocurrirle a un abogado. No es que el proceso se lo quite el acusado, eso no ocurre nunca, desde luego; un acusado que ha tomado a un abogado determinado tiene que quedarse con él, ocurra lo que ocurra. ¡Cómo podría seguir adelante solo, una vez que ha recabado ayuda! Por lo tanto, eso no ocurre, pero sí ocurre a veces que el proceso toma una dirección en la que el abogado no puede continuarlo. Se despoja sencillamente al abogado del proceso, del acusado y de todo; entonces, ni las mejores relaciones con los funcionarios sirven ya, porque ellos mismos no saben nada. El proceso ha entrado en una fase en la que no se puede ya prestar ayuda, en que trabajan en él tribunales inaccesibles, en que el acusado no es ya accesible para el abogado.
> 
> **El proceso** (Location 1576)

---

> Siempre había progresos, pero nunca se podía comunicar la naturaleza de esos progresos. Siempre estaba trabajando en la primera solicitud, pero nunca la terminaba,
> 
> **El proceso** (Location 1595)

---

> «Es la Justicia», dijo el pintor por fin. «Ahora la reconozco», dijo K., «aquí está la venda en los ojos y aquí la balanza. Pero ¿no tiene alas en los talones y no está corriendo?» «Sí», dijo el pintor, «tengo que pintarla así por encargo; en realidad es la Justicia y la diosa de la Victoria al mismo tiempo.» «No es una buena combinación», dijo K. sonriendo, «la Justicia tiene que reposar; si no, se moverá la balanza y será imposible una sentencia justa.» «Tengo que someterme a quien me ha hecho el encargo», dijo el pintor.
> 
> **El proceso** (Location 1894)

---

> en torno a la figura de la Justicia siguió reinando la claridad, salvo un matiz imperceptible; en medio de aquella claridad, la figura parecía destacarse especialmente, apenas recordaba ya a la diosa de la Justicia, pero tampoco a la de la Victoria; ahora parecía totalmente la diosa de la caza.
> 
> **El proceso** (Location 1908)

---

> «Usted mismo me ha dicho hace un momento que el tribunal es totalmente impermeable a las pruebas.» «Impermeable solo a las pruebas que se presentan al tribunal»,
> 
> **El proceso** (Location 1962)

---

> Todo juez quiere ser pintado como fueron pintados los antiguos y grandes jueces, y eso solo puedo hacerlo yo.» «Eso es envidiable», dijo K., pensando en su puesto en el banco. «¿ Entonces su puesto es inamovible?» «Sí, inamovible», dijo el pintor, encogiéndose orgulloso de hombros. «Por eso puedo atreverme de cuando en cuando a ayudar a algún pobre hombre que tiene un proceso.»
> 
> **El proceso** (Location 1977)

---

> «Me he olvidado de preguntarle ante todo qué clase de liberación quiere. Hay tres posibilidades, a saber, la absolución auténtica, la absolución aparente y el aplazamiento indefinido.
> 
> **El proceso** (Location 1986)

---

> «He hablado de dos cosas distintas: de lo que dice la Ley y de lo que he sabido por mi experiencia personal, no debe usted confundirlas.
> 
> **El proceso** (Location 1997)

---

> «Vamos a prescindir pues de la absolución auténtica; sin embargo, usted mencionó otras dos posibilidades». «La absolución aparente y el aplazamiento indefinido. Solo puede tratarse de ellas», dijo el pintor.
> 
> **El proceso** (Location 2014)

---

> la absolución aparente requiere un esfuerzo concentrado, aunque temporal, y el aplazamiento indefinido un esfuerzo mucho menor, pero continuo.
> 
> **El proceso** (Location 2039)

---

> «Entonces ¿seré libre?», dijo K. dudando. «Sí», dijo el pintor, «pero solo aparentemente libre o, más exactamente, provisionalmente libre. Porque los jueces subalternos, entre los que se encuentran los que yo conozco, no pueden absolver definitivamente; ese derecho solo lo tiene el tribunal superior, totalmente inalcanzable para usted, para mí y para todos.
> 
> **El proceso** (Location 2055)

---

> «Pero esa segunda absolución tampoco es definitiva», dijo K., y torció la cabeza con desaprobación. «Naturalmente que no», dijo el pintor, «a la segunda absolución sigue la tercera detención, a la tercera absolución, la cuarta detención y así sucesivamente. Eso está implícito en el concepto de absolución aparente.»
> 
> **El proceso** (Location 2080)

---

> «el aplazamiento indefinido consiste en mantener continuamente el proceso en sus fases procesales inferiores. Para conseguirlo es necesario que el acusado y la persona que lo ayuda, especialmente esta, estén en constante contacto personal con el juez.
> 
> **El proceso** (Location 2085)

---

> «Los dos métodos tienen en común que impiden la condena del acusado». «Pero impiden también la absolución auténtica», dijo K. en voz baja, como si se avergonzara de haberse dado cuenta. «Ha comprendido el meollo del asunto»,
> 
> **El proceso** (Location 2107)

---

> Si uno quiere hacer algo por su proceso, no se puede ocupar mucho del resto.»
> 
> **El proceso** (Location 2255)

---

> Una de esas supersticiones consiste, por ejemplo, en que muchos pretenden saber por el rostro del acusado, especialmente por el dibujo de sus labios, el resultado del proceso.
> 
> **El proceso** (Location 2268)

---

> «Esperar no es inútil», dijo el comerciante, «solo es inútil intervenir independientemente.
> 
> **El proceso** (Location 2282)

---

> «Tengo la sospecha de que no solo su juicio equivocado sobre mi asistencia jurídica, sino también el resto de su comportamiento se debe a que, a pesar de ser acusado, lo han tratado demasiado bien
> 
> **El proceso** (Location 2466)

---

> No era ya un cliente, sino el perro del abogado.
> 
> **El proceso** (Location 2534)

---

> «La sentencia no se dicta de repente: el proceso se convierte poco a poco en sentencia.»
> 
> **El proceso** (Location 2761)

---

> El guardián solo comunicó el mensaje salvador cuando ya no podía ayudar al hombre.»
> 
> **El proceso** (Location 2815)

---

> «Una triste opinión», dijo K., «la mentira se convierte en principio universal.»
> 
> **El proceso** (Location 2888)

---

> K. sabía ahora muy bien que su deber hubiera sido coger el cuchillo que pasaba de mano en mano por encima de él y clavárselo él mismo.
> 
> **El proceso** (Location 2971)