---
title: "Europe Central"
author: William T. Vollmann
date: 2026-04-10
Rating: 10 / 10
---

### Highlights

> At such moments, when we find ourselves in danger of losing the protagonist we love, the tale of our marriage begins to glow, and the letters tremble on the page as once did our own souls when we realized the inevitability of the first kiss.
> 
> **PINCER MOVEMENTS** (Location 363)

---

> In the ever timely words of Comrade N. V. Krylenko (whose own destiny would be death by shooting): We must execute not only the guilty. Execution of the innocent will impress the masses even more.
> 
> **PINCER MOVEMENTS** (Location 398)

---

> But those pseudo-democratic phrases of yours are printed in the constitutions of capitalist republics all over the world! Don’t you see that they mean nothing? How can you support universal suffrage when the richest people control the vote? Freedom of the press— who owns that press? A people’s government— of which people? You’ve let yourself become a pawn of the White Guard clique—
> 
> **PINCER MOVEMENTS** (Location 499)

---

> Her future was suicide. Beside her bleeding corpse she left a note denouncing her husband’s crimes.
> 
> **PINCER MOVEMENTS** (Location 516)

---

> And in the present case, her compulsive attachment to a traitor she’d never met constituted no less than an assault upon the Party. She’d embarrassed Lenin. Here was a chance to do Lenin a favor, but also to put that fat old hag in her place. Moreover, he now had perfect means to blackmail Lenin should he ever need to.
> 
> **PINCER MOVEMENTS** (Location 522)

---

> this sensation, suitably translated into the chord D-D-Sch, later found its way into both his Fifteenth Symphony and the unholy Opus 110.
> 
> **PINCER MOVEMENTS** (Location 900)

---

> Karl stood self-deprecatingly out of the picture except when they called him. About him his poor patients remembered: The doctor came immediately, and his invoice never.
> 
> **PINCER MOVEMENTS** (Location 1025)

---

> To this provocation, Comrade Stalin has an answer: Shoot Tukhachevsky. Tukhachevsky should have spent more time reading the newspapers. Then he would have known that tanks will never be any threat.
> 
> **PINCER MOVEMENTS** (Location 1332)

---

> Elena might not have looked much like that to anyone but Shostakovich, and even to him only on certain days, when the music she inspired achieved its extreme limit of formalism.
> 
> **PINCER MOVEMENTS** (Location 1359)

---

> When we sent her north in ’35, it was simply to put pressure on Shostakovich, to remind him.
> 
> **PINCER MOVEMENTS** (Location 1389)

---

> But with Lina, because she was now more adult and more experienced, she did it in much the way that von Karajan conducts Shostakovich’s Tenth Symphony: more smooth, rounded, polished, elegant (one hears this especially in the brasses), less harsh and desperate than as André Previn does it.
> 
> **PINCER MOVEMENTS** (Location 1417)

---

> Uncanny how different the same notes can sound!
> 
> **PINCER MOVEMENTS** (Location 1421)

---

> But the strangest thing of all about her was that she knew how to disguise herself in plainness (I suppose so that she wouldn’t get hurt). Once she’d put on her round glasses and tied her hair into a bun, hardly anybody looked at her when she walked down the street.
> 
> **PINCER MOVEMENTS** (Location 1428)

---

> She loved women, and he loved her for it.
> 
> **PINCER MOVEMENTS** (Location 1436)

---

> Each of Shostakovich’s symphonies I consider to be a multiply broken bridge, an archipelago of steel trailing off into the river.
> 
> **PINCER MOVEMENTS** (Location 1655)

---

> no one who has read the entire case file can deny that Elena Konstantinovskaya’s clitoris was electric and that its sweet vibrations sing forever in the cello melody which opens the first movement.
> 
> **PINCER MOVEMENTS** (Location 1672)

---

> Leitmotiv, which we most often find applied specifically to Wagner, is a very short passage relating to a character, object or event: for instance, the Magic Fire music. Leave that to the Fascists, I say! Theme, at least in Shostakovich, gets worked out, developed, is longer.
> 
> **PINCER MOVEMENTS** (Location 1835)

---

> He’d finished, and Elena was back on top of him again, riding him in just the way she liked until she climaxed with the sound of a honeybee, the bow passing smoothly and shrilly across the sounding board. Returning to the Russian melody, Opus 40 then gives the piano another turn at pleasuring itself, so that a second rocking-horse copulation gallops to a happy ejaculation, at which point the piano sparkles and glows;
> 
> **PINCER MOVEMENTS** (Location 1892)

---

> The Poles say that life itself is a long smelly train of refugees which travels Europe’s slowest tracks, getting shunted aside to make room for military transports and industrial freight; there everyone sits, sweltering, stinking, fearing and grieving. The whistle shouts; time to move again! Here comes the next border, where policemen and plainclothesmen will winnow more of us away (her visa is incorrect; he’s actually an escaped Jew). The most laughable thing is that we hated life; we wanted to “get somewhere”; and now that they’re taking us somewhere by the truckload, we wish that we were still on that long train where everything stank! Well, that’s life, all right.
> 
> **PINCER MOVEMENTS** (Location 1919)

---

> The aerial bombardment of Guernica turned out to be a contrapuntal masterpiece, and our new machine-guns didn’t jam, either.
> 
> **PINCER MOVEMENTS** (Location 1936)

---

> Do you remember when Hitler staged that exhibition of degenerate art? Don’t get me wrong; every time I see a German I want to string him up by the balls; nonetheless, I’m man enough to say this straight: Hitler wasn’t incorrect in that instance.
> 
> **PINCER MOVEMENTS** (Location 2076)

---

> He was engaged in what it’s now fashionable to call inner emigration. At my office we don’t much care for that term, and I’ll tell you why: Hindemith, von Karajan and Furtwängler make music for the Hitlerites, and then, when it’s all over, they have the effrontery to plead: Word of honor, I wasn’t really here! I couldn’t possibly have collaborated, since I was living in my head the entire time!—
> 
> **PINCER MOVEMENTS** (Location 2093)

---

> When she was still young and beautiful enough to write that the past’s power can fail, she mourned unkissed lips. When our Revolution proved that the past can in fact be broken, what then? Unkissed lips returned to hang eternally over her in the yellow fog over Leningrad.
> 
> **PINCER MOVEMENTS** (Location 2134)

---

> By then she’d begun to learn that even greater than the power of the absent lover is our power, Soviet power! We were going to plait her braids more tightly for her . . .
> 
> **PINCER MOVEMENTS** (Location 2145)

---

> In our Soviet Russia of today, when art is supposed to be positive and life-affirming, there is simply no place for this kind of person.
> 
> **PINCER MOVEMENTS** (Location 2176)

---

> The way we educate these people is first to shoot someone they love, so that they realize that this can and will happen to them; next, we take away someone they love more than themselves. When we did this to Shostakovich, the results were excellent.
> 
> **PINCER MOVEMENTS** (Location 2193)

---

> In 1938 we arrested her son again and condemned him to death by shooting, but we were still just playing; we were curious to see if that would bring her around.
> 
> **PINCER MOVEMENTS** (Location 2212)

---

> after all, Akhmatova was the poet of “Requiem,” which even our yes-man Shostakovich admired and which I’m sorry to say I’ve heard on the lips of students, prisoners, prostitutes, peasants and kerchiefed factory women. Needless to say, it gets no mention in the Great Soviet Encyclopedia.
> 
> **PINCER MOVEMENTS** (Location 2223)

---

> And that night when I went home, I don’t mind confessing that my head was filled with all kinds of ridiculous word-rubbish, such as the moon and six candles, and a kiss upon her eyelashes. What was I to do? Finally I picked up The Foundations of Leninism and read two pages at random. That cured me.
> 
> **PINCER MOVEMENTS** (Location 2326)

---

> To his vassals and henchmen in Munich he chants: I go the way that Providence dictates, with the assurance of a sleepwalker.—
> 
> **PINCER MOVEMENTS** (Location 2446)

---

> Göring continues: The Czechs, a vile race of dwarfs without any culture— nobody even knows where they came from— are oppressing a civilized race; and behind them, together with Moscow, there can be seen the everlasting face of the Jewish fiend!
> 
> **PINCER MOVEMENTS** (Location 2459)

---

> Italy falls, but the sleepwalker knows how to save her from the Jews. Parachutes as beautiful as white flowers bloom upon the skies which he’s now capturing. Black columns of smoke have translated the beaches of Normandy into the stage darkness after an intermission. In the next act he must sing of retreating German troops, of dead horses and throttled light.
> 
> **PINCER MOVEMENTS** (Location 2638)

---

> But where are his muscled heroes with their swords? Are they all dead? Snowy Russian tanks breast bluish flames and bluish snow to conquer Auschwitz, where more than seven tons of human hair await transshipment. A parade of skinny, desiccated corpses comes forth to tell lies and inspire new Jewish conspiracies.
> 
> **PINCER MOVEMENTS** (Location 2661)

---

> The explosion of rapture at his First Symphony so long ago should have warned him, for in our Soviet Union as in any besieged zone it’s unwise to stand out despicably or dashingly.
> 
> **PINCER MOVEMENTS** (Location 2718)

---

> When his teachers cited the program music of Mussorgsky, Wagner, Berlioz and Rimsky-Korsakoff, our tousleheaded young genius argued that these compositions could be peeled away from their supposed subjects without detriment; if they couldn’t, they failed as music.
> 
> **PINCER MOVEMENTS** (Location 2742)

---

> he dwelled, like all children, at the heart of the world. I prefer not to brand him a narcissist, but people do take on the characteristics of the places where they live, and Petersburg is as labyrinthine, enigmatic and literally self-centered
> 
> **PINCER MOVEMENTS** (Location 2753)

---

> Petersburg infects her most sensitive children with a desperation as noble as it is impractical.
> 
> **PINCER MOVEMENTS** (Location 2757)

---

> For Petersburg remains above all the city of Raskolnikov, who exists only in Dostoyevsky’s nightmares but whose crime, murder for the sake of an idea, proves its reality again and again.
> 
> **PINCER MOVEMENTS** (Location 2759)

---

> He was a year old when Bloody Sunday destroyed the Russian people’s faith in their Tsar.
> 
> **PINCER MOVEMENTS** (Location 2766)

---

> A month after his eleventh birthday, revolution struck. The minds of the losers learned to duck down behind frozen eyes.
> 
> **PINCER MOVEMENTS** (Location 2779)

---

> His mother tried to fight them when they took away his borrowed piano, but he told her not to worry; he could hear each chord in his head as soon as he wrote it on paper. Beethoven hadn’t let deafness stop him, so Mitya himself could still, well, you know.
> 
> **PINCER MOVEMENTS** (Location 2787)

---

> Or, as Mitya would put it, each one composes his own score, and then we all compare versions.
> 
> **PINCER MOVEMENTS** (Location 2792)

---

> It began to be said of him that he was an individualist. His allegiance to collective life was only a pretense. He could not overcome his addiction to the transgressive harmonies of the chromatic scale.
> 
> **PINCER MOVEMENTS** (Location 2807)

---

> Before he was even twenty, his First Symphony premiered with the Leningrad Philharmonic. As might be imagined, a faction opposed the debut. Objections of immaturity and grotesquerie he met with his usual implacable courtesy.—
> 
> **PINCER MOVEMENTS** (Location 2822)

---

> Although it might be irritating to him to do as others told him to do, as long as he could build secret trapdoors and escape hatches into every score, so that the world beneath the piano keys hadn’t been forgotten, he was still living on his own terms.
> 
> **PINCER MOVEMENTS** (Location 2911)

---

> With women he continued to (so Sollertinsky phrased it) play the octave, meaning that he could sound the same note in the hearts of several conquests, just as a pianist simultaneously touches two F-sharps eight notes apart.
> 
> **PINCER MOVEMENTS** (Location 3040)

---

> In 1935, when Comrade Stalin made twelve-year-olds subject to the death penalty, and Akhmatova was writing that without hangman and gallows a poet has no place in this world, his Cello Sonata in D Minor (Opus 40) provoked the authorities’ wrathful puzzlement.
> 
> **PINCER MOVEMENTS** (Location 3053)

---

> About Opus 40 we might note that it was written during the months of his adulterous passion with the translator E. E. Konstantinovskaya, and that its melodies reflect those emotional and sexual vicissitudes. (She slept in his arms. He lay listening to the wind.)
> 
> **PINCER MOVEMENTS** (Location 3060)

---

> At the beginning of 1936 he was called to Moscow to appear at a performance of his opera “The Lady Macbeth of the Mtensk District.” Such a summons could signify nothing less than the presence of Comrade Stalin.
> 
> **PINCER MOVEMENTS** (Location 3076)

---

> “Lady Macbeth” had premiered in Leningrad two years earlier, to more than half an hour of “hysterical applause”; eighty-three performances had sold out.
> 
> **PINCER MOVEMENTS** (Location 3084)

---

> It was, in short, the opera’s ideological content, not the composer’s soul, which required that “melody” be permitted to shine only briefly, and then only in epiphanies of eroticism dragged down immediately afterward by the piglike gruntings of the brasses. (What a cultural soldier our Shostakovich! Throughout his life, his music would remain admirably unrelieved.)
> 
> **PINCER MOVEMENTS** (Location 3127)

---

> Listening carefully to the bitter fartings of the trumpets, the defiant clashings of the brasses in Act I, he knew that he had truly conveyed the benightedness of prerevolutionary, vegetative Russia; and, moreover, that he’d carried the audience with him.
> 
> **PINCER MOVEMENTS** (Location 3143)

---

> Came the seduction, half a rape— cold, angry and brassy, with jeeringly lascivious oohs and ahs from the brasses, until Sergei had finished, and Katerina’s desperate boredom returned with an ugly wilting glissando.
> 
> **PINCER MOVEMENTS** (Location 3154)

---

> At the end of the third act, Stalin, Molotov and the other luminaries arose from the State Box, then withdrew in an ominous silence.
> 
> **PINCER MOVEMENTS** (Location 3165)

---

> He went backstage to thank the musicians— who recoiled as if he were a leper. His mouth twitched crazily. He took up his briefcase in silence. No one saw him out.
> 
> **PINCER MOVEMENTS** (Location 3168)

---

> Two days later, Pravda unmasked the opera’s bourgeois obscurantism.
> 
> **PINCER MOVEMENTS** (Location 3176)

---

> Mitya, listen. I allow you your mistresses and your antisocial games, which might even be crimes. Haven’t I done enough? Do I have to let you commit suicide, too?
> 
> **PINCER MOVEMENTS** (Location 3257)

---

> Shostakovich prevailed upon himself to disturb Marshal Tukhachevsky, with whom he’d been acquainted for more than ten years. Scourge of Poland, butcher of Kronstadt and Tambov (his maxim for eradicating anti-Soviet banditry: One should practice large-scale repression and employ incentives), proponent of mechanization, mobility and operational shock, Tukhachevsky had attended four performances of “Lady Macbeth.”
> 
> **PINCER MOVEMENTS** (Location 3345)

---

> our Red Army’s strategic genius was himself an amateur violinist and violin-maker. Moreover, he and Shostakovich both admired the ballerina Olga Lepeshinskaya’s legs.
> 
> **PINCER MOVEMENTS** (Location 3350)

---

> For Tukhachevsky had promised to write a letter— direct to Comrade Stalin! Tukhachevsky had said: We’ll solve this question correctly.— Tukhachevsky had assured him: Don’t worry, Dmitri Dmitriyevich. I always get whatever I ask for.
> 
> **PINCER MOVEMENTS** (Location 3402)

---

> Thus almost before he knew it he’d completed his Fourth Symphony, the one in C Minor (Opus 43), but the unalloyed congratulations of that capitalist lackey Otto Klemperer, then visiting Moscow and Leningrad on a Beethoven tour, only increased his peril. The next day, Nina gave birth to their first child Galina.
> 
> **PINCER MOVEMENTS** (Location 3407)

---

> What kind of silence could have been silenter than the noiseless fear which oozed out of his orchestra at that moment, the musicians lighting cigarettes alone, shying away from their own instruments as if from something dangerously electrified? When he returned downstairs, sweaty and ashen, he announced that he had made a personal and entirely voluntary decision to withdraw it from the program. It would not be performed until the end of 1961.
> 
> **PINCER MOVEMENTS** (Location 3428)

---

> A Black Maria came for Tukhachevsky. They tortured him and put him on trial. (He is said to have asked one of his desperately self-incriminating co-defendants: Are you dreaming?)
> 
> **PINCER MOVEMENTS** (Location 3454)

---

> Not long after these events, Shostakovich was summoned to the offices of the NKVD to inquire into his connection with the traitor Tukhachevsky.
> 
> **PINCER MOVEMENTS** (Location 3458)

---

> They wanted to know whether it was true that he’d played violin duets together with the enemy of the people Tukhachevsky. He confessed that it was. They inquired into the matter of musical codes. What messages might be transmitted by a violin?
> 
> **PINCER MOVEMENTS** (Location 3473)

---

> They asked him what he knew about Tukhachevsky’s plot to kill Comrade Stalin. He said he didn’t know anything. They said to him: Today is Saturday. We’ll sign your pass and let you go home. But on Monday you’d better be here, and you’d better remember something. This is very serious.
> 
> **PINCER MOVEMENTS** (Location 3479)

---

> All that saved him was the arrest of his interrogator.
> 
> **PINCER MOVEMENTS** (Location 3483)

---

> Subtitled “A Soviet artist’s creative reply to just criticism,” and ending as it did fortissimo in a major key, the Fifth Symphony premiered to stormy ovations in 1937, but Party investigators accused him of planting applauding stooges among the audience. In Leningrad, the third movement’s largo literally excited tears. People rushed to the stage like accolytes. The conductor Mravinsky waved the score in the air. Shostakovich grew pallid and weak as the defiant applause continued. Such expressions were an insult to Comrade Stalin . . .
> 
> **PINCER MOVEMENTS** (Location 3493)

---

> In the autumn of 1938, not long before the first snowfall, he announced that his next symphony would be dedicated to Lenin. Thin, anxious, pale, distinguished by a knife-sharp profile, he promised to include folk songs, too. But at the premiere, not a single reference to Lenin could be found. The critics sneered that the finale of this Sixth so-called Symphony was nothing more than the recapitulation of a football match; he never to the end of his life forgot that humiliation, but at least his life did not feel threatened.
> 
> **PINCER MOVEMENTS** (Location 3516)

---

> Although it was the program music of the Seventh Symphony which would make him famous, the course of the war is better symbolized by the first three movements of his incomparably greater Eighth Symphony in C Minor (an unwholesome work, to be sure, for its pessimism deviates from the Party line).
> 
> **PINCER MOVEMENTS** (Location 3537)

---

> The deep, thrumming resonance of the very first chord evokes a community united only by sleep. Wickedness hovers outside the frosty windows of Leningrad. This wickedness is on the march; and the Eighth Symphony, compressing time like the walls of a condemned cell, hastens its arrival.
> 
> **PINCER MOVEMENTS** (Location 3541)

---

> Every general who dared to warn of militarypreparations on the German side, of tanks and planes massing, got threatened with death.
> 
> **PINCER MOVEMENTS** (Location 3551)

---

> So came the night of 21-22 June 1941, when the stern, dignified melancholy of the Eighth Symphony’s opening rapidly shrills into outright alarm. After a grim stretch of strings, it rises even higher into stridency, this time with a martial component. Drumbeats like distant bursts of machine-guns announce full war, and horns scream like air raid sirens. Barbarossa begins:
> 
> **PINCER MOVEMENTS** (Location 3570)

---

> Throughout his career, ballet and movie scores were his bread and butter. When it came to his own work, he continued to expressly reject any claim to programmatic representation: Red Army men were not brass instruments, he said.— I do not believe him.—
> 
> **PINCER MOVEMENTS** (Location 3585)

---

> The third movement, the allegro non troppo, begins in flight, the score itself, that pale flat sheet of endlessness called the Ukrainian steppes, being half obscured by burning fields and towns whose doom has been translated musically into low strings.
> 
> **PINCER MOVEMENTS** (Location 3589)

---

> Children scream like piccolos.
> 
> **PINCER MOVEMENTS** (Location 3593)

---

> As gong, snare drum and cymbals sound a triumphal fanfare of evil, they crush us under tank treads; they toast themselves by upraising our decapitated heads
> 
> **PINCER MOVEMENTS** (Location 3615)

---

> His Seventh or so-called “Leningrad” Symphony was by some accounts already underway before the invasion. In August 1939, when the faithful demanded to know why in defiance of all his promises that undistinguished Sixth Symphony had failed to memorialize Lenin, Shostakovich twitched, slid his spectacles up his nose, smiled to the utmost of his cunningly hidden spite, and announced poker-faced that the Seventh would be program music of a wisely sycophantic species at last: First movement— Lenin’s youth. Second movement— Lenin leading the October storm . . . These words got eagerly reproduced in Leningradskaya Pravda, Moskovskii Bolshevik and suchlike organs of our trusting Soviet press.
> 
> **PINCER MOVEMENTS** (Location 3632)

---

> Establishing the date of inspiration for the first movement is particularly crucial, since its infamous Rat Theme, the marionette in eleven variations, evokes the madness of German Fascism. What indeed might it represent, had its conception occurred while we were still friends with Hitler the Liberator? (Here’s a hint: In the Rat Theme some critics claim to find a mixture of “Deutschland über Alles” and the “Merry Widow”; but there may also be a trace of Tchaikovsky’s Fifth.
> 
> **PINCER MOVEMENTS** (Location 3656)

---

> They lit their cigarettes and sat there yawning while he played the first five hundred measures of his Seventh Symphony. Interrupting him, they demanded to know: Was there any residual formalism in it?
> 
> **PINCER MOVEMENTS** (Location 3763)

---

> And then that so-called Rat Theme or Fascism Theme or whatever it is, well, frankly, Dmitri Dmitriyevich, there’s been some concern. How long is it? How long? Let’s see, let’s see; I believe it’s two hundred and eighty bars. What does the length have to do with anything? No wonder Konstantinovskaya left him! Shostakovich, have you ever once satisfied a woman? I know why they call you a masturbator! No, that’s all fine, Dmitri Dmitriyevich. That’s irrelevant. Our concern is that it begins too melodiously, which might mislead the masses into believing— That I like rats? Always the joker! That I’m a, a, so to speak, a Hitlerite? Out of your own mouth! You ought to be extremely careful. So if you could . . .
> 
> **PINCER MOVEMENTS** (Location 3784)

---

> We have, moreover, the example of the infamous Twelfth Symphony. According to Lebedinsky, this supposed ode to Lenin was actually an angry satire against the founder of our Soviet Union. Realizing three or four days before the premiere that this music was practically a death sentence for his entire family, he sat down and wrote a complete new score—
> 
> **PINCER MOVEMENTS** (Location 3845)

---

> And the Rat Theme’s second iteration was still more open, sweet and beautiful. But when it came around again, a woodwind lurked dissonantly beneath the high sweetness. The Rat Theme now assumed a brassy life, shrugging off its former tentativeness, with celli, horns, piccolos, clarinets, brasses and xylophone creeping in en route to the ostinato.
> 
> **PINCER MOVEMENTS** (Location 3886)

---

> but in its tenth incarnation it grew creepy and horrid, with the moaning dissonance of air raid sirens and U-boat alarms; and in the eleventh it marched and bayed in a full-throated major key which might have seemed no worse than pompous in another context
> 
> **PINCER MOVEMENTS** (Location 3895)

---

> I suppose that critics with nothing better to do will, so to speak, damn me copying Ravel’s “Bolero.” Well, let them. You see, my dear friend, that’s how I hear war!);
> 
> **PINCER MOVEMENTS** (Location 3897)

---

> I fear that I have not really described this third movement very well. Let me try again. It opens, as I’ve said, with a stately joy equivalent to that of Rimsky-Korsakoff’s “Grand Pacques,” then dims down to a frame of sternness to introduce one of the most purely beautiful themes Shostakovich ever wrote, which will be reiterated with an Asian tinge.
> 
> **PINCER MOVEMENTS** (Location 3993)

---

> When I listen to the later Shostakovich, the real Shostakovich, whose melodies are almost completely lightless, I don’t know what to believe about this Seventh Symphony.
> 
> **PINCER MOVEMENTS** (Location 4005)

---

> October was when the potatoes ran out. It wasn’t until November that people started feeding on a jelly made from leather straps.
> 
> **PINCER MOVEMENTS** (Location 4013)

---

> His mother, his sister and his brother-in-law had to stay behind.— In short, the authorities agreed with his mother, who’d written that if the roof fell in and she had to choose whom to save, the answer would be of course Mitya— for this would be the duty of everyone to society, for the sake of art— disregarding all personal feeling.
> 
> **PINCER MOVEMENTS** (Location 4128)

---

> “Lady Macbeth” was going to win him the permanent patronage of Comrade Stalin. The way it turned out was actually, how should I say, educational.
> 
> **PINCER MOVEMENTS** (Location 4148)

---

> They needed his symphony without delay, just as they needed the new Katyusha rockets.
> 
> **PINCER MOVEMENTS** (Location 4173)

---

> In December it got worse. Some calculated that six thousand perished every day of that month; others said four, or ten. No one had the strength to count. Like ripe pears falling off trees, frozen bodies dropped out of windows into the snowy streets. Cannibals were said to be killing stray children every day; steak-meat was cut from the shoulders, thighs and buttocks of corpses abandoned at the cemetery.
> 
> **PINCER MOVEMENTS** (Location 4211)

---

> The last note of the Seventh Symphony was written on 29 December 1941, in tired, crowded Kuibyshev.
> 
> **PINCER MOVEMENTS** (Location 4237)

---

> Again they urged him to join the Party, because doing so would help the Seventh to be more widely understood.
> 
> **PINCER MOVEMENTS** (Location 4241)

---

> Stalin himself is said to have commented that the Seventh was of as great striking power as a squadron of bombers. Pravda called it the creation of the conscience of the Russian people.
> 
> **PINCER MOVEMENTS** (Location 4265)

---

> Bartók parodied the Seventh with bitter disgust— a compliment of sorts.
> 
> **PINCER MOVEMENTS** (Location 4271)

---

> In the postwar era, other intellectuals who’d never been compelled to pitch their tents in necessity’s winds would soon disdain the Seventh Symphony more loudly, hearing in it a musical battleground occupied by two utterly irreconcilable antagonists: Shostakovich’s desire to express reality, and his need to please his masters. Reader, which would you choose?
> 
> **PINCER MOVEMENTS** (Location 4273)

---

> Comrade Stalin himself has stated that the very concept of nationality is but a smokescreen used by the capitalists to prevent us from seeing class differences. As for the Party’s dictum that art must be national in form, socialist in content, that’s a mere transition scheme to wean the people gently from their hidebound categories.
> 
> **PINCER MOVEMENTS** (Location 4277)

---

> Yet if you sin and then return to God, your status is higher. As the saying goes, “Those who return to God occupy a place where even the completely righteous cannot stand.” And so it came to pass that on 11 April 1942, Shostakovich received the Stalin Prize, First Class.
> 
> **PINCER MOVEMENTS** (Location 4282)

---

> The first movement, which is rather idyllic and slight until the Rat Theme, with here and there a reverie which recalls for me Novgorod’s ancient towers silhouetted against the evening sky, reminded the German Fascists of their own landscapes, since after all it was meant to speak to them,
> 
> **PINCER MOVEMENTS** (Location 4338)

---

> Now that city which Dostoyevsky likens to a consumptive girl blushing into beauty briefly and inexplicably was free again, free to devour herself in secret claustrophobic maelstroms of fear.
> 
> **PINCER MOVEMENTS** (Location 4355)

---

> Now that we didn’t need the Anglo-Americans anymore, it was high time to bring up her past. In August 1946, we expelled her from the Leningrad Union of Writers.
> 
> **PINCER MOVEMENTS** (Location 4372)

---

> It was in his Eighth Symphony that he first began to articulate the various danses macabres which he could no longer prevent himself from hearing. Bones, murdered or merely perished, ought to stay silent. That’s the law. But, quick and shrill as a violin-screech, they come back, to the terror of all who stand guilty of living, and then they dance, playing on their tomb-lids as lightly as cats— but the game’s evil, hateful, angry; there’s no fun in being a skeleton!
> 
> **PINCER MOVEMENTS** (Location 4381)

---

> In time, these hauntings within his ears would evolve into the terrifying Opus 110.
> 
> **PINCER MOVEMENTS** (Location 4386)

---

> Now for his best known accomplishment: When the battle of Stalingrad began in the summer of ’42, Roman Karmen, characteristically, longed to go there.— To see the defeated Paulus! he kept laughing. That’s every Russian soldier’s dream . . .
> 
> **PINCER MOVEMENTS** (Location 4783)

---

> His famous photo of Paulus, rigid and pale at the surrender at Stalingrad, reminds me of Karmen himself on the day that Elena left him.
> 
> **PINCER MOVEMENTS** (Location 4812)

---

> The point is, the point is that here, you see, in our Soviet homeland, for us . . .— and here Shostakovich’s lips fleered out and flittered into a spitefully sarcastic smile— film is the most important art form, not music.
> 
> **PINCER MOVEMENTS** (Location 5101)

---

> Speak the truth, like a Communist. Will we lose Moscow? I think not. By the end of this month they’ll start freezing to death, and then we can counterattack . . .
> 
> **PINCER MOVEMENTS** (Location 5180)

---

> In March, shortly before the premiere of Shostakovich’s Seventh Symphony, Comrade Stalin appointed him Deputy Commander of the Volkhov Front. The strategic aim: to break the siege of Leningrad. Of course the assignment was impossible, but at this stage of the war, what wasn’t?— Vlasov said: Comrade Stalin, I accept the responsibility.
> 
> **PINCER MOVEMENTS** (Location 5221)

---

> each victim had been shot in the base of the skull— a method of execution which the German language, so capable of inventing words for all eventualities, names a Nackenschuss.
> 
> **PINCER MOVEMENTS** (Location 5314)

---

> To my mind, Bolshevism is a crime inflicted against the world in general, and Russia in particular. You Slavs are perfectly capable of ethical conceptions, as I know from Dostoyevsky and— hm, Tolstoy’s not really manly— and yet you’ve allowed yourselves to be tricked into following these, well, excuse me, these murderers.
> 
> **PINCER MOVEMENTS** (Location 5412)

---

> The Polish campaign won’t get more than a paragraph in the history books. But we’re going to have to write an entire chapter about you Slavs! Do you know what I told my wife last summer? I told her what my commanding officer promised me. Don’t worry, I said. The Russian question will be solved in six weeks.
> 
> **PINCER MOVEMENTS** (Location 5456)

---

> Your form of rule was discredited long ago by Plato. In the Republic he points out that true democracy is mob rule. And that’s what you Slavs have. Why do you think we were able to conquer you so quickly? Because mob rule purged the best thinkers in your officer corps!
> 
> **PINCER MOVEMENTS** (Location 5573)

---

> The point is that unlike our system, Communism leaves no place for individual merit.
> 
> **PINCER MOVEMENTS** (Location 5577)

---

> Well, we Germans also give credit where credit is due. Some of us don’t mind calling your Tukhachevsky a genius, even though— well, it was out of fear of his genius that you shot him. We would have made him a Field-Marshal!
> 
> **PINCER MOVEMENTS** (Location 5578)

---

> many of us disagree with Berlin on a number of important points! And I want you to think about that, General Vlasov. If I were a Russian and I announced that I disagreed with Moscow, what do you think would happen to me?
> 
> **PINCER MOVEMENTS** (Location 5719)

---

> He asked for Napoleon’s memoirs, but they told him that that sort of thing wasn’t considered very uplifting.
> 
> **PINCER MOVEMENTS** (Location 5802)

---

> But there’s one matter very dear to my heart in which you’ve never quite believed: the honor of the German soldier. To get right down to it, Germans really are honorable people. They don’t murder women and children.
> 
> **PINCER MOVEMENTS** (Location 6110)

---

> Vlasov’s Russian wife had been arrested and put to death in retribution for his treason. In the interests of that highest good, rationality, it was needful to show Vlasov that there could be no turning back.)
> 
> **PINCER MOVEMENTS** (Location 6299)

---

> in those autumn days of 1944, when even Vlasov could hardly deny the concentration camps, the hostages shot in batches, the ice-grained women’s corpses frozen to their hanging-ropes
> 
> **PINCER MOVEMENTS** (Location 6400)

---

> the men had been made to hold lamps and watch as their womenfolk were raped by hordes of Red Army soldiers. Men who resisted were castrated; women who resisted were disemboweled.
> 
> **PINCER MOVEMENTS** (Location 6440)

---

> On 27.4.45, his comrade Zherebkhov urged him to flee to Spain by air, to work for the liberation movement in securer surroundings. Vlasov replied that he wished to share his soldiers’ fate.
> 
> **PINCER MOVEMENTS** (Location 6618)

---

> The primary goal of Operation Blau was to seize Russia’s oil fields in the Caucasus.
> 
> **PINCER MOVEMENTS** (Location 6758)

---

> the announcement was simply agonizing, not only because von Bock was a friend, but also because he was a Field-Marshal— the highest rank to which any German soldier could aspire: second only to the Führer himself! To Paulus, therefore, this capricious alteration of authority seemed demeaning and worse; for a moment he felt positively indignant at the Führer.
> 
> **PINCER MOVEMENTS** (Location 6824)

---

> Paulus believed that once the Supreme Command had set a goal for an Army Group, the Army Group ought to be allowed to achieve that goal in its own fashion. But this was not the Führer’s way, at least not since Operation Barbarossa had begun to go wrong.
> 
> **PINCER MOVEMENTS** (Location 6827)

---

> The fuel situation is becoming critical, the Führer went on. If I don’t get the oil of Maikop and Grozny, I’ll have to liquidate this war. The political generals don’t understand that.
> 
> **PINCER MOVEMENTS** (Location 6836)

---

> Most of us find it easy enough to believe that whatever benison fate grants us must be deserved; but to Paulus, who preferred real iron to dreams of gold,
> 
> **PINCER MOVEMENTS** (Location 6871)

---

> Sixth Army, you see, was not just any army; it was our Reich’s single greatest fighting force:
> 
> **PINCER MOVEMENTS** (Location 6873)

---

> He still believed that the Soviet command structure might well collapse in another four to six weeks; our Führer had said that Russia would then become the German India.
> 
> **PINCER MOVEMENTS** (Location 6913)

---

> He had been imagining that he was Furtwängler, the Führer of the music, whose melody now came streaming into everyone’s hearts; when suddenly he realized that after all he could be this; he too could own a baton encrusted with precious stones like Göring’s; and he began to see war somewhat as our Führer must, which is to say not as the implementation of preconsidered operations, but as music in and of itself, pulsations of godlike creativity whose patterns are their own harmonies.
> 
> **PINCER MOVEMENTS** (Location 6934)

---

> After the misery of the Moscow campaign, everyone had learned better than to squander Russia’s golden summer days. That was why Operation Blau needed to be completed by the end of October at the latest.
> 
> **PINCER MOVEMENTS** (Location 6977)

---

> Congratulating all of us on the successful fulfillment of Operation Blau, Phase II, the Führer canceled Phase III and commenced Operations Edelweiss and Heron. Operation Heron was a lightning attack on Stalingrad, and the man charged with that operation was Lieutenant-General Paulus. Operation Edelweiss was the continuation of our drive infinitely southeast-ward, for whose sake Paulus was now commanded to give up fifty percent of his ammunition and fifty percent of his fuel.
> 
> **PINCER MOVEMENTS** (Location 7037)

---

> The forces of Adolf Hitler, having in the meantime destroyed two more Russian armies, now drew near the City of Stalin. Therefore, what was about to happen had to happen.
> 
> **PINCER MOVEMENTS** (Location 7048)

---

> On 22.8.42, he enjoyed a light moment with the officers when the radio announced that Brazil had declared war on the Reich; somebody remarked that Field-Marshal von Reichenau had always expressed a desire to visit Rio de Janeiro, and Paulus, wishing to deflect them from thoughts of the dead, whom they surely all missed (von Reichenau had never failed to remember Paulus’s birthday), replied with a pleasant half-smile: Gentlemen, without a doubt the Brazilian campaign will have its compensations!—
> 
> **PINCER MOVEMENTS** (Location 7063)

---

> Stalingrad was to be held at all costs.
> 
> **PINCER MOVEMENTS** (Location 7112)

---

> And to think he could have gone to Africa instead!
> 
> **PINCER MOVEMENTS** (Location 7132)

---

> In December 1940 he had also predicted that Operation Barbarossa might last longer than a single summer. The Führer had flown into a rage and shouted: There is not going to be a winter campaign!— So that was a sore point between them. Paulus could never mention winter campaigns now.
> 
> **PINCER MOVEMENTS** (Location 7155)

---

> There was no hope for Germany if she failed to continue forward in every direction.
> 
> **PINCER MOVEMENTS** (Location 7395)

---

> Worse yet, those Romanians had permitted their artillery to be captured! As much as it humiliated him, there was nothing for it now but to ask the Führer for new operational and tactical reserves— an innovation for which we must credit Julius Caesar;
> 
> **PINCER MOVEMENTS** (Location 7478)

---

> now the ring was hardening just as ice does: a delicate skin at first, as easy to crack as sugar-glazing.
> 
> **PINCER MOVEMENTS** (Location 7601)

---

> Everyone advised him to recommend a breakout to the Führer, before it was too late. In that case, he said to them, more than ten thousand wounded and most of our heavy weapons would have to be written off. And then what? First we give up Stalingrad; then we recapitulate Napoleon’s retreat. Surely you remember your history, gentlemen. He started with four hundred thousand men. When he left Moscow he had a hundred thousand. That’s attrition for you. Then the retreat. He got to Poland with ten thousand .
> 
> **PINCER MOVEMENTS** (Location 7627)

---

> For now, any breakout was forbidden. Voronezh and Stalingrad were our two strongpoints in this zone. Both of them must be held to the death. They said to Paulus: The Führer’s instructed the Ministry of Aviation to supply you with all resources
> 
> **PINCER MOVEMENTS** (Location 7641)

---

> they cried that they wanted to break out at once, but Lieutenant-General Paulus made it clear that he accepted the Führer’s decision.—
> 
> **PINCER MOVEMENTS** (Location 7684)

---

> Your airlift has failed us. We’ve received only one-sixth of the supplies you promised. With this, my army can neither exist nor fight.
> 
> **PINCER MOVEMENTS** (Location 7835)

---

> Herr Colonel-General, Reich-Marshal Göring himself has promised us— We could have broken out before, Paulus interrupted. But the Führer believed the Reich-Marshal. What am I supposed to tell my soldiers now?
> 
> **PINCER MOVEMENTS** (Location 7836)

---

> And just how would he go about absolving me? He would issue a direct order that you initiate Thunderclap. As your superior officer, he would then take the consequences upon himself.
> 
> **PINCER MOVEMENTS** (Location 7871)

---

> And he felt that our Führer far away at Wolf’s Lair understood him. If he only continued to do his best here at Stalingrad for as long as he could, our Führer would forgive and preserve him.
> 
> **PINCER MOVEMENTS** (Location 7894)

---

> and the pallid, moody immensity of Russia hypnotized him; aside from the fact that he couldn’t stop shivering, he might have been on holiday with Coca at Baden-Baden, sitting beside her in the sand, rereading War and Peace; he’d just reached the section about Napoleon’s retreat, which as a result of his own research he could confirm had been very accurately written;
> 
> **PINCER MOVEMENTS** (Location 8036)

---

> On 15.1.43, when news came that the enemy had broken through our pincers at faraway Leningrad, Paulus fell silent.
> 
> **PINCER MOVEMENTS** (Location 8051)

---

> Did he have an inkling yet what he would be forced to suffer? Probably, since by then more than one man heard him say: History has already passed its verdict on me . . .— Stalingrad would be called “the turning point.” After Stalingrad, and as a result of Stalingrad, the mastery of central Europe would pass from Germany to Russia. And all because of him!
> 
> **PINCER MOVEMENTS** (Location 8072)

---

> The prudent soldier leaves his original medals at home, and wears authorized copies to guard against loss or frontline rust. He had not done this. Such behavior on the part of a high-ranking officer might have been construed as timidity.
> 
> **PINCER MOVEMENTS** (Location 8085)

---

> On 22.1.43, the last airstrip in Stalingrad fell to the Russians. Paulus again requested permission to surrender. The Führer replied: You must stand fast to the last soldier and the last bullet.
> 
> **PINCER MOVEMENTS** (Location 8089)

---

> Our Führer had promoted Paulus to Field-Marshal.
> 
> **PINCER MOVEMENTS** (Location 8153)

---

> No German Field-Marshal has ever in history fallen alive in enemy hands.
> 
> **PINCER MOVEMENTS** (Location 8174)

---

> Paulus, weary and thin, joined the anti-Fascist Union of German Officers. Why not? The Führer had already said: That’s the last Field-Marshal I shall appoint in this war.
> 
> **PINCER MOVEMENTS** (Location 8256)

---

> and here, in a huddle of black dress suits, the musicians were playing a string quartet by a certain D. D. Shostakovich, said to have been a great favorite of the late Comrade Stalin’s. The last Field-Marshal stood politely smiling as he listened. He hated the dissonant harmonies, which reminded him less of melody than they did of war.
> 
> **PINCER MOVEMENTS** (Location 8318)

---

> They gave him a villa and allowed him to serve the people as a middle-ranking police inspector.
> 
> **PINCER MOVEMENTS** (Location 8326)

---

> When Hilde Benjamin, nicknamed “the Red Guillotine,” became Minister of Justice, she made the correct decision, preserving and even promoting him, for Friedrich Paulus was a painstakingly accurate subordinate.—
> 
> **PINCER MOVEMENTS** (Location 8358)

---

> He lacked what a far abler Field-Marshal (I mean of course von Manstein, who was presently serving time in a British jail) practically embodied; modestly calling it the “Prussian tradition,” as if it were just a procedure which he followed without especial credit to him; von Manstein, in short, was an officer who knew how to be close to his men. Did this Inspector Paulus think that he was too good for his colleagues?
> 
> **PINCER MOVEMENTS** (Location 8367)

---

> As the great Moltke used to say, Genius is diligence.
> 
> **PINCER MOVEMENTS** (Location 8391)

---

> In 1960, the very year when Shostakovich visited Dresden and, evidently feeling stifled by the dreamily mysterious forest all around, composed his unhappy Opus 110, Paulus’s memoir Ich stehe hier auf Befehl saw the light;
> 
> **PINCER MOVEMENTS** (Location 8409)

---

> Ernst Paulus followed our Führer’s wish at last, blowing off the skullcap in a grey and crimson shower. The last thing he saw, or seemed to see, was an army of white skeletons on that black day.
> 
> **PINCER MOVEMENTS** (Location 8415)

---

> In those days, neutrality meant friendlessness at best, while allegiance to either side invited a capital sentence from the other.
> 
> **PINCER MOVEMENTS** (Location 8433)

---

> She says: You can’t hang all hundred and ninety million of us.
> 
> **PINCER MOVEMENTS** (Location 8450)

---

> Her death became a movie (“ Soyuzdetfilm,” 1944), with a score composed by Shostakovich. Decades after the war, memories of Zoya reincarnated themselves in the witch Loreley, who sings an irresistible song of suicide in the same composer’s “Death” Symphony.
> 
> **PINCER MOVEMENTS** (Location 8494)

---

> So the German hunters felt that everything was diminishing now. Sometimes there weren’t even gold teeth. Ebbing Jewry might dry up completely, as it continued to seem, yet profitlessly, rustling and dying, draining into each new earth-pit, its blood absorbed, its memory walled off like the festering heart of Shostakovich’s still unwritten Eighth String Quartet (Opus 110), the charred smears of Jewish villages quickly overgrown with grasses golder than guilt.
> 
> **PINCER MOVEMENTS** (Location 8911)

---

> How could Gerstein go on? And yet the blond man is said to have secretly flown to Finland to inform people there of the Final Solution.
> 
> **PINCER MOVEMENTS** (Location 9225)

---

> He opened the new issue of Signal and read an article about conditions in America: Negro schoolchildren were intimidating their teachers in several larger cities. Even the Americans were beginning to see that measures might be necessary.
> 
> **PINCER MOVEMENTS** (Location 9232)

---

> Now, Berlin wants to know whether this office has been hard enough, whether measures have been taken. For instance, it’s alleged that the female inhabitants of Lidice are still alive. I’m going to tell Berlin that you’re not men here, that you’re just a bunch of soft-shelled Jewish creeps.— In the end, because he acted so crazy that he must really be from Berlin, they allowed him to read the file on Lidice: one hundred and seventy-three men shot in the village, nineteen more liquidated in detention, seven women rendered harmless, two hundred and three others sent to concentration camps, a hundred and five children either deported or Germanized, the village razed, all with the approval of our Führer himself.
> 
> **PINCER MOVEMENTS** (Location 9250)

---

> He had always known that the sleepwalker knew, but that knowledge had been kept secret from himself, like a skeleton in a forest, like something silver on black.
> 
> **PINCER MOVEMENTS** (Location 9256)

---

> One is tempted to dismiss Gerstein as a romancer, writes the historian-ethicist Michael Balfour. He must have realized that his actions were having no result.
> 
> **PINCER MOVEMENTS** (Location 9298)

---

> Father, I . . . To me, the worship of Our Lord means nothing unless it’s expressed in practical acts of charity.
> 
> **PINCER MOVEMENTS** (Location 9393)

---

> I also fought on the Westfront in the last war, Kurt; you can’t imagine the things I saw . . . The son almost laughed.— No, father. I can’t imagine.
> 
> **PINCER MOVEMENTS** (Location 9427)

---

> the Western Allies still refused to believe. Gerstein was in despair.
> 
> **PINCER MOVEMENTS** (Location 9448)

---

> Now he no longer dared to destroy the prussic acid. Therefore he became an accomplice, history said.
> 
> **PINCER MOVEMENTS** (Location 9498)

---

> I’m telling you, even as we speak, people are being stripped naked and forced into gas chambers all over Central Europe! You can hear them screaming . . .
> 
> **PINCER MOVEMENTS** (Location 9547)

---

> Now it’s your turn, Gerstein! Are you one of us or not? Tell us a story.
> 
> **PINCER MOVEMENTS** (Location 9605)

---

> When was the last time you personally sent a Jew to the Promised Land?
> 
> **PINCER MOVEMENTS** (Location 9624)

---

> To get right down to it, Gerstein, what’s your stance on the Jewish question? Franz, I’m a specialist in cyanide disinfectants. Don’t you understand what that means?
> 
> **PINCER MOVEMENTS** (Location 9625)

---

> It’s better not to investigate evil things too deeply, Kurt, not only for your safety and ours but also because evil deserves to be respected! Would you strip a leper of his clothes and expose him? Would you call attention to the ugliness of someone who owns the power to do you harm?
> 
> **PINCER MOVEMENTS** (Location 9670)

---

> All your life, you’ve been the martyr. You’ve suffered the strictness of your father, but bearing it never brought you any peace. You stood up to evil and got your teeth knocked out. You warned us all of evil and went to a concentration camp. When all of us helped you get rehabilitated— and you know, Kurt, it wasn’t just your father; it really was all of us— you promptly did everything you could to get sent to Belzec, and now you have nightmares! I can’t help wondering whether you’re bringing your own fate upon yourself.
> 
> **PINCER MOVEMENTS** (Location 9679)

---

> These terrible things keep happening to you because you insist that you’re not evil like everyone else.
> 
> **PINCER MOVEMENTS** (Location 9685)

---

> Pride, Kurt, or willed blindness. You think that you’re better than we are. So you attempt the impossible. Of course you’ll get punished.
> 
> **PINCER MOVEMENTS** (Location 9687)

---

> As for Gerstein, he continued to hold his dangerously illegal gatherings, seeking always to warn about and learn about the Third Reich’s latest crimes: the mass hangings at Plötzensee, the reprisals in Slovakia, Dr. Brachtl’s liver puncture experiments, Jewish hands in the air, Jewish eyes looking desperately away,-men
> 
> **PINCER MOVEMENTS** (Location 9733)

---

> In 8.44 we find him writing to his father: You are wrong about one thing. I never participated in any of this. Whenever I received orders, I not only didn’t follow them, but made sure they were disobeyed. For my part, I leave all this with clean hands and a clear conscience.
> 
> **PINCER MOVEMENTS** (Location 9739)

---

> In 1949 the Denazification Council of Tübingen refused to rehabilitate his memory, calling him a “petty Nazi.”
> 
> **PINCER MOVEMENTS** (Location 9757)

---

> It may be that the mere fact of making such efforts, associated with a constant risk of death, had been sufficient to persuade him that his conscience and his hands were unsullied. But this conviction does not indicate whether those efforts always achieved the desired success.
> 
> **PINCER MOVEMENTS** (Location 9758)

---

> On 20.1.65 he was in fact rehabilitated. By that time, anti-Semites around the world were already denying that anything untoward had happened.
> 
> **PINCER MOVEMENTS** (Location 9761)

---

> Sulkily, Karmen muttered that the Allies reminded him of Elena, who kept always saying I understand while making no move to do anything about the situation.
> 
> **PINCER MOVEMENTS** (Location 10013)

---

> As for the second front, by the time our Allies finally opened the second front, who cared? It’s true that they died by the thousands on the beaches of Normandie. But we’d already died by the hundreds of thousands. Moreover, it’s objectively clear that their only reason for invading France at that late date was to deny us total victory in Germany.
> 
> **PINCER MOVEMENTS** (Location 10021)

---

> That’s why so few of us supported Operation Citadel. After all, we should have been easier on ourselves: it wasn’t our task to win; no one expected that of us. It was only our job to take the blame.
> 
> **PINCER MOVEMENTS** (Location 10056)

---

> To be a German means to do a thing for its own sake.
> 
> **PINCER MOVEMENTS** (Location 10411)

---

> Field-Marshal von Manstein served him with a writ of I-told-you-so.
> 
> **PINCER MOVEMENTS** (Location 10574)

---

> Stalin gloated: If the Battle of Stalingrad signalled the twilight of the German-Fascist Army, then the Battle of Kursk confronted it with catastrophe.—
> 
> **PINCER MOVEMENTS** (Location 10586)

---

> The telephone rang. His heart exploded sickeningly. He lifted the receiver and heard nothing but an evil silence. This was what they sometimes did to make sure you were home, when they, you know.
> 
> **PINCER MOVEMENTS** (Location 10678)

---

> Very quietly he reinterred the receiver, took up his briefcase, which contained a toothbrush, clean underwear, and a few scraps of music paper, and then he went out to the landing by the elevator, waiting very quietly for an hour, so that the children would not have to see him being arrested.
> 
> **PINCER MOVEMENTS** (Location 10680)

---

> it would have been too unbearable for him not to hope.
> 
> **PINCER MOVEMENTS** (Location 10708)

---

> After all, one of life’s best pleasures is reading a book of perfect beauty; more pleasurable still is rereading that book; most pleasurable of all is lending it to the person one loves:
> 
> **PINCER MOVEMENTS** (Location 10766)

---

> I’ll never forget the look on Justice Jackson’s face when Hagen rose, stared straight forward, and coolly explained: The function of Germans in Europe, and our duty itself, is to take the blame for everything. We commit crimes so that the rest of you can feel pure.
> 
> **PINCER MOVEMENTS** (Location 10896)

---

> His bride, Eva, who was as rich and good as Holstein butter, had now swallowed a capsule on his instructions. She lay beside him on the sofa, with her big cowlike eyes filming over. He raised the Walther to his head, then hesitated, lowered it a trifle, and peered into the barrel, to see what he might see within the mountain.
> 
> **PINCER MOVEMENTS** (Location 10974)

---

> Back in Germany where fog bleeds silver slime upon the willows, chestnut trees and maples, which is to say too far back to be imagined, our sisters were prostituting themselves for chocolate or chewing gum.
> 
> **PINCER MOVEMENTS** (Location 11009)

---

> Well, they’re the victors, so they must be the master race.— This was how we tried to explain it to ourselves.
> 
> **PINCER MOVEMENTS** (Location 11013)

---

> Germany was gone forever. The two lapdog states which remained could be tricked into fighting each other eternally, just as we and Germany used to do.
> 
> **PINCER MOVEMENTS** (Location 11046)

---

> According to an American lecturer, the Eighth String Quartet of Shostakovich (Opus 110) is supposed to represent the Curtain’s darkness, but (speaking only for myself), I’d have to say that my sensation on the Communist side was something quite different from melancholy; everything was dark, that’s true, but it was the darkness of a circus tent, where anything could happen.
> 
> **PINCER MOVEMENTS** (Location 11064)

---

> What about your “Song of the Forests,” Herr Schostakowitsch? Isn’t that a bit of Stalinist ass-kissing?
> 
> **PINCER MOVEMENTS** (Location 11363)

---

> For instance, the Iron Curtain was better for both sides; I’d realized that now. It used to be that the NKVD drove right into West Berlin to kidnap people they didn’t like, and once they were back in the Russian sector there was nothing anybody could do. Now we were safer from them, and they were safer from us; that was why LIFE HAS BECOME BETTER.
> 
> **PINCER MOVEMENTS** (Location 11397)

---

> I finally comprehended that I would always be in the dark as to the real strategic purpose of this operation.
> 
> **PINCER MOVEMENTS** (Location 11539)

---

> That meant that I must be awake at last: I knew that I didn’t know.
> 
> **PINCER MOVEMENTS** (Location 11541)

---

> What about Shostakovich? By this question I don’t mean, who is he? Opus 110 answers that. I mean, what shall I do about him?
> 
> **PINCER MOVEMENTS** (Location 11648)

---

> That was how I learned that no is stronger than yes. (Shostakovich already knew that.) It takes two yesses for I to become we, but only one no for we to break apart, no matter what the other party wishes.
> 
> **PINCER MOVEMENTS** (Location 11728)

---

> Berliners queued up for their turn at the barrel of American milk. Smiling, skinny old men who remembered quite well how to shout Heil Hitler! wrapped themselves up in all their clothes, sat on rubble and drank bowls of American soup.
> 
> **PINCER MOVEMENTS** (Location 11798)

---

> The Red Guillotine busily condemned people to death. Sometimes, when I wasn’t being executed myself, I used to watch the executions from one of the twin stone pillars which overlook Tempelhof’s circular runway.
> 
> **PINCER MOVEMENTS** (Location 11848)

---

> I wouldn’t want you to disbelieve in happy endings, at least not on our side. We’d won the inestimable treaure of democracy: shabby West Berliners lining up to vote, and silver-white summer clouds over everything.
> 
> **PINCER MOVEMENTS** (Location 11856)

---

> The so-called “West German” press describes her as a negroid woman with dark, evil eyes,
> 
> **PINCER MOVEMENTS** (Location 11871)

---

> The Red Guillotine remains one of our foremost zero hour activists, and in the era of this legend, most of which takes place between the constitutions of 1949 and 1968, we all saw her name if not her face.
> 
> **PINCER MOVEMENTS** (Location 11876)

---

> She longed to apply to Germany the progressive legal science of our Eastern mother, the Soviet Union.
> 
> **PINCER MOVEMENTS** (Location 11897)

---

> And so Fräulein Lange decided to study law at Heidelberg. Her mother asked why. She replied: I believe I will be able to help the victims of injustice.
> 
> **PINCER MOVEMENTS** (Location 11921)

---

> Bourgeois historians, romantics and deviants prefer to remember Weimar Berlin as a concretion of the Princess Café’s private niches, where Georg’s brother Walter and Walter’s poet friend Heinle used to meet prostitutes.
> 
> **PINCER MOVEMENTS** (Location 11937)

---

> Whenever she lost a trial, she had one very particular thing to say to her client. It was not the so-called “consolation” with which a bourgeois lawyer seeks to wash his own hands of what the fired trade unionist or the hungry thief must now suffer— or, if it was, it was consolation sharp as a razor. It inculcated hatred; it simplified and abstracted the case to its socioeconomic essentials; it directed energy toward the future. What she said was this: I’ve come to recognize that questions of law and justice are at the same time questions of power.
> 
> **PINCER MOVEMENTS** (Location 11965)

---

> The plan of the zero hour activists: Since East Germany doesn’t even have trade unions yet, our first task will be to complete the bourgeois revolution of 1848. Then we’ll smash the monopoly capitalists and Junkers who created Nazism. No elections, of course. Hitler had elections.
> 
> **PINCER MOVEMENTS** (Location 11988)

---

> a delegation of doctors dared to interrupt us with the demand that we permit German women raped by the Red Army to obtain abortions. Comrade Ulbricht replied: The Germans should have thought about that before they launched Operation Barbarossa. Comrade Benjamin, you’re a woman; surely you can understand! We appeal to you! I stand by Comrade Ulbricht, replied the Red Guillotine. But, Comrade Benjamin, you were there yesterday when those two Mongolians raped Resi Nordlund in the street. We saw you pass by! And you feel nothing? My feelings are of no relevance, said the Red Guillotine contemptuously.
> 
> **PINCER MOVEMENTS** (Location 12052)

---

> I have nothing to say about the individuals involved in this case. As Communists we must be realistic. Legislation follows the Party, doesn’t it? The Party follows Comrade Stalin, doesn’t it? Do you think that Comrade Stalin’s in a mood to let us accuse the Red Army of anything?
> 
> **PINCER MOVEMENTS** (Location 12063)

---

> She passed the test; she retained her reputation for impartiality.)
> 
> **PINCER MOVEMENTS** (Location 12067)

---

> Who has ever once experienced this woman when she pulls out all the stops of her ice-cold intellect won’t soon forget her. She alone is the law.
> 
> **PINCER MOVEMENTS** (Location 12131)

---

> You’re not simply a Jew by marriage, now, are you, Frau Benjamin? You’re a blood-Jew. Do you know what Germans think about blood-Jews?
> 
> **PINCER MOVEMENTS** (Location 12306)

---

> And everything got worse and worse in our ever more advanced socialist society right up until 1989, the last year of her old age, by which time her dark eyes kept looking away from everything, while her drawn mouth showed teeth. A few months after she closed her eyes forever, so did East Germany.
> 
> **PINCER MOVEMENTS** (Location 12389)

---

> Her praises stretch as long as the lines at the Intertank gas station.
> 
> **PINCER MOVEMENTS** (Location 12394)

---

> They entered the maternity ward at gunpoint and raped the nurse who persuaded them not to rape a mother who’d just given birth. I won’t say who it is; you know her. Perhaps she knew what would happen, in which case I admire her sacrifice. Lina, you have no idea what it was like. They raped us on the streets, on the trains, in the fields. They arrested us and raped us. They raped us as we were cleaning their floors. Of course it wasn’t quite as bad as at the beginning, when they used to rape us in front of our husbands
> 
> **PINCER MOVEMENTS** (Location 12748)

---

> Best listened to in a windowless room, better than best an airless room— correctly speaking, a bunker sealed forever and enwrapped in tree-roots— the Eighth String Quartet of Shostakovich (Opus 110) is the living corpse of music, perfect in its horror. Call it the simultaneous asphyxiation and bleeding of melody. The soul strips itself of life in a dusty room.
> 
> **PINCER MOVEMENTS** (Location 12863)

---

> What key most effectively expresses bereavement? In the darkness, a cello saws out a tune as dry as the buzzing of wasps within a skull.
> 
> **PINCER MOVEMENTS** (Location 12871)

---

> Death having done its work, we must now suffer through the dying. Thus Opus 110.
> 
> **PINCER MOVEMENTS** (Location 12890)

---

> As early as 1944, the cellist V. Berlinsky, while praising his astounding musical memory, had felt forced to describe him as a lump of nerves.
> 
> **PINCER MOVEMENTS** (Location 12912)

---

> Stalin’s enthusiastically ruthless shadow Comrade Zhdanov (who was soon to die under peculiar circumstances) announced to the Leningrad Union of Soviet Writers: Leninism proceeds from the fact that our literature cannot be politically indifferent, cannot be “art for art’s sake.”
> 
> **PINCER MOVEMENTS** (Location 12935)

---

> Reading this directive in the pages of Pravda, Shostakovich understood that it was only a matter of time before they turned their attention back to music. It would be “Lady Macbeth” all over again.
> 
> **PINCER MOVEMENTS** (Location 12940)

---

> The sincerity of that Seventh Symphony, whenever I hear it I can hardly bear it! I’m so ashamed of it now.
> 
> **PINCER MOVEMENTS** (Location 12956)

---

> What drew Shostakovich to Jewish harmonies? The simplest answer, and the truest, might be their sadness.
> 
> **PINCER MOVEMENTS** (Location 12991)

---

> and in our Soviet Union we accept the Marxist conception that art, and indeed all culture, comprises a mere superstructure founded on economic realities.
> 
> **PINCER MOVEMENTS** (Location 12996)

---

> What’s your content? I . . . I have no content; I’m empty. Then say so in your music.
> 
> **PINCER MOVEMENTS** (Location 13041)

---

> The flat, the pianos, the dacha and everything were a gift from Comrade Stalin. (Keep your eye on that queer, Stalin told Beria. Sooner or later he’ll fuck up. Then I want you to hit him hard.)
> 
> **PINCER MOVEMENTS** (Location 13065)

---

> As for Shostakovich himself, struggling to seek beauty in his way, to be true only to the melodies he heard (this being the only loyalty he could not betray), he descended like a spinning bomb toward the tomb of Opus 110. There he could explode all he liked.
> 
> **PINCER MOVEMENTS** (Location 13077)

---

> You promised us Lenin in your Sixth Symphony. Then you promised him in the Seventh. Not that we have anything against the Seventh, of course, but when will you get around to Lenin?
> 
> **PINCER MOVEMENTS** (Location 13103)

---

> Although his Ninth Symphony had disappointed many critics, his Second Piano Trio won a Stalin Prize!
> 
> **PINCER MOVEMENTS** (Location 13112)

---

> And so now our new propaganda organ Culture and Life began to attack a certain D. D. Shostakovich. By 1948 he was being accused once more of formalistic and anti-democratic tendencies.
> 
> **PINCER MOVEMENTS** (Location 13126)

---

> In February, much of his work, including that invidious Eighth Symphony, was banned by the organ Glavretkom— a necessary policy, with which no true Communist can argue. E. A. Mravinsky, who’d conducted the premiere of the Fifth a decade ago, under equally foreboding circumstances, had raised the score above his head then, at considerable risk to himself. Now the Fifth was to be outlawed altogether. Mravinsky conducted the final performance, kissed the score, then raised it high .
> 
> **PINCER MOVEMENTS** (Location 13144)

---

> For Mravinksy’s grand gesture, as for the other one back in ’38, he felt no gratitude, no, no, even gratitude he must dissimulate! Impossible to say what tune the “organs” might play now! And that impossibility haunted him. Every night his terror broke through his sleep.
> 
> **PINCER MOVEMENTS** (Location 13172)

---

> August was when they hanged the Fascist collaborator A. A. Vlasov. That’s how we light the way ahead with a searchlight.
> 
> **PINCER MOVEMENTS** (Location 13199)

---

> In September, while Comrade Stalin’s cadres began rounding up Zionist conspirators, Shostakovich was stripped of his teaching jobs at the Leningrad Conservatory and the Moscow Conservatory alike.—
> 
> **PINCER MOVEMENTS** (Location 13200)

---

> Poor Maxim, now ten years old, found himself required to denounce his father during an examination at music school.— Smiling when he heard, Shostakovich stroked the boy’s hair.
> 
> **PINCER MOVEMENTS** (Location 13208)

---

> Naturally, comrades, and I’m sure those sanctions will, mmm, to speak, inspire me to, to (Ninusha will love this!) future creative work and provide, er, insights—
> 
> **PINCER MOVEMENTS** (Location 13269)

---

> At this very same moment, his “Song of the Forests” (Opus 81), which celebrated Soviet labor (and incidentally praised Comrade Stalin), resounded in almost every factory of the USSR.
> 
> **PINCER MOVEMENTS** (Location 13292)

---

> Opus 81 was good music greyed down for the sake of survival— greyed down to gaudy gold.
> 
> **PINCER MOVEMENTS** (Location 13299)

---

> You can’t hide your secrets from me, Mitya. When you were sleeping with that slut Elena I could literally smell her on you. That cheap, catty smell of her— ugh! You’re a man who has to have affairs.
> 
> **PINCER MOVEMENTS** (Location 13323)

---

> You’re always looking for a Muse to follow, and she’s got to be a dark-eyed Muse from someplace else.
> 
> **PINCER MOVEMENTS** (Location 13336)

---

> In January 1949, Comrade Stalin finally began his campaign against Jewish influences. Maybe it was only now, with the distractions of the war years more or less mastered, that he’d found the time to read Mein Kampf.
> 
> **PINCER MOVEMENTS** (Location 13368)

---

> Shostakovich was sent to New York as a member of the Soviet peace delegation. All his works had been un-banned four days before. (We’ll take care of that problem, Comrade Shostakovich.— This was exactly what Stalin had said on the telephone. Oh, me, oh, my, he’d, so to speak, authorized the operation!)
> 
> **PINCER MOVEMENTS** (Location 13371)

---

> They sent him to East Germany as the principal Soviet delegate to the Bach Festival. He didn’t want to go, but he was on the jury.
> 
> **PINCER MOVEMENTS** (Location 13446)

---

> He’d already promised to take the appropriate “class approach.”
> 
> **PINCER MOVEMENTS** (Location 13447)

---

> He felt as if he were suffocating and bleeding at the same time. What was that sound? He wanted a piano to compose on. What was that sound? On the windowsill of the car, his fingers began to tap out the allegro molto of Opus 110.
> 
> **PINCER MOVEMENTS** (Location 13459)

---

> apparently he used to aphorize: It’s merely a question of time and manpower. That was how Bach must have built his compositions;
> 
> **PINCER MOVEMENTS** (Location 13464)

---

> Then and there he resolved to compose a cycle of preludes and fugues (Opus 87), dedicated to her and arranged in ascending fifths.
> 
> **PINCER MOVEMENTS** (Location 13520)

---

> In 1951 he was elected deputy to the Supreme Soviet of the Russian Federated Soviet Republic. Taking his bench, he felt the gaze of the pale, titanic Lenin behind him. Lenin was stone. He was stone. They asked him when he would consecrate his symphony to Lenin, and he muttered something.
> 
> **PINCER MOVEMENTS** (Location 13530)

---

> He could not forget that time when the NKVD had interrogated him about his connection with Marshal Tukhachevsky. Down the hall he’d heard somebody screaming— very pure screams mostly in B-flat; in due time he’d wring them into Opus 110. Now he was a deputy to the Supreme Soviet. Tomorrow he’d be lying next to Tukhachevsky if that was what they wanted. How did that jingle go? It’s not enough to love Soviet power. Soviet power also has to love you.
> 
> **PINCER MOVEMENTS** (Location 13546)

---

> We’re all in favor of internationalism, Dmitri Dmitriyevich, but there’s a difference between internationalism and cosmopolitanism, if you see what I’m saying. You’re playing into the hands of the Zionists!
> 
> **PINCER MOVEMENTS** (Location 13588)

---

> Meanwhile he finished his Fifth Quartet, wearing his heart on his musical sleeve by quoting from the Trio for Clarinet, Violin and Piano of his beloved Galina Ustvolskaya.
> 
> **PINCER MOVEMENTS** (Location 13617)

---

> In 1953, the Jewish composer Weinberg was arrested. With almost suicidal courage, Shostakovich opened his desk, withdrew a single sheet of music-paper as thin as that with which we blacked out windows back in Leningrad, turned it over and wrote a letter directly to Comrade Beria on his colleague’s behalf.
> 
> **PINCER MOVEMENTS** (Location 13633)

---

> Because the spouse of an enemy of the people automatically became an enemy, too, Weinberg’s wife Natalya would be arrested next—
> 
> **PINCER MOVEMENTS** (Location 13636)

---

> Fortunately, Stalin now shook his fist at the sky, fell back into bed and died; and a month afterward Weinberg found himself released.
> 
> **PINCER MOVEMENTS** (Location 13657)

---

> This new Tenth Symphony of his, which capitalists had the impudence to call his “masterpiece,” was of course attacked in the home country for dissonance and pessimism. Moreover, it contained an offensively erotic element. The second movement teemed with his musical signature intertwined with the musical initials of his latest unrequited love, the young pianist E. M. Nazirova. He hastened to apologize for all this in Sovietskaya Muzyka.
> 
> **PINCER MOVEMENTS** (Location 13676)

---

> It’s said that shortly after Stalin’s death a guest discovered Shostakovich reading the monster’s official biography, but in secret, as if it were shameful. Why, millions had read that book (or at least bought it)! Just as Mein Kampf had been on practically every German family’s bookshelf during a certain period, so in the days of the “cult of personality” Stalin’s life had sold rather well— even better, perhaps, than Stalin’s Foundations of Leninism. No Soviet citizen could get away from it. And now, only now, Shostakovich was reading it— and now he was hiding it! It was all so strange . . .
> 
> **PINCER MOVEMENTS** (Location 13690)

---

> Almost a decade between symphonies, isn’t that so? You’re not exactly a shock worker!
> 
> **PINCER MOVEMENTS** (Location 13713)

---

> They asked him if he knew that M. Weinberg had been approached by an agent of British intelligence. They wanted to know when his Lenin Symphony would be finished. They demanded that he join the Communist Party, which is the only true party of the working class. He preferred to be associated with the working class, didn’t he? They kept referring to your obligation to the people.
> 
> **PINCER MOVEMENTS** (Location 13720)

---

> his song-cycle From Jewish Poetry premiered at last (in cosmopolitan Leningrad, of course.) We forgave him this Zionist provocation, in spite of the fact that he still held back from joining the Party. Even when he used his growing prestige to help effect the posthumous rehabilitation of V. Meyerhold, we continued to forbear.
> 
> **PINCER MOVEMENTS** (Location 13875)

---

> In 1956, the year of Khruschev’s “secret speech” denouncing the Stalin cult, the Eighth Symphony was rehabilitated; and an editorial in the journal Voprosy Filosofii decried the repression of “Lady Macbeth” twenty years ago.
> 
> **PINCER MOVEMENTS** (Location 13935)

---

> The real point is that the “Muddle Instead of Music” article in Pravda has never been retracted. Therefore, it’s still in force.
> 
> **PINCER MOVEMENTS** (Location 13963)

---

> That fall his Eleventh Symphony, which had already achieved immense success in spite of its secret references to the Soviet tanks now crushing the Hungarian uprising (Maxim had whispered: Papa, what if they hang you for this?), won a Lenin Prize— which after Khruschev’s secret speech could not be called a Stalin Prize anymore, you see.
> 
> **PINCER MOVEMENTS** (Location 14025)

---

> That was the year that they appointed him Chairman of the Organizing Committee for the First International Tchaikovsky Competition (the prize went to a tall young American named Van Cliburn);
> 
> **PINCER MOVEMENTS** (Location 14049)

---

> I’m shooting for 110, which will be a quartet, something intimate, so that everybody can hear the, the, whatchamacallit.
> 
> **PINCER MOVEMENTS** (Location 14056)

---

> I promise to apply just as soon as I finish my symphony about Lenin. That way I’ll, so to speak, have something to offer.
> 
> **PINCER MOVEMENTS** (Location 14095)

---

> Back in ’36, for instance, the only reason you weren’t dragged down with Tukhachevsky was that your interrogator got arrested. Well, guess what? He’s been rehabilitated!
> 
> **PINCER MOVEMENTS** (Location 14102)

---

> This was the time that his First Cello Concerto in E-flat Major premiered. In the last movement was a parody of Stalin’s favorite tune “Suleiko”— so deeply buried, to be sure, that not even Rostropovich, to whom the concerto had been dedicated, could have ever sniffed it out—
> 
> **PINCER MOVEMENTS** (Location 14107)

---

> Leave that crap to the intellectuals! shouted Khruschev. Just tell me you’re a Party man. Are you a Party man?
> 
> **PINCER MOVEMENTS** (Location 14147)

---

> When he sobered up, he found he’d signed an application for membership in the Communist Party.
> 
> **PINCER MOVEMENTS** (Location 14306)

---

> It was the personal wish of Comrade Khruschev that he join the Party, they’d said. Many changes had been made. He’d find that it was really a very nice Party now, a lovely Party, really.
> 
> **PINCER MOVEMENTS** (Location 14317)

---

> But Maxim’s applying to the Composers’ Union, and if I refuse to . . . No, I’ll hold out.
> 
> **PINCER MOVEMENTS** (Location 14370)

---

> Gazing out the train window at the rich blonde grass of the German plains, he felt a sense of shame and strangeness, as if he had unveiled the nakedness of some dead woman.
> 
> **PINCER MOVEMENTS** (Location 14383)

---

> Regarding the war damage (caused by incendiary bombs), he said to himself: Dresden’s wrecked, all right, but I remember how that first shell smashed into the side of the apartments across the street, and then, four-beat rest, and then from that smoking hole, which was about two storeys wide, I’d say, rubble and corpses began hissing out! A snare drum could recapitulate that sound. It was quite . . . That’s what you did to Leningrad. For nine hundred days! You did it.
> 
> **PINCER MOVEMENTS** (Location 14405)

---

> matter. The distinguishing feature of Jewish music is the ability to construct a jolly melody on a foundation of sad intonations.
> 
> **PINCER MOVEMENTS** (Location 14454)

---

> I wrote an ideologically deficient quartet which nobody needs. I reflected that if I die someday, it’s hardly likely anyone will compose a work dedicated to my memory. So I decided to write one myself. You could even write on the cover: Dedicated to the composer of this quartet.
> 
> **PINCER MOVEMENTS** (Location 14460)

---

> he dedicated Opus 110 “to the victims of war and fascism.” Why not? Whatever he did made no difference. He, of course, was nobody’s victim, because he’d agreed to, you know.
> 
> **PINCER MOVEMENTS** (Location 14463)

---

> On the official side, a certain D. D. Shostakovich excretes new program music for the masses. And on the mirror-side, where all’s presumably flameless (otherwise we’d glimpse red writhings when we gazed down into those bottomless black slits of the piano keys), a counterpart D. D. Shostakovich composes Opus 110.
> 
> **PINCER MOVEMENTS** (Location 14471)

---

> When the Nine Hundred Days began and Maxim was weeping in the night from hunger, I promised I’d write him into the Seventh. And I did; I wrote that for him. Now’s my final chance to make sure I didn’t waste any of his tears, because . . . It was in A-flat minor, I’ll never forget that.
> 
> **PINCER MOVEMENTS** (Location 14483)

---

> We prefer our personal tragedies, because we’re all cowards and bastards.
> 
> **PINCER MOVEMENTS** (Location 14490)

---

> Sometimes he drank until he fell asleep. When he awoke, he reached for the tumbler, muttering into the mirror: Generally speaking, I, I’m a degenerate.
> 
> **PINCER MOVEMENTS** (Location 14494)

---

> I’m going to make sure that Opus 110 contains everything, since it’s the last time I’ll still be, so to speak, me.
> 
> **PINCER MOVEMENTS** (Location 14509)

---

> About this quartet the most fundamental thing which can be said is that it is too sad even to rise from a moan into a wail at death’s uncompassed crescendo.
> 
> **PINCER MOVEMENTS** (Location 14520)

---

> it’s as bright as the electric light which illuminates the gas chamber when it’s time to ascertain whether all the Jews are dead;
> 
> **PINCER MOVEMENTS** (Location 14522)

---

> Yet on the whole the effect is of somebody drowning, his most desperate convulsions already behind him; he’s begun to inhale water; the green water he sees is going black; and he’s settling down into the muck.
> 
> **PINCER MOVEMENTS** (Location 14524)

---

> Hence the opening notes of the first movement as carefully hopeless as men in a snow-trench before Leningrad, resting their machine-guns on blocks of ice.
> 
> **PINCER MOVEMENTS** (Location 14530)

---

> This is why it’s reductionist to claim that this quartet is merely the corrective to the Seventh Symphony, the distillation of Leningrad’s agony with the propaganda decanted off.
> 
> **PINCER MOVEMENTS** (Location 14534)

---

> Opus 110 explodes out of it, like metal splinters protruding from broken ferro-concrete.
> 
> **PINCER MOVEMENTS** (Location 14548)

---

> As the Führer once said: One can’t fight a war with Salvation Army methods! Opus 110 repeats this dictum in the speech of instruments.
> 
> **PINCER MOVEMENTS** (Location 14556)

---

> The very first moment that Shostakovich arrived in Dresden, music flooded his skull in a hideous scream; he clutched at his chest and the world whirled, but nothing else did:
> 
> **PINCER MOVEMENTS** (Location 14558)

---

> He didn’t escape; he won’t get away this time, either; so in Opus 110 he self-loathingly quotes himself:
> 
> **PINCER MOVEMENTS** (Location 14564)

---

> And whenever there’s any beauty at all in Opus 110, it’s dismembered;
> 
> **PINCER MOVEMENTS** (Location 14571)

---

> And Shostakovich, entering the negative spaces beneath the piano’s black keys at last, extends his front line beyond music into a perfect hell where his life, dekulakization and Operation Barbarossa become one.
> 
> **PINCER MOVEMENTS** (Location 14582)

---

> Life’s a transfer prison. Sunlight between two darknesses isn’t sunlight at all; it’s central Europe herself, which is to say that it’s the fourth movement’s largo, which manages to convey the atmosphere of sickening expectation which overhung Shostakovich at this period;
> 
> **PINCER MOVEMENTS** (Location 14630)

---

> because Opus 110 is no progression, only a prison, and the prisoner (one D. D. Shostakovich) has now paced the walls right back to his starting point. He’s at the center of the world, you see.
> 
> **PINCER MOVEMENTS** (Location 14654)

---

> Hence Opus 110’ s horror as intimate as the throat-slime of music, the strings dripping with bitterness and hate.
> 
> **PINCER MOVEMENTS** (Location 14656)

---

> That same year, he whom the capitalists had misnamed “the Mozart of modern Russia” composed his Twelfth Symphony, whose subject at last was Lenin— a hateful, grotesque satire of Lenin.
> 
> **PINCER MOVEMENTS** (Location 14662)

---

> Now his Fourth Symphony, which he’d completed in 1936, could finally be performed in public for the very first time. Not long after, our vigilant German allies erected the Berlin Wall.
> 
> **PINCER MOVEMENTS** (Location 14668)

---

> In 1961, when we defended socialism by constructing the Berlin Wall, “Lady Macbeth” got restaged at last, but with the erotic parts excised.
> 
> **PINCER MOVEMENTS** (Location 14709)

---

> when word got out that his Thirteenth Symphony was explicitly linked to Yevtushenko’s subversive poem “Babi Yar,” 44 and so the district Party secretary cried out: This is outrageous! We let Shostakovich join the Party and then he goes and presents us with a symphony about Jews!—
> 
> **PINCER MOVEMENTS** (Location 14740)

---

> After Yevtushenko caved in and made the changes which the Party required, to deemphasize the Jewish nature of that massacre, Shostakovich got drunk with Lebedinsky, whom he saw less and less these days, and he whispered: I am a Jew! Oh, how I want to be a Jew . . .
> 
> **PINCER MOVEMENTS** (Location 14743)

---

> Guess what a great comrade said? Anyone in this world who does not succeed in being hated by his adversaries does not seem to me to be worth much as a friend. Guess who? He’s, so to speak, a German. An Austrian, actually. A late Austrian.
> 
> **PINCER MOVEMENTS** (Location 14844)

---

> The following year, as the new purges of Soviet literature began, he was named Hero of Socialist Labor. By then the infamous dissident A. I. Solzhenitsyn was already referring to him as “the shackled genius.” Yet he dared to sign a petition in Solzhenitsyn’s favor.
> 
> **PINCER MOVEMENTS** (Location 14939)

---

> Opus 110 towered above us all; he’d brought a new evil into the world without solving an old one.
> 
> **PINCER MOVEMENTS** (Location 14967)

---

> the grim Fourteenth Symphony, whose proclaimed theme was death, and whose melodies (if they can even be called that) were blacker than the smoke from a burning oil depot.
> 
> **PINCER MOVEMENTS** (Location 14975)

---

> Unfortunately, the Fifteenth was no more than a feeble rearguard action, a holding-on behind enemy-occupied lines. Many a chord got borrowed from Wagner, Prokofieff, Mussorgsky and a certain D. D. Shostakovich. On the whole, it was as grey as Tukhachevsky’s eyes, as white as Glikman’s intentions, as clean as Nina’s fingernails, as solitary as Irina’s, you know.
> 
> **PINCER MOVEMENTS** (Location 15051)

---

> He lived on to 1973, when he signed an open letter in Pravda denouncing the human rights activist A. Sakharov. This servile act cost him several of his remaining friends.
> 
> **PINCER MOVEMENTS** (Location 15106)

---

> Now that he was safely dead, there was no need to disgrace him; for that matter, he’d been dead ever since he composed Opus 110.
> 
> **PINCER MOVEMENTS** (Location 15147)

---

> under Van Cliburn’s hands the piano keys seemed to be made sometimes of ice, sometimes of steel, and sometimes of fragrant toffee.
> 
> **PINCER MOVEMENTS** (Location 15166)

---

> the purpose of competitions is not to reward individual “merit,” but to educate the masses.
> 
> **PINCER MOVEMENTS** (Location 15168)

---

> he repeated the Tchaikovsky concerto, which the New York Times, still using the language of war, described as a big, percussive attack that dominated the orchestra. While it’s true that he peppered the first movement with powerfully booming chords whose metronome-like steadiness overwhelmed the romantic warmth of the strings, he was no war machine. His loudest hammer-blows remained somehow bell-like, controlled. Moreover, that opening thunder soon gave way to crystalline arpeggios, each note of which glittered as distinctly as an ice-crystal.
> 
> **PINCER MOVEMENTS** (Location 15215)

---

> Shostakovich was the Chairman of the Organizing Committee for this First International Tchaikovsky Competition (an appointed position, whose bestowal underlined the Party’s confident expectation that his rehabilitation would never be a source of regret), and so it was actually he who’d been required to stand at the podium, praising Van Cliburn, and he who’d transmitted the medal and the envelope of cash into the boy’s sweaty hand while newsmen’s flashbulbs exploded like antiaircraft rounds.
> 
> **PINCER MOVEMENTS** (Location 15224)

---

> Dmitri Dmitriyevich, you’re the person our generation depends on to give us answers. Please, I beg of you, don’t let them talk you into joining the Party. You can’t imagine how many people are counting on you to hold firm . . .
> 
> **PINCER MOVEMENTS** (Location 15244)

---

> Why had Vlasov made such an impression on Shostakovich? No, the impression must have been made later, at the war’s end, when the man got hanged for treason and cowardice.
> 
> **PINCER MOVEMENTS** (Location 15266)

---

> And now Shostakovich began to perceive some haunted and guarded quality about the American’s soul. And indeed, the man in raspberry-colored boots who dropped by the next day to drink vodka said with a wink: You see, Dmitri Dmitriyevich, he’s a homosexual. We know this irrefutably. It’s in his file.
> 
> **PINCER MOVEMENTS** (Location 15325)

---

> As seen from Sirius, Goethe’s works will be mere dust a thousand years from now, and Sixth Army an indecipherable name, incomprehensible to all.— Then he strode to the top of a railroad embankment, and fired blindly at the Russians until they shot him down.
> 
> **PINCER MOVEMENTS** (Location 15355)

---

> And this blond bacterium from America was here on a mission to transform the death which presently characterized all Europeans, and perhaps even vivified them, back into dirt. The bacterium would win.
> 
> **PINCER MOVEMENTS** (Location 15363)

---

> What are we Germans going to be now? A rabble of syphilitic raped girls and legless men!— So he pulled the trigger. That takes guts. Paulus didn’t have the courage to do it at Stalingrad.
> 
> **PINCER MOVEMENTS** (Location 15480)

---

> the goal here was to write a series of parables about famous, infamous and anonymous European moral actors at moments of decision.
> 
> **SOURCES** (Location 15634)

---

> It is unlikely that Shostakovich never got over Elena, as has been imagined in this book. There is equally no reason to suppose that Elena’s marriage with Karmen failed because she was still in love with Shostakovich.
> 
> **AN IMAGINARY LOVE TRIANGLE: SHOSTAKOVICH, KARMEN, KONSTANTINOVSKAYA** (Location 17588)

---

> When I think of Shostakovich, and when I listen to his music, I imagine a person consumed by fear and regret, a person who (like Kurt Gerstein) did what litttle he could to uphold the good— in this case, freedom of artistic creation, and the mitigation of other people’s emergencies. He became progressively more beaten down, and certainly experienced difficulty saying no— a character trait which may well have kept him alive in the Stalinist years. In spite of the fact that he joined the Party near the end, to me he is a great hero— a tragic hero, naturally.
> 
> **AN IMAGINARY LOVE TRIANGLE: SHOSTAKOVICH, KARMEN, KONSTANTINOVSKAYA** (Location 17592)

---

> Roman Karmen was not a great artist, but he was a brave, adventurous sort whom it would now be all too easy to dismiss as a Stalinist propagandist. He and Käthe Kollwitz may fairly be called fellow propagandists, although to my mind the latter was by far the former’s superior from the “aesthetic” point of view.
> 
> **AN IMAGINARY LOVE TRIANGLE: SHOSTAKOVICH, KARMEN, KONSTANTINOVSKAYA** (Location 17602)

---

> In our Soviet Union, of course, one may only be apolitical in the most enthusiastic and even militant fashion. It’s said that on one occasion Vlasov, having just denounced the brutal, hypocritical murderousness of a certain article in Pravda, was interrupted by the visit of a Party apparatchik. Quickly he began to praise the selfsame article. When the guest had gone away at last, Vlasov’s wife, standing numbly in the kitchen doorway, said to him, “Andrei, can you really live like that?”
> 
> **Acknowledgements** (Location 17764)

---

> Here we might as well insert another allegory. The metal of the day was steel. Hitler and Mussolini had their Pact of Steel, “Stalin” is a quite literally steely pseudonym;
> 
> **Acknowledgements** (Location 17769)

---

> The even more mendacious accusation that Vlasov and his cohorts were hanged with piano wire, a hook being inserted at the base of each skull, can be refuted with the simplest extract from the Program of the Communist Party of the Soviet Union: “Communist morality is the noblest and most just morality, for it expresses the interests and ideals of the whole of working mankind.”
> 
> **Acknowledgements** (Location 17790)