---
title: "Los Detectives Salvajes"
author: Roberto Bolaño
date: 2026-01-15
Rating: 9 / 10
---

### Highlights

> Ernesto San Epifanio dijo que existía literatura heterosexual, homosexual y bisexual. Las novelas, generalmente, eran heterosexuales, la poesía, en cambio, era absolutamente homosexual, los cuentos, deduzco, eran bisexuales, aunque esto no lo dijo.
> 
> **Los detectives salvajes** (Location 1290)

---

> Al final hubo amenazas y cuando se marcharon yo me reía a gritos y Rosario lloraba como una Magdalena.
> 
> **Los detectives salvajes** (Location 1855)

---

> qué lástima que pase el tiempo, ¿verdad?, qué lástima que nos muramos y que nos hagamos viejos y que las cosas buenas se vayan alejando de nosotros al galope.
> 
> **Los detectives salvajes** (Location 2900)

---

> Hay escritores cenizos, gafes, de los cuales más vale salir huyendo, no importa que creas o no en la mala suerte, no importa que seas positivista o marxista, de esa gente hay que huir como de la peste negra. Y esto lo digo con el corazón en la mano: hay que confiar en el instinto. Yo sabía que sacando el libro de ese muchacho jugaba con fuego.
> 
> **Los detectives salvajes** (Location 4968)

---

> Y les pregunté a los muchachos, les dije, muchachos, ¿qué es lo que han sacado en limpio de este poema?, les dije, muchachos, yo llevo más de cuarenta años mirándolo y nunca he entendido una chingada. Ésa es la verdad. Para qué voy a mentirles. Y ellos dijeron: es una broma, Amadeo, el poema es una broma que encubre algo muy serio.
> 
> **Los detectives salvajes** (Location 6259)

---

> El azar nos guía aunque nada hemos dejado al azar. Un escritor debe parecer un censor, nos dijeron nuestros mayores y hemos seguido esa flor de pensamiento hasta su penúltima consecuencia. Un escritor debe parecer un articulista de periódico. Un escritor debe parecer un enano y DEBE sobrevivir.
> 
> **Los detectives salvajes** (Location 8147)

---

> Disciplina y un cierto encanto dúctil, ésas son las claves para llegar a donde uno se proponga. Disciplina: escribir cada mañana no menos de seis horas. Escribir cada mañana y corregir por las tardes y leer como un poseso por las noches. Encanto, o encanto dúctil: visitar a los escritores en sus residencias o abordarlos en las presentaciones de libros y decirles a cada uno justo aquello que quiere oír. Aquello que quiere oír desesperadamente. Y tener paciencia, pues no siempre funciona. Hay cabrones que te dan una palmadita en la espalda y luego si te he visto no me acuerdo. Hay cabrones duros y crueles y mezquinos. Pero no todos son así. Es necesario tener paciencia y buscar. Los mejores son los homosexuales, pero, ojo, es necesario saber en qué momento detenerse, es necesario saber con precisión qué es lo que uno quiere, de lo contrario puedes acabar enculado de balde por cualquier viejo maricón de izquierda.
> 
> **Los detectives salvajes** (Location 8205)

---

> Sé que el secreto de la vida no está en los libros. Pero también sé que es bueno leer, en eso estábamos los dos de acuerdo, es instructivo o es un consuelo. Él leía libros, yo leía revistas como Muscle Mag o Muscle & Fitness o Bodyfitness.
> 
> **Los detectives salvajes** (Location 8707)