---
title: "Quarto de Despejo"
author: Carolina Maria de Jesus
date: 2026-02-23
Rating: 9 / 10
---

### Highlights

> Mesmo elas aborrecendo-me, eu escrevo. Sei dominar meus impulsos. Tenho apenas dois anos de grupo escolar, mas procurei formar o meu carater. A unica coisa que não existe na favela é solidariedade.
> 
> **Início** (Location 216)

---

> Os meus filhos não são sustentados com pão de igreja. Eu enfrento qualquer especie de trabalho para mantê-los. E elas, tem que mendigar e ainda apanhar. Parece tambor. A noite enquanto elas pede socorro eu tranquilamente no meu barracão ouço valsas vienenses.
> 
> **Início** (Location 221)

---

> —De que partido é aquela faixa? Li P.S.B. e respondi Partido Social Brasileiro[ 3]. Passou o Senhor Germano, ela perguntou novamente: —Senhor Germano, esta faixa é de que partido? —Do Janio[ 4]!
> 
> **Início** (Location 240)

---

> Eu, e D. Maria Puerta, uma espanhola muito boa, defendíamos o Dr. Adhemar.
> 
> **Início** (Location 246)

---

> Com os homens e as mulheres eu tenho um olhar duro e frio. O meu sorriso, as minhas palavras ternas e suaves, eu reservo para as crianças.
> 
> **Início** (Location 564)

---

> —Não, meu filho. A democracia está perdendo os seus adeptos. No nosso paiz tudo está enfraquecendo. O dinheiro é fraco. A democracia é fraca e os políticos fraquissimos. E tudo que está fraco, morre um dia.
> 
> **Início** (Location 582)

---

> ... E o pior na favela é o que as crianças presenciam. Todas crianças da favela sabem como é o corpo de uma mulher. Porque quando os casais que se embriagam brigam, a mulher, para não apanhar sai nua para a rua.
> 
> **Início** (Location 686)

---

> Ela olhava a favela, suas lamas e suas crianças paupérrimas. Foi o olhar mais triste que eu já presenciei. Talvez ela não mais tem ilusão. Entregou sua vida aos cuidados da vida.
> 
> **Início** (Location 705)

---

> Eu não gosto do Kubstchek. O homem que tem um nome esquisito que o povo sabe falar mas não sabe escrever.
> 
> **Início** (Location 1226)

---

> Como é horrível levantar de manhã e não ter nada para comer. Pensei até em suicidar. Eu suicidando-me é por deficiência de alimentação no estomago. E por infelicidade eu amanheci com fome.
> 
> **Início** (Location 1569)

---

> Achei o dia bonito e alegre. Fui catando papel.
> 
> **Início** (Location 1582)

---

> Dizem que a Princesa Margareth da Inglaterra tem desgosto de ser princesa[ 27]. São os dilemas da vida.
> 
> **Início** (Location 1631)

---

> A favela é o quarto de despejo. E as autoridades ignoram que tem o quarto de despejo.
> 
> **Início** (Location 1689)

---

> Não posso ir num espetáculo, porisso Deus envia-me estes sonhos deslumbrantes para minh’alma dolorida.
> 
> **Início** (Location 1907)

---

> ... O senhor Dario ficou horrorizado com a primitividade em que eu vivo. Ele olhava tudo com assombro. Mas ele deve aprender que a favela é o quarto de despejo de São Paulo. E que eu sou uma despejada.
> 
> **Início** (Location 2369)

---

> Eu parei de escrever o Diário porque fíquei desiludida. E por falta de tempo.
> 
> **Início** (Location 2605)

---

> Quando circulava pelas ruas o povo abordava-me para dizer que havia me visto no O Cruzeiro.
> 
> **Início** (Location 2790)

---

> Eu estou cançada e enojada da favela.
> 
> **Início** (Location 2869)

---

> Temos só um geito de nascer e muitos de morrer.
> 
> **Início** (Location 2971)