---
title: "Si Esto Es un Hombre"
author: Primo Levi
date: 2026-01-28
Rating: 9 / 10
---

### Highlights

> Pero las madres velaron para preparar con amoroso cuidado la comida para el viaje, y lavaron a los niños, e hicieron el equipaje, y al amanecer las alambradas espinosas estaban llenas de ropa interior infantil puesta a secar; y no se olvidaron de los pañales, los juguetes, las almohadas, ni de ninguna de las cien pequeñas cosas que conocen tan bien y de las que los niños tienen siempre necesidad. ¿No haríais igual vosotras? Si fuesen a mataros mañana con vuestro hijo, ¿no le daríais de comer hoy?
> 
> **PRIMO LEVI** (Location 74)

---

> En menos de diez minutos todos los que éramos hombres útiles estuvimos reunidos en un grupo. Lo que fue de los demás, de las mujeres, de los niños, de los viejos, no pudimos saberlo ni entonces ni después: la noche se los tragó, pura y simplemente.
> 
> **PRIMO LEVI** (Location 146)

---

> Desaparecieron así en un instante, a traición, nuestras mujeres, nuestros padres, nuestros hijos. Casi nadie pudo despedirse de ellos.
> 
> **PRIMO LEVI** (Location 157)

---

> ARBEIT MACHT FREI,
> 
> **En el fondo** (Location 174)

---

> nuestra lengua no tiene palabras para expresar esta ofensa, la destrucción de un hombre. En un instante, con intuición casi profética, se nos ha revelado la realidad: hemos llegado al fondo. Más bajo no puede llegarse: una condición humana más miserable no existe, y no puede imaginarse.
> 
> **En el fondo** (Location 250)

---

> Häftling: me he enterado de que soy un Häftling.
> 
> **En el fondo** (Location 263)

---

> Hemos aprendido bien pronto que los huéspedes del Lager se dividen en tres categorías: los criminales, los políticos y los judíos.
> 
> **En el fondo** (Location 355)

---

> los criminales llevan junto al número, cosido en la chaqueta, un triángulo verde; los políticos un triángulo rojo; los judíos, que son la mayoría, llevan la estrella hebraica, roja y amarilla.
> 
> **En el fondo** (Location 356)

---

> La muerte empieza por los zapatos: se han convertido, para la mayoría de nosotros en auténticos instrumentos de tortura que, después de las largas horas de marcha, ocasionan dolorosas heridas las cuales fatalmente se infectan.
> 
> **En el fondo** (Location 383)

---

> Tengo que confesarlo: después de una única semana en prisión noto que el instinto de la limpieza ha desaparecido en mí.
> 
> **LA INICIACIÓN** (Location 466)

---

> son pocos los que están allí más de dos semanas y nadie más de dos meses: dentro de estos límites tenemos que morirnos o curarnos. Quien tiende a curarse, en Ka-Be se cura; quien tiende a agravarse, de Ka-Be lo mandan a la cámara de gas.
> 
> **KA-BE** (Location 551)

---

> Heimweh se llama en alemán este dolor, es una bella palabra y quiere decir «dolor de hogar».
> 
> **KA-BE** (Location 704)

---

> Mas el hombre que sale del Ka-Be, desnudo y casi siempre insuficientemente restablecido, se siente proyectado en la oscuridad y en el vacío del espacio sideral. Los pantalones se le caen, los zapatos le hacen daño, la camisa no tiene botones. Busca un contacto humano y no encuentra más que espaldas vueltas. Es inerme y vulnerable como un recién nacido, pero a la mañana siguiente tendrá que ir a trabajar.
> 
> **NUESTRAS NOCHES** (Location 726)

---

> Con mi espalda contra la suya, me esfuerzo por conquistar una superficie razonable de jergón; ejerzo con los riñones una presión progresiva contra los suyos, luego me doy vuelta y pruebo a empujarle con las rodillas, lo cojo por los tobillos y trato de colocarlo un poco más allá de manera que no tenga sus pies pegados a la cara: pero es inútil, es mucho más pesado que yo y parece petrificado por el sueño.
> 
> **NUESTRAS NOCHES** (Location 763)

---

> Es un tormento obsceno y una vergüenza indeleble: cada dos, cada tres horas, tenemos que levantarnos para verter la gran dosis de agua que de día estamos obligados a absorber en forma de potaje que nos calma el hambre: es la misma agua que por la noche nos hincha los tobillos y las orejas e imprime a todas las fisonomías una semejanza deforme, y cuya eliminación impone a los riñones un trabajo enervante.
> 
> **NUESTRAS NOCHES** (Location 799)

---

> Nos toca arrastrarnos hasta la letrina con el cubo que da golpes contra las pantorrillas desnudas, desagradablemente caliente; está lleno mucho más allá de cualquier límite razonable y es inevitable que, con las sacudidas, algo se derrame sobre los pies, de manera que por muy repugnante que sea esta función siempre es preferible tener que ir nosotros mismos a que tenga que ir nuestro compañero de litera.
> 
> **NUESTRAS NOCHES** (Location 811)

---

> La procesión del cubo y los tropezones de los talones desnudos en la madera del suelo se transforman en otra procesión simbólica: somos nosotros, grises e idénticos, pequeños como hormigas y grandes hasta las estrellas, apretados el uno contra el otro, innumerables, ocupando toda la llanura hasta el horizonte; a veces nos fundimos en una sustancia única, una masa angustiosa en la que nos sentimos apresados y sofocados;
> 
> **NUESTRAS NOCHES** (Location 817)

---

> Son poquísimos los que esperan durmiendo el Wstawa'c: es un momento de dolor demasiado agudo para que el sueño más duro no se rompa al sentirlo acercarse. El guardia nocturno lo sabe y por eso es por lo que no lo pronuncia con tono de orden, sino con una voz llana y baja, como quien sabe que el anuncio va a encontrar atentos todos los oídos y va a ser escuchado y obedecido.
> 
> **NUESTRAS NOCHES** (Location 830)

---

> Tener un compañero de cama alto de estatura es una desgracia, significa perder horas de sueño; y precisamente a mí me tocan siempre compañeros altos porque yo soy bajo y dos altos juntos no pueden dormir.
> 
> **EL TRABAJO** (Location 849)

---

> los que hacen mal la cama, los schlechte Bettenbauer, son castigados rigurosamente),
> 
> **EL TRABAJO** (Location 853)

---

> La convicción de que la vida tiene una finalidad está grabada en todas las fibras del hombre, es una propiedad de la sustancia humana.
> 
> **UN DÍA BUENO** (Location 939)

---

> Aquí y hoy, nuestra finalidad es llegar a la primavera.
> 
> **UN DÍA BUENO** (Location 941)

---

> En cambio, para nosotros, el Lager no es un castigo; para nosotros no se prevé un término, y el Lager no es otra cosa que el género de existencia a nosotros asignado, sin límites de tiempo, en el seno del organismo social germánico.
> 
> **MÁS ACÁ DEL BIEN Y DEL MAL** (Location 1133)

---

> Además, los enfermeros obtienen grandes ganancias del tráfico de cucharas. El Lager no provee de cuchara a los recién llegados, aunque el potaje semilíquido no pueda ser consumido de otra manera.
> 
> **MÁS ACÁ DEL BIEN Y DEL MAL** (Location 1170)

---

> A los curados, en el acto de darlos de alta y antes de vestirlos, la cuchara les es confiscada por los enfermeros, que la envían en venta a la Bolsa.
> 
> **MÁS ACÁ DEL BIEN Y DEL MAL** (Location 1175)

---

> En conclusión, el hurto en la Buna, castigado por la Dirección Civil, es autorizado y estimulado por los SS; el hurto en el campo, reprimido severamente por los SS, es considerado por los civiles una operación normal de cambio; el hurto entre Häftlinge es generalmente castigado pero el castigo afecta con la misma gravedad al ladrón y al robado.
> 
> **MÁS ACÁ DEL BIEN Y DEL MAL** (Location 1186)

---

> En efecto, estoy persuadido de que ninguna experiencia humana carece de sentido ni es indigna de análisis, y de que, por el contrario, hay valores fundamentales, aunque no siempre positivos, que se pueden deducir de este mundo particular del que estamos hablando.
> 
> **Los hundidos y los salvados** (Location 1195)

---

> es cuanto de más riguroso habría podido organizar un estudioso para establecer qué es esencial y qué es accesorio en el comportamiento del animalhombre frente a la lucha por la vida.
> 
> **Los hundidos y los salvados** (Location 1200)

---

> No creo en la más obvia y fácil deducción: que el hombre es fundamentalmente brutal, egoísta y estúpido tal y como se comporta cuando toda superestructura civil es eliminada, y que el Häftling no es más que el hombre sin inhibiciones.
> 
> **Los hundidos y los salvados** (Location 1201)

---

> frente a la necesidad y el malestar físico oprimente, muchas costumbres e instintos sociales son reducidos al silencio.
> 
> **Los hundidos y los salvados** (Location 1204)

---

> queda claro que hay entre los hombres dos categorías particularmente bien distintas: los salvados y los hundidos.
> 
> **Los hundidos y los salvados** (Location 1205)

---

> Esta división es mucho menos evidente en la vida común; en ésta no sucede con frecuencia que un hombre se pierda, porque normalmente el hombre no está solo y, en sus altibajos, está unido al destino de sus vecinos;
> 
> **Los hundidos y los salvados** (Location 1208)

---

> es excepcional que alguien crezca en poder sin límites o descienda continuamente de derrota en derrota hasta la ruina.
> 
> **Los hundidos y los salvados** (Location 1209)

---

> remisión porque cada uno está desesperadamente, ferozmente solo.
> 
> **Los hundidos y los salvados** (Location 1215)

---

> En la historia y en la vida, parece a veces discernirse una ley feroz que reza: «a quien tiene, le será dado; a quien no tiene, le será quitado». En el Lager, donde el hombre está solo y la lucha por la vida se reduce a su mecanismo primordial, esta ley inicua está abiertamente en vigor, es reconocida por todos.
> 
> **Los hundidos y los salvados** (Location 1220)

---

> Pero a los «musulmanes», a los hombres que se desmoronan, no vale la pena dirigirles la palabra, porque ya se sabe que se lamentarán y contarán lo que comían en su casa.
> 
> **Los hundidos y los salvados** (Location 1224)

---

> Su vida es breve pero su número es desmesurado; son ellos, los Muselmänner, los hundidos, los cimientos del campo; ellos, la masa anónima, continuamente renovada y siempre idéntica, de no-hombres que marchan y trabajan en silencio, apagada en ellos la llama divina, demasiado vacíos ya para sufrir verdaderamente. Se duda en llamarlos vivos: se duda en llamar muerte a su muerte, ante la que no temen porque están demasiado cansados para comprenderla.
> 
> **Los hundidos y los salvados** (Location 1245)

---

> Si los hundidos no tienen historia, y una sola y ancha es la vía de la perdición, las vías de la salvación son, en cambio, muchas, ásperas e impensadas.
> 
> **Los hundidos y los salvados** (Location 1251)

---

> La vía maestra, como ya he dicho, es la Prominenz. Prominenten se llaman los funcionarios del campo a partir del director-Häftling (Lagerältester), los Kapos, los cocineros, los enfermeros, los guardias nocturnos, hasta los barrenderos de las barracas y los Scheissminister y Bademeister (encargados de letrinas y duchas).
> 
> **Los hundidos y los salvados** (Location 1252)

---

> Los prominentes judíos constituyen un triste y notable fenómeno humano. Convergen en ellos los sufrimientos presentes, pasados y atávicos, y las tradiciones y la educación de hostilidad hacia el extranjero, para convertirlos en monstruos de insociabilidad y de insensibilidad.
> 
> **Los hundidos y los salvados** (Location 1256)

---

> Son el típico producto de la estructura del Lager alemán: ofrézcase a algunos individuos en estado de esclavitud una posición privilegiada, cierta comodidad y una buena probabilidad de sobrevivir, exigiéndoles a cambio la traición a la solidaridad natural con sus compañeros, y seguro que habrá quien acepte.
> 
> **Los hundidos y los salvados** (Location 1258)

---

> su capacidad de odiar, que se mantenía viva en dirección a sus opresores, se volverá, irracionalmente, contra los oprimidos,
> 
> **Los hundidos y los salvados** (Location 1263)

---

> situación análoga de rivalidad y de odio entre los sometidos;
> 
> **Los hundidos y los salvados** (Location 1268)

---

> Muchísimos han sido los caminos imaginados y seguidos por nosotros para no morir: tantos como son los caracteres humanos. Todos suponen una lucha extenuadora de cada uno contra todos, y muchos, una suma no pequeña de aberraciones y de compromisos. El sobrevivir sin haber renunciado a nada del mundo moral propio, a no ser debido a poderosas y directas intervenciones de la fortuna, no ha sido concedido más que a poquísimos individuos superiores, de la madera de los mártires y de los santos.
> 
> **Los hundidos y los salvados** (Location 1282)

---

> De todos los coloquios con Henri, incluso de los más cordiales, he salido siempre con una ligera sensación de derrota; con la sospecha confusa de haber sido yo también, de alguna manera inadvertida, no un hombre frente a él, sino un instrumento en sus manos.
> 
> **Los hundidos y los salvados** (Location 1413)

---

> –Wo sind Sie Geboren? -me trata de Sie, de usted: el Doktor Ingenieur Pannwitz no tiene sentido del humor.
> 
> **EXAMEN DE QUÍMICA** (Location 1499)

---

> Las noticias, sabidas en el tajo, del desembarco aliado en Normandía, de la ofensiva rusa y del frustrado atentado contra Hitler, habían levantado oleadas de esperanzas violentas pero efímeras.
> 
> **LOS ACONTECIMIENTOS DEL VERANO** (Location 1635)

---

> En realidad, para los civiles somos los intocables. Los civiles, más o menos explícitamente y con todos los matices que hay entre el desprecio y la conmiseración, piensan que por haber sido condenados a esta vida nuestra, por estar reducidos a esta condición nuestra, debemos estar manchados por alguna misteriosa y gravísima culpa.
> 
> **LOS ACONTECIMIENTOS DEL VERANO** (Location 1703)

---

> Los personajes de estas páginas no son hombres. Su humanidad está sepultada, o ellos mismos la han sepultado, bajo la ofensa súbita o infligida a los demás.
> 
> **LOS ACONTECIMIENTOS DEL VERANO** (Location 1718)

---

> en el curso de estos meses, de octubre a abril, de cada diez de nosotros, morirán siete. Quien no se muera sufrirá minuto por minuto, día por día, durante todos los días:
> 
> **OCTUBRE DE 1944** (Location 1728)

---

> Del mismo modo que nuestra hambre no es la sensación de quien ha perdido una comida, así nuestro modo de tener frío exigiría un nombre particular. Decimos «hambre», decimos «cansancio», «miedo» y «dolor», decimos «invierno», y son otras cosas.
> 
> **OCTUBRE DE 1944** (Location 1734)

---

> En Birkenau, la chimenea del Crematorio humea desde hace diez días. Hay que hacerle sitio a una enorme expedición que va a llegar del gueto de Posen. Los jóvenes dicen a los jóvenes que serán elegidos todos los viejos. Los sanos dicen a los sanos que sólo serán elegidos los enfermos. Serán excluidos los especialistas. Serán excluidos los judíos alemanes. Serán excluidos los Números Bajos. Serás elegido tú. Seré excluido yo.
> 
> **OCTUBRE DE 1944** (Location 1781)

---

> En cualquier momento del día en que prestemos oído a las voces de nuestros cuerpos, en que interroguemos a nuestros miembros, la respuesta es la misma: no nos bastarán las fuerzas. Todo, en torno a nosotros, habla de destrucción y de fin.
> 
> **DIE DREI LEUTE VOM LABOR** (Location 1921)

---

> El Kapo nos escudriña con una risa enconada. Un belga, un rumano y un italiano: tres Franzosen, en resumen. ¿Es posible que tuviesen que ser tres Franzosen los elegidos para el paraíso del laboratorio?
> 
> **DIE DREI LEUTE VOM LABOR** (Location 1944)

---

> En estas condiciones, personas menos expertas que nosotros en las cosas del Lager también podrían ser tentadas por la esperanza de sobrevivir y por el pensamiento de la libertad. Nosotros no, nosotros sabemos cómo funcionan estas cosas; todo esto es un regalo del destino, que como tal es gozado lo más intensamente posible, y de prisa: pero del mañana no hay certeza.
> 
> **DIE DREI LEUTE VOM LABOR** (Location 1977)

---

> El mes pasado, uno de los crematorios de Birkenau ha sido hecho saltar por los aires. Ninguno de nosotros sabe (y tal vez no lo sepa nunca) cómo ha sido exactamente realizada la empresa: se habla del Sonderkommando del Kommando Especial adscrito a las cámaras de gas y a los hornos, el cual viene siendo periódicamente exterminado, y que es mantenido escrupulosamente segregado del resto del campo. Lo que es cierto es que en Birkenau un centenar de hombres, de esclavos inermes y débiles como nosotros, han sacado de sí mismos la fuerza necesaria para actuar, para madurar los frutos de su odio.
> 
> **EL ÚLTIMO** (Location 2100)

---

> Gracias a mi ya larga experiencia de las cosas del campo, había conseguido llevarme mis pertenencias personales; un cinto de cables eléctricos trenzados; la cuchara-cuchillo; una aguja con tres hebras de hilo; cinco botones y, en fin, dieciocho piedras de eslabón que había robado en el Laboratorio. De cada una podían sacarse, afinándola pacientemente con el cuchillo, tres piedrecitas más pequeñas del tamaño adecuado para un encendedor normal de cigarrillos. Habían sido tasadas en seis o siete raciones de pan.
> 
> **HISTORIA DE DIEZ DÍAS** (Location 2135)

---

> Todos los sanos (quitado algún bien aconsejado que en el último instante se desnudó y se echó en cualquier litera de la enfermería) partieron duran te la noche del 18 de enero de 1945. Debían de ser cerca de veinte mil, procedentes de varios campos. En su casi totalidad, desaparecieron durante la marcha de evacuación: Alberto entre ellos. Quizás alguien escriba un día su historia.
> 
> **HISTORIA DE DIEZ DÍAS** (Location 2199)

---

> Hoy pienso que, sólo por el hecho de haber existido un Auschwitz, nadie debería hablar en nuestros días de Providencia: pero lo cierto es que, en aquel momento, el recuerdo de los salvamentos bíblicos en las adversidades extremas pasó como un viento por todos los ánimos.
> 
> **HISTORIA DE DIEZ DÍAS** (Location 2235)

---

> fue entonces cuando Towarowski (un franco-polaco de veintitrés años, con tifus) propuso a los otros enfermos que cada uno de ellos nos diese una rebanada de pan a los tres que trabajábamos, y su proposición fue aceptada. Sólo un día antes un acontecimiento semejante habría sido inconcebible. La ley del Lager decía: «Come tu pan y, si puedes, el de tu vecino», y no dejaba lugar a la gratitud. Quería decir que el Lager había muerto.
> 
> **HISTORIA DE DIEZ DÍAS** (Location 2266)

---

> Creo que se podría fijar en aquel momento el principio del proceso mediante el cual, nosotros, los que no estábamos muertos, de Häftlinge empezamos lentamente a volver a ser hombres.
> 
> **HISTORIA DE DIEZ DÍAS** (Location 2270)

---

> es valiente quien afronta un peligro grave con buen ánimo; Charles y yo fuimos valientes aquella mañana. Extendimos nuestras exploraciones al campo de los SS, inmediatamente fuera de la alambrada eléctrica.
> 
> **HISTORIA DE DIEZ DÍAS** (Location 2353)

---

> Encontramos en las mesas platos medio llenos de menestra ya congelada, que devoramos con gran satisfacción; jarras todavía llenas de cerveza transformada en un hielo amarillento, un tablero con una partida empezada. En los cuartos, gran cantidad de cosas preciosas.
> 
> **HISTORIA DE DIEZ DÍAS** (Location 2355)

---

> Algunos SS, probablemente dispersos, pero armados, penetraron en el campo abandonado. Se encontraron con que dieciocho franceses se habían instalado en el refectorio de la SS-Waffe. Allí los mataron a todos metódicamente, de un tiro en la nuca, y alinearon después los cuerpos retorcidos en la nieve del camino; hecho lo cual, se fueron. Los dieciocho cadáveres se quedaron expuestos hasta la llegada de los rusos; nadie tuvo fuerzas para darles sepultura.
> 
> **HISTORIA DE DIEZ DÍAS** (Location 2360)

---

> El resultado fue que desde entonces, a través de la delgada pared, toda la sección de los diarreicos me llamó noche y día por mi nombre, con las inflexiones de todas las lenguas de Europa, acompañado de súplicas incomprensibles, sin que yo pudiese ponerle remedio. Me sentía al borde del llanto, los habría maldecido.
> 
> **HISTORIA DE DIEZ DÍAS** (Location 2373)

---

> Yacíamos en un mundo de muertos y de larvas. La última huella de civismo había desaparecido alrededor de nosotros y dentro de nosotros. La obra de bestialización de los alemanes triunfantes había sido perfeccionada por los alemanes derrotados.
> 
> **HISTORIA DE DIEZ DÍAS** (Location 2458)

---

> no es hombre quien, perdido todo recato, comparte la cama con un cadáver. Quien ha esperado que su vecino terminase de morir para quitarle un cuarto de pan, está, aunque sin culpa suya, más lejos del hombre pensante que el más zafio pigmeo y el sádico más atroz.
> 
> **HISTORIA DE DIEZ DÍAS** (Location 2460)

---

> Parte de nuestra existencia reside en las almas de quien se nos aproxima: he aquí por qué es no humana la experiencia de quien ha vivido días en que el hombre ha sido una cosa para el hombre.
> 
> **HISTORIA DE DIEZ DÍAS** (Location 2462)

---

> De los once de la Infektionsabteilung fue Sómogyi el único que murió en los diez días. Sertelet, Cagnolati, Towarowski, Lakmaker y Dorget (de este último no he hablado hasta ahora; era un industrial francés que, después de operado de peritonitis, se había enfermado de difteria nasal), murieron unas semanas más tarde en la enfermería rusa provisional de Auschwitz. En abril me encontré en Katowice con Schenck y Alcalai, que estaban con buena salud. Arthur se reunió felizmente con su familia, y Charles ha vuelto a su profesión de maestro; nos hemos escrito largas cartas y espero volverlo a ver algún día.
> 
> **HISTORIA DE DIEZ DÍAS** (Location 2477)

---

> pensé que mi palabra resultaría tanto más creíble cuanto más objetiva y menos apasionada fuese; sólo así el testigo en un juicio cumple su función, que es la de preparar el terreno para el juez. Los jueces sois vosotros.
> 
> **APÉNDICE DE 1976** (Location 2520)

---

> un enemigo que se rectifica ha dejado de ser un enemigo.
> 
> **APÉNDICE DE 1976** (Location 2525)

---

> y sin embargo, no había un alemán que no supiese de la existencia de los campos, o que los considerase sanatorios.
> 
> **APÉNDICE DE 1976** (Location 2568)

---

> Todos los alemanes eran testigos de la multiforme barbarie antisemita: millones de ellos habían presenciado, con indiferencia o con curiosidad, con desdén o quizás con maligna alegría, el incendio de las sinagogas o la humillación de los judíos y judías obligados a arrodillarse en el fango de la calle.
> 
> **APÉNDICE DE 1976** (Location 2570)

---

> En la Alemania de Hitler se había difundido una singular forma de urbanidad: quien sabía no hablaba, quien no sabía no preguntaba, quien preguntaba no obtenía respuesta.
> 
> **APÉNDICE DE 1976** (Location 2591)

---

> El concepto de evasión como obligación moral está continuamente reafirmado en la literatura romántica (¿ os acordáis del conde de Montecristo?),
> 
> **APÉNDICE DE 1976** (Location 2602)

---

> los alemanes habían perfeccionado, en esta empresa de muerte colectiva, una estrategia diabólicamente astuta y versátil. En la mayor parte de los casos, los recién llegados no sabían qué se les tenía preparado: se los recibía con fría eficiencia pero sin brutalidad, se los invitaba a desnudarse «para la ducha», a veces se les entregaba una toalla y jabón, y se les prometía un café para después del baño. Las cámaras de gas, en efecto, estaban camufladas como salas de duchas, con tuberías, grifos, vestuarios, perchas, bancos, etcétera.
> 
> **APÉNDICE DE 1976** (Location 2640)

---

> el imperio concentracionario de Auschwitz no estaba formado por un solo Lager, sino por unos cuarenta: el campo de Auschwitz propiamente dicho se alzaba en la periferia de la pequeña ciudad del mismo nombre (Oswiecim, en polaco), tenía capacidad para unos veinte mil prisioneros y, por así decir, era la capital administrativa del conjunto; además estaba el Lager (o más exactamente el grupo de Lager: de tres a cinco, según la época) de Birkenau, que llegó a contener a sesenta mil prisioneros, de los cuales cuarenta mil eran mujeres y en los que funcionaban las cámaras de gas y los hornos crematorios; y finalmente un número continuamente variable de campos de trabajo, alejados de la «capital» hasta cientos de kilómetros: mi campo, llamado Monowitz, era el más grande de éstos y había llegado a tener doce mil prisioneros. Estaba a unos siete kilómetros al este de Auschwitz. Toda esa zona se encuentra hoy en territorio polaco.
> 
> **APÉNDICE DE 1976** (Location 2659)

---

> prefiero la parte del testigo a la del juez:
> 
> **APÉNDICE DE 1976** (Location 2692)

---

> A partir de más o menos 1941, se volvieron gigantescas máquinas de muerte: las cámaras de gas y los crematorios habían sido deliberadamente proyectados para destruir vidas y cuerpos humanos en una escala de millones;
> 
> **APÉNDICE DE 1976** (Location 2701)

---

> En esta lúgubre comparación entre dos modelos de infierno, hay que agregar que en los Lager alemanes, en general, se entraba para no salir:
> 
> **APÉNDICE DE 1976** (Location 2706)

---

> en la Unión Soviética, en el período más duro, la mortandad era de un 30 por ciento de la totalidad de ingresados, un porcentaje sin duda intolerablemente alto; pero en los Lager alemanes la mortandad era del 90-98 por ciento.
> 
> **APÉNDICE DE 1976** (Location 2716)

---

> Hitler, pintor fallido, arquitecto fracasado, vuelca sobre los judíos su resentimiento y su envidia de frustrado.
> 
> **APÉNDICE DE 1976** (Location 2820)

---

> si no hubiera vivido la temporada de Auschwitz, es probable que nunca hubiera escrito nada.
> 
> **APÉNDICE DE 1976** (Location 2908)