---
title: "Streams of Gold, Rivers of Blood"
author: Anthony Kaldellis
date: 2026-02-20
Rating: 9 / 10
---

### Highlights

> Our period, however, was exceptional in two other ways. It began with a burst of violence aimed at the empire’s neighbors,
> 
> **Preface** (Location 201)

---

> The tide would turn during the eleventh century. Three new enemies— the Normans, Pechenegs, and Seljuk Turks— would fall upon the empire and strip it of many of its conquests.
> 
> **Preface** (Location 206)

---

> The years between 955, when the general Nikephoros Phokas was placed in command of the army and launched a strategy of aggressive conquest, and 1081, when the general Alexios Komnenos seized the throne amidst imperial collapse and political chaos, were a pivotal period in Byzantine history.
> 
> **Preface** (Location 211)

---

> According to this model, the imperial “state” ruled by the Macedonian dynasty was challenged by the landowning “magnates” of Asia Minor, who were powerful “families” that were eating up peasant lands and angling to run the empire in a way that benefited their own class. As far as I can tell, this picture is fictitious. It leads to tendentious interpretations of events and individuals that serve a modern agenda, specifically to show how and when Byzantium became “feudalized.”
> 
> **Preface** (Location 266)

---

> The gravest domestic threat to the emperors at the beginning of our period was the armies of Asia Minor and their officers, such as Phokas, whereas toward the end the greatest threat came from the armies and officers of Macedonia, such as Bryennios.
> 
> **Preface** (Location 282)

---

> It had a proper name, Romanía, which had been in use since the fourth century.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 319)

---

> The Byzantines also ranked themselves and their ruler as superior in standing, prestige, culture, antiquity, and world-historical importance (even on a theological level), a claim that was often accepted by their neighbors, especially smaller Christian powers. The Byzantine basileus was not like any other king.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 321)

---

> Byzantium was not much of an empire by the most common modern definition of that word, namely rule by one ethnic or religious group (a minority of the population) over a multiethnic majority of subjects.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 323)

---

> Overall, Romanía looked more like a Roman kingdom that had minorities than a true multiethnic empire,
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 329)

---

> By ancient or medieval standards, and for a realm of its size, Byzantium was culturally homogeneous, socially integrated, and unified by exclusive and sovereign state institutions. It is important to stress how different it was in this respect from western medieval kingdoms.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 337)

---

> The Roman people, moreover, were not divided by law or custom into castes or fixed classes; nor was nobility claimed as a right of blood by a handful of families.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 346)

---

> It was an aristocracy of service, not blood, despite the occasional rhetoric, and it “organized power through title and office rather than through family.”
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 354)

---

> But in practice, the emperors were highly vulnerable and insecure for reasons relating to the nature of the monarchy since its creation by Augustus and stemming in part from its elective ideology; there was no hereditary or absolute right to power.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 361)

---

> there were two main political arenas in Romanía: Constantinople and the frontier armies.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 377)

---

> Constantinople was a magnet for the most talented and well-connected, but also the most destitute, for it was there that imperial and Church philanthropy was most bountiful. It was a place of opportunity. The founder of the reigning Macedonian dynasty, Basileios I (867– 886), was a peasant who went to the City to escape poverty, and maneuvered his way to the throne.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 401)

---

> skillful use of the mechanisms of imperial governance. Roughly speaking, these were of three types: permanent institutions that operated in the background regardless of the degree of interest an emperor showed in them; the cultivation of political support through the system of court titles and offices, which shaped the upper echelons of imperial society; and personnel decisions that created a regime around the emperor.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 407)

---

> The three permanent institutions that were most important in terms of their administrative apparatus and impact on the rest of society were the army, the Church, and the tax system.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 410)

---

> The Church also had a large bureaucracy, for managing its extensive properties and personnel and for resolving the legal questions that arose from the application of canon law to society.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 417)

---

> The emperor generally dominated the Church on the mundane level of administration. He could depose or appoint patriarchs of Constantinople, who, in our period of interest, were mostly administrators serving at the emperor’s pleasure.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 421)

---

> Lobbying at the court by all classes of society mostly aimed at obtaining tax exemptions.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 432)

---

> Offices were salaried positions in the administration or army that required the performance of specific functions (e.g., a strategos or general; protasekretis or head of the secretariat). Titles, by contrast, were salaried honorifics that fixed one’s status in the court hierarchy, but had no functions and were for life.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 435)

---

> Byzantine emperors did not traditionally rule through their families.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 467)

---

> Emperors also preferred to give extraordinary powers to men who could not take the throne, especially eunuch administrators.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 479)

---

> The Byzantine emperors excelled at projecting soft power. They allowed foreign rulers to compete for the privilege of marrying into the Byzantine elite;
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 487)

---

> To receive the envoys of Tarsos (in Cilicia) in 946, the reception hall and its surroundings were decked out with silk hangings, laurel wreaths and flowers, and silver chains, and the hall was covered with Persian carpets and sprinkled with rose water. The entire court, thousands of people, stood in a prescribed order in full ceremonial regalia, acclamations were chanted to the accompaniment of organs, and the emperor sat on a throne that was imagined to be a replica of that of the Old Testament king Solomon. It was flanked by mechanical moving animals, including roaring lions and warbling birds, and could be lifted up into the air while the envoys were prostrate on the floor.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 490)

---

> The tagmata consisted of full-time soldiers and contained a higher ratio of elite cavalry.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 519)

---

> starting in 955, a strategy of conquest was put into motion against the most dangerous enemies in the southeast, the Cilician cities (such as Tarsos) and the Hamdanid emirate of Aleppo under Sayf al-Dawla. The exponents of this brutal new phase of war were Nikephoros Phokas and Ioannes Tzimiskes.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 540)

---

> Much attention has been paid recently to the question of whether the Byzantines had a concept of Holy War. The question is somewhat distracting, as it requires us (again) to view Byzantium through a western prism, one that is itself derived from a particular (and problematic) view of the Crusades.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 558)

---

> The military history of this period had a different trajectory from the economic. On the military side, the empire expanded dramatically after 955 and quickly lost ground between 1064 and 1078. But the period overall witnessed economic and demographic growth.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 571)

---

> In the first half of the twentieth century, prominent Byzantinists sought to normalize the empire’s history within its broader medieval context by finding the point when it became “feudalized” and thereby joined the mainstream of western history by moving from a bureaucratic-Roman statist mode of existence to a proper medieval one.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 578)

---

> The feudalization paradigm becomes especially problematic the closer it is brought to bear on the events that it aims to explain. Those events are better explained within the known features of the Byzantine political scene, where potential rivals financially maintained by the court were always looking to seize power within a stable system, rather than as symptoms of far-reaching socioeconomic changes.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 595)

---

> The emperors were threatened not by landowners but by army officers.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 600)

---

> there is no evidence that they were dangerous because of their property— in other words, that they were so rich that they could challenge the imperial state by means of personal resources, something that was possible in the West.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 601)

---

> they were dangerous because they could subvert the loyalty of the armies through the military prestige that they had acquired through service.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 602)

---

> To seize power, they had to act subversively from within the imperial system, not leverage it from the outside.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 608)

---

> This elite was marked by high turnover and had no hereditary right to office or titles, and no legal authority over persons and territories except that which came from office.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 620)

---

> “aristocracy” better describes the rhetoric used by some of these people while they held power. But taking it at face value as a socioeconomic category, we risk turning the political ambitions of generals and courtiers into a narrative of class conflict against “the state” that led to feudalization— a fiction.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 626)

---

> Nikephoros Phokas followed the same policies as Basil II, the enemy of the Phokades.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 631)

---

> In the famine of 927– 928, some small landowners and members of village communes (taxed as units by the state) were compelled to sell their land cheaply to owners of larger estates (which were taxed outside the commune system), including to monasteries and the churches.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 637)

---

> The nature of the powerful must also be considered. They were not some private interests newly created by inscrutable and unstoppable economic forces operating “out there” in the provinces but, as defined in the laws themselves, state officials, title holders, high-ranking churchmen, and rich monasteries. 29 In other words, the emperors were facing a socioeconomic problem that the imperial order itself had created and was maintaining, an old story.
> 
> **Introduction: The Byzantine Empire in the Tenth Century** (Location 660)

---

> In the tenth century, Bulgaria was one of the most important Christian states in Europe. The pagan Bulgars had crossed the Danube in 680, taken over the Roman province of Moesia, and gradually expanded their control over the central Balkans. The Romans never forgot that the Bulgars had occupied Roman territory.
> 
> **Part I   Conquest and Consolidation** (Location 1440)

---

> The Bulgar ruling class assimilated to the predominantly Slavic-speaking subject population, a process that accelerated with conversion to Christianity in the ninth century.
> 
> **Part I   Conquest and Consolidation** (Location 1444)

---

> The most powerful ruler of Bulgaria, Simeon (893– 927), raised in Constantinople as a child, used force to secure recognition of his status as basileus or tsar, i.e., a peer of the Roman emperor, and a patriarch for his capital Preslav.
> 
> **Part I   Conquest and Consolidation** (Location 1446)

---

> After the end of the Roman empire in the West, it was the Franks who created a new imperial framework there, unifying the north and pushing farther into central Europe than the Romans ever had.
> 
> **Part I   Conquest and Consolidation** (Location 1491)

---

> It was inevitable that a Frank would one day be proclaimed “emperor” in Rome, even if no one in the West knew what that meant, not even Charlemagne himself.
> 
> **Part I   Conquest and Consolidation** (Location 1499)

---

> However, in the western empire that he created “Roman” corresponded to no identity— other than the people of the city of Rome— and there were no conventions governing its use. Claims to “empire” petered out in the late ninth century along with the Carolingian dynasty itself.
> 
> **Part I   Conquest and Consolidation** (Location 1500)

---

> In later centuries, the union of crowns and titles that Otto had effected was regarded as the foundation of the Holy Roman Empire.
> 
> **Part I   Conquest and Consolidation** (Location 1507)

---

> After the eleventh century their realm was called imperium Romanum, as in ancient Rome.
> 
> **Part I   Conquest and Consolidation** (Location 1510)

---

> In Romanía, the equivalent titles and concepts had a different valence, making the two imperial ideologies incommensurate. There actually was a Roman people in the east, which had a strong sense of its Roman identity and continuity from ancient Rome.
> 
> **Part I   Conquest and Consolidation** (Location 1516)

---

> eastern Romans did not care much if a foreign ruler wanted to be called a basileus— whether that was taken as king or emperor— but they considered it an aggressive move if his title claimed sovereignty over “the Romans,” because that referred to them.
> 
> **Part I   Conquest and Consolidation** (Location 1519)

---

> When westerners wanted to annoy the Byzantines they would call them “Greeks” and assert that they had lost their claim to the Roman name by forgetting Latin or fostering heresies.
> 
> **Part I   Conquest and Consolidation** (Location 1521)

---

> Louis II was in conflict with Basileios I precisely over southern Italy, and in his letter he styled himself imperator Romanorum Augustus and called Basileios imperator Novae Romae, explaining to him that he was a Greek with no understanding of Roman tradition.
> 
> **Part I   Conquest and Consolidation** (Location 1523)

---

> The Reich and Romanía were fundamentally different entities.
> 
> **Part I   Conquest and Consolidation** (Location 1528)

---

> The murder of Nikephoros Phokas, on the night of December 10– 11, 969, as he slept in his own palace, surrounded by his newly finished walls, is one of the most infamous events in Byzantine history. The site of the deed was remembered as “Phokas’ chamber” for centuries thereafter, and a lookout was placed on the palace walls to prevent the same from happening again;
> 
> **Part I   Conquest and Consolidation** (Location 1634)

---

> There can be no doubt about the chief plotter. Ioannes Tzimiskes, the emperor’s nephew, was prominent in Nikephoros’ rise to power and the conquest of Cilicia.
> 
> **Part I   Conquest and Consolidation** (Location 1639)

---

> From the scene of the crime, Tzimiskes went to the throne room of the Chrysotriklinos and donned imperial regalia. Nikephoros’ head in a window neutralized the bodyguard corps.
> 
> **Part I   Conquest and Consolidation** (Location 1668)

---

> It is not clear why Tzimiskes banished Theophano. If we believe the worst that our sources say about her, she was a lower-class seductress and poisoner of emperors. I am inclined to believe none of this, not even her alleged affair with Tzimiskes before the murder, which was probably just a palace coup facilitated by the parakoimomenos.
> 
> **Part I   Conquest and Consolidation** (Location 1702)

---

> A later vernacular poem satirized the ambitions of Theophano—“ she wanted the cake” but the other woman (Theodora) ate it— while “the men with shriveled cocks and gaping assholes” (i.e., the eunuchs Polyeuktos and Basileios) paraded the former empress on a mule.
> 
> **Part I   Conquest and Consolidation** (Location 1707)

---

> Tzimiskes is remembered as a bold general who was successful on the field of battle, yet his moves in 969– 970 reveal a consummate politician.
> 
> **Part I   Conquest and Consolidation** (Location 1742)

---

> As an emerging culture, Kievan Rus’ was unlike anything on the Byzantine horizon.
> 
> **Part I   Conquest and Consolidation** (Location 1750)

---

> These were basically trading settlements founded along the major rivers north of the Black Sea by Scandinavians who raided for plunder as Vikings while also expanding trade routes. Over time they assimilated into the culture of their predominantly Slavic-speaking subjects.
> 
> **Part I   Conquest and Consolidation** (Location 1752)

---

> in the course of three months Tzimiskes had added more territory to the empire in a single swoop than any emperor since Justinian. For the first time since the seventh century the empire extended to the Danube.
> 
> **Part I   Conquest and Consolidation** (Location 1850)

---

> The patriarchate of Bulgaria was abolished (at least in Byzantine eyes) and replaced by a metropolitan bishopric subordinate to Constantinople.
> 
> **Part I   Conquest and Consolidation** (Location 1853)

---

> The roots of the Fatimid movement and state lay in the sectarian divisions of Islam. Their leadership represented a branch of the Ismaili branch of the Shia. The Shia believe that Muhammad’s son-in-law Ali was the heir of the Prophet and also the first Imam, that is, a religious leader possessing special insight into God’s message. In effect, they did not accept the legitimacy of the Umayyad and Abbasid caliphs.
> 
> **Part I   Conquest and Consolidation** (Location 1887)

---

> Tzimiskes’ Grand Tour, which involved almost no actual battles, revealed how weak the empire’s neighbors were to the southeast, but also how unlikely it was that the Romans could conquer and annex additional lands in this direction.
> 
> **Part I   Conquest and Consolidation** (Location 1960)

---

> We know that he was a good general. It is likely that he was a good emperor as well.
> 
> **Part I   Conquest and Consolidation** (Location 2003)

---

> As a modern historian has observed, “what is important is that Samuil called his state Bulgarian; furthermore, Byzantine sources called it Bulgarian also and treat Samuil as a ruler continuing the former Bulgarian state.” 3 Roman sources claim that the Kometopouloi “rebelled” after the death of Tzimiskes in 976, which was what Romans called any action that harmed imperial interests. In reality, their rise must have entailed a complex power struggle in Bulgaria that is invisible to us.
> 
> **Part I   Conquest and Consolidation** (Location 2031)

---

> theme until they were granted an amnesty in 980.20 Most civil wars in Byzantium ended quickly, in about a year or less, and decisively, one way or the other. They were focused around individuals, never ideologies, and most Romans quickly decided which side they would support. The first rebellion of Skleros, which lasted for more than three years, was among the longest.
> 
> **Part I   Conquest and Consolidation** (Location 2128)

---

> Basil was making his own decisions because a domestic “coup” had meanwhile shaken up the imperial court. Basil had ended the unofficial “reign” of his great-uncle Lakapenos, and the position of Phokas was also compromised: removed from the position of domestikos, which he had held for almost ten years, he was made doux of the East with authority over Antioch, after Melissenos had completed his mission. 46 This reshuffling of power led to another round of civil war.
> 
> **Part I   Conquest and Consolidation** (Location 2281)

---

> stand-off lacked experienced brokers like Lakapenos. This could not last for long. Basil correctly understood that the odds would tilt in his favor if he acquired military credentials of his own, thereby reassuring his subjects that Phokas’ military leadership was not necessary. He wisely stayed away from the eastern front, which was Phokas’ playing field. So he made the decision to strike against the Bulgarians, in the west. It made good sense, but the result would be disaster that plunged the empire into civil war and emboldened the new Bulgarian state that would trouble the empire for another thirty years.
> 
> **Part I   Conquest and Consolidation** (Location 2306)

---

> Rushing off, he was ambushed by Samuil in the pass of Trajan’s Gate on August 16 (this was by the fortress of Stoponion, now Ihtiman). The army was scattered, its supply train and the imperial tent were plundered, and the emperor barely escaped to Philippopolis.
> 
> **Part I   Conquest and Consolidation** (Location 2321)

---

> The campaign was perceived as incompetent. 54 It was likely in the immediate aftermath of Trajan’s Gate that Samuil recovered the original heart of the Bulgarian empire, including Preslav.
> 
> **Part I   Conquest and Consolidation** (Location 2324)

---

> Within a few years, Samuil ruled a realm reaching from the Black Sea to the Adriatic and from the Danubian lands to northern Greece.
> 
> **Part I   Conquest and Consolidation** (Location 2329)

---

> Worse, the defeat weakened the emperor in the cold war against his two military rivals.
> 
> **Part I   Conquest and Consolidation** (Location 2334)

---

> 65Basil also made an important foreign-policy decision: he offered Vladimir (or Volodymyr, 978– 1015), the king of the Rus’ in Kiev and son of Svjatoslav, his much-requested twenty-seven-year-old sister Anna in marriage, in exchange for military aid, on the condition that Vladimir convert to Christianity.
> 
> **Part I   Conquest and Consolidation** (Location 2370)

---

> Netting a born-in-the-purple imperial princess, an unprecedented feat— one, moreover, that had been beyond the reach of Otto I and Hugh Capet— was a tremendous coup.
> 
> **Part I   Conquest and Consolidation** (Location 2375)

---

> Moreover, Vladimir’s aggressive Christianization of Rus’ unified his realm and increased his power over it; he had, in fact, previously sought to consolidate his subject’s paganism under his control. Also, his choice of Byzantine Orthodoxy increased his access to the west while shielding him from ecclesiastical meddling by the Catholic Franks, who tended to send their own missionaries and bishops, trying, in this way, to dominate their neighbors.
> 
> **Part I   Conquest and Consolidation** (Location 2379)

---

> Moreover, it seems that after taking Kiev Vladimir had found his Varangian mercenaries to be troublesome and demanding, so he wanted to unload them on the Romans.
> 
> **Part I   Conquest and Consolidation** (Location 2384)

---

> “Anna departed with reluctance. ‘It is as if I were setting out into captivity,’ she lamented; ‘better were it for me to die at home.’ But her brothers protested, ‘Through your agency God turns the land of Rus’ to repentance’.”
> 
> **Part I   Conquest and Consolidation** (Location 2420)

---

> Basil formed his six thousand Varangians into a new imperial tagma, which, for the next two centuries, would draw its recruits primarily among Scandinavians, who often returned home after gaining riches in imperial service
> 
> **Part I   Conquest and Consolidation** (Location 2424)

---

> In the case of this reign, and with the possible exception of the Bulgarian war( s), we have no reason to believe that there was much happening. In other words, Basil’s reign after 989 may have been a time of relative peace, quiet, and prosperity for the majority of his subjects, at least those who were not living next to his wars.
> 
> **Part I   Conquest and Consolidation** (Location 2480)

---

> The “darkness” that envelops Constantinople probably means that for some fifty years there were few famines, unpopular appointments, vexatious taxation, or abuses by soldiers. This would make Basil one of the most successful Byzantine emperors on the domestic front, and the years 989– 1025 (and beyond) the most peaceful in the history of the empire.
> 
> **Part I   Conquest and Consolidation** (Location 2482)

---

> Byzantines began to remember him as the Bulgar Slayer. Even if it was as a later invention, the moniker was certainly appropriate. Basil no doubt killed many Bulgarians, and it is likely that he spent most of his reign fighting against them in a war whose extraordinary length had no precedent in Roman tradition.
> 
> **Part I   Conquest and Consolidation** (Location 2491)

---

> Along the eastern front, Basil had inherited a viable situation that needed only maintenance and enforcement. With peace secure at home after early 989, he focused on the conflict with Bulgaria, where the situation was not viable.
> 
> **Part I   Conquest and Consolidation** (Location 2505)

---

> Basil had turned the status quo of 970, which required enforcement and policing, into a lasting peace, a major achievement on his part.
> 
> **Part I   Conquest and Consolidation** (Location 2614)

---

> Bulgaria may have been his priority, but securing the east is exactly what he did, more effectively and lastingly than his predecessors.
> 
> **Part I   Conquest and Consolidation** (Location 2657)

---

> We know little, then, about the first four years of the war, except that it was fought in Macedonia (understood in a broad geographical sense).
> 
> **Part I   Conquest and Consolidation** (Location 2685)

---

> In sum, for the years 997– 1003 we have only a jumble of incoherent bits of information.
> 
> **Part I   Conquest and Consolidation** (Location 2729)

---

> However, we have no information about the decade 1003– 1014. When the curtain rises in 1014, we see that the Bulgarian state controlled a fair amount of territory
> 
> **Part I   Conquest and Consolidation** (Location 2733)

---

> is not until 1014 that the veil of silence rises on the Bulgarian war.
> 
> **Part I   Conquest and Consolidation** (Location 2742)

---

> A major theme in discussions of Basil’s reign, indeed of the later Macedonian dynasty, is the tension between the emperor and the emerging aristocracy.
> 
> **Part I   Conquest and Consolidation** (Location 2744)

---

> This section will assess the role of Basil II in the long-standing efforts by emperors to curb the abuses of the “powerful” in Byzantine society.
> 
> **Part I   Conquest and Consolidation** (Location 2748)

---

> The idea that Basil was at war with the “aristocracy” is overblown, and I would add that it was not defined by socioeconomic criteria to begin with; Basil, like many other emperors, was concerned specifically and primarily about army officers with clout, prestige, and connections. No one in Romanía had enough land to challenge an emperor, but an army could do so.
> 
> **Part I   Conquest and Consolidation** (Location 2751)

---

> In the thirty-five years between 989 and 1025, Basil passed an extremely small number of measures that might have negatively affected the aristocracy, so small that they cannot constitute a sustained policy of class warfare.
> 
> **Part I   Conquest and Consolidation** (Location 2772)

---

> The Varangian Guard, made up of foreigners loyal to the emperor with no prior ties to Roman society, gave Basil another advantage in facing down potential rivals. That had been their original function, after all.
> 
> **Part I   Conquest and Consolidation** (Location 2781)

---

> He also sought to protect himself not against an alleged “landowning aristocracy” but rather a powerful class of army officers.
> 
> **Part I   Conquest and Consolidation** (Location 2841)

---

> As for the missing decade, Skylitzes says only that Basil continued to invade Bulgaria every year.
> 
> **Part I   Conquest and Consolidation** (Location 2854)

---

> We now read the most macabre report in Byzantine history. The emperor blinded them all, in total between fourteen thousand and fifteen thousand men, except for one out of every hundred, who was blinded in only one eye in order to lead the others home. Samuil, about seventy, fainted when he saw this horror and died of a heart attack two days later, on October 6.4
> 
> **Part I   Conquest and Consolidation** (Location 2867)

---

> The historicity of Basil’s atrocity has been questioned. 6 We have seen repeatedly that he could resort to harsh punishments, but the figure seems vastly inflated: fifteen thousand casualties would have decimated Bulgarian military manpower, and yet the war continued without interruption.
> 
> **Part I   Conquest and Consolidation** (Location 2876)

---

> It was the largest conquest the Romans had made in centuries, and, even though that territory had once been ruled by them, it had long been under foreign rule and probably only a small minority of its population would have been culturally Roman.
> 
> **Part I   Conquest and Consolidation** (Location 2933)

---

> Unfortunately, we have little information about the identity of most of the subjects of the former Bulgarian empire, or whether even a majority identified as Bulgarian. Whoever they thought they were, Romans would not accept them as their own.
> 
> **Part I   Conquest and Consolidation** (Location 2955)

---

> So Byzantium was now a proper imperial state, with Romans ruling non-Romans to a degree that had not been seen since antiquity.
> 
> **Part I   Conquest and Consolidation** (Location 2960)

---

> In the absence of information about the crucial decade 1003– 1014, the war between Romanía and Bulgaria cannot properly be evaluated. Certainly, Bulgaria was the most formidable opponent of Roman arms at this time. On the eastern front, all that Basil had to do was show up in person and his enemies would withdraw.
> 
> **Part I   Conquest and Consolidation** (Location 2992)

---

> The long reign of Basil witnessed the ultimate extension and consolidation of Byzantine power in southern Italy.
> 
> **Part I   Conquest and Consolidation** (Location 3163)

---

> It is unclear to what degree the Venetians yet believed that they were a fully autonomous political community, though they did make separate deals with the western and eastern emperors.
> 
> **Part I   Conquest and Consolidation** (Location 3173)

---

> The emperor made overtures to his western counterpart, Otto III,
> 
> **Part I   Conquest and Consolidation** (Location 3184)

---

> This was the second pope in the past two decades to come directly from the court in Constantinople.
> 
> **Part I   Conquest and Consolidation** (Location 3189)

---

> Overall, momentum in Italy was on the Byzantine side, even during the Bulgarian war. “It was now that Byzantium began truly to leave marks on the landscape and culture of southern Italy.”
> 
> **Part I   Conquest and Consolidation** (Location 3199)

---

> Soon after his death, and certainly during the chaos and defeat of the later eleventh century, Basil came to be regarded as one of the greatest emperors of all time. By the twelfth century he was being called “the Bulgar Slayer,” a name that stuck.
> 
> **Part I   Conquest and Consolidation** (Location 3257)

---

> This was a reign stripped down to the essentials: just the emperor and the army, both away from the capital much of the time.
> 
> **Part I   Conquest and Consolidation** (Location 3269)

---

> What about high culture? Almost half a century after Basil’s death, the historian Michael Psellos looked back to him as a model emperor when it came to the army and the treasury, but noted that he generally scorned literature and intellectual life.
> 
> **Part I   Conquest and Consolidation** (Location 3273)

---

> The history of Roman society in the core provinces of the empire during this half-century is an almost complete blank, with the exception of stray details provided by saints’ lives. 80
> 
> **Part I   Conquest and Consolidation** (Location 3301)

---

> By 1025, the empire had almost three centuries of gradual expansion and consolidation of territory behind it. The Isaurian emperors of the eighth century held ground against the Bulgars and Arabs, and their successors in the ninth and tenth reabsorbed Greece and Romanized most of its Slavic settlers. Basileios I conquered Tephrike in 879, and Kourkouas conquered Melitene in 934. But the conquests of 955– 1025 were on a different scale.
> 
> **Part I   Conquest and Consolidation** (Location 3317)

---

> Specifically, the regime of Nikephoros Phokas (both before and while he was emperor) identified the emirates of Crete, Cilicia, and Aleppo as threats to imperial security.
> 
> **Part I   Conquest and Consolidation** (Location 3324)

---

> we do not know why each of them thought that he was at war, which is why this war has been so often psychologized as a personal obsession of Basil brought on by his defeat in 986.
> 
> **Part I   Conquest and Consolidation** (Location 3348)

---

> In summary, Tzimiskes was sucked into a partial conquest of Bulgaria in 971, and this unresolved situation pulled the Romans into a broader conflict.
> 
> **Part I   Conquest and Consolidation** (Location 3354)

---

> Let us consider now the effect on the empire itself. In 955, Romanía was relatively homogeneous.
> 
> **Part I   Conquest and Consolidation** (Location 3387)

---

> Unlike actual empires, there was no ethnic, religious, linguistic, or cultural distinction between rulers and the vast majority of subjects.
> 
> **Part I   Conquest and Consolidation** (Location 3391)

---

> After converting to Orthodoxy and learning Greek, these groups often disappear from the record after a few generations, i.e., they were absorbed into the general Roman background.
> 
> **Part I   Conquest and Consolidation** (Location 3400)

---

> Yet Byzantine Romanía had now bitten off far more than it had ever tried to chew and digest in the past. These were established and constituted realms, not refugees from the caliphate or decentralized bands.
> 
> **Part I   Conquest and Consolidation** (Location 3410)

---

> This brings us to one of the most overblown issues in Byzantine history, the alleged struggle between the “state” and the “powerful.” Twentieth-century historians preferred to see events— the stuff of “narrative”— as merely surface reflections of deeper socioeconomic upheavals with dramatic overtones of class struggle over land and social power, and with the state competing against the magnates or some putative “landed aristocracy” over control of the peasantry.
> 
> **Part I   Conquest and Consolidation** (Location 3467)

---

> Historians of socioeconomic trends assume that the premodern state was almost always powerless to stop these allegedly “deeper” transformations from taking place on the ground, but there is no evidence for or against this assumption either. For all we know, the problem was overstated by the emperors to begin with (their laws are our main evidence for its existence), or effectively suppressed by them. What we should not do is conflate this issue with the officer-class problem. Historians who conflate the two have never been able to explain why emperors who came from the alleged magnate class (Phokas and Tzimiskes) failed to repeal the antipowerful land legislation. No matter their background, all emperors sought to protect themselves against rivals while safeguarding the tax and recruitment basis of the imperial army, especially against the Church and the monasteries.
> 
> **Part I   Conquest and Consolidation** (Location 3481)

---

> The Rus’, who accepted Byzantine Christianity, were not closer to Byzantium than the Ottonian Germans, who aped Roman imperial forms.
> 
> **Part I   Conquest and Consolidation** (Location 3518)

---

> The conversion of the Rus’ is often hailed as one of the great achievements of Byzantium, but those words give a misleading impression and are deeply colored by hindsight, namely the later division of the Christian world between Catholic and Orthodox realms.
> 
> **Part I   Conquest and Consolidation** (Location 3520)

---

> Byzantium did not stop acquiring territory in 1025. It continued to expand right up to the moment in the 1060s when it was surprised to realize that it was about to contract dramatically.
> 
> **Part I   Conquest and Consolidation** (Location 3526)

---

> It is not clear that any kind of “decline” set in soon after the death of Basil II. What we can say is that without him to suppress the political scene of Romanía, power was gradually reclaimed by the other elements of the polity, including the extended palace, the political and military elites, the populace of Constantinople, and even one patriarch.
> 
> **Part I   Conquest and Consolidation** (Location 3529)

---

> The most pressing problem, of course, was the succession; both Basil and Konstantinos had put this off until the last moment. Apparently, it was all arranged in haste when Konstantinos fell ill in November 1028.
> 
> **Part II   New Enemies and the Return of Politics** (Location 3591)

---

> This was the first of many irregular marriages that prolonged the Macedonian dynasty in its twilight. 11 But it did not solve the underlying issue, as Romanos had no heirs and Zoe was almost fifty.
> 
> **Part II   New Enemies and the Return of Politics** (Location 3599)

---

> Konstantinos’ reign also inaugurated a structure of imperial governance that proved detrimental in the long run, as Psellos clearly realized, especially when the empire later came under fiscal and military strain. 13 It can be delineated as follows: a mostly civilian emperor residing in the capital and rewarding his mostly civilian courtiers, including eunuchs, from the proceeds of a growing and increasingly monetized economy, while army officers posted to the frontier backwaters began to feel starved of favor, access, money, men, and opportunities.
> 
> **Part II   New Enemies and the Return of Politics** (Location 3606)

---

> Romanos is often depicted by scholars as a representative of an alleged aristocracy, ruling in its class interests, but this was not the case. In reality, he was an insecure ruler who sought to fill Basil’s boots by acquiring military prestige, resulting in a fiasco.
> 
> **Part II   New Enemies and the Return of Politics** (Location 3616)

---

> In 1030, Romanos decided to attack Aleppo. His generals advised against it, 21 a sure sign that his motives were political and domestic.
> 
> **Part II   New Enemies and the Return of Politics** (Location 3655)

---

> Romanos had been astonishingly lucky. The debacle at Aleppo improved the empire’s security. The Roman armies were still the most formidable, and had suffered few casualties.
> 
> **Part II   New Enemies and the Return of Politics** (Location 3712)

---

> Psellos presents Zoe as a lustful woman who acquired a young lover too, one Michael, the brother of the eunuch Ioannes.
> 
> **Part II   New Enemies and the Return of Politics** (Location 3752)

---

> The regime of the Paphlagonians illuminates some fundamental truths about the workings of power in Byzantium. These were understood by the eunuch Ioannes, who orchestrated the transition of 1034.
> 
> **Part II   New Enemies and the Return of Politics** (Location 3769)

---

> The mechanisms of power could, therefore, legitimate a bunch of nobodies. And the impersonal institutions of governance could enable them to rule.
> 
> **Part II   New Enemies and the Return of Politics** (Location 3780)

---

> The “secret of empire” in Byzantium— to paraphrase Tacitus— was that almost any Roman could become emperor. No right to the throne came from family, social class, virtue, achievement, law, or religious fantasy. Such claims helped, but only as rhetorical arguments to justify a takeover. In reality, emperors were made when they had secured sufficient backing from other elements within the republic, given the specific circumstances that had brought them to the throne. Legitimacy was a function of popularity, of gaining support and countering opposition.
> 
> **Part II   New Enemies and the Return of Politics** (Location 3792)

---

> The Paphlagonians maintained the integrity of the empire, but we notice a turn toward an increasingly defensive posture.
> 
> **Part II   New Enemies and the Return of Politics** (Location 3830)

---

> For the empire’s core provinces, the eleventh century was a period of demographic and economic expansion. It took a long time for historians to recognize this fact, but it is now documented, well studied, and accepted.
> 
> **Part II   New Enemies and the Return of Politics** (Location 3862)

---

> From the historical point of view, it is worth pointing out two trends. The first is the gradual reclamation of the Aegean islands. Before the conquest of Crete, they were the targets of Arab raids and were conceived in the Byzantine literary imagination as desolate places, good for exiling enemies. Now they were places of investment and growth. The second is the belated arrival and expansion of monasticism in Greece. A late convert to Christianity, southern Greece had not developed notable monastic traditions before this time.
> 
> **Part II   New Enemies and the Return of Politics** (Location 3871)

---

> This was to be Byzantium’s last Sicilian venture, so it is fitting that it left its mark on European memory.
> 
> **Part II   New Enemies and the Return of Politics** (Location 3901)

---

> It is easy to conclude that Sicily was lost because of petty infighting, and that Maniakes would have finished the job. But the problem was endemic to the imperial system: all emperors, especially the Paphlagonians, were vulnerable to the ambitions of other powerful Romans.
> 
> **Part II   New Enemies and the Return of Politics** (Location 3917)

---

> Michael took the extraordinary move of castrating all his living male relatives, regardless of their age, which presumably included Konstantinos, the savior of Thessalonike.
> 
> **Part II   New Enemies and the Return of Politics** (Location 3996)

---

> The people now cheered and celebrated, but Zoe quickly tried to displace her sister, whom she hated. The crowd, however, demanded that the two reign together.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4019)

---

> In the end, they were pulled out, paraded in a brief humiliating procession, and blinded in a tight circle of people, the uncle with stoic dignity and the nephew kicking and screaming.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4024)

---

> Michael’s spectacular fall awed contemporaries. Three historians (Psellos, Attaleiates, and Skylitzes) devoted major set pieces to it, the first claiming that it was the most important event in his work.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4028)

---

> The Paphlagonians revealed not only that almost anyone could become emperor, but that an emperor could be destroyed by almost anyone— or, in this case, everyone.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4041)

---

> In past centuries, the court would host bride shows to select a suitably beautiful and pious wife for a young male heir. In 1042, the gender roles were reversed: Zoe, who was over sixty but blond and still youthful-looking, had her pick from among the best-looking and most distinguished men in the empire.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4065)

---

> After the death of his second wife, he had fallen for her cousin, Maria Skleraina, who had followed him to Mytilene and supported him financially. Once in the palace, he brought her to the capital with Zoe’s permission; eventually, he introduced her to the palace and began to treat her as a wife, a third empress with the title sebaste (“ Augusta”) and a third expense account for her own good works and favors.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4083)

---

> The geostrategic position of Romanía was altered irrevocably in the eleventh century by the coming of the Normans to southern Italy and the Seljuks to the east, developments that impressed themselves urgently on Roman awareness during the reign of Monomachos.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4093)

---

> The history, fighting style, and sociopolitical organization and ambitions of the Normans made them a distinctively new threat to the empire. By the early eleventh century, the Normans were the Frenchified descendants of Vikings who had settled in Normandy ca. 900.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4097)

---

> What Norman leaders needed above all, both at home and abroad, were taxable properties to support themselves and their followers. In the eleventh century, they became experts at state takeovers: they would identify a weak or ailing state (England, Muslim Sicily, Byzantium in the 1080s), attack its army and aim to take over its government, subject the local population, enrich themselves, and fund further expansionism.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4103)

---

> What they did in southern Italy was slightly different. Here they sought employ as mercenaries, as the land was especially inviting to Norman ambitions.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4106)

---

> Among the emperors of our period, Monomachos is the only one to whom we may attribute if not a “policy” in cultural, social, and economic matters then at least a series of initiatives or preferences that were noted by contemporaries.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4216)

---

> Specifically, he invested heavily in ancient philosophy, especially Neoplatonism, and sought to fuse it with Christian theology in a way that makes it hard to know which side of the partnership was truly in control.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4245)

---

> What we might loosely call the “upper middle classes” now become visible in our sources, and do so in significant numbers for the first time. It may even be possible to recapture something of their cultural profile.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4262)

---

> Whereas the social horizon of literature in Byzantium was previously confined to a fairly small circle, we now observe, in the letters of Psellos and the poems of Christophoros Mytilenaios, a much wider group of contacts participating in previously elite cultural exchanges and asking for classical knowledge and epigrams to adorn their religious dedications.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4264)

---

> The Seljuk conquests represented the most pivotal moment in the history of the Near East since the Arab conquests of the seventh century.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4398)

---

> A myth of common origin was invented to unify this military confederation of Turks whose founders,
> 
> **Part II   New Enemies and the Return of Politics** (Location 4404)

---

> At the beginning of his reign, Monomachos had an irregular “domestic” life, to be sure, featuring one official empress-wife, one unofficial empress-wife-mistress (Skleraina), and one empress-sister-in-law.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4506)

---

> Zoe’s death, which passed with hardly a notice, 20 was important for dynastic continuity; only Theodora now remained. Monomachos’ own condition was visibly deteriorating already in 1047. His arthritis rendered him incapable of walking, and he had to be held up and then carried, in excruciating pain. 21 Yet his sex drive was undiminished.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4514)

---

> Two measures have been taken by historians as signaling a narrative of imperial decline, the first as a cause, the second as a symptom, though both are hard to interpret. The first is Monomachos’ alleged demobilization, defunding, or overtaxation of the army in “Iberia,” which is supposed to have exposed the empire to Seljuk attack through that corridor.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4542)

---

> The second was Monomachos’ broader use of Phokas’ tetarteron, the lighter-weight gold coin, albeit now in a more devalued form and coupled with a partial devaluation of the standard gold coin (i.e., a reduction in the gold content of the coins).
> 
> **Part II   New Enemies and the Return of Politics** (Location 4545)

---

> The decade after 1043 was the turning point between a viable imperial presence in southern Italy and its imminent extinction at the hands of Norman aggressors. The entire structure of power there changed in ways that had an impact on the empire’s relations with the Latin west, especially the popes. There followed, in 1054, the visit of the papal legates in Constantinople, which has been discussed more than any other event of Monomachos’ reign, because it allegedly shaped the future of Catholic-Orthodox relations, or at least revealed tensions that were liable to burst out at any moment. The Byzantine sources barely mention either events, and the so-called Schism of 1054 has been downgraded to the status of a “non-event.” 32 But there may have been more to it, and the loss of Italy was certainly real.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4561)

---

> There is a “traditional” view about these events, which is that they led to a schism between the two Churches and that Keroularios was mostly to blame (as most old views are pro-western and anti-Byzantine). There is now also a “new traditional” view, which is that these events had almost no immediate impact, even on Church relations; were hardly noticed by contemporaries; and were caused by two misbehaving individuals (Humbert and Keroularios). But it is probably time to revisit the new orthodoxy too, as it ameliorates the past by downplaying the significance of conflict, probably to cater to modern feelings.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4639)

---

> Therefore 1054 was possible only because key Byzantines too held inflexible positions.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4656)

---

> Schism does not mean only that two Churches are in open war against each other. It is not necessarily a legal fact created by official documents. It may also be a sense or belief that there is no community between two Churches. The situation in 1054 showed that this was already the case for many at Rome and Constantinople, and not among fringe elements either.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4659)

---

> Before the decade’s end, the Church of Rome would recognize the Normans as its own warriors and within a couple of decades it would endow them with the right to conquer Byzantium in the name of God.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4665)

---

> As the link to the previous dynasty was becoming increasingly attenuated and there were no plans for a succession, more vultures began to circle around the throne. Yet Monomachos handled all these challenges successfully, with a minimum of disruption to the political sphere. He did not become a paranoid executioner, and the civil wars were over quickly, with few casualties. He promoted intellectuals at the court, men such as Mauropous, Psellos, and Christophoros Mytilenaios, who left their mark on the history of Byzantine literature and thought. He made access to education and the court and senate more feasible for many, though we cannot gauge the social consequences of his policies.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4670)

---

> As for imperial defense, Monomachos must be rehabilitated immediately. The worn narrative that he was a “civilian” emperor who did not care much for the army and allowed the empire’s strategic situation to deteriorate is completely false.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4675)

---

> The only true loss was in Italy, and it would prove irrevocable. Otherwise, the empire continued to expand in the east as well as economically and intellectually.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4685)

---

> the challenges facing Monomachos were not typical. All three enemies were “new,” sometimes with unfamiliar fighting styles (especially the Normans), but more importantly with new objectives. The Normans were not just a Lombard uprising or yet another pathetic incursion by a German emperor. They were mercilessly filling a power vacuum in southern Italy.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4691)

---

> She was in her early seventies, and had an interesting story. Placed in a convent by her sister for conspiring with Konstantinos Diogenes, she twice came to power via coups: first when the people rose up against Michael V in 1042 and (against Zoe’s wishes) elevated Theodora to imperial rank; and again in 1055, when she and her household eunuchs scuttled Monomachos’ succession plans.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4789)

---

> The regime of Michael VI was as similar to the regime of Theodora as her eunuchs could make it, except it lacked the fig leaf of dynastic continuity. Instead of an empress ruling through eunuchs, eunuchs now ruled through a weak emperor.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4826)

---

> Isaakios was the first emperor in our period who certainly faced a deficit in the budget, and had to take drastic measures.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4916)

---

> Many modern accounts of the mideleventh century present it negatively. This was when the Byzantines allegedly lost the peace by failing to prepare for a host of emerging new challenges, and when imperial defenses atrophied at the hands of “civilian” emperors more interested in mistresses and building churches.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4996)

---

> Some historians have then superimposed on it a story of feudalization, proposing that “great families,” defined as landowners, struggled against the Macedonian state in an effort to impose their class interests on it.
> 
> **Part II   New Enemies and the Return of Politics** (Location 4998)

---

> The most striking development, absent from most modern surveys, is the return of multipolarity to the political sphere. For thirty-five years, Basil II had concentrated power into his own hands.
> 
> **Part II   New Enemies and the Return of Politics** (Location 5003)

---

> What we do not find any evidence for, by contrast, is the idea that these political developments reflected a socioeconomic struggle between the imperial state and large landowners, called Anatolian magnates or the like in modern literature.
> 
> **Part II   New Enemies and the Return of Politics** (Location 5013)

---

> There is no evidence that the independent peasantry declined, that large estates were growing, 1 or that the officer class had any socioeconomic class consciousness.
> 
> **Part II   New Enemies and the Return of Politics** (Location 5019)

---

> rebel leaders had no ability to deploy “personal” forces from outside the army. They did not have private armies; in other words, they did not have the ability to challenge the state independently of its own infrastructure.
> 
> **Part II   New Enemies and the Return of Politics** (Location 5030)

---

> This is the place to address the distinction between the political wing of the state and the military, or, in the sources’ language, between the politikon and the stratiotikon.
> 
> **Part II   New Enemies and the Return of Politics** (Location 5035)

---

> The emperors did begin to face budget shortfalls around 1050, and this is likely the reason they devalued the coinage. They had been spending too much to maintain the loyalty of their subjects, which was a function of the systemic weakness of the throne, especially as dynastic continuity was becoming more attenuated with every succession.
> 
> **Part II   New Enemies and the Return of Politics** (Location 5055)

---

> This must be stressed on the level of imperial defense and control too: there was no decline here in the period 1025– 1059. Historians have assumed that because everything fell apart visibly after 1071, internal factors must have been rotting the empire on the inside all along, and some have wanted to trace that rot back to Basil II. What we have instead was a series of systemic problems that were endemic to the Roman empire and came to a head in this period.
> 
> **Part II   New Enemies and the Return of Politics** (Location 5062)

---

> I reject the idea that the emperors were lulled into thinking that eternal peace had come at last, demobilized the army, and so “lost the peace.”
> 
> **Part II   New Enemies and the Return of Politics** (Location 5077)

---

> The strategic situation was more ominous, yet none of the emperors in this period failed Romanía, least of all Monomachos. Domestic spending was a problem, and Isaakios took measures to rein it in. For most of the inhabitants of the empire, especially for Romans in the core territories, this period would have been one of prosperity, and imperial largess would have made many rich too.
> 
> **Part II   New Enemies and the Return of Politics** (Location 5082)

---

> If Byzantium experienced any decline before the collapse of the 1070s, it happened during Doukas’ reign.
> 
> **Part III   Collapse** (Location 5108)

---

> Doukas, he says bluntly, neglected the army and the frontier defenses. Specifically, the soldiers were not properly equipped or supplied, and the more costly, high-quality soldiers were discharged, leaving the worse ones behind. 5 Unfortunately, we cannot translate this into precise or institutional terms; nor do we have hard data to gauge the extent of the problem. What is baffling is that anyone would think, in 1059, that this was sound policy. No one in the recent history of Byzantium had advocated such a terrible idea.
> 
> **Part III   Collapse** (Location 5122)

---

> Byzantine Italy disappeared during the 1050s and 1060s. The empire’s gravitational pull weakened and the region was fully absorbed into a different political world, that of the Normans, the papacy, and Lombard duchies.
> 
> **Part III   Collapse** (Location 5217)

---

> Our sources claim that he defunded and downgraded the army, but it is difficult to know what that meant. If I could have the budget figures for one reign, it would be his.
> 
> **Part III   Collapse** (Location 5247)

---

> She had to swear and sign it before the patriarch, kaisar, her children, and the senate; and the senators and patriarch then had to sign it themselves. By a curious chance, we have the text of this oath. In it the empress promises to remain faithful to Doukas by invoking the sky, earth, and all the elements, calling on the Trinity, Theotokos, Cherubim, Seraphim, and all other orders of angels, prophets, apostles, martyrs, and saints, and agrees to be torn apart, burned, and thrown into the sea if she even thinks about remarrying.
> 
> **Part III   Collapse** (Location 5260)

---

> The empress and others realized that a general had to be placed on the throne, but inevitably there would be a dispute over who and there was also the matter of the oath.
> 
> **Part III   Collapse** (Location 5280)

---

> According to Attaleiates, who was probably present, the empress, the senators, and the patriarch deliberated and decided that the common good had to be placed over the jealous wishes of a dying husband: the oath “would harm the common good and contribute to the destruction of the Roman empire.”
> 
> **Part III   Collapse** (Location 5285)

---

> In 1067, the Romans seem to have come to their senses. The eastern frontier was collapsing and they were about to lose the heartland of their empire. Nor was it clear why this had happened. Twenty years had passed since large imperial armies had operated in the east (against Ani, Dvin, and Ibrahim Inal). Why had it been so long? For ten years after that they had credibly defended against attacks. But now everything was in shambles. Diogenes knew exactly what he had to do: massively reassert the imperial presence on the frontier and, if possible, inflict a devastating defeat on the enemy.
> 
> **Part III   Collapse** (Location 5303)

---

> The expedition of 1068 was a great success. It attained its primary strategic objective, which was to plug the hole in the defense of Syria, and began to impose costs on raiding. Moreover, it restored Roman morale.
> 
> **Part III   Collapse** (Location 5352)

---

> battle of Mantzikert, the most famous in Byzantine history, excepting the siege of 1453.
> 
> **Part III   Collapse** (Location 5413)

---

> the battle was long held to have shifted the balance of power between Christians and Muslims in the east.
> 
> **Part III   Collapse** (Location 5415)

---

> The emperor came to Mantzikert and assessed that he would be able to take it with only a fraction of his army.
> 
> **Part III   Collapse** (Location 5426)

---

> Diogenes did indeed reduce Mantzikert easily, but just then it was reported that Turks were near. It was in fact the sultan, but Diogenes apparently believed it was only a minor force.
> 
> **Part III   Collapse** (Location 5428)

---

> Diogenes now grasped the miscalculation in dividing up the army. He had planned to link up with the other contingents quickly, or recall them in a pinch, but now he was simply cut off. Believing that they would not arrive in time, he wanted to settle the issue by battle.
> 
> **Part III   Collapse** (Location 5439)

---

> We now have two versions of events. According to Attaleiates, the Turks retreated before the emperor, who pursued them for a long while but stopped when he realized he had left the camp unguarded and feared an ambush. He gave the signal to turn around, but this was misinterpreted in the rear as a signal to retreat because the emperor had fallen, which caused a panic.
> 
> **Part III   Collapse** (Location 5442)

---

> Attaleiates’ account may be the best that we have, but it was written in a context of heated recriminations and a contest over memory. In his account, the main Roman and Turkish armies never really engaged; there was no “battle of Mantzikert.”
> 
> **Part III   Collapse** (Location 5449)

---

> The takeaway image here is that only Diogenes actually fought, ahead of the Romans, and unsupported by them.
> 
> **Part III   Collapse** (Location 5451)

---

> The tradition in Bryennios-the-grandson, by contrast, which is possibly based on the recollections of his grandfather the doux, agrees on the outcome but recounts a more formal battle in which the Turks defeat the Roman right wing, Andronikos in the rear retreats (for no apparent reason), and the emperor is surrounded and taken.
> 
> **Part III   Collapse** (Location 5453)

---

> In the end, splitting the army proved catastrophic, as contemporaries realized. 67 Diogenes also failed to gather intelligence effectively. He had no idea the sultan was coming to Mantzikert, prepared to fight.
> 
> **Part III   Collapse** (Location 5457)

---

> As a result of these miscalculations, a Roman emperor was captured in battle for the first time in nine hundred years, and held for eight days.
> 
> **Part III   Collapse** (Location 5461)

---

> The battle of Mantzikert was not costly in terms of casualties, but the survivors had scattered and were leaderless. 70 The most high-ranking officers on site who could have rallied them, such as Andronikos Doukas, rushed back to the capital to play politics. Moreover, there was no money.
> 
> **Part III   Collapse** (Location 5471)

---

> The biggest challenge the emperor faced was the blow to his prestige. He had been brought in to provide much-needed military leadership, and it had led to this. His credibility was gone.
> 
> **Part III   Collapse** (Location 5476)

---

> Emperors in the past had been murdered (Michael III) and even blinded (e.g., Michael V), but Diogenes became a tragic figure in Byzantine imagination. He had made a valiant effort to save the state and had done no harm to his political opponents. On top of his own failure, he was dealt multiple betrayals.
> 
> **Part III   Collapse** (Location 5513)

---

> The “traditional” view was that the battle of Mantzikert sealed the fate of Asia Minor, which would now become “Turkey.” The “new traditional” view is that the battle itself was not a disaster, as only a small part of the army was lost. It was the civil war that opened the floodgates to Turkish settlement.
> 
> **Part III   Collapse** (Location 5517)

---

> But in reality, there is no way to separate foreign warfare from domestic politics in Romanía. The civil war was caused by the battle,
> 
> **Part III   Collapse** (Location 5520)

---

> This last reign by a Doukas was when the empire lost Asia Minor, so it was bound to elicit negative verdicts. Many lost their lands and homes at this time.
> 
> **Part III   Collapse** (Location 5536)

---

> No one hated Michael Doukas personally. He seems to have been a decent enough young man, except he was completely unfit to be emperor, especially in a time of crisis. (The only two times that dynastic succession actually worked in the eleventh century produced bad rulers: Michael V and VII.) Michael was said to be fit only to be a bishop.
> 
> **Part III   Collapse** (Location 5541)

---

> Unfortunately we do not know the exact state of the army in 1072. Parts of it had been mauled and dispersed at Mantzikert, but the army sent to Khliat under Trachaneiotes and Roussel returned to Mesopotamia, albeit under unclear circumstances; they too may have been attacked. 7 The civil war would have reconstituted the armies— for another two maulings. Unfortunately, we do not know the numbers that fought for either side.
> 
> **Part III   Collapse** (Location 5564)

---

> Something was drying up the wealth in the capital, and it was almost certainly the loss of revenues from the lands in Asia Minor being overrun by Turks and deserted by Romans.
> 
> **Part III   Collapse** (Location 5570)

---

> year 1071– 1072 was a global turning point. The Romans lost their last Italian possession, Bari, to the Normans. They had already lost much of Armenia, certainly Vaspurakan, before Mantzikert, and now they lost the remainder. There was a new regime in the palace after a civil war, and a new king in Abkhazia-Kartli, Giorgi II. Even Alp Arslan had gotten himself killed in a silly way off in Central Asia, and was succeeded by his son Malik Shah (1072– 1092), a teenager. The situation was grim, but hardly hopeless. The empire still had resources and determined defenders. Let us survey the frontier.
> 
> **Part III   Collapse** (Location 5578)

---

> The Balkan provinces remained generally stable and were probably providing most of state revenue.
> 
> **Part III   Collapse** (Location 5583)

---

> The Roman response in the western Balkans immediately after the civil war of 1072 reveals no systemic weakness. But what about the east? The situation there was chaotic, in part because of the nature of Turkish movements.
> 
> **Part III   Collapse** (Location 5603)

---

> Thus, the imperial periphery did not collapse after Mantzikert and the civil war. Paradoxically, it was the center of Asia Minor that collapsed first, and eventually dragged down the periphery with it.
> 
> **Part III   Collapse** (Location 5626)

---

> Within a generation, the majority of Asia Minor, which had been Roman for a thousand years, would be split between three powers: the Seljuk sultanate of Rum in the center (around Ikonion), the Danishmends in the center-east (around Sebasteia), and the Armenian Rubenid dynasty in Cilicia and the Tauros mountains.
> 
> **Part III   Collapse** (Location 5628)

---

> But, as it turned out, it was not only the Turks that they had to fight in the mid-1070s; it was also another act of Norman self-aggrandizement. This broke the back of Roman Asia Minor.
> 
> **Part III   Collapse** (Location 5634)

---

> Roussel de Bailleul’s attempt to create a realm for himself in central Asia Minor closely followed the Norman playbook for interlopers, importing to Romanía the strategies that he and his countrymen had been practicing in southern Italy.
> 
> **Part III   Collapse** (Location 5636)

---

> At this point the playbook for interlopers became that for conquerors (see Sicily, England), where they instigated a direct attack on a foreign society with the aim of taking it over and replacing its ruling class with their own followers, all in the name of a legalistic or religious pretext.
> 
> **Part III   Collapse** (Location 5643)

---

> was the last Roman army that would march across Asia Minor to Kaisareia. That would be done again only by the Crusaders.
> 
> **Part III   Collapse** (Location 5665)

---

> Theirs was to be the last Roman army in Asia Minor making any progress inland before the First Crusade. There would be no more tagmata in the east. At this point Asia Minor was effectively lost.
> 
> **Part III   Collapse** (Location 5675)

---

> Roussel made a fascinating and almost unprecedented decision: he created his own puppet emperor and Roman court.
> 
> **Part III   Collapse** (Location 5679)

---

> The Norman adventurer was creating a shadow Roman government to provide political cover to his aggression. This policy would be repeated by Robert Guiscard only a few years later and by the Crusaders in 1203.
> 
> **Part III   Collapse** (Location 5681)

---

> henceforth, and for the rest of their history, the Romans would hire Franks to fight Turks and Turks to fight Franks, depending on who was threatening them more. This was when Franks and Turks began to fight between themselves over the corpse of Romanía, which they would do hotly for another five hundred years.
> 
> **Part III   Collapse** (Location 5688)

---

> There was now no way to save Roman Asia Minor. The court had given the Turks a huge boost in its single-minded determination to eliminate Roussel.
> 
> **Part III   Collapse** (Location 5697)

---

> The court now gave the task of capturing Roussel to Alexios Komnenos, the future emperor, who was not yet twenty. He had no money and hardly any men, but was likely loyal.
> 
> **Part III   Collapse** (Location 5703)

---

> The Komnenian writers dramatize Alexios’ capture of Roussel, probably in 1076. He allegedly waged guerrilla warfare against the Franks with 150 Alan soldiers. In reality, the court put out another warrant for Roussel’s arrest among the local Turks, and one Tutak (possibly the same as Artuk), who was on good terms with him before, now treacherously arrested him at a feast and delivered him to Amaseia. Alexios seems to have been there only to accept the captive;
> 
> **Part III   Collapse** (Location 5709)

---

> The Romans were able to suppress the little Normandy that was being carved out of their territory, but at the cost of losing Asia Minor to the Turks.
> 
> **Part III   Collapse** (Location 5719)

---

> just as they would destroy Constantinople first, in 1204, before the Turks could do so in 1453.
> 
> **Part III   Collapse** (Location 5727)

---

> This was protection money on an imperial scale. The plan worked for Michael VII, but the court should have known better: any agreement or even contact with a Norman created actionable precedents and legalistic pretexts for future aggression.
> 
> **Part III   Collapse** (Location 5751)

---

> The Norman conquest of southern Italy had already dislocated families that moved to Greece. 39 Interestingly, the Norman conquest of England also produced a flood of Anglo-Saxon refugees who were dislocated by the racist regime of William the Conqueror, and many of them trekked to Constantinople and took up service in the Varangian guard.
> 
> **Part III   Collapse** (Location 5753)

---

> By October 1077, the second Doukas regime had finally lost credibility. Its two most prominent generals, men who had commanded in every part of the empire and had been present at the most decisive campaigns of the past twenty years, proclaimed themselves emperors.
> 
> **Part III   Collapse** (Location 5786)

---

> Roman politics in Asia Minor had become a game of aligning Turkish interests, and every civil war resulted in more gains for them.
> 
> **Part III   Collapse** (Location 5820)

---

> Botaneiates’ extremely distinguished career had been in the military, but his name is associated with no victories.
> 
> **Part III   Collapse** (Location 5830)

---

> In a thousand years, no Roman emperor had taken hold of a more diminished state. Asia Minor was effectively lost, the Balkans in the throes of a major rebellion and periodically overrun by Pechenegs, and imperial revenues severely diminished.
> 
> **Part III   Collapse** (Location 5833)

---

> He was following the policies that he had observed emperors follow his whole life, those which had broken the fisc.
> 
> **Part III   Collapse** (Location 5836)

---

> Whereas Franks and Turks had previously been used against each other, they were now both being used together against rebel Roman armies.
> 
> **Part III   Collapse** (Location 5855)

---

> With Asia Minor mostly lost and the western Balkans overrun by Normans, contemporaries felt that the empire was almost lost.
> 
> **Part III   Collapse** (Location 5914)

---

> Yet Alexios inaugurated a new dynasty and a new era for the Roman empire. The Romans mustered the resources and the will to pull through and rebuild. When the Crusaders arrived in 1096, they encountered a Komnenian Roman empire.
> 
> **Part III   Collapse** (Location 5918)

---

> Byzantinists are understandably reluctant to admit the reality of decline and fall, especially after struggling for decades to banish those terms, but we cannot deny that something went catastrophically wrong in the third quarter of the eleventh century.
> 
> **Part III   Collapse** (Location 5924)

---

> Something seems to have gone wrong in the defense of Asia Minor in the reign of Konstantinos X Doukas, though its nature remains opaque. We hear of cutbacks to military spending, though we do not know exactly what form they took, how they were implemented, or why. There is no reason to suppose that the state was generating less revenue than before,
> 
> **Part III   Collapse** (Location 5928)

---

> At the end of his frustratingly opaque reign, the Roman armies appear demoralized, underfunded, and disorganized. Major cities of Asia Minor were sacked. Yet the vigorous campaigns of Diogenes show that numbers, organization, discipline, and strategic sense were still there, albeit also a shortage of cash.
> 
> **Part III   Collapse** (Location 5933)

---

> Some historians have tried to argue that Mantzikert was not the disaster that it has been made out to be, and it is certainly true that it did not cause a huge loss of life. But that is not why it was a disaster.
> 
> **Part III   Collapse** (Location 5936)

---

> Mantzikert ushered in the civil war of 1071– 1072, the three-year war with Roussel (1073– 1076), and the multiple civil wars of 1077– 1081.
> 
> **Part III   Collapse** (Location 5943)

---

> Thus, every civil war after 1071 fueled a death spiral of imperial collapse. At the end of those wars, there were hardly any Roman armies left in the east. The process was incredibly swift.
> 
> **Part III   Collapse** (Location 5950)

---

> The political problem was systemic. Was there also a systemic problem in the army? Historians have searched for and proposed underlying changes that made Byzantine defenses vulnerable to Seljuk attack. Before we discuss them, we must consider the possibility that structural weakening, even if it can be proven, was immaterial, i.e., that the Seljuks posed a threat of such magnitude that Byzantium would not have withstood it either before or after the alleged changes to its defenses.
> 
> **Part III   Collapse** (Location 5955)

---

> What factors supposedly weakened the Roman army so that it could not keep out the Turks? The most commonly cited is the “decline of the thematic armies.” According to this theory, thematic armies were primarily defensive, located in the affected frontier regions, bound to the lands that supported them, and geared more toward harassing raiders in passes than conquering foreign lands.
> 
> **Part III   Collapse** (Location 5964)

---

> The armies of conquest relied instead on the more professional, mobile tagmata, which gradually eclipsed and replaced the thematic forces.
> 
> **Part III   Collapse** (Location 5966)

---

> the field has to come clean about the moralizing and politicized way in which it has discussed thematic armies, who are valorized as patriot “farmer-soldiers” as opposed to the professional or “mercenary” armies of the eleventh century that were led by the incipient forces of Byzantine feudalism.
> 
> **Part III   Collapse** (Location 5992)

---

> Although few still uphold this model, its fetishization of the thematic armies lives on independently. Yet that too needs to be laid to rest along with the feudalization narrative.
> 
> **Part III   Collapse** (Location 5999)

---

> Another key term is “mercenary.” We have to be careful with this word and to distinguish between mercenaries and professional soldiers. Byzantinists rarely do this, but it is crucial. 11 The tagmata consisted largely of professional Roman soldiers paid to fight for their country. In our period they almost never attacked civilians. They participated in civil wars, but that is because, as Romans, they had a stake in the polity. Mercenaries, by contrast, were hired foreigners who could and did switch allegiance, which is usually how they came into the emperors’ employ, as the latter had more money.
> 
> **Part III   Collapse** (Location 6015)

---

> It was only in the 1070s, after the destruction of the native armies, that mercenaries made up a greater (relative) percentage. And then they proved to be disastrous, especially the Normans, but they had always been unreliable, even the Pechenegs and Oghuz.
> 
> **Part III   Collapse** (Location 6028)

---

> the reliance on mercenaries after 1071 becomes problematic in light of another factor. In the 1070s, we begin to see a split between the Balkan and Anatolian officer class. This is not mentioned as such in the sources, but, while Asia Minor was being lost, the likes of Bryennios, Basilakes, and Trachaneiotes— and their Roman armies— did little to help in the east, and were (apparently) not asked to do so by the Doukas regimes. Their western armies seem to have survived to fight multiple civil and foreign wars in 1078– 1085, and they are sometimes described as substantial. This cleavage is mysterious, as is the bifurcation in Roman fortunes (the Balkans vs. Asia Minor) during this decade. Usually emperors (witness Monomachos) were able to transfer armies from east to west and vice versa to meet pressing needs. Where were the westerners when the east was being lost?
> 
> **Part III   Collapse** (Location 6035)

---

> Finally, the civil wars of the eleventh century also had nothing to do with a putative process of feudalization. Quite the contrary, the Komnenoi came to power at a time when all lands, whether belonging to peasants or “magnates,” were being lost to the Turks. The Komnenoi rose on the basis not of their socioeconomic power but of their military-political careers.
> 
> **Part III   Collapse** (Location 6055)

---

> Far from being taken over by the landed aristocracy, under the Komnenoi it was the state that had to financially support its ruling class.
> 
> **Part III   Collapse** (Location 6063)

---

> The idea that there were families struggling to entrench themselves against “the state” has to be abandoned.
> 
> **Part III   Collapse** (Location 6077)

---

> In the end, the main cause of the imperial collapse was likely exogenous. In the late tenth century, the Romans were waging offensive warfare, enjoyed crushing advantages, and succeeded in conquering territories lost to the empire for more than three centuries. By 1081, they were fighting for their survival and had lost the east.
> 
> **Part III   Collapse** (Location 6078)

---

> No Roman empire— ancient or Byzantine, with themata or tagmata— could cope with three new enemies simultaneously.
> 
> **Part III   Collapse** (Location 6084)

---

> And so, in the course of a decade or less, Roman Asia Minor went from the oblivion of peace and prosperity to the oblivion of foreign occupation.
> 
> **Part III   Collapse** (Location 6089)

---

> The so-called First Crusade presents itself in almost perfect narrative form. Its flawless pace and trajectory (through beginning, middle, and end) betray the hand of a master dramatist. In Act I (1095), a spiritual leader (pope Urban II) calls upon high and low alike to right an injustice being done in faraway lands by vicious heathens.
> 
> **Part III   Collapse** (Location 6099)

---

> In Act II (1096– 1097), our protagonists enter the Christian but foreign land of Byzantium, a once-supreme but now distressed empire, and reach its magnificent capital. Its ruler, Alexios I Komnenos, is outwardly supportive but has goals of his own and wants to use the crusaders to advance them.
> 
> **Part III   Collapse** (Location 6105)

---

> In Act III (1097– 1098), the crusaders march out into the unknown, passing through hills, mountains, and deserts.
> 
> **Part III   Collapse** (Location 6112)

---

> The rest settle down to besiege Antioch, a brilliant move by the dramatist. It pauses the story’s momentum to introduce other elements of dramatic tension: cold, hunger, patient endurance, and the outbreak of rivalries among the leaders.
> 
> **Part III   Collapse** (Location 6115)

---

> And just as the crusaders take the city, they are besieged in it by a relief Muslim army from Mosul. This could not have been done better in a work of fiction.
> 
> **Part III   Collapse** (Location 6118)

---

> Then, there is an (appropriate) lull between Acts III and IV, as the crusaders seem to lose sight of their goal, and become disorganized and disunited.
> 
> **Part III   Collapse** (Location 6120)

---

> In Act IV (1099), some of the survivors finally get their act together and march on Jerusalem, which they capture after a fierce siege. They massacre the population and defeat a Fatimid army.
> 
> **Part III   Collapse** (Location 6122)

---

> The story thus ends by achieving exactly the lofty goals set out at the beginning, which rarely happens in history, and our heroes do so against the odds and after many adventures in foreign lands.
> 
> **Part III   Collapse** (Location 6123)

---

> Similar events that happened before (and elsewhere) are excluded when we label this the First Crusade. Moreover, the Crusade did not end with the conquest of Jerusalem; more waves continued to arrive, only they were far less spectacular in their accomplishments and have been played down accordingly.
> 
> **Part III   Collapse** (Location 6128)

---

> Instead, this chapter will survey the crucial Byzantine contribution to the making of the First Crusade and its course, as one of its many matrices. The crusade was only a dramatic combination of preexisting elements, which its own brightness later cast into permanent shadow, and then it progressed according to patterns that are best revealed by the history of Byzantium that is recounted in the present book, including the strategic choices of the Byzantine leadership.
> 
> **Part III   Collapse** (Location 6141)

---

> The First Crusade was only a dramatic combination of preexisting ideals and behaviors. In its aftermath, crusading was an established and even routine part of the cultural repertoire of medieval Europe, recognized through a more or less stable system of signs, practices, and conventions.
> 
> **Part III   Collapse** (Location 6149)

---

> This chapter will not reopen those debates but instead aims to highlight the imperial interests and strategies of Byzantium in the central part of the story, that is between 1096 and the siege of Antioch.
> 
> **Part III   Collapse** (Location 6153)

---

> This chapter will argue that, as the crusade later worked its way across post-Roman Asia Minor, it marched under imperial direction, replayed experiences from the recent Byzantine past, and poured itself into the old flasks that the empire had left behind in the east.
> 
> **Part III   Collapse** (Location 6157)

---

> The crusaders regarded themselves as pilgrims, and the Byzantines had extensive experience of such groups and their logistical and diplomatic needs from the moment they entered Romanía, crossed to Asia at Constantinople, and ventured into Muslim lands.
> 
> **Part III   Collapse** (Location 6160)

---

> Enough westerners traveled to the east in the eleventh century that their experiences and tales made the journey a familiar form of Christian devotion.
> 
> **Part III   Collapse** (Location 6174)

---

> The second aspiration that propelled the First Crusade was religious war against Muslims. On a certain level, war is war: killing people to take their land and stuff and citing a pretext that the aggressors call, and usually believe is, a just cause. But the way a religious war plays out, the contours of its violence, and the impact on religious-political history are also dependent on the cultural specifics of its justification and motivation. Violence and faith were generally entwined in medieval Christianity, but two theaters in which the ideology of religious war against Muslims had been pioneered and deployed to justify conquest and the expansion of Christianity (i.e., the realm of the Church of Rome) were Spain and Sicily.
> 
> **Part III   Collapse** (Location 6192)

---

> A case can be made that “in Sicily, the fundamental concepts of crusading were born.”
> 
> **Part III   Collapse** (Location 6206)

---

> There was a wave, then, rolling across the Mediterranean of religious war against the Muslims that aimed to subject their lands to the Church. It was only a matter of time until it set its sights on the east.
> 
> **Part III   Collapse** (Location 6208)

---

> The Byzantines (dangerously) tried to exploit this momentum and give it an outlet that would serve their interests. This brings us to the third constituent element of the First Crusade: the appeal for military aid from the eastern empire.
> 
> **Part III   Collapse** (Location 6215)

---

> Muslim conquests inflamed the Christian imagination.
> 
> **Part III   Collapse** (Location 6230)

---

> Gregory was willing to plan an expedition to save Byzantium, but only if it enabled him to conquer the eastern empire ecclesiastically, by subordinating its Church to his. When that prospect receded, he was just as willing to authorize Robert Guiscard to conquer Byzantium on the most specious of pretexts, in 1081, when the pope and the duke made up. Gregory made it clear that the planned war against Byzantium was a Just War, in religious terms, and excommunicated Alexios.
> 
> **Part III   Collapse** (Location 6242)

---

> Historians interested in Byzantine perceptions of the First Crusade have only Anna Komnene’s panegyrical history of her father, the Alexiad.
> 
> **Part III   Collapse** (Location 6257)

---

> Anna suggests that news of the crusaders’ imminent arrival took her father by surprise, and she suppresses his role in soliciting their services. For her they were basically a barbarian invasion.
> 
> **Part III   Collapse** (Location 6260)

---

> The Alexiad, then, does not necessarily represent all Byzantine views of the Crusade, or even Alexios’ policies toward it. To reconstruct those, we must draw conclusions from all the sources.
> 
> **Part III   Collapse** (Location 6265)

---

> Our sources love battles, not logistics and paperwork.
> 
> **Part III   Collapse** (Location 6313)

---

> which means they were being treated as a nominal Roman army from the start. The cost would have been prodigious for the Byzantine state and refutes any claim that Alexios did not “support” the crusaders. The latter were traveling with large amounts of funds, yet they were not gouged. To the contrary, the emperor showered their leaders with gold and expensive gifts from beginning to end. This was not how emperors reacted to invasions but rather how they treated potential clients, recruits to the imperial system. To judge from their behavior when they reached the capital, the dukes and counts understood this perfectly and largely consented to it.
> 
> **Part III   Collapse** (Location 6316)

---

> The nature and contents of the oaths sworn to Alexios have been much debated. The Latin chroniclers and many modern historians of the Crusade, being medievalists by training, view it instinctively within a western “feudal” framework.
> 
> **Part III   Collapse** (Location 6399)

---

> It is probably more correct to view the oath in the long Byzantine tradition of securing foreign armies and lords for imperial service, which flexibly accommodated their values.
> 
> **Part III   Collapse** (Location 6402)

---

> As for its clauses, the most specific was the obligation to surrender to Alexios any former Byzantine cities and territory that the crusade recovered from the enemy. It also made the emperor the nominal commander of the entire expedition.
> 
> **Part III   Collapse** (Location 6405)

---

> But what he had accomplished through his reception of the crusading armies was impressive. When they arrived, they had no overall leader and no definite strategy. They certainly intended to reach Jerusalem and do … something there, and freeing the Christians of the east, including of Asia Minor, was part of their original purpose. 52 Yet now they had an overall leader and at least a proximate set of goals before entering Syria: to defeat the Turks in Asia Minor, as Alexios directed, and to restore his empire there, after which they could move on (whether with or without him probably remained unclear).
> 
> **Part III   Collapse** (Location 6409)

---

> In fact, the decentralized origin of the First Crusade and convergence on Constantinople had left it with little choice but to accept Alexios as its leader.
> 
> **Part III   Collapse** (Location 6414)

---

> Alexios had probably gone as far as he could toward turning the crusade into an official imperial army.
> 
> **Part III   Collapse** (Location 6423)

---

> And, according to the oath, captured towns were to be turned over to the officers sent by Alexios, implying that his new “sons” did not formally count as officers of the Roman empire. 57 This fact proves that the arrangement was understood, at least by Alexios and likely also by Bohemond, to be temporary.
> 
> **Part III   Collapse** (Location 6432)

---

> The restoration of Roman Asia Minor was begun by the second wave of the crusade under Alexios, twenty years after he was last there as a general serving the Doukas regime.
> 
> **Part III   Collapse** (Location 6444)

---

> the crusade has largely been viewed as something separate from Byzantium, as only passing through. In fact, it was functioning largely as a Byzantine imperial army, and the role of Alexios himself needs to be rethought.
> 
> **Part III   Collapse** (Location 6447)

---

> In sum, the fact the army did not head directly for Antioch, but went on this long detour to restore the empire’s clients in Cappadocia-Armenia, suggests that its goal at this point was still a broader restoration of Christianity in the east under imperial direction, and not just Jerusalem.
> 
> **Part III   Collapse** (Location 6521)

---

> But what had Alexios and the Byzantines been doing while the crusaders marched on Antioch? One of the driving dynamics in the drama of the crusade is the alleged absence of the Byzantines.
> 
> **Part III   Collapse** (Location 6550)

---

> Did Alexios simply abandon the crusaders to their fate, as implied by his “absence,” while he consolidated his recent gains in Asia Minor?
> 
> **Part III   Collapse** (Location 6553)

---

> In fact, we know exactly what Alexios was doing in the meantime, and whether we see it as an “abandonment” of the crusade or not depends on how we view the crusade in 1097. In that year the crusade was not driven by a single-minded determination to reach Jerusalem, if it ever was. It fulfilled the original terms laid out by Urban, namely, to help the Christian communities of the east under Turkish rule and “to liberate the Churches of the East,” as the pope put it86— a broader conception. Also, it followed the instructions of Alexios in laying the foundations of an imperial restoration in the east.
> 
> **Part III   Collapse** (Location 6556)

---

> The Byzantine operations in the west in 1097– 1098, therefore, were entirely in keeping with the spirit and intent of the crusade— to rescue eastern Christians under Turkish rule— and should be reintegrated into its history (or it should be integrated into Byzantine history).
> 
> **Part III   Collapse** (Location 6567)

---

> In other words, the crusade did not leave Alexios behind at Nikaia and “strike out on its own.” Rather, it performed one part of a two-part operation across Asia Minor. Alexios did not “disappear,” as he does from some modern accounts. He also seems to have delivered on his promise to continue to supply the crusaders by sea.
> 
> **Part III   Collapse** (Location 6574)

---

> But it was at Philomelion that things went wrong, when crusaders fleeing from Antioch told Alexios that all was lost and persuaded him to turn back. Coupled with Bohemond’s cynical seizure of Antioch, which “spoiled the crusade for Alexios,” its history diverged at this point from that of an imperially managed operation.
> 
> **Part III   Collapse** (Location 6581)

---

> The crusade did not merely pass through Byzantium. It was Alexios who turned it into a single force and directed its movements and strategy all the way to Antioch;
> 
> **Part III   Collapse** (Location 6586)

---

> As for Byzantium, the crusade marked the moment after which it could no longer treat the west as a distant backwater. This was when Byzantium realized that the west had become quite a separate world of its own, propelled by novel tensions that it could not control. For the rest of its history, Byzantium would be surrounded and colonized, inspired and repulsed, engaged and destroyed by the west.
> 
> **Part III   Collapse** (Location 6589)