---
title: "Symphony for the City of the Dead"
author: M. T. Anderson
date: 2026-02-15
Rating: 8 / 10
---

### Highlights
> Shostakovich once said that the Leningrad Symphony was about “the Leningrad that Stalin destroyed and that Hitler merely finished off.”
> 
> **Prologue** (Location 107)

---

> It was called “the Window on the West,” because it was the most European of Russian cities. It was a city of the arts, a city of poetry, a city of music, a city of the sciences.
> 
> **PART ONE** (Location 126)

---

> In 1905, the year before Dmitri Shostakovich’s birth, his father supposedly joined a mass march on the tsar’s Winter Palace to support striking workers and demand justice and bread.
> 
> **PART ONE** (Location 160)

---

> Petrograd, the city of the arts, was wild with frenzied experimentation.
> 
> **PART ONE** (Location 446)

---

> “Blow up, destroy, wipe from the face of the earth all the old artistic forms,” cried the head of the Petrograd Committee of Enlightenment. “How can the new artist, the proletarian artist, the new man not dream of this?” New art, new music, and new drama had to be found for a new world where workers ruled.
> 
> **PART ONE** (Location 460)

---

> Petrograd swarmed with new art movements: Cubo-Futurists and Neo-Primitivists, Constructivists and Suprematists, Rayonists and Productivists.
> 
> **PART ONE** (Location 464)

---

> The relations between the cities of Moscow and Petrograd were changing. When Shostakovich was a child under the tsars, St. Petersburg — Petrograd — was the capital. After the Russian Revolution, Lenin decided that distant Moscow — with its medieval fortress and its ancient roots in older Russian government — should be the capital of the new Soviet Russia.
> 
> **PART ONE** (Location 660)

---

> Shostakovich’s Second and Third Symphonies (1927 and 1929, respectively) are built like the street-corner spectacles of the Futurists, complete with bellowed Communist songs at the end.
> 
> **PART ONE** (Location 701)

---

> What music should the working class, the proletariat, be listening to? (There was very little sense that they should just be able to decide for themselves.)
> 
> **PART ONE** (Location 823)

---

> Critics, however, were no longer as excited about experiment as they had been a couple of years earlier; now they complained that the crazed music was too bizarre, and even worse, “irrelevant to students [and] metal- and textile-workers.”
> 
> **PART ONE** (Location 835)

---

> the age of experimentation in Soviet Russia was over.
> 
> **PART ONE** (Location 838)

---

> In projects like these, Shostakovich adhered to the demands of the new style that was sweeping the arts in Soviet Russia, later called Socialist Realism.
> 
> **PART ONE** (Location 953)

---

> “The main attention of the Soviet composer must be directed towards the victorious progressive principles of reality, towards all that is heroic, bright, and beautiful.”
> 
> **PART ONE** (Location 957)

---

> A couple of days later, he telegrammed a friend in Moscow: “Remaining in Leningrad. Nina pregnant. Remarried. Mitya.”
> 
> **PART ONE** (Location 1094)

---

> The article threatened: “It is a game of clever ingenuity that may end very badly.”
> 
> **PART ONE** (Location 1140)

---

> While (despite claims to the contrary) there is no evidence that Stalin actually wrote “A Mess Instead of Music,” it is certain that he approved it.
> 
> **PART ONE** (Location 1144)

---

> What was this formalism? It literally means music, art, or writing that pays more attention to form and technique than to content.
> 
> **PART ONE** (Location 1167)

---

> “One after another, composers, directors, and critics who had all previously praised the opera [Lady Macbeth of Mtsensk District], got up to the podium and took back their earlier judgments.” They all admitted that “they had made an error, and only now had the Velikiy Vozhd, the Great Leader Stalin, opened their eyes.”
> 
> **PART ONE** (Location 1212)

---

> The great Sergei Prokofiev retreated from the spiky deviltry of his youthful style and escaped into the bright-colored worlds of fairy-tale ballet, adaptations of the classics, pieces for children (Peter and the Wolf), mass songs, and an abjectly fawning cantata in praise of Stalin:
> 
> **PART ONE** (Location 1302)

---

> The show trials were very public and were carefully stage-managed. Stalin wanted everyone to see proof of guilt, proof of the conspiracy that threatened to bring down the whole nation.
> 
> **PART ONE** (Location 1319)

---

> Perhaps most worrying for the orchestral players was the way the symphony ends. By the tenets of Socialist Realism, at the end of a work, there should be a sense of the sunlit Communist future. In the Fourth, after all the sneers and blows and japes, after the assaults and the postapocalyptic birdcalls and a poky funeral march that sounds as if the hearse is being led by a donkey — after almost an hour of kaleidoscopic travail — it seems as if finally, joy has been achieved.
> 
> **PART ONE** (Location 1343)

---

> And then, towering over all of it, a blaring and satanic anthem spreads its wings, obliterating everything.
> 
> **PART ONE** (Location 1349)

---

> the symphony ends, not with a vision of future hope through massed singing, but rather with whispered, eerie, shell-shocked numbness.
> 
> **PART ONE** (Location 1351)

---

> Through the transformation of tunes, symphonies like Shostakovich’s Fourth can tell stories without describing any specific events at all. For example, several themes from the work’s first movement that seem groping, wounded, or incompetent reappear as characters at the end of the symphony, now played as cheerful little street dances. Then they are squashed — silenced. It is clear they are acting out some drama.
> 
> **PART ONE** (Location 1392)

---

> Another one of his ex-girlfriends from his youth (Galina Serebryakova) was arrested and imprisoned for seventeen years. Two decades later, she spoke out about her imprisonment. In front of a crowded hall, she unfastened a couple of buttons and pointed to the torture scars on her back. Shostakovich was in the audience. Upon seeing the flesh he had once touched so tormented, he collapsed onto the floor.
> 
> **PART ONE** (Location 1446)

---

> Shostakovich’s uncle was arrested and disappeared. Shostakovich’s sister Maria and her husband were both arrested. Maria was exiled to Central Asia. Her husband was accused of terrorism and imprisoned in a work camp, where he died.
> 
> **PART ONE** (Location 1454)

---

> When the NKVD had finished purging other groups, then Stalin purged the NKVD itself.
> 
> **PART ONE** (Location 1520)

---

> “The papers were full of announcements like ‘I, So-and-so, announce that I have nothing to do with my father, enemy of the people So-and-so. I broke off with him ten years ago.’
> 
> **PART ONE** (Location 1546)

---

> At around this time, Shostakovich got an order to meet with an investigator at “the Big House,” the NKVD’s grim, modernist headquarters in Leningrad
> 
> **PART ONE** (Location 1632)

---

> over the weekend, Zakovsky had been condemned and arrested. His appointments had apparently been canceled.
> 
> **PART ONE** (Location 1658)

---

> The Leader had just participated in a plot with Hitler to cripple his own army. Meanwhile, Hitler trained one of the world’s most fearsome fighting forces — the German Wehrmacht — for war.
> 
> **PART ONE** (Location 1677)

---

> the purge liquidated or imprisoned about 60 or 70 percent of the officers in the Soviet military. Ninety percent of the generals had disappeared. Thirteen out of fifteen commanders of the army were gone.
> 
> **PART ONE** (Location 1694)

---

> In the month after Tukhachevsky’s death, Shostakovich wrote the symphony’s tragic slow movement. Supposedly, it took him only three days to write.
> 
> **PART ONE** (Location 1712)

---

> This phrase —“ a Soviet artist’s practical creative answer to just criticism”— was repeated again and again when the symphony made its way across the oceans to America.
> 
> **PART ONE** (Location 1800)

---

> “I think that it is clear to everyone what happens in the Fifth. The rejoicing is forced, created under threat. . . . It’s as if someone were beating you with a stick and saying, ‘Your business is rejoicing, your business is rejoicing,’ and you rise, shaky, and go marching off, muttering, ‘Our business is rejoicing, our business is rejoicing.’ . . . You have to be a complete oaf not to hear that.”
> 
> **PART ONE** (Location 1820)

---

> Sixth Symphony, which, though it began dark-hued and somber, ended in two fast, playful movements.
> 
> **PART ONE** (Location 1853)

---

> after Hitler secretly sent death squads to assassinate all his rivals in the Nazi Party — a bloodbath known as the Night of Long Knives — Stalin couldn’t help but admire his enemy’s ingenuity. “Did you hear what happened in Germany?” he gushed to an adviser. “Some fellow, that Hitler! Splendid! That’s a deed of some skill!”
> 
> **PART TWO** (Location 1950)

---

> Suddenly, the Soviet government, which had put citizens to death for collaboration with the Nazis, was warning people not to criticize the Nazis on pain of imprisonment.
> 
> **PART TWO** (Location 2009)

---

> Alexander Solzhenitsyn observed, “Not to trust anybody was very typical of Josef Stalin. All the years of his life did he trust one man only, and that was Adolf Hitler”—
> 
> **PART TWO** (Location 2088)

---

> The Luftwaffe was unopposed in the air. The Soviet air force didn’t have time to scramble. Their planes were still lined up neatly on their airfields, uncamouflaged, parked wingtip to wingtip. Within a few short minutes of Operation Barbarossa’s official launch, 738 Soviet aircraft had been destroyed without ever leaving the ground.
> 
> **PART TWO** (Location 2166)

---

> Shostakovich immediately decided that he, too, would sign up for military service. He wanted to be useful somehow, in a real and concrete way.
> 
> **PART TWO** (Location 2213)

---

> Shostakovich was turned down by the People’s Volunteers. An official told him, “You will be called when required.” His poor eyesight may have been the reason they gave. It is likely, however, that his application was rejected because of his celebrity. The government wanted to make sure he remained safe.
> 
> **PART TWO** (Location 2240)

---

> “Everything’s lost. I give up. Lenin founded our state and we crapped all over it.”
> 
> **PART TWO** (Location 2353)

---

> It was at this point in the Great Patriotic War that Stalin disappeared. He would not answer the phone. He hid at his house and did not respond to questions.
> 
> **PART TWO** (Location 2355)

---

> At the Hermitage Museum, once part of the palace of the tsars, hundreds worked to remove all the artwork so it could be shipped farther east, into the Ural Mountains, for safekeeping.
> 
> **PART TWO** (Location 2382)

---

> When he got to the plucky, ghastly little march that grew and grew, Glikman heard in it “the Fascist invasion.”
> 
> **PART TWO** (Location 2531)

---

> The composer was worried people might compare this repeated march with another popular piece, Maurice Ravel’s Bolero. “Well, let them,” he said. “That is how I hear war.”
> 
> **PART TWO** (Location 2541)

---

> The nine-hundred-day Siege of Leningrad — the longest siege in recorded history — had begun. The Shostakovich family — along with two and a half million others — were trapped.
> 
> **PART TWO** (Location 2614)

---

> On September 8, Shostakovich began work on the second movement of the symphony. It is a careful, wary dance movement, supposedly written to recall happier times in Leningrad. He considered calling it “Reminiscences” or “The Dream.”
> 
> **PART TWO** (Location 2645)

---

> The Leningrad city bosses had decided in their wisdom to store all of the city’s emergency food supplies in one place — a compound of thirty-eight old, wooden warehouses in the city’s southwest quadrant — the Bedayev warehouses. The Germans, having figured this out, had aimed their incendiary bombs right for them.
> 
> **PART TWO** (Location 2667)

---

> Someone in power had discovered that Shostakovich was writing a new symphony. Word came down that, to boost morale, he should talk about it on the radio.
> 
> **PART TWO** (Location 2823)

---

> The moment Shostakovich spoke over the radio, the story of the Seventh Symphony started to sparkle and to effervesce into myth.
> 
> **PART TWO** (Location 2913)

---

> A photo of him dressed in a firefighter’s uniform became one of the most enduring images of the Great Patriotic War. It is quite likely that this photo was staged, however, and it’s not even certain he typically wore this uniform,
> 
> **PART TWO** (Location 2916)

---

> They boiled belts and animal pelts. Unfortunately, treated leather, unlike rawhide, was saturated with polish and tanning chemicals. It took a long process of trial and error to learn how to cook a belt.
> 
> **PART TWO** (Location 3297)

---

> Operation Barbarossa, Hitler’s invasion of Russia, had been launched on the anniversary of Napoleon’s invasion. To Hitler’s generals, that detail now seemed gloomily prophetic.
> 
> **PART TWO** (Location 3349)

---

> “Of course — Fascism,” said Shostakovich. “But music, real music, can never be literally tied to a theme. [Nazism] is not the only form of Fascism; this music is about all forms of terror, slavery, the bondage of the spirit.”
> 
> **PART TWO** (Location 3425)

---

> it’s about the Leningrad that Stalin destroyed and that Hitler merely finished off.
> 
> **PART TWO** (Location 3434)

---

> Years later, Shostakovich, like most others, referred to the theme as “the ‘invasion’ episode.” That also, of course, means little, as it appeared in a magazine, and he often didn’t write his own articles.
> 
> **PART TWO** (Location 3441)

---

> “Within a single family . . . the order in which its members typically died was grandfather and infants first, grandmother and father (if not at the front) second, mother and older children last.”
> 
> **PART TWO** (Location 3520)

---

> The criminal profile of corpse-eaters was surprising. Only 2 percent had a previous criminal record. They were primarily women, uneducated females with no employment and no local Leningrad address. They were, in other words, often refugees who had fled to the city and who therefore did not have ration books at all. They had to make a choice between eating those already dead or dying themselves.
> 
> **PART TWO** (Location 3561)

---

> It appears that especially in late January and in February, when order utterly broke down in some districts of the city, there really were a few organized cannibal bands that hunted down lonely military couriers for food or lured people from bread lines and clubbed them over the head.
> 
> **PART TWO** (Location 3602)

---

> Zhdanov agreed that a performance of the piece in Shostakovich’s own city was vital for morale.
> 
> **PART TWO** (Location 3702)

---

> A legend circulated (and still persists) that Shostakovich wrote for such a large orchestra because he knew that all “the musicians performing the piece got a quadruple norm of food, and he knew that while they were rehearsing they would be fed better.”
> 
> **PART TWO** (Location 3757)

---

> Many disagreed with his generosity. Several American generals believed that the USSR was about to collapse. It seemed to them that any weaponry shipped to the Russians would soon be in German hands, helping the German cause.
> 
> **PART TWO** (Location 3786)

---

> “Stop acting like a Santa Claus, Chief! And let’s get something from Stalin in return.”
> 
> **PART TWO** (Location 3789)

---

> “We’ve lost millions of people, and they want us to crawl on our knees because they send us Spam.”
> 
> **PART TWO** (Location 3799)

---

> The opening strides forth confidently. If it is a portrait of a city, it is a city animated with purpose and pride. Then a second melody follows — this one gentle and tender, quiet. But it is at this point that the symphony itself is “invaded.”
> 
> **PART TWO** (Location 3823)

---

> Almost a million people escaped across Lake Ladoga in 1942, and 270,900 tons of food made it to the city over the ice that winter.
> 
> **PART TWO** (Location 3868)

---

> The Germans held the southern shore of the lake. They had a clear view and a clear shot to the Road of Life. The trucks made easy targets. German guns blasted at the convoys day and night.
> 
> **PART TWO** (Location 3882)

---

> This may explain the symphony’s somewhat eccentric route. We know now that the box of microfilm took an epic and surprising journey.
> 
> **PART TWO** (Location 4000)

---

> The microfilm landed in Recife, Brazil, at a landing field that was, at that point, only a few metal Quonset huts.
> 
> **PART TWO** (Location 4016)

---

> The Am-Rus Music Corporation finally anointed conductor Arturo Toscanini — a noted anti-Fascist — for the piece’s American premiere.
> 
> **PART TWO** (Location 4030)

---

> A painting of Shostakovich appeared on the front of Time magazine — the first composer ever to make it onto the cover.
> 
> **PART TWO** (Location 4039)

---

> Everything in the article is designed to suggest that Shostakovich is really just like an American dad reading Time, sprawled on his sofa.
> 
> **PART TWO** (Location 4048)

---

> Many critics were unimpressed with the piece.
> 
> **PART TWO** (Location 4058)

---

> It did not produce the Second Front that Stalin hoped for so desperately. In the summer of 1942, the Allies were stretched too thin to think of attacking the Germans on European soil. Stalin was furious, but the British and American forces would delay the Second Front until 1944.
> 
> **PART TWO** (Location 4103)

---

> Shostakovich’s symphony was the most visible element of a wider program to convince the public that assisting Russia at that desperate point in the war was essential. By January 1943, polls showed that 90 percent of Americans believed that food aid to Russia should be increased, even at the expense of domestic food supplies. Just a year and a half before, the Soviet Union had been viewed as an enemy.
> 
> **PART TWO** (Location 4107)

---

> The final note in the orchestral logbook reads: “Rehearsal did not take place. Srabian is dead. Petrov is sick. Borishev is dead. Orchestra not working.”
> 
> **PART TWO** (Location 4131)

---

> went from door to door, trying to find out which of his musicians still remained alive.
> 
> **PART TWO** (Location 4135)

---

> The first rehearsal was scheduled to last for three hours. They broke up after fifteen minutes.
> 
> **PART TWO** (Location 4154)

---

> It called for a huge orchestra of more than a hundred players. He had only fifteen, and they were near death.
> 
> **PART TWO** (Location 4158)

---

> Decomposing, dismembered corpses in the streets that had been hidden under the ice. Severed legs with meat chopped off them. Bits of bodies in the bins. Women’s bodies with breasts cut off, which people had taken to eat. They had been buried all winter but there they were for all the city to see how it had remained alive.”
> 
> **PART TWO** (Location 4202)

---

> The piece was so long they never once played it all the way through until the dress rehearsal, three days before the performance.
> 
> **PART TWO** (Location 4214)

---

> Three of the orchestral players died before they ever got to play the piece in full.
> 
> **PART TWO** (Location 4220)

---

> the Grand Philharmonia Hall would be an obvious target for bombing — lit up in the midst of a blackout. To ensure the performance would not be interrupted, he launched a diversionary attack on German lines on the opposite side of the city.
> 
> **PART TWO** (Location 4228)

---

> The army had set up speakers to blare it across no-man’s-land at the enemy lines, where German soldiers huddled in their trenches and gun emplacements.
> 
> **PART TWO** (Location 4256)

---

> In 1992, on the fiftieth anniversary of the Leningrad performance, the same orchestra was called together in the same hall to play the piece again. By that time, only fourteen of them remained alive.
> 
> **PART TWO** (Location 4303)

---

> he was writing his Eighth Symphony. It is a powerfully distressed piece, unremitting in its depiction of war.
> 
> **PART THREE** (Location 4343)

---

> when they requested music for a dance number about soccer. “May I compose the music for ‘Soccer,’ if you have nothing against it?” he asked. A colleague mused, “I don’t know why he was so keen on writing soccer music. He was a funny man. . . .”
> 
> **PART THREE** (Location 4359)

---

> On April 12, the German Philharmonic Orchestra held its last concert in Berlin — a counterpart to the performance of the Seventh Symphony in Leningrad. But the music they played was the end of a piece by Wagner depicting the twilight of the old German gods, and their sacred stronghold, Valhalla, burning.
> 
> **PART THREE** (Location 4412)

---

> In February of 1948, Leningrad Communist Party boss Andrei Zhdanov called together prominent musicians, composers, and musicologists to discuss Soviet music and present them with a decree. He condemned “formalism” in modern music; he complained that the music of “anti-people” composers such as Shostakovich and Prokofiev sounded like “a piercing road drill, or a musical gas-chamber.” It was a return to the attacks of 1936 and “A Mess Instead of Music.”
> 
> **PART THREE** (Location 4481)

---

> they pointed out that when Russia was losing the war, he wrote his triumphant Seventh, whereas when the tide of war shifted and Russia began to win, he wrote his gloomy, despairing Eighth.
> 
> **PART THREE** (Location 4491)

---

> When members of the Politburo arrived, none of them wanted to call a doctor, since Stalin had recently accused several prominent doctors of murder. (His own doctor was being tortured at the time.)
> 
> **PART THREE** (Location 4556)

---

> Shostakovich wrote his Tenth Symphony, which contains his musical monogram — the letters DSCH — played secretly, yet defiantly, as notes in a tune. At first, he calls out his own name with anxiety, until, late in the symphony, it returns in triumph, as if he is finally able to shout, “I AM DMITRI SHOSTAKOVICH! I AM DMITRI SHOSTAKOVICH!”
> 
> **PART THREE** (Location 4573)

---

> In 1960, he was forced to join the Communist Party. He broke down sobbing.
> 
> **PART THREE** (Location 4587)

---

> he was writing his series of string quartets, a “diary” that, according to his wife, spelled out “the story of his soul.” As he grew older, the story told in the quartets grew stranger and more remote.
> 
> **PART THREE** (Location 4610)

---

> He kept composing even when hospitalized and very sick. The rest of the time, he watched soccer on television.
> 
> **PART THREE** (Location 4619)

---

> As musicologist Richard Taruskin mused, “Testimony may be authentic and true, or inauthentic and false, or authentic but false, or even inauthentic but true.”
> 
> **Author’s Note** (Location 4688)

---

> he had to create speech that was silent, and silence that spoke.
> 
> **Author’s Note** (Location 4703)