---
title: "The War for Gaul"
author: Julius Caesar
date: 2026-03-23
Rating: 9 / 10
---

### Highlights
> Cormac McCarthy should be the one to write the story of Caesar in Gaul. As insensitive and brutal as McCarthy’s Americans afoot in a land of native and Spanish peoples they wrongly took for uncivilized, Caesar’s armies had little excuse for what they did and they preferred not to remember it once done.
> 
> **Introduction** (Location 41)

---

> Books about war often make us sympathize with the wretchedness of the victims. This one forces us to be Romans of the kind its author wanted to be.
> 
> **Introduction** (Location 54)

---

> The old maxim is ars est celare artem—“ never let ’em see you sweat” captures the sense of that shopworn Latin phrase.
> 
> **Introduction** (Location 69)

---

> In fact, readers should pay particular attention to the Haedui throughout, just as readers of Thucydides should always keep an eye on the Corinthians.
> 
> **Introduction** (Location 95)

---

> Caesar’s own creation of “Gaul” was a long-, long-lasting achievement. His Gaul is roughly today’s France, his Germania roughly today’s Germany.
> 
> **Introduction** (Location 129)

---

> The victory is won when the defeated commander decides not to risk another battle.
> 
> **Introduction** (Location 137)

---

> The atrocities of war that we will review in these years were strategically vital to Rome’s success. They showed the Gauls that a civilized people would stop at nothing to secure their conquest of the barbarians.
> 
> **Introduction** (Location 149)

---

> The curious fact of Roman history, to which Caesar is no exception, is that hostage-taking very, very rarely led to any harm befalling the hostages.
> 
> **Introduction** (Location 202)

---

> The Latin word barbarus echoes Greek βάρβαρος, supposedly onomatopoetic for the inarticulate babbling of the uncivilized.
> 
> **Introduction** (Location 211)

---

> To be sure, Caesar’s Julii were an old family of the good sort, faded away into mere respectability. None of his real ancestors had done anything noteworthy in a couple of hundred years.
> 
> **Introduction** (Location 235)

---

> (If Cicero was the quintessential “new man” from a family that had never known power, we should think of Caesar as new-from-recycled-materials.)
> 
> **Introduction** (Location 239)

---

> Sulla advanced Marius’ strategy for self-aggrandizement by inventing the practice of offering his troops the prospect of land ownership (most of them now were too poor to own anything) if they served him long enough and well enough. A Roman general who returned successfully from war was acclaimed with the title imperator. From Sulla forward, imperatores mattered increasingly more than consuls.
> 
> **Introduction** (Location 252)

---

> It’s important to realize that in Pompey’s decade and a half Caesar was always the rising star. He never had any military achievement to match that of Pompey, not even his defeat of Vercingetorix in 52— a defeat the book you are about to read rather magnifies, undoubtedly to ensure that Caesar’s greatness would equal Pompey’s.
> 
> **Introduction** (Location 283)

---

> In these shabby years, the two most important bad boy might-have-beens of Caesar’s age both came to bad ends, Catiline and Clodius. Caesar was astute enough to use them, in some ways even support them, but to escape their fate.
> 
> **Introduction** (Location 296)

---

> Catiline could have been a somebody in Roman politics, but he was headstrong and impatient.
> 
> **Introduction** (Location 303)

---

> What is clear is that Caesar came closer than any other senator to supporting Catiline, speaking up, in Cicero’s hour of histrionics, for moderation and restraint, speaking against the death penalty.
> 
> **Introduction** (Location 316)

---

> Clodius was another crowd-pleaser with poor impulse control. In December 62, enamored of Caesar’s wife (Pompey’s daughter), he tricked himself out in drag and slipped into Caesar’s house during the festival of the Good Goddess (Bona Dea), which was a ladies-only event. A serving girl detected him and raised an alarm. This was the opportunity for Caesar to divorce his wife with the famous remark that Caesar’s wife should be above suspicion.
> 
> **Introduction** (Location 331)

---

> Clodius was now willing to front for Caesar in pleasing the mob without Caesar needing to take responsibility for Clodius’ acts.
> 
> **Introduction** (Location 337)

---

> If we view Cicero not from his point of view but from Caesar’s, the sequence of Caesar’s acts amounted to excellent management— that is to say, defanging— of Cicero and his possibility for serious mischief.
> 
> **Introduction** (Location 360)

---

> Three or four secretaries or agents waited on him at all times and we get the story that he dictated letters while on horseback, sometimes several at once.
> 
> **Introduction** (Location 413)

---

> Suetonius12 assessed his work and saw only three real reverses that he faced in his nine years: almost losing his ships in a storm off Britain, the losses of the legates Sabinus and Cotta and many of their troops in the ambushes of 54, and the loss of a legion in battle at Gergovia during the great uprising of 52, followed by the great victory at Alesia that brought the insurgency of Vercingetorix to an end.
> 
> **Introduction** (Location 416)

---

> If a modern therapist got him on the couch, he would have to address the paradox of voracious appetite, especially sexual and probably bisexual, but also relentless self-discipline to the point of ascetic austerity.
> 
> **Introduction** (Location 454)

---

> Cicero says Caesar always had a couplet of Euripides’ Phoenissae in mind, which he renders roughly “if you must break the law, break it for the sake of being a king: otherwise behave yourself.”
> 
> **Introduction** (Location 466)

---

> The only people he seems not to have been able to buy were Cato and his circle.
> 
> **Introduction** (Location 474)

---

> Cicero found this an embarrassment in 51/ 50 when, still in debt to Caesar from a loan in probably 54, he tried to give the money back and Caesar wouldn’t have it— keeping him on the string. And in 50 Cicero hesitated to speak up against Caesar for fear that Caesar’s man of affairs Balbus would turn up shortly after to call the debt at an unsustainable moment.
> 
> **Introduction** (Location 476)

---

> Cicero, into whose hands a fair amount of Caesarean money fell, was censorious in his On Duties (De officiis), written a few months after the Ides of March, saying that generosity was one thing, but distribution of ill-gotten gains had nothing generous about it.
> 
> **Introduction** (Location 485)

---

> Because the Latin term “commentarius” has a long later history in English, we usually leave the word to be rendered by its cognate, but in its time the word came closer in sense to “memorandum” or “notebook,” in the sense of an informal document recording factual material.
> 
> **Introduction** (Location 488)

---

> The least that must be said is that the commentarii are highly selective and narrowly focused.
> 
> **Introduction** (Location 503)

---

> The most famous feature of the book, of course, is the third-person narrative.
> 
> **Introduction** (Location 511)

---

> the narrative has no future— no anticipation of his plans beyond the tactics of a single battle, no hint of future events that at the time of writing he already certainly knew. We are meant to feel that we are there in Gaul, with the troops, amid the events of the moment, as blind to the future as the army was.
> 
> **Introduction** (Location 517)

---

> So when were they written? Scholarly wars on the scale of Caesar and the Nervii can be fought over this subject. There are partisans for annual publication and for all-at-once production.
> 
> **Introduction** (Location 520)

---

> The great bridge over the Rhine in the fourth commentary generally gets a special page or two of diagrams.
> 
> **Introduction** (Location 586)

---

> This map is intentionally drawn to approximate the knowledge that a Roman reader might have or have drawn from reading Caesar. It is still much too accurate for its purpose, showing the land masses, mountains, rivers, and seas as accurately as moderns know how to represent them.
> 
> **Map of Gaul** (Location 676)

---

> The three generalissimos dandling the empire on their knees would all die violently— Crassus with his army in 53, Pompey on the run from Caesar in 49, and Caesar at the base of a statue of Pompey in 44.
> 
> **FIRST COMMENTARY: 58 BCE** (Location 696)

---

> Caesar very consciously chose to be alarmed and take action when he heard that the Helvetians (a name we never translate, though we very reasonably could, as “Swiss”) were restless in their lands north of lake Geneva and were packing up to move to the west of Gaul, quite a bit further out of Roman way than where they already lived.
> 
> **FIRST COMMENTARY: 58 BCE** (Location 734)

---

> Led by Ariovistus, whom Caesar had recognized the year earlier in his consulship as a friend of the Roman people, this was a warband that had elbowed across the Rhine to pillage and intrude upon the Sequani along the river south of Strasbourg.
> 
> **FIRST COMMENTARY: 58 BCE** (Location 750)

---

> On Caesar’s telling, Ariovistus was the wicked German enemy of Gallic peace, but we can see that he was also a player in a very domestic Roman political story.
> 
> **FIRST COMMENTARY: 58 BCE** (Location 754)

---

> What is ostensibly a story about Germans is also a story about domestic Roman politics.
> 
> **FIRST COMMENTARY: 58 BCE** (Location 757)

---

> (This is the first of four moments for the tenth legion in the commentaries where they appear as the favorite child.
> 
> **FIRST COMMENTARY: 58 BCE** (Location 761)

---

> Observe now Caesar’s dealings with the Haedui, powerful and influential in central Gaul, with a capital city called Bibracte not far from modern Autun in Burgundy. They had “friended” (as we now say) the Helvetians, but washed their hands of them as they went down to disaster. Then most importantly it was they who put Caesar on the warpath against Ariovistus. The story of the threat to Gallic stability by the German wild men is all theirs. When all is done for Caesar, after many vicissitudes, the Haedui will prove to be doing just fine. Caesar never lets on that he knows their game.
> 
> **FIRST COMMENTARY: 58 BCE** (Location 781)

---

> The toughest of all are the Belgians, because they are farthest from our province, its culture, and its manners, and because merchants reach them least often bringing things that make men womanly.
> 
> **FIRST COMMENTARY: 58 BCE** (Location 792)

---

> After his death, the Helvetians still undertook to carry out their decision to leave their own country. When they thought they were ready, they set fire to all their towns (a dozen of them), their villages (some 400), and all their private farmhouses. They burned up all their grain except what they would take with them, to make them readier to face every danger for knowing there was no hope of returning home.
> 
> **FIRST COMMENTARY: 58 BCE** (Location 819)

---

> There were 263,000 Helvetians, 36,000 Tulingi, 14,000 Latobrigi, 23,000 Rauraci, 32,000 Boii; of these, 92,000 could bear arms. The total of all came to 368,000. When a census Caesar ordered was held after they returned home, the number was found to be 110,000.
> 
> **FIRST COMMENTARY: 58 BCE** (Location 994)

---

> Caesar, by reputation (his own and the army’s), by fresh victory, and in the name of the Roman people, could keep a greater mass of Germans from being brought across the Rhine and could protect all Gaul from Ariovistus’ depredations.
> 
> **FIRST COMMENTARY: 58 BCE** (Location 1024)

---

> To that embassy Ariovistus replied: If he needed anything from Caesar, he would go to him; if Caesar wanted anything, he should come to him.
> 
> **FIRST COMMENTARY: 58 BCE** (Location 1040)

---

> He was surprised that Caesar or indeed the Roman people should have any business in his Gaul, which he had won in combat.
> 
> **FIRST COMMENTARY: 58 BCE** (Location 1043)

---

> Ariovistus replied: It was the law of war that conquerors command the conquered as they wish. The Roman people was equally accustomed to commanding their vanquished as they chose, not as others prescribed. If Ariovistus did not tell the Roman people how to use its authority, he should not be kept from exercising authority by the Roman people. The Haedui had risked war, clashed at arms, and been overcome, so now they were his tributaries.
> 
> **FIRST COMMENTARY: 58 BCE** (Location 1052)

---

> one of the soldiers of the tenth not unfacetiously said Caesar had done more than he promised. He promised to make the tenth his praetorian guard, but enrolled it among the knights instead.
> 
> **FIRST COMMENTARY: 58 BCE** (Location 1113)

---

> If Ariovistus killed him, he would do a favor for many nobles and leaders of the Roman people— he’d been told this directly by their own messengers. He could win their friendship and influence by killing Caesar.
> 
> **FIRST COMMENTARY: 58 BCE** (Location 1140)

---

> When Caesar asked prisoners why Ariovistus wouldn’t fight, he found out that the custom with the Germans was for the mothers to cast lots and read signs to proclaim whether it was time to engage or not. They had said the Germans would not win if they joined battle before the new moon.
> 
> **FIRST COMMENTARY: 58 BCE** (Location 1176)

---

> Procillus said they had cast lots over him three times in his presence, to see whether to burn him alive at once or hold him for another day, and he was saved by virtue of the lots.
> 
> **FIRST COMMENTARY: 58 BCE** (Location 1197)

---

> Pompey was granted a five-year term— effectively a five-year monopoly on a role as the most visible and generous benefactor of the urban populace.
> 
> **SECOND COMMENTARY: 57 BCE** (Location 1269)

---

> This is one of very few places in Caesar’s account where he lets us see him turning his campaign into significant financial advantage for himself.
> 
> **SECOND COMMENTARY: 57 BCE** (Location 1291)

---

> Even if we were to discount the number 53,000 by 50 or 80 percent as a mental exercise, managing such a mob on its path to immiseration was a considerable logistical effort, one that made its own impression on all those who saw the trains of the recently enslaved trudging past.
> 
> **SECOND COMMENTARY: 57 BCE** (Location 1295)

---

> When his report that all Gaul had been pacified arrived, his management of public opinion at a distance won him a formal thanksgiving decreed by the Senate amounting to fifteen days’ holiday, three times the usual number.
> 
> **SECOND COMMENTARY: 57 BCE** (Location 1298)

---

> Caesar would make the claim of total pacification several more times, unembarrassed then when the next uprising broke out.
> 
> **SECOND COMMENTARY: 57 BCE** (Location 1301)

---

> The thanksgiving decree effectively put a seal of approval on the whole of Caesar’s unlicensed escapades.
> 
> **SECOND COMMENTARY: 57 BCE** (Location 1302)

---

> Caesar encouraged the Remi and spoke to them generously,
> 
> **SECOND COMMENTARY: 57 BCE** (Location 1332)

---

> our forces killed as many of them as the day was long,
> 
> **SECOND COMMENTARY: 57 BCE** (Location 1379)

---

> they allowed import of no wine or other luxury goods, because they thought these things weakened spirits and diminished courage. They were fierce and very brave, criticizing and accusing the other Belgae for surrendering to the Roman people and throwing away their ancestral courage.
> 
> **SECOND COMMENTARY: 57 BCE** (Location 1400)

---

> After this battle, the Nervii were almost destroyed in name and race.
> 
> **SECOND COMMENTARY: 57 BCE** (Location 1474)

---

> Recounting the calamity to their nation, they said they were reduced from 600 to three senators, from 60,000 people to scarcely 500.14
> 
> **SECOND COMMENTARY: 57 BCE** (Location 1477)

---

> Next day the gates were broken— no one defended them now— and our soldiers entered and Caesar sold the whole town in one auction lot. The buyers reported the number enslaved at 53,000.
> 
> **SECOND COMMENTARY: 57 BCE** (Location 1507)

---

> The first half-dozen paragraphs of his account of this year really belong to the narrative of the preceding year, whose story extended into late November. They are postponed for rhetorical effect, to allow that narrative of the second commentary to conclude with victory and thanksgiving.
> 
> **THIRD COMMENTARY: 56 BCE** (Location 1542)

---

> The meeting was held on about the seventeenth of April and a deal was quickly done. First, the consular election for 55 must be carried successfully for Pompey and Crassus, and so Caesar would release some of his men to come down to Rome in the winter to offer their votes and their intimidating presence in support of the chosen candidates. In return, Caesar’s command would be extended another five years, after which he could stand for election to be consul again in 48. Both Pompey and Crassus would have extended governorships of their own coming out of their next consular year. (Pompey took Spain, with no intention of actually going there, while Crassus accepted Syria as a base of operations for what he expected would be his own great military adventure against the Parthians.)
> 
> **THIRD COMMENTARY: 56 BCE** (Location 1563)

---

> Cicero believed that the virtuous and educated man who could hold a crowd with his words was the ideal leader for Roman society, and he wrote this and several other books on that theme in just the years when it was becoming clear that he was completely and entirely wrong.
> 
> **THIRD COMMENTARY: 56 BCE** (Location 1598)

---

> The whole of their senate was killed and the rest of them sold into slavery.
> 
> **THIRD COMMENTARY: 56 BCE** (Location 1711)

---

> Given old prejudices about theaters, actors, and immorality, the temple’s presence in the complex mitigated the presence of a permanent theater in the eyes of traditionalists.
> 
> **FOURTH COMMENTARY: 55 BCE** (Location 1822)

---

> a separate law extended Caesar’s time in Gaul by five years. Just how that five years would be counted was a matter of disagreement from then until the civil war of 49 broke out, and modern scholars are scarcely less divided. It would appear that the law, improbably, did not set an explicit end date.
> 
> **FOURTH COMMENTARY: 55 BCE** (Location 1833)

---

> Caesar’s story is blunt and painful. He defeated them without loss of Roman life while his men slaughtered some vast number of the enemy. Caesar is quite barefaced in asserting the intention and the achievement of slaughter, so much so that he happily exaggerates.
> 
> **FOURTH COMMENTARY: 55 BCE** (Location 1840)

---

> What we can take away from the episode is that Caesar had the chance to act ruthlessly and did so and wanted it known that he had acted with no limits and no leniency to destroy an enemy force.
> 
> **FOURTH COMMENTARY: 55 BCE** (Location 1849)

---

> The main thing to recall about this bridge is that Caesar didn’t need one— boats would have done just fine—, but there was ostentation to begin with in building the bridge (to impress the local population) and ostentation again in talking about it in great deal in his report of the year. The self-praise has had its desired effect.
> 
> **FOURTH COMMENTARY: 55 BCE** (Location 1857)

---

> Slaughtered enemies and going boldly where no Roman had gone before were not enough for Caesar, however, and so he took one more cast at Pompey-rivaling glory this year, achieving another anticlimax. He made for Britain.
> 
> **FOURTH COMMENTARY: 55 BCE** (Location 1866)

---

> Just how much Caesar knew of Britain is hard to read, for we can barely surmise who and how reliable his sources might have been.
> 
> **FOURTH COMMENTARY: 55 BCE** (Location 1868)

---

> The crossing to Britain, both this year and in 54, was challenging for Caesar for several reasons. The tides and currents of the open ocean were hard for Romans to imagine and manage when all their sea experience came from the tideless Mediterranean. Heavy-laden rowing ships were anything but nimble in the waters of the English Channel. On both trips, Caesar’s arrival in Britain put him at some disadvantage, which he describes, both in terms of position and condition of his ships. He took two legions on this trip, the tenth and the seventh, quickly realized that he had no force with which to do anything, and made his way back to Gaul by late September.
> 
> **FOURTH COMMENTARY: 55 BCE** (Location 1877)

---

> it was this book, not whatever happened on that shore, that created the glory.
> 
> **FOURTH COMMENTARY: 55 BCE** (Location 1885)

---

> Cato, winning a praetorship for 54 in the same election as Ahenobarbus, proposed handing Caesar over to the Germans in expiation for this year’s massacre but found no support for his outrage.
> 
> **FOURTH COMMENTARY: 55 BCE** (Location 1897)

---

> After the German war, Caesar for many reasons decided he should cross the Rhine, especially because he saw how easily Germans were persuaded to come over to Gaul. He wanted them to fear for their own property, realizing that the Roman people’s army could and would cross the Rhine.
> 
> **FOURTH COMMENTARY: 55 BCE** (Location 1984)

---

> He designed the bridge thus:
> 
> **FOURTH COMMENTARY: 55 BCE** (Location 1996)

---

> Ten days after lumber began to be assembled, the job was done and the army brought over.
> 
> **FOURTH COMMENTARY: 55 BCE** (Location 2005)

---

> With little of summer left and though the winters here come early, Caesar still made to set out for Britain, because he knew help came from there to our enemies in just about all the Gallic wars.
> 
> **FOURTH COMMENTARY: 55 BCE** (Location 2016)

---

> So the difficulty was immense because the ships— for their size— could only halt in deep water, but the soldiers, in strange territory, their hands full, burdened with large, heavy weapons, had to jump from the ships, find their feet in the waves, and fight the enemy all at once, while the others had hands free to hurl weapons fearlessly and spur on their experienced horses either from dry land or going a little ways into the water, knowing the ground well. Terrified and completely inexperienced at this kind of fighting, our men did not show the enthusiasm and zeal they bring to land fighting.
> 
> **FOURTH COMMENTARY: 55 BCE** (Location 2049)

---

> the eagle-bearer of the tenth legion, praying the gods that it would go well for the legion, said “Jump, comrades, unless you want to hand over the eagle to the enemy. I will surely have done my duty to the republic and our general!”
> 
> **FOURTH COMMENTARY: 55 BCE** (Location 2057)

---

> As our men made dry land and their comrades followed, they attacked the enemy and put them to flight, but were unable to go farther because the cavalry had not been able to hold course and reach the island. In this one thing his old luck failed Caesar.
> 
> **FOURTH COMMENTARY: 55 BCE** (Location 2065)

---

> The moon happened to be full that night, which habitually makes the highest tides on the ocean, but our men did not know that. So the ships Caesar had brought ashore were filled with waves at the same time the storm pounded the ones lashed at anchor. Our men had no way of managing or helping them.
> 
> **FOURTH COMMENTARY: 55 BCE** (Location 2078)

---

> Knowing this, the British chiefs who had come to Caesar after the battle talked among themselves, seeing the Romans short of cavalry, ships, and grain and knowing how few soldiers were there by how small were the camps, smaller still because Caesar had crossed the legions without their usual baggage.
> 
> **FOURTH COMMENTARY: 55 BCE** (Location 2084)

---

> During the winter, Caesar also found time to study Cicero’s On the Orator. It was both a work about rhetoric but also a veiled manifesto about a Roman political system in which the qualities of what old Cato had called the “good man skilled at speaking” mattered more in leaders than proficiency at conquest and plunder. Caesar took the work so seriously that he used his time in these months to write his own learned and polished reply De analogia (On Analogy). The work espoused a view of language more austere, rational, and disciplined than was usually to be found in old crowd-pleasers like Cicero. Caesar himself was much less frequently than Cicero on stage as a speaker, but was nonetheless highly successful and both widely and deeply well-read besides. Suetonius tells us that the work was written while Caesar was on the way from hearing cases in northern Italy back to his army. We should agree with Suetonius that the discipline and focus required to do this were impressive, if the story is true.
> 
> **FIFTH COMMENTARY: 54 BCE** (Location 2168)

---

> (Pliny the elder reports that Caesar could write, with relays of secretaries, as many as seven letters at one time.)
> 
> **FIFTH COMMENTARY: 54 BCE** (Location 2188)

---

> Caesar returned to Britain with five legions in August and September. This visit left more time for exploration and skirmishes with the locals, but in fact was as fruitless as the first.
> 
> **FIFTH COMMENTARY: 54 BCE** (Location 2197)

---

> Caesar tells frankly the memorable story of the disaster that ensued. The Eburones under Ambiorix attacked and massacred one and a half legions in the winter quarters closest to them.
> 
> **FIFTH COMMENTARY: 54 BCE** (Location 2204)

---

> The Nervii not far away took heart and besieged Quintus Cicero in his camp (using siegework tactics they had learned by imitating what Caesar did to them earlier in the war) until the general came rushing in pell-mell to the rescue with two under-strength legions: Caesar was quite the hero.
> 
> **FIFTH COMMENTARY: 54 BCE** (Location 2207)

---

> The island is a triangle, one side facing Gaul. One corner on this side, by Kent, where almost all ships from Gaul come ashore, looks to the rising sun, while the lower corner looks south.
> 
> **FIFTH COMMENTARY: 54 BCE** (Location 2318)

---

> But Gaul was of one mind: this day was set for attacking all Caesar’s winter camps, so no legion could come to the aid of another.
> 
> **FIFTH COMMENTARY: 54 BCE** (Location 2410)

---

> Then the leaders and princes of the Nervii who could approach Cicero with some claim of friendship said they wished to speak with him. Permission granted, they argued the same as Ambiorix had done to Sabinus. All Gaul was in arms, the Germans had crossed the Rhine, the winter quarters of Caesar and the others were assailed.
> 
> **FIFTH COMMENTARY: 54 BCE** (Location 2494)

---

> Some messengers were caught and tortured to death in sight of our soldiers.
> 
> **FIFTH COMMENTARY: 54 BCE** (Location 2527)

---

> Then he convinced a Gallic cavalryman with a large bribe to take a message to Cicero. He sent it written in Greek characters, 27 so our plans would not be understood by the enemy if intercepted. If he could not reach Cicero, Caesar advised him to tie the message to a throwing spear’s strap and throw it into the fort.
> 
> **FIFTH COMMENTARY: 54 BCE** (Location 2543)

---

> praised Cicero and the legion deservedly. He praised individually by name the centurions and tribunes whose great courage he learned from Cicero’s account.
> 
> **FIFTH COMMENTARY: 54 BCE** (Location 2570)

---

> He decided to stay with the army all winter, because the uprisings in Gaul had been so considerable.
> 
> **FIFTH COMMENTARY: 54 BCE** (Location 2578)

---

> After the disastrous loss of Sabinus and his men, Caesar left his hair and beard to grow until he had taken vengeance.
> 
> **SIXTH COMMENTARY: 53 BCE** (Location 2690)

---

> the commentary on the year 53 is remarkable for its extensive ethnographic description of Gauls and Germans and their ways of life.
> 
> **SIXTH COMMENTARY: 53 BCE** (Location 2692)

---

> The patronizing ethnographic tone has the effect of firmly distancing the Gauls from the Romans, not merely as “other” but as fundamentally different in kind, as living in a very different world from the Romans.
> 
> **SIXTH COMMENTARY: 53 BCE** (Location 2696)

---

> When he comes to the Germans, he begins unreliably and veers off into sheer fantasy by the time he is done.
> 
> **SIXTH COMMENTARY: 53 BCE** (Location 2698)

---

> Crassus doubtless thought himself the new Alexander, but when faced with Parthian archers, his imagination failed him. He expected the Parthians to run out of arrows, but they did not.
> 
> **SIXTH COMMENTARY: 53 BCE** (Location 2721)

---

> The poet Lucan a century later would say that the problem was that Caesar could not stand to have anyone rank ahead of him in Roman politics and Pompey could not stand to have anyone his equal.
> 
> **SIXTH COMMENTARY: 53 BCE** (Location 2728)

---

> In all Gaul, two sorts of men stand out in rank and esteem. (For commoners are treated almost like slaves, venturing nothing on their own, being asked no advice. Many, oppressed by debt or huge levies or vengeful potentates, swear themselves into service to nobles who have all the rights over them that masters have with slaves.) One of these two sorts are the druids, the other the knights.
> 
> **SIXTH COMMENTARY: 53 BCE** (Location 2823)

---

> The druids rule on almost all public and private disputes and if there is a case of a crime committed, a murder done, or a suit about inheritance or property, they decide it and set rewards and penalties.
> 
> **SIXTH COMMENTARY: 53 BCE** (Location 2827)

---

> They think it wrong to write these things down, while in most other matters, both public and private records, they use Greek writing. They seem to do this for two reasons: because they did not want the teaching spread among the masses and did not want learners to trust in writing and pay less attention to memory. It is often the case for many that reliance on writing reduces attention to learning and memory.
> 
> **SIXTH COMMENTARY: 53 BCE** (Location 2838)

---

> The whole nation of Gauls is much devoted to rituals, so those who suffer serious illness or face battle and danger either sacrifice human victims or promise to do so and use the druids as ministers of these sacrifices.
> 
> **SIXTH COMMENTARY: 53 BCE** (Location 2847)

---

> When a well-born paterfamilias dies, his relatives assemble and, if there is suspicion about the death, they interrogate wives as they would slaves. If they find something, they torture them with fire and rack, then kill them.
> 
> **SIXTH COMMENTARY: 53 BCE** (Location 2867)

---

> Like Jets and Sharks, the two groups passed each other, exchanging words and gestures of defiance and contempt. As they had almost passed each other, a fight broke out and Clodius was wounded by a javelin throw from the other side. His gang was routed from the scene and his fate was entirely in Milo’s hands.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3080)

---

> Clodius’ funeral the next day then turned into the sort of incident that civil wars can spring from. His widow first had his body exposed to public view in the Forum on the rostra, the place where orators addressed citizens and mobs. Egged on from there by the widow and sympathetic tribunes, the funeral mob carried his body into the adjacent curia, the home of the senate, and set it up to be burned at the center of that hall. The fire flew up out of control and burned the entire venerable senate house to the ground.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3084)

---

> The author of the revolt was an Arvernian noble named Vercingetorix, whom Caesar had once declared to be a friend.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3092)

---

> Pompey still offered to guarantee that Caesar could stand for election to the consulship of 48 during the year 49 without having to give up his army and return to Rome and the prospect of criminal prosecution.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3098)

---

> Consul without colleague was almost but not quite the same as dictator. Pompey held sole executive power, but as consul he still had to meet with and care for the actions of the senate, which a dictator could avoid.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3105)

---

> Pompey ended by rejecting the marriage proposals Caesar had been floating and instead married a daughter of Metellus Scipio, whom Pompey then arranged (in August) to have elected as second consul for the year. Metellus was well rewarded for his daughter and his complaisance.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3108)

---

> When Caesar arrived, he found the most concerted resistance he had yet faced, now centered not in the northern reaches of Belgic Gaul, where he had been based the last several years, but in the heart of the landmass itself, with Vercingetorix the ringleader representing the powerful Arverni people whose name survives on their land, the modern Auvergne.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3111)

---

> There follow three great battles in a year that could easily have seen Caesar defeated and dead. Avaricum, Gergovia, and Alesia extend in a zigzag from west to east, along the boundary between Roman power and Gallic resistance. Caesar won the first, lost the second, and performed a miracle at the third.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3120)

---

> No reader of Caesar ever fails to see vividly the person and personality of Vercingetorix, the great hero of the Gauls— as Caesar tells it. If Ali needed Frazier, then Caesar needed Vercingetorix (once he had survived victorious himself!) to show how great a general he had been.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3127)

---

> Vercingetorix ended his life as a prize exhibit in the triumphal parade and was then summarily executed when he had no further contribution to make to Caesar’s glory.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3132)

---

> The Haedui, who had played Caesar deftly in all the earlier years of the war, usually on his side, were also in revolt this year. But when the year and the war was done, Caesar was careful not to punish those peoples harshly. He needed them for Rome’s future in Gaul and he did for them what the allies did not do after World War I for Germany. He made them live and thrive and find it easier to accept subjection than to continue in thoughts of rebellion. We see very little of how Caesar managed this, but it may be the most important single thing he did in Gaul.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3134)

---

> Gallic leaders summon meetings in woods and wild places, complaining about the death of Acco and observing that the same could happen to them. They bemoan the common lot of Gaul. With every promise and bribe they challenge men to begin war and liberate Gaul, risking their necks.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3156)

---

> In all, better to be killed in battle than fail to regain the warrior’s glory and the liberty handed down by their ancestors.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3160)

---

> And there likewise was Vercingetorix, Celtillus’ son, an Arvernian, a youth of immense influence, whose father had dominated Gaul and been killed by his own people for seeking to be king.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3171)

---

> “These are the gifts you have from me,” said Vercingetorix, “whom you accuse of treason. By my efforts you see a great victorious army taken down by famine without a drop of your blood. I have taken care no nation will welcome them when they shamefully flee.”
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3295)

---

> They tunneled under our ramp, the more knowledgeably because there are great ironworks among them and every kind of tunneling is known and practiced. They covered the whole wall with towers on all faces and wove hides over them. In sallies by night and day they set fire to the ramp or attacked soldiers busy working. They matched the height of our towers, as these were forced up higher every day by work on the ramp, by adding to their towers with timbers. They intercepted our tunnels, slowing their progress with sharp, bent stakes and boiling pitch and huge rocks, preventing them from reaching the walls.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3301)

---

> They were preparing to do this by night when their womenfolk suddenly rushed into the open, throwing themselves weeping at the feet of their husbands, begging in every way that they not hand them and their children to the enemy to be punished, for by nature they were too weak to take flight. When they saw the men standing by their plan (in extreme danger fear is impervious to pity) they began to shout out and betray the flight to the Romans.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3323)

---

> Startled and scared, the enemy were dislodged from walls and towers into squares and avenues, making their stand in tight clusters, thinking that if they were attacked on any side, they could form a line and fight it out.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3331)

---

> Angered by the slaughter at Cenabum and the laborious siege, they spared neither the age-weary nor women nor children. Of the whole 40,000, scarcely 800, who fled town at first uproar, made it safe to Vercingetorix.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3335)

---

> Adversity diminishes authority for other generals, but his reputation instead increased by the day after the loss.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3348)

---

> Issuing this decision, he encouraged the Haedui to forget quarrels and strife, leave everything else aside, and devote themselves to the war and to anticipating the rewards they would earn from him when Gaul was conquered. They should send him all their cavalry and ten thousand infantry quickly, which he would assign to watching the grain supplies.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3372)

---

> The Haedui were the only state preventing assured victory for Gaul, while the others were held back by their prestige. If they were brought over, there would be no way for Romans to stay in Gaul.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3397)

---

> Why should Haedui need Caesar to rule on their own customs and law, rather than have the Romans come to them?
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3399)

---

> Caesar was greatly troubled by this news, for he had always specially favored the Haedui. Without hesitation he takes four light-armed legions and all his cavalry from camp,
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3420)

---

> About halfway there, riders sent from Fabius tell him how dangerous things are: they report the camp attacked by huge forces, fresh troops constantly replacing tired ones, wearing ours down with incessant toil, for the size of our camp made the same men stay constantly on the rampart.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3429)

---

> To keep from being surrounded by the united nations, he began to think how he could leave Gergovia and collect his whole army without making a departure in fear of revolt look like running away.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3446)

---

> Giving this speech, he finally encouraged them not to be upset and not to credit enemy courage for what was merely the effect of uneven ground.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3505)

---

> War spreads as the Haeduan revolt becomes known. Embassies are sent in all directions. They strive to recruit allies with whatever influence, prestige, and money they can. Taking and executing the hostages Caesar had left with them, they frighten the reluctant.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3571)

---

> Vercingetorix settles in three camps nearly ten miles from the Romans and calls his cavalry commanders to council, declaring the time of victory was at hand. The Romans were leaving Gaul, fleeing to the province. 23 This was enough to gain immediate freedom, but little help for future peace and tranquility.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3597)

---

> The fortification begun by the Romans had a circuit of nine miles. Camps were pitched in good places and twenty-three forts were constructed there, in which detachments were placed by day in case of a sudden breakout.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3621)

---

> Giving these orders, he sends the cavalry out quietly toward midnight through a gap in our siege works. He orders all the grain brought to him and sets the death penalty for those who do not obey. He distributes to the soldiers the cattle the Mandubii had gathered in abundance. Grain he begins to measure out sparingly and gradually. He brings all the forces posted in front of town back inside. Thus he waits for help from Gaul and prepares to continue the war.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3634)

---

> Learning this from refugees and captives, Caesar establishes this manner of fortification: He dug a trench twenty feet wide with vertical sides, so the trench’s bottom was as wide as its top opening. The other fortifications he laid out four hundred feet from the trench, with this in mind, that because he had to enclose so large a space and the whole could not easily be surrounded with a ring of soldiers, he had to avoid unexpected or night onrushes of enemy hordes against his fortifications or having weapons thrown by daylight against our men as they worked.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3638)

---

> When this was done, following the most level ground possible and enclosing some dozen miles, he completed a second set of separate fortifications against an external enemy, so the garrisons by our fortifications would not be surrounded, if it came to it, even by huge forces; and to avoid being forced to leave camp while in danger, he orders them all to bring in thirty days’ fodder and grain.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3656)

---

> Everyone worked with heart and hand for this war. Eight thousand cavalry28 and about 250,000 infantry were collected and reviewed in Haedui territory, counted up, and assigned commanders.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3673)

---

> The Mandubii, who had let them into the town, are required to leave with their children and wives. When they reached the Roman fortifications, they wept and prayed to be taken in and fed as slaves. But Caesar put out guards on the ramparts and forbade their admission.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3701)

---

> But Mark Antony and the legate Gaius Trebonius, who had charge of defense here, sent men taken from the farther outposts to where they knew ours were hard pressed.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3725)

---

> A hill on the north, too large around for our men to incorporate in their works, made for camp on sloping and disadvantageous ground. Legates Gaius Antistius Reginus and Gaius Caninius Rebilus held it with two legions. Reconnoitering the land with scouts, enemy leaders select sixty thousand from the nations with the greatest reputation for courage. They decide secretly together what to do and how, choosing the attack time for around noon.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3733)

---

> Vercingetorix sees his men from the citadel of Alesia and comes out of the town. He brings out hurdles, poles, sheds, sickles— everything needed for a sally. They fight everywhere at once, trying everything.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3739)

---

> The shouting behind the fighters does a lot to frighten our men, because they see their danger hanging on the courage of others. What men can’t see upsets their minds most.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3741)

---

> Both sides think this is the best time to fight. The Gauls: if they don’t break through, all hope is lost; the Romans: if they prevail, they will see all their labors ended.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3744)

---

> Next day, Vercingetorix calls a council to say he had entered the war not out of personal need but for the liberty of all. Forced to yield to fortune, he offers himself to them, either to die to placate the Romans or to be handed over alive.
> 
> **SEVENTH COMMENTARY: 52 BCE** (Location 3766)

---

> From here, we leave Caesar’s words behind to conclude the story of his years in Gaul.
> 
> **EIGHTH COMMENTARY: 51–50 BCE** (Location 3835)

---

> Those who argue that the whole work was published at once need to find a way to explain the choice to publish then. If Caesar was indeed working year-by-year, then what needs explaining is only the failure to produce commentary a year later, at the end of 51.
> 
> **EIGHTH COMMENTARY: 51–50 BCE** (Location 3839)

---

> What we have in this eighth commentary, covering the two last years Caesar spent in Gaul, comes from the hand of Aulus Hirtius.
> 
> **EIGHTH COMMENTARY: 51–50 BCE** (Location 3841)

---

> Hirtius wrote his commentary on the last years of the Gallic war and another on Caesar’s war at Alexandria after Caesar’s death.
> 
> **EIGHTH COMMENTARY: 51–50 BCE** (Location 3847)

---

> Years had elapsed since the events recounted and it is unlikely that Hirtius had intended in the moment to write such an account. Accordingly, whatever materials he had to draw on (any by Caesar himself?), his account is less precise and accurate than those of the earlier commentaries written by the greater writer closer to the time of events.
> 
> **EIGHTH COMMENTARY: 51–50 BCE** (Location 3848)

---

> The lucidity, crispness, and narrative speed of Caesar’s prose have become familiar by now. Hirtius, by contrast, writes sludge.
> 
> **EIGHTH COMMENTARY: 51–50 BCE** (Location 3852)

---

> Hirtius gives us the official version, the authorized Caesarean story.
> 
> **EIGHTH COMMENTARY: 51–50 BCE** (Location 3859)

---

> Remarkably, he recounts some episodes of the preceding year that Caesar omitted in his seventh commentary, leaving us to wonder what else Caesar had omitted over the years.
> 
> **EIGHTH COMMENTARY: 51–50 BCE** (Location 3861)

---

> What we have here ends as Caesar returns to Cisalpine Gaul at the end of 50. It was there that he monitored the deteriorating situation in Rome, welcomed the fleeing tribunes Antony and Cassius Longinus, and made his decision to go to Rome.
> 
> **EIGHTH COMMENTARY: 51–50 BCE** (Location 3872)

---

> Gaul in 51 was exhausted but not yet at rest. The great rebellion was over, but insurgencies continued.
> 
> **EIGHTH COMMENTARY: 51–50 BCE** (Location 3875)

---

> Caesar ordered that the fighters among the prisoners all be mutilated: their hands were cut off. This was a sentence of either painful death (infected wounds in the circumstances were likely) or burdensome life.
> 
> **EIGHTH COMMENTARY: 51–50 BCE** (Location 3881)

---

> More troubling was Marcellus’ argument that Caesar’s great victory in 52 over Vercingetorix showed that his job in Gaul was done and so he and his army should come home.
> 
> **EIGHTH COMMENTARY: 51–50 BCE** (Location 3894)

---

> When he reached Uxellodunum ahead of all expectations, he found the town surrounded by fortification.
> 
> **EIGHTH COMMENTARY: 51–50 BCE** (Location 4163)

---

> Caesar knew everyone was aware of his mild temperament and did not fear anyone thinking he acted harshly out of cruelty.
> 
> **EIGHTH COMMENTARY: 51–50 BCE** (Location 4191)

---

> He cuts the hands off all who had borne arms and lets them live so the punishment for wrongdoing would be well attested.
> 
> **EIGHTH COMMENTARY: 51–50 BCE** (Location 4194)

---

> Caesar saw and judged that things were going well everywhere in Gaul. While Gaul had been beaten and subjugated in the preceding summers, he had never visited Aquitaine, but partially subdued it by sending Publius Crassus, so he set out with two legions to spend the summer’s end there.
> 
> **EIGHTH COMMENTARY: 51–50 BCE** (Location 4201)

---

> Bear in mind that the settlement in 52 of the great rebellion had let the Haedui off the hook for their betrayals and failings.
> 
> **EIGHTH COMMENTARY: (CONTINUED) 50 BCE** (Location 4266)

---

> Cooperation was to be profitable. Rome did not always end its conquests with so flagrant a purchase of elite support, but there was almost always some element of reward for submission.
> 
> **EIGHTH COMMENTARY: (CONTINUED) 50 BCE** (Location 4268)

---

> Pompey met that request by agreeing to supply the legion he had supposedly loaned to Caesar some time before. In other words, the request of one from each was effectively a move to strip two from Caesar.
> 
> **EIGHTH COMMENTARY: (CONTINUED) 50 BCE** (Location 4272)

---

> If there was a plus for Caesar in this transfer, it lay in the attitude of those troops toward Pompey and Caesar. They respected Caesar; they knew they were supposed to respect Pompey.
> 
> **EIGHTH COMMENTARY: (CONTINUED) 50 BCE** (Location 4275)

---

> a moment of overbearing confidence for Pompey, quoting him as claiming that he could stamp his foot on the ground and Italy would pour forth whole armies to support him.
> 
> **EIGHTH COMMENTARY: (CONTINUED) 50 BCE** (Location 4283)

---

> Crisis loomed over whether Caesar would be allowed to run for consul for the year 48 during the summer of 49 without giving up his troops and returning to the city.
> 
> **EIGHTH COMMENTARY: (CONTINUED) 50 BCE** (Location 4290)

---

> On 1 December, Cato proposed that both Caesar and Pompey should dismiss their armies and present themselves as citizens at Rome.
> 
> **EIGHTH COMMENTARY: (CONTINUED) 50 BCE** (Location 4293)

---

> Caesar speaks for himself about this crisis in the opening pages of his commentaries on the civil war. What was anyone else thinking?
> 
> **EIGHTH COMMENTARY: (CONTINUED) 50 BCE** (Location 4298)

---

> On January 7, they passed the senatus consultum ultimum, “the senate’s ultimate decree” granting the consuls virtually unrestricted authority to take whatever steps they judged necessary to defend the republic.
> 
> **EIGHTH COMMENTARY: (CONTINUED) 50 BCE** (Location 4305)

---

> Now it was time for the tribunes Antony and Cassius, powerless to help further, to flee to Caesar.
> 
> **EIGHTH COMMENTARY: (CONTINUED) 50 BCE** (Location 4308)

---

> On the night of January 10, Caesar’s troops crossed the tiny river Rubicon that formed the boundary between home and abroad.
> 
> **EIGHTH COMMENTARY: (CONTINUED) 50 BCE** (Location 4309)

---

> Caesar’s arrival was greeted by all the municipalities and colonies with unbelievable honor and love. This was the first time he came to them after the war with all Gaul.
> 
> **EIGHTH COMMENTARY: (CONTINUED) 50 BCE** (Location 4331)

---

> both could give up their weapons and dismiss their armies. With that the city would be free and autonomous. He did not merely promise this, but even tried to obtain a senatorial decree through voting.
> 
> **EIGHTH COMMENTARY: (CONTINUED) 50 BCE** (Location 4345)

---

> When his friends and colleagues came to kill him, it was not for his crimes but for his success and his future imagined successes. Claiming all of “Gaul” for Roman sway was self-evidently a good thing for Rome.
> 
> **After War, after Gaul** (Location 4386)

---

> Should Caesar have been assassinated? The case in favor was powerful and obvious: he sought too much power, entailing the downfall of the established order.
> 
> **After War, after Gaul** (Location 4393)

---

> “if we want things to stay the same, things will have to change.”
> 
> **After War, after Gaul** (Location 4396)

---

> his standing as the kind of larger-than-life figure to whom adverse judgments do not stick is secure.
> 
> **After War, after Gaul** (Location 4401)

---

> Caesar holds sway still, of course, especially over these pages. It is a book cool, controlled, and calm.
> 
> **After War, after Gaul** (Location 4404)

---

> Most of all, it presents in plain view a series of ghastly slaughters recounted with no sign of regret or bad conscience, and none but the slightest mention of the vast plunder that accompanied the slaughters.
> 
> **After War, after Gaul** (Location 4407)

---

> Cool, focused, unhurried: the narrator of all but the last commentary is in his lofty, detached third-person voice himself the real hero of the story.
> 
> **After War, after Gaul** (Location 4411)

---

> What he does with language, so he did with life. On every page of The Gallic War the simple, unambiguous nouns and verbs carom off each other like billiard balls. There are few adjectives and they serve mostly to fix the nouns in place. The adverbs are all active— they aim the verbs.
> 
> **Three Meditations on Caesar, His War, and His Book** (Location 4456)

---

> He should be read as he wrote, at great speed.
> 
> **Three Meditations on Caesar, His War, and His Book** (Location 4459)