---
title: "The Nights are Quiet in Tehran"
author: Shida Bazyar
date: 2026-04-21
Rating: 8 / 10
---

### Highlights

> The Shah has gone, and we’re at the beginning of a new age, a new system, a new freedom for which we are now preparing ourselves.
> 
> **1979: Behzad** (Location 43)

---

> Since the Revolution, we have been venturing into buildings we didn’t know before. Before, we were in living rooms, sometimes in secret offices, sometimes on buses, visiting the movement in other cities. Since the Revolution, all doors seem to have opened, to let everyone in everywhere.
> 
> **1979: Behzad** (Location 175)

---

> we just have to keep fighting, to create a new Cuba, a new Soviet Union.
> 
> **1979: Behzad** (Location 200)

---

> These clerics think they have the people and we have the intellect;
> 
> **1979: Behzad** (Location 262)

---

> Now, after the Revolution, we don’t comb our hair, or wash it; the last thing we want is to look like the young Americans the Shah wanted us to be.
> 
> **1979: Behzad** (Location 296)

---

> The further we get from the Revolution, the more pictures of Ayatollah Khomeini we see, and the more groups are banned and vanish back into secrecy.
> 
> **1979: Behzad** (Location 370)

---

> And then everything happens very quickly. There we were, still thinking our main job was to sit and discuss and read and speak and plan and plan and plan, and now our leaders’ strategy has changed and we’re taking up arms again, preparing an offensive against the clerics, wanting the streets back, wanting our rights back, and we’re slap bang in the middle of the fight again.
> 
> **1979: Behzad** (Location 448)

---

> Suddenly you can’t remember when the shared fight during the Revolution turned into a fight among ourselves to become the new rulers.
> 
> **1979: Behzad** (Location 456)

---

> They’re torturing people in prison until they talk. But we can imagine it, because it is so very like what we knew before the Revolution.
> 
> **1979: Behzad** (Location 553)

---

> Their little Amin, who since the Revolution has finally found his calling and stopped lazing around. They’d felt honoured to have a son who renounced vices and the West and chose to pray. Thought he would be in good hands with the believers. Now he’s carrying out death sentences in the name of Allah, and no court in the land is going to stop him.
> 
> **1979: Behzad** (Location 631)

---

> I had no desire to remind him of the arguments they had all slung at me back then, when I dared to say that a free-market economy can bring progress, if it’s managed carefully. How embarrassed he’d been that I, his wife, had said such a thing, and how long he had spent going on at me until I eventually conceded that all people were equal and their earnings should be equal, too. When you say a thing like that, no one can dispute it.
> 
> **1989: Nahid** (Location 818)

---

> We used to say, There is nothing private, there is only the Revolution. Because we didn’t yet know what it was to know there is a land of carefree, joyful games in the next room that you are endangering with your own actions.
> 
> **1989: Nahid** (Location 1101)

---

> Behzad and I always say, Germany is our exile, and to me the word seems like a frozen state, in which I am supposed to try and move about all the same.
> 
> **1989: Nahid** (Location 1119)

---

> It’s lucky that my Laleh will never be an adult here, and I’ll never lose her to a fountain and brightly coloured leggings; by the time she’s that age, we’ll be back, Khomeini will be dead, everything will be different, everything better, and until then I will keep saying no when she asks for chewing gum — that might be how it all starts, first she gets chewing gum, and in a few years she’ll want to sit by the fountain in brightly coloured leggings.
> 
> **1989: Nahid** (Location 1159)

---

> What would you study — literature again? No, I say, so quickly that Ulla must be able to tell I’ve thought about this, weighed up the options. I think, what use will they have for a literary scholar when Khomeini dies and a new system is being built? With a scholar of German literature, at that? No, I say, economics, perhaps — or political science. But my German isn’t good enough yet. Ulla says, Goodness me, Nahid. You’re young and clever, and you have an emancipated husband who supports you, you can do this.
> 
> **1989: Nahid** (Location 1270)

---

> because of course I’m older and, like the adults, I never talk about what happened in the time before Germany.
> 
> **1999: Laleh** (Location 1333)

---

> The hijab slips, and while the machine is still doing the countdown, a few strands of hair fall across my forehead, and I quickly tuck a few strands of hair back under the hijab. What happens if there is hair in the photo? Does it get rejected by the embassy? What if the photos aren’t rejected, but we still get turned away at passport control, because an embassy worker wasn’t paying attention, because I wasn’t paying attention, because the machine started the countdown too quickly?
> 
> **1999: Laleh** (Location 1390)

---

> Mama has been having these crying episodes ever since we applied for our Iranian passports, ever since we bought the suitcases.
> 
> **1999: Laleh** (Location 1407)

---

> There are people and smells and images that sit so deep and sometimes come to the surface so suddenly, feeling so right that I have no idea how I could have forgotten them on all those days at school and evenings in Marie’s room. They sit so deep because they’re bound up with childhood and security and safety. Until I go back to school and immediately forget it all. And then eventually it catches up with me again, and I think, Why is it that I have to carry these things around with me and Marie and David and bloody Maja don’t even know what that feels like? I really don’t want to know what it feels like to be Mama.
> 
> **1999: Laleh** (Location 1416)

---

> Ava slices open a peach, it releases its perfume, and now that I’ve learned what real peaches taste and smell like, I never want to eat a peach in Germany again.
> 
> **1999: Laleh** (Location 1634)

---

> Do you wear make-up, at home? Ava asks.
> 
> **1999: Laleh** (Location 1658)

---

> Because from the school’s point of view, of course I could, but it would be weird to wear make-up in front of Mama and Papa — I’d have to explain, give them reasons, find convincing arguments for why going to school in make-up is a good idea, on an adult level, a theoretical level. And that’s just too stressful.
> 
> **1999: Laleh** (Location 1668)

---

> A friend of mine painted her fingernails, Ava says, and they pulled them out. She says it without any emotion in her voice, and for a moment I have the horrific image of fingers without nails and how painful that must be.
> 
> **1999: Laleh** (Location 1670)

---

> wonder what Ava would be like if she was in Germany and in my class. She might be loud and funny, and then she’d sit with Maja and the boys at break time.
> 
> **1999: Laleh** (Location 1724)

---

> When we first got here, I was surprised at all the women wearing black mantos, because they must make you even hotter. Now I think how nice it would be if my manto was black and not grey, because no one would notice the sweat.
> 
> **1999: Laleh** (Location 1738)

---

> And I stick out more here than I ever have before; I’m probably the only woman in this country who hides her body and yet is more visible than she’s ever been in her life. You walk differently, they say, You look at people differently.
> 
> **1999: Laleh** (Location 1785)

---

> The way they always find everything exciting and make so much effort to look beautiful, only to then hide themselves under a hijab. And the way I just can’t take what they’re doing and how they’re doing it completely seriously, because I’m always kind of thinking, Sure, you’re ridiculously nice and you’re fond of me, but actually you’re not leading a real life here; real life is in Germany. There, you can make decisions about your own future, you might be able to change things that aren’t going well, and if you break the rules in the process, they call it individualism. And the thought instantly makes me feel bad.
> 
> **1999: Laleh** (Location 1796)

---

> She isn’t really listening, goes on talking straightaway, turning to the others: Everything is good in Germany, the hospitals, too, the medicines, the schools, it’s not like it is here, she proclaims. I don’t have to say anything else, because the other women are agreeing about how good hospitals and medicines and schools are in Germany.
> 
> **1999: Laleh** (Location 1823)

---

> no grade in any other subject must ever get so bad that my parents want to come and speak to my teachers but can’t get an appointment.
> 
> **1999: Laleh** (Location 1864)

---

> he would just give us a smile and spend the whole time talking to Papa, and what they talked about was nothing to do with me. Things that adults do. Things that I can’t say when I began to understand. My parents did forbidden things in a country where everything is forbidden. That’s how I would explain it to Tara, if she asked.
> 
> **1999: Laleh** (Location 1943)

---

> I’ve got quite good at thinking about something else and blocking out Mama’s and Khale Azar’s whispering, because I have no interest in what they’re talking about. But khodkoshi is a word that makes me prick up my ears. Suicide sounds much gentler; khodkoshi actually sounds like a violent act, and maybe that makes it the right word.
> 
> **1999: Laleh** (Location 1996)

---

> The drugs here cost less than a litre of milk, my uncle said disparagingly. It’s a way to keep people stupid. Religion is the opiate of the people, but these people need opiates to escape from religion.
> 
> **1999: Laleh** (Location 2005)

---

> But Yasaman is obsessed with finding all German men awful; she claims that having relationships with German men is assimilation, and subjugating yourself. She wants to take Iranian studies at university, become a journalist, become better than this cringy white middle class, as she calls it.
> 
> **1999: Laleh** (Location 2056)

---

> Ava looks at me. Here? Satisfied? The three of us couldn’t be sitting here together if the windows weren’t tinted, if there weren’t so many other people around us, if we didn’t happen to be in a more moderate phase than we were a few years ago — is that really not obvious to you?
> 
> **1999: Laleh** (Location 2075)

---

> And now it’s all over? No, says Nima. It’s just that no one dares take to the streets anymore. The government planted rioters among us, and they were so out of order that the police were able to take action against us at once.
> 
> **1999: Laleh** (Location 2089)

---

> It’s impossible to keep studying here now. And I find it strange that he doesn’t lower his voice as he says it, that there is no fear now about saying the words out loud — maybe because everything else is already forbidden, and because there are too many other things to fear for you to fear everything.
> 
> **1999: Laleh** (Location 2093)

---

> Going to university here is like taking a little time out, just waiting for when you’ll no longer be allowed to do anything.
> 
> **1999: Laleh** (Location 2107)

---

> Yasaman has told me so many stories about her cousins, who slept with all these men and then on their wedding nights had to invent elaborate tricks to leave virginal marks in the bed.
> 
> **1999: Laleh** (Location 2112)

---

> For years, I was jealous of Marie, whose parents look happy in their hippy photos, beautiful and sunny and youthful. And here, they have fat albums of my young parents tucked away, like they’ve been held captive here all these years.
> 
> **1999: Laleh** (Location 2189)

---

> I just found it kind of exciting to act like I really needed to have one before going to bed, and if the pair of them had known, it would have triggered a lot of rational, intellectual conversations about the dangers of smoking. My parents were speaking quietly, because for some reason they never talked about us in front of us, like too much transparency would harm our good upbringing.
> 
> **2009: Mo** (Location 2296)

---

> We thought we were doing the only thing that was right, my father said, and that shields you from the reality.
> 
> **2009: Mo** (Location 2302)

---

> Now these other twenty-three-year-olds are suddenly everywhere, on the streets of Tehran, on the news websites, even on RTL here in Germany. And in my head. Huge numbers of them on the streets, drawn out of their houses and their silence, and suddenly there, fighting back.
> 
> **2009: Mo** (Location 2358)

---

> Maryam doesn’t pay Tobi any attention; instead, she looks at me and asks, because she probably overheard what I said about this strike: Alright then, what do we need to do better? And I could throw up right there and then. Tobi’s Maryam is not only too much like Tobi’s girlfriends always are, she’s political as well. Or thinks she is. Whatever — I can already predict how this will play out: no matter what I say now, she’ll manage to invalidate it with her over-inflated alternative-leftist rhetoric copied off the TV, in a way that will force me into pretending to agree rather than arguing back, so I might as well not bother and just sit drooling beside Tobi, saying Education wants to be free.
> 
> **2009: Mo** (Location 2372)

---

> I called Amme Simin and she says the streets are green, completely green — they were already green before the elections, and people went to vote feeling hopeful for the first time again, Mo, did you see the news?
> 
> **2009: Mo** (Location 2400)

---

> Mo, they were saying on TV these are the biggest protests since 1979. Laleh sounds excited, really and truly excited. She talks so naturally about 1979, like she was there.
> 
> **2009: Mo** (Location 2413)

---

> These are the things I’d be doing if I was there. These are the things that have to be done because people like my parents aren’t there any longer.
> 
> **2009: Mo** (Location 2435)

---

> Then I thought, Actually, I can fight my own battles, and she doesn’t have any info about my feelings, even if she might be right. So I said, Maryam, it’s fine. Then Maryam gave me the horrified look that had previously belonged to the acne guy, and she was red in the face as she told me I only thought that because I was socialised here. She genuinely used the word socialised.
> 
> **2009: Mo** (Location 2601)

---

> Because my parents silently register everything they see on the German news as not their problem. At least, that’s what I say. It might not be true, because if it wasn’t their problem, they wouldn’t be watching the news.
> 
> **2009: Mo** (Location 2715)

---

> a man appears with a camera, quickly squats down and aims his lens at Tara. Tara senses it and knows it and leaves the cigarette in the corner of her mouth and raises her hands again and looks at the sky. I turn away so I won’t have to watch. And yet I can’t help but imagine the photo of Tara ending up on Iranian blogs.
> 
> **2009: Mo** (Location 2893)

---

> Maryam says, Hey, don’t worry. It will happen. It’s just the fucking media, acting like nothing else of any importance is going on in the world right now just because some paedophile pop star died. But it’s still happening. She looks at me and nods. You’ll see. As soon as Ahmadinejad is gone, it’ll kick off in Egypt, too. Then Mubarak will be gone, and Assad will be next, and eventually all the dictators will be out.
> 
> **2009: Mo** (Location 2982)