---
title: "The Voices of Morebath"
author: Eamon Duffy
date: 2026-04-30
Rating: 10 / 10
---

### Highlights

> This is a book about a sixteenth-century country priest, and the extraordinary records he kept. It deals with ordinary people in an unimportant place, whose claim to fame is that they lived through the most decisive revolution in English history, and had a priest who wrote everything down.
> 
> **Preface** (Location 82)

---

> Through his eyes, or rather, through his voice, talking, talking, talking – for he wrote these accounts to be read aloud to his parishioners – we catch a rare and precious glimpse of life and death in an English village. His accounts reveal its complex social life, its strains, tensions and conflicting personalities, its search for internal harmony, its busy pre-Reformation piety, its struggles to meet the growing demands of the Tudor war-effort against Scotland and France.
> 
> **Preface** (Location 93)

---

> For the last twenty years of his life the priest, garrulous as ever, documents a changed community, reluctantly Protestant, no longer focussed on the religious life of their parish church but increasingly preoccupied with the secular demands of the Elizabethan state, the equipping of armies and the payment of taxes.
> 
> **Preface** (Location 108)

---

> Surnames in Morebath were often simply the farm name – Alsyn at Perry, John at Moore, William at Timewell, Robert at Wood – and the priest often identifies householders by a single-word reference to their farm – Burston, Court, Wood
> 
> **1 A Place Apart** (Location 238)

---

> However, occupational and family surnames were also freely used: George the Smith is interchangeable with George Smith; John Hukeley is called John Smith in 1537,12 presumably because of his occupation; Lucy Scely, widow of the miller William, is Luce at Mill,
> 
> **1 A Place Apart** (Location 240)

---

> Occasionally, patronyms are used as surnames – Lewis Trychay’s daughter Joan occurs as ‘Jone Lewys’, as indeed does his wife. 13 It is all very confusing.
> 
> **1 A Place Apart** (Location 244)

---

> these sources combine to suggest a population of not many more than 150 men women and children through the mid-Tudor period.
> 
> **1 A Place Apart** (Location 256)

---

> In so small a community, everyone was known and communal life intense, even perhaps at times claustrophobic.
> 
> **1 A Place Apart** (Location 257)

---

> After the church, the most important building in the parish was the church house, also called the church ale-house.
> 
> **1 A Place Apart** (Location 293)

---

> Parishioners were expected to attend and spend their money, and official representatives came and supported from surrounding parishes, a favour which had to be returned when the parishes concerned held their own ales.
> 
> **1 A Place Apart** (Location 306)

---

> The language in which the priest reports the incident is value laden, a rhetoric designed to shame ‘froward fellows’ and to persuade the ‘parish universall’ to cease ‘trobyll or vexacion: and ‘be contendyd to be ordred’, so as to have ‘unite and pece a mongg us’. The quest for unity and peace, at Morebath as everywhere else in Tudor England, was an ideal eagerly pursued because often lacking.
> 
> **1 A Place Apart** (Location 312)

---

> There were no very rich men in Morebath, and the gap between the well-to-do and the poor was narrower than in many more prosperous communities.
> 
> **1 A Place Apart** (Location 345)

---

> wool dominated the parish economy; every householder in Morebath had one or more (mostly small) flocks of sheep.
> 
> **1 A Place Apart** (Location 373)

---

> A few of the better houses in the parish may have been of stone
> 
> **1 A Place Apart** (Location 382)

---

> Even her best clothes, however, were probably old-fashioned. Morebath women, like country women everywhere in early Tudor England, passed their garments of state on from generation to generation.
> 
> **1 A Place Apart** (Location 396)

---

> Until the reign of Edward VI, however, the poorest of all are concealed from us in the Morebath sources. Poor there certainly were, though we have virtually no hard information about beggars and the destitute in Morebath and its region for most of the Tudor period, and even servants and labourers like ‘Harry Tanner’s wife’ often surface first and last only when someone buys a funeral knell for them, or pays for their burial.
> 
> **1 A Place Apart** (Location 438)

---

> But it is death rather than birth which the registers bring into sobering focus. Morebath seems to have avoided major outbreaks of epidemic disease, like the sweating sickness that ravaged other parts of north and north-west Devon in the 1550s, but it had constant acquaintance with untimely death.
> 
> **1 A Place Apart** (Location 458)

---

> Most will have succumbed to disease, some to mischance, like the unnamed ‘ladd that was killed with the knyffe’, a stranger from Stoodleigh who leapt to his horse at Exebridge in 1558 and impaled himself on his own dagger, leaving the parish with elaborate and expensive arrangements to make for the inquest.
> 
> **1 A Place Apart** (Location 466)

---

> This brutally high level of mortality among their children may explain the custom, maddening to the historian trying to pick his way through meagre documentation, of naming several children of the same generation of the same family with the same name.
> 
> **1 A Place Apart** (Location 480)

---

> All the accounts up to and including those for 1573 are written in a single bold and clear hand, elegant to start with, coarsening with age into spikiness, occasionally made erratic by illness or stress, marked throughout by easily recognisable features (such as a distinctive letter ‘G’, always formed by placing point-to-point a diamond and a jagged triangle), and retaining to the end its distinctive energy and dash. The writing is that of the Vicar of Morebath from 1520 until his death in May 1574, Sir Christopher Trychay.
> 
> **2 The Voices of Morebath** (Location 572)

---

> The result is the fullest and most remarkable of all sets of Tudor churchwardens’ accounts, fifty years of uniquely expansive and garrulous commentary on the affairs of a tiny and otherwise obscure rural community in one of the remotest regions of early modern England, during the revolutionary religious and social upheavals of the English Reformation.
> 
> **2 The Voices of Morebath** (Location 586)

---

> Over the last generation, growing interest in the implementation and pace of official religious policy during the Reformation, and a heightened sense of the centrality of the localities for an understanding of early modern society in general, has led historians of religion, politics and of popular culture to place enormous emphasis – and correspondingly high hopes – on churchwardens’ accounts.
> 
> **2 The Voices of Morebath** (Location 595)

---

> the arithmetic of most such accounts, those of Morebath included, is often extremely unreliable. Totals of expenditure or income are frequently miscalculated by amounts ranging from a few pence to several pounds, a phenomenon so widespread as to lead some historians to question the viability of systematic statistical analysis based on them.
> 
> **2 The Voices of Morebath** (Location 603)

---

> As we shall see, the Morebath book fits firmly into this category of accounts: though it was certainly intended by its clerical compiler as a written repository of the parish memory, occasionally cross-referenced for ease of consultation, though it contains some pious and a great deal of exhortatory material, and though some items were quite explicitly notes and memoranda intended for reference rather than public recitation, the bulk of its contents are transcripts not so much of documents as of scripts, the traces in black and white of a man talking.
> 
> **2 The Voices of Morebath** (Location 697)

---

> None of these stores should be thought of as ‘guilds’: they were purely and simply funds, with the single complication required by the management of livestock.
> 
> **2 The Voices of Morebath** (Location 737)

---

> The Maiden store was another matter. The Maidens probably included all unmarried girls of twelve or so, the age at which girls began to take communion.
> 
> **2 The Voices of Morebath** (Location 738)

---

> The Young Men’s store, which included all bachelors of communicant age, which for men usually meant about fourteen years and above, played a central role in parish finances and, by implication, its social life.
> 
> **2 The Voices of Morebath** (Location 748)

---

> The store of Our Lady was the most important store in the parish. Like the others it existed to maintain a light, in this case before the principal image of the Virgin. The two wardens of this store derived the bulk of their income from the church’s largest flock of sheep, called ‘Our Lady’s sheep’, normally from about twenty to two dozen and producing about forty pounds weight of wool each year. Like all the church sheep, this flock was distributed piecemeal to individual parishioners, who were responsible for accounting to the wardens for the animals in their care at the end of the year, and for handing in the fleeces after shearing.
> 
> **2 The Voices of Morebath** (Location 761)

---

> The system of parochial obligation involved in the maintenance of these church flocks was quite remarkable. Many West Country parishes drew income from sheep and cattle, but most seem to have operated some sort of profit-sharing system, whereby parishioners were paid to keep the sheep and cows, or themselves paid a fee for the hire of the animals, keeping the wool or milk in return, or where parish and custodian split the profits
> 
> **2 The Voices of Morebath** (Location 772)

---

> But keeping one of the Morebath church sheep was considered a parochial obligation, only occasionally refused. As we shall see, each year the priest reported in minute detail on the disposal of the church sheep round the parish, noting explicitly who had or had not animals from the church flocks, and commenting, usually with an edge, on those who refused. Those declining the obligation were expected to pay the church a fine of 3d or 4d called a ‘sheep’s lease’, which was passed on by the wardens to whoever accepted the sheep in place of the recusant parishioner.
> 
> **2 The Voices of Morebath** (Location 776)

---

> In a community where grazing was at a premium and most flocks were small, the responsibility and labour involved in keeping one or more of the church sheep was a demanding commitment.
> 
> **2 The Voices of Morebath** (Location 783)

---

> Election travelled round the parish by farms and cottages, and the head of each household was expected to serve when their turn came round, even where that head was a widow.
> 
> **2 The Voices of Morebath** (Location 801)

---

> With so many offices to fill each year, the refusal of parishioners who ‘wolde not doo ther diligens’ 52 was a serious matter, and finding substitutes could be difficult.
> 
> **2 The Voices of Morebath** (Location 807)

---

> As might be expected in a small community with a small population, service as High Warden was not and could not be restricted to the well-to-do: the essential qualification was headship of a household, and the poor served as well as the prosperous.
> 
> **2 The Voices of Morebath** (Location 831)

---

> To qualify as one of the ‘Five Men’ financial security was essential, because from time to time they were expected to solve cash-flow problems from their own resources. 69 As we shall see, this aspect of their office was to be crucial in Edward’s reign, when they assumed a dominant role in managing the series of crises the Reformation brought to the parish.
> 
> **2 The Voices of Morebath** (Location 857)

---

> Throughout the 1520s and 1530s, therefore, in any one year twelve parishioners, eight of them heads of households, held parish office, in addition to the ‘Five Men’. The degree of active parochial involvement this demanded from a community as small and relatively poor as Morebath is staggering.
> 
> **2 The Voices of Morebath** (Location 863)

---

> Morebath is unique, however, in the extraordinary verbal immediacy of its accounts, which bear all the marks of being transcripts of a spoken text. Where the vast majority of Tudor parish and guild accounts are desiccated lists of income and expenditure, often compiled wholly or largely in Latin, those of Morebath are vividly personalised and precisely located in a specific time.
> 
> **2 The Voices of Morebath** (Location 889)

---

> until 1540 all the accounts except those of the Maiden Wardens are written in the first person, as if the accounting warden or wardens were speaking directly.
> 
> **2 The Voices of Morebath** (Location 899)

---

> the only exceptions to this ubiquitous first person convention are the Maiden Wardens’ accounts. These are invariably presented in the third person,
> 
> **2 The Voices of Morebath** (Location 914)

---

> It is not clear whether this difference of address was an example of gender discrimination because the Maiden store was the only one always administered by women, or whether it stemmed from the fact that the Maiden Wardens were often and perhaps always very young girls, whose finances were managed for them by older male relatives, by the High Wardens or by the priest.
> 
> **2 The Voices of Morebath** (Location 916)

---

> In place of a series of balance sheets, it seems, we have a sophisticated succession of living voices.
> 
> **2 The Voices of Morebath** (Location 940)

---

> This correction of the wardens’ arithmetic simultaneously reveals to us the presence of the priest, not only writing down the account but reading it to the parish, and establishes a distance between scribe and warden, since it makes it clear that the financial substance of the account remained the wardens’ own.
> 
> **2 The Voices of Morebath** (Location 952)

---

> the accounts follow a common and tightly ordered set of conventions of organisation, presentation and language, and they are marked throughout by a distinctive English timbre and an equally distinctive repertoire of Latin words and phrases. Together, these stylistic traits reveal an idiosyncratic and garrulous personality, a single voice, the same no matter whose name heads the bill.
> 
> **2 The Voices of Morebath** (Location 974)

---

> From 1540, when the Henrician attack on the cult of the saints led to the merging or abolition of the lesser stores, the priest opened that sheep count not with an invocation to the Virgin, but with the psalm verse used at the opening of the hours of the breviary, ‘Deus in adiutorium meum intende’ [O God, come to my help], though he continued to invoke the parish patron, St George, before the High Wardens’ accounts – all of which demonstrates a degree of sophisticated theological nuance (and a sense of ecclesiastical politics and prudence) not very common among the rural laity.
> 
> **2 The Voices of Morebath** (Location 993)

---

> The priest was also prone to drop into Latin when matters directly affecting his own concerns were being reported, or when he wished in some way to distance himself from what was being said.
> 
> **2 The Voices of Morebath** (Location 1003)

---

> the priest often seems to use a Latin word or phrase also to establish distance between himself and what he is reporting. Sometimes the effect is faintly sardonic, as when he reports a claim he does not necessarily believe, for example the loss of one the church ewes: ‘the yewe that [John Waters] hadde that came from William Tymwell ys gon (ut dicit) [so he says]’.
> 
> **2 The Voices of Morebath** (Location 1018)

---

> Dozens of entries make it plain that he not only wrote out all the accounts, but that it was he who read them aloud to the parish on behalf of the wardens on their accounting Sunday. We can be sure of this because in the process he often takes the opportunity to drop the persona of the reporting warden, and to address his parishioners directly.
> 
> **2 The Voices of Morebath** (Location 1028)

---

> Rather implausibly, however, the occasions which provided Sir Christopher with his best opportunity to set before the parish this repertoire of rhetorical devices, designed to maintain and promote an idealised image of their unity and mutual obligations, were the annual sheep counts.
> 
> **2 The Voices of Morebath** (Location 1096)

---

> This meant that in a given year, two thirds or more of the households in the parish had at least one of the church sheep, and young animals were being passed from one farm to another in the course of the year, as parishioners and wardens tried to spread the burden of responsibility fairly. The sheep counts were therefore the most concrete expression of the demands which the parish made on the parishioners of Morebath, and of their mutual obligations, and in reporting them the priest made the most of it.
> 
> **2 The Voices of Morebath** (Location 1104)

---

> The Morebath accounting days and audits, therefore, were far more than simple business meetings at which duly elected parish officials reported to their constituency. They were formal exercises in the construction of community, opportunities for the parish to confront its values and measure the performance of its members, and for the priest to weave round his parishioners a loose rhetorical web designed to school them in the virtues of community.
> 
> **2 The Voices of Morebath** (Location 1161)

---

> In copying the accounts of his parish into a book, Sir Christopher knew that he was writing for posterity. The account book was more than a ledger to keep trace of income and spending. It was an archive, designed to record the benefactors of the parish and ensure that they were prayed for, to inform the wardens of their responsibilities, to record collective decisions binding ‘ever here after by this boke’, an oracle to be consulted in time of dispute.
> 
> **3 The Pursuit of Peace** (Location 1222)

---

> The communal life of Morebath, as we have seen, made heavy demands on its people. Parish officials had to enforce those obligations and, if they were flouted and persuasion failed, might refer the recalcitrant to external authority, the ecclesiastical or even the manor courts.
> 
> **3 The Pursuit of Peace** (Location 1280)

---

> the Morebath accounts have plenty of examples of the extreme care so small a community needed to take to ensure a fair distribution of responsibility, and of the wary compilation of records to prevent conflict, whether the issue was religious or secular.
> 
> **3 The Pursuit of Peace** (Location 1284)

---

> This incident provides the first evidence in the accounts of the strain which the legislative action of the Tudor state might place on the internal workings of the parish: within five years the accelerating pace of Henry’s religious revolution would begin to cut deep into the living tissue of Morebath’s communal life.
> 
> **3 The Pursuit of Peace** (Location 1351)

---

> The boundaries between matters of the soul and of the body in Morebath were loosely drawn. This emerges from a poignant entry in the accounts for 1531, when Richard Hukeley completed a bequest made by his recently deceased daughter Joan for a candlestick of five lights to burn before the image of the Virgin. Joan Hukeley’s bequest did not cover the full cost of the new candlestick, and so her father paid the rest. He did so, however, not simply out of paternal piety for a dead daughter, but with an additional ulterior motive which strikes the squeamish modern reader as shockingly mercenary. The parish, it seemed, owed Hukeley money for expenses incurred on their behalf for work on the railing of Exebridge, and he hoped that his bounty towards the altar of Our Lady might encourage the parishioners to settle this debt. And so, the priest explains, he gave this money in his daughter’s memory, ‘by cause you schuld se the soner that he mayth be contendyd for the rayling of Exbryge’.
> 
> **3 The Pursuit of Peace** (Location 1382)

---

> 1537 was the last year in which Morebath’s pre-Reformation pieties, and the complex social arrangements which underlay them, would remain comparatively undisturbed. Sir Christopher’s account of the rise and resolution of these conflicts allows us to observe the dynamics of a world at the last possible moment before it underwent dramatic and far-reaching change. As a working model of the inter-penetration of secular and religious values and institutions in pre-Reformation England, the clerkship dispute at Morebath would be hard to better.
> 
> **3 The Pursuit of Peace** (Location 1594)

---

> For although we do not have access to the intimacies of Morebath’s religion, we do have plentiful evidence of its external shell, its busy piety, a piety vigorously directed and urged on by their priest. Sir Christopher came to Morebath in the summer of 1520. He was probably in his late twenties, delighted to be there, young, energetic and eager.
> 
> **4 The Piety of Morebath** (Location 1757)

---

> At any rate, from the moment of his arrival he flung himself into a flurry of activity which, over the next fifteen years, would gather and grow until it resembled not so much a breath as a gale, and which simultaneously transformed the interior of his church, and the devotional life of his parish.
> 
> **4 The Piety of Morebath** (Location 1761)

---

> What was lacking among Morebath’s intercessors in 1520 was any saint who might embody regional pride and sense of identity. These were universal saints, venerated not only in Devon but throughout England and indeed the whole of western Europe.
> 
> **4 The Piety of Morebath** (Location 1794)

---

> Soon after his arrival in the parish, therefore, he set about remedying this lack in the pieties of Morebath.
> 
> **4 The Piety of Morebath** (Location 1800)

---

> On 20 November 1534, while the Morebath burglar prepared his tinderbox and ladder for the raid on St Sidwell’s shoe, the clerks of the House of Commons were copying and engrossing a short piece of legislation which had finally completed its slow way through parliament that same week. The Act of Supremacy declared that ‘the king, our sovereign Lord, his heirs and successors, kings of this realm, shall be taken, accepted and reputed the only supreme head on earth of the Church of England, called Anglicana Ecclesia‘. 1 This was the crowning moment of the revolution in religious affairs which had been gathering momentum over the previous five years. The Act translated into statute an already accomplished practical transfer of all the jurisdictional powers of the Pope to a layman, the King of England. By it, the liberties of the Church of England from secular interference that had been guaranteed by Magna Carta were repudiated in favour of total control by the Crown, and the English church’s thousand-year-old allegiance to the Holy See was formally brought to an end.
> 
> **5 Banishing Saint Sidwell** (Location 2056)

---

> The progress of the Reformation in England to this point had been by no means a foregone conclusion. When Martin Luther’s attack on the Catholic Church and the authority of the Pope first began to spread outside Germany, the pious King of England had been one of the most determined and most organised opponents of the new teachings. Henry and his chief minister, Cardinal Wolsey, had mobilised the theologians of Oxford and Cambridge to preach and write against Luther.
> 
> **5 Banishing Saint Sidwell** (Location 2064)

---

> Henry himself published a competent defence of the seven sacraments against Luther, for which in 1521 the grateful Pope Leo X granted him the title Defender of the Faith.
> 
> **5 Banishing Saint Sidwell** (Location 2069)

---

> He genuinely worried that his marriage to his brother’s widow, despite the papal dispensation, might have broken the natural law and so have angered God: more to the point, he wanted a son, and knew now that his ageing Spanish queen would not provide one.
> 
> **5 Banishing Saint Sidwell** (Location 2081)

---

> From 1529 Henry pursued two different but complementary strategies to secure his freedom from Catherine and the right to marry Anne.
> 
> **5 Banishing Saint Sidwell** (Location 2085)

---

> At this stage Henry himself remained firmly Catholic, though increasingly hostile to the pope, but Anne Boleyn held genuinely Protestant opinions and was surrounded by Protestant clients.
> 
> **5 Banishing Saint Sidwell** (Location 2092)

---

> By the beginning of 1533 Anne was pregnant and Henry urgently needed his divorce.
> 
> **5 Banishing Saint Sidwell** (Location 2104)

---

> Sir Christopher and his leading parishioners would have taken a break from clearing their church for the new pews to make their way to Bampton or Tiverton sometime in the early summer of 1534 to take this oath, their first direct encounter with the changes which were about to shatter their world.
> 
> **5 Banishing Saint Sidwell** (Location 2113)

---

> In June 1535 a proclamation spelled out the implications of the abolition of ‘the abuses of the Bishop of Rome, his authority and jurisdiction’. Clergy were commanded to teach the Royal Supremacy to their people, and to ‘cause all manner prayers, orisons, rubrics, canons in mass books, and all other books used in the churches, wherein the said Bishop of Rome is named or his presumptuous and proud pomp and authority preferred, utterly to be abolished, eradicated and erased out, and his name and memory to be nevermore (except to his contumely and reproach) remembered’.
> 
> **5 Banishing Saint Sidwell** (Location 2157)

---

> In obedience to this proclamation, Sir Christopher, like the rest of the parish clergy of England, will have been required by the bishop’s official to scrape or cut the pope’s name out of the Canon of the Mass in his mass-book, and to cease to bid the parish to pray for him each Sunday.
> 
> **5 Banishing Saint Sidwell** (Location 2163)

---

> It is perhaps unlikely that anyone in Morebath wept bitter tears over the disappearance of their local monastery, though some, including their priest, may have shaken their heads over the attack on religious life that it represented.
> 
> **5 Banishing Saint Sidwell** (Location 2199)

---

> The reform measures of August 1536 touched parish life more closely, and were the clearest sign so far of the extent of the revolution represented by the Royal Supremacy.
> 
> **5 Banishing Saint Sidwell** (Location 2208)

---

> Every parson or rector of a church was to provide a bible in Latin and English, to be placed in the church for anyone who wished to read.
> 
> **5 Banishing Saint Sidwell** (Location 2224)

---

> The progress of reform can be measured by the fact that all the bishops, even so unreconstructed an establishment conservative as Veysey, found themselves obliged to enforce so dramatic a break with traditional pieties. Conservatives everywhere reacted to all this with outrage, and traditionalist clergy used the pulpit to advocate resistance to the new religious mood.
> 
> **5 Banishing Saint Sidwell** (Location 2300)

---

> The most radical aspect of the new injunctions, however, was the heightened ferocity of their language against the cult of images. All parish clergy were now instructed to preach a sermon at least once a quarter declaring ‘the very Gospel of Christ’, in which they were to exhort their people to works of charity, mercy and faith prescribed in Scripture, ‘and not to repose their trust and affiance in any other works devised by men’s phantasies, besides Scripture; as in wandering to pilgrimages, offering of money, candles, or tapers to images or relics, or kissing or licking the same, saying over a number of beads, not understood or minded on, or in such-like superstition’.
> 
> **5 Banishing Saint Sidwell** (Location 2314)

---

> These directives against images were so many arrows aimed at the heart of Sir Christopher Trychay. Since his arrival in Morebath, he had coaxed the pieties of the parish into precisely those expresssions of the cult of the saints which the injunctions now denounced as ‘mens phantasies’, contrary to Scripture.
> 
> **5 Banishing Saint Sidwell** (Location 2323)

---

> The injunctions were to become a battleground between reformers and their opponents. Conservatives argued that they merely banned abuse: images might remain as laymen’s books, provided no pilgrimage was made to them nor candles burned before them.
> 
> **5 Banishing Saint Sidwell** (Location 2336)

---

> Morebath’s obedience in all this was strikingly prompt. Many Devon parishes dragged their feet over one aspect or another of the 1538 Injunctions. Bishop Veysey complained bitterly in October 1539 of the persistence in the diocese of the celebration of abrogated feastdays and of ‘superstitious’ observances surrounding the cult of the saints, for example the refusal of carters and smiths to work on the feast of St Loy.
> 
> **5 Banishing Saint Sidwell** (Location 2437)

---

> Yet precisely because it is clear that Sir Christopher remained a firm believer in the intercession of the saints, the extent and promptness of Morebath’s conformity to the letter of the 1538 Injunctions becomes all the more striking. Elsewhere in Devon many parishes made no such wholesale attempts at accommodation.
> 
> **5 Banishing Saint Sidwell** (Location 2500)

---

> Whatever their source, the attempt to establish some sort of normality in the wake of the Injunctions and the drastic reduction of Morebath’s stores was only partially successful.
> 
> **5 Banishing Saint Sidwell** (Location 2522)

---

> For now an extraordinary change comes over the accounts in Sir Christopher’s book. With the single exception of the Maiden Wardens’ accounts, he had to this point invariably presented the accounts of all the stores of Morebath, as well as those of the High Wardens and the Four Men, in the person of the accounting warden. Each of the accounts, therefore, was an exercise in symbolic ventriloquism in which the priest, whose distinctive tone of voice is never for a moment in abeyance, and who certainly read the accounts aloud on the wardens’ behalf, nevertheless effaces himself within the phrasing of the accounts themselves in order to allow the wardens to seem to speak in their own right.
> 
> **5 Banishing Saint Sidwell** (Location 2547)

---

> From 1540 onwards, however, all the accounts are presented in the third person:
> 
> **5 Banishing Saint Sidwell** (Location 2556)

---

> It is hard to put one’s finger on the exact significance of this shift, and there is a danger of reading too much into it.
> 
> **5 Banishing Saint Sidwell** (Location 2559)

---

> It is as if with the disappearance of the stores and the receding of the saints, the community of the parish also reconfigured itself, and was less broadly and less personally conceived.
> 
> **5 Banishing Saint Sidwell** (Location 2566)

---

> The last years of Henry’s reign must have seemed, to begin with, calm after storm for Morebath.
> 
> **6 Morebath Dismantled** (Location 2674)

---

> The Henrician Reformation, a tiger in the late 1530s, seemed now a reassuringly torpid tabby-cat.
> 
> **6 Morebath Dismantled** (Location 2676)

---

> The calm, however, was deceptive: within three years of entering into their contract with Thomas Glasse, the parish was to be to all intents and purposes bankrupt, the interior of its church gutted, its ornaments defaced or confiscated, and its remaining social institutions in disarray. Morebath itself was to be implicated in the folk protest known as the Prayer Book Rebellion, which would end with the butchering of thousands of the men of Devon and Cornwall by foreign mercenaries under a royal flag. At the root of it all was religion, and the social impact of rapid religious change, implicit in the advance of a Protestantism more radical than anything Morebath or any other parish in Devon had ever contemplated, even in nightmare.
> 
> **6 Morebath Dismantled** (Location 2687)

---

> The disposal of church plate to meet parochial or national emergencies was nothing new, nor in itself of much religious significance: it was to prove, however, a portent of the spoliation which was soon to devastate Morebath’s life.
> 
> **6 Morebath Dismantled** (Location 2735)

---

> The boy king was an ardent protestant, surrounded by protestant advisers and guardians. The evangelical party was now triumphant in Court and Capital, and a floodtide of religious revolution was about to be loosed on England. The nation knew it.
> 
> **6 Morebath Dismantled** (Location 2757)

---

> To the reader possessed of hindsight, there is an autumnal tone to this count of the black vestments. It was to prove Catholic Morebath’s swan-song, the last untroubled expression of its pre-Reformation piety.
> 
> **6 Morebath Dismantled** (Location 2814)

---

> The new Injunctions ordered the destruction not only of all abused statues and shrines, but even of such images in stained glass windows, an advance towards an absolute ban on imagery almost without parallel in protestant Europe.
> 
> **6 Morebath Dismantled** (Location 2827)

---

> Ardent Protestants now had the mandate they needed for an all-out onslaught on the forms of traditional religion. In London, evangelicals began a wholesale purge of all the images in the city churches and in St Paul’s.
> 
> **6 Morebath Dismantled** (Location 2836)

---

> It is worth pausing over the significance of this ending for Morebath. The church sheep were an important source of income, whose abolition was to contribute to the calamitous financial crisis shortly to engulf the parish. But there was more to their disappearance than mere finance. Morebath’s curious system of parochial custodianship had regularly involved virtually every farmer and cottager in a very direct expression of support for and involvement in the community of the parish.
> 
> **6 Morebath Dismantled** (Location 2863)

---

> It is very doubtful, however, whether this sudden amputation of so central a parish institution was perceived as an uncomplicated blessing even by those who had grumbled about it or resisted its obligations. Religious reform here touched and tampered not only with the parish’s economy, but with its sense of itself. More and worse was to follow.
> 
> **6 Morebath Dismantled** (Location 2871)

---

> The prohibition of church ales was the first blast in what was to become an ongoing puritan campaign against popular disorder, destined to stretch well into the next century; 29 it was also a body-blow to the parishes of the West Country, for in many, perhaps in most, ales were an indispensable source of revenue.
> 
> **6 Morebath Dismantled** (Location 2883)

---

> The ales were also a lynchpin of social life, the raison d’être of the church houses. Theirs was a religious as well as a social reality, since, in their shared feasting linked to religious festivals and the parish dedication, the ales were one of the most practical expressions possible of the life of charity which the parish existed to support and foster.
> 
> **6 Morebath Dismantled** (Location 2886)

---

> The Commissioners’ blasé instruction to churchwardens to go on raising just as much money without the ales must have added insult to injury, a rewording of Pharaoh’s order to the Israelites to go on making bricks without straw.
> 
> **6 Morebath Dismantled** (Location 2890)

---

> This dissolution of the last of its organisations was a bleak moment for the parish, made bleaker still by the fact that the expenses of the Visitation on top of the continuing payments to Thomas Glasse had exhausted all the accumulated stock of the parish, and the banning of ales left them with no discernible way of replenishing them.
> 
> **6 Morebath Dismantled** (Location 2910)

---

> It seemed to many that the dissolution of the chantries was a mere prelude to the rape and pillage of the parishes, and many began a pre-emptive sale of their treasures to forestall confiscation.
> 
> **6 Morebath Dismantled** (Location 2932)

---

> By the spring of 1549, Morebath’s financial crisis had deepened to desperation.
> 
> **6 Morebath Dismantled** (Location 2990)

---

> The closure and disposal of the church house, devastating as its implications must have been for Morebath’s corporate life, was not their only trouble. The order to compile and certify to the Commissioners an inventory of church goods clearly alarmed the parish, and we possess a vivid documentary snapshot of their attempt to fend off the confiscations which they feared it foreboded.
> 
> **6 Morebath Dismantled** (Location 3011)

---

> All over England, parishes were reacting to the increasing pressure from the Crown in the same way, hiding or selling their treasures to prevent their confiscation. And all over England, too, the atmosphere of uncertainty and confusion, and the flood of church goods coming on to the market, led to an opportunistic surge in sacreligious thefts.
> 
> **6 Morebath Dismantled** (Location 3032)

---

> By the early summer of 1549, therefore, the parish of Morebath had been stripped to the bone. Its images and many of its ritual furnishings were gone, its vestments concealed, its social life was suspended as the church house lay locked and empty, and every one of its parish organisations had been dissolved. A decade before there had been a minimum of twelve elected parish officials active in Morebath, frequently involving women and always including two teenage youths and two girls. Between them all, they raised and managed a total annual income of up to £ 10, deployed about a multitude of parish projects. There was now a single warden, operating with a balance in hand of less than 2/ =, and, as a result of the sale of the church flock, the outlawing of ales and the consequent disappearance of parish feasting, without any regular source of income to meet the mounting costs of reformation. The concealment of the vestments and the sale of the church house goods in the spring of 1549 are a measure of the desperate straits to which so conformist a community as Morebath had been reduced by the course of reform over the previous twelve months. At this low ebb, the parish’s local problems, which were replicated across the county, were swept decisively into greater upheavals. The smouldering grievances of rural England erupted.
> 
> **6 Morebath Dismantled** (Location 3040)

---

> It is routine now to draw a very hard and sharp distinction between the western ‘rebellion’, as historians have come to call it, and these East Anglian and Home Counties ‘commotions’. The western protest was religiously conservative, its major demands, as we shall see, being for a wholesale reversal of the Edwardine Reformation. By contrast, the leaders of the eastern camps deployed a biblical rhetoric, designed to ally them with the reform aspirations of Somerset’s regime.
> 
> **6 Morebath Dismantled** (Location 3086)

---

> Morebath’s part in all this is hidden in ambiguity; indeed, until 1997 none of those who used Sir Christopher’s accounts, myself included, appear to have noticed that the parish had any part in it at all. It is clear that there were no protestants in Morebath, and as we have seen, the Edwardine reforms had pushed its social and religious structures to the point of collapse and beyond.
> 
> **6 Morebath Dismantled** (Location 3200)

---

> An astonishing entry by the priest in the parish accounts reveals, however, that the men of Morebath did more than murmur. We know now for certain that the patience of this most law-abiding of villages snapped in mid-July 1549, and that they equipped and financed a group of five young men to join the rebels in the camp outside Exeter at St David’s Down.
> 
> **6 Morebath Dismantled** (Location 3204)

---

> On first consulting the Morebath manuscript in 1995 I noticed Binney’s mistranscription, and grasped at once that the entry must refer to the siege of Exeter, but I was unwilling to credit that Sir Christopher could have documented in detail the parish’s involvement in armed rebellion, naming not only the men who had directly participated, but the parishioners who provided the money for their arms and maintenance money. In an essay published in 1997, I aired those doubts, and the enormous problems implicit in the notion of a parish equipping its sons for rebellion and then solemnly recording the proceedings in the churchwardens’ accounts. I concluded that the entry must refer to the pressing of the young men of Morebath into a government militia presided over by Paulet, their Manorial Steward.
> 
> **6 Morebath Dismantled** (Location 3234)

---

> And, with hindsight, Sir Christopher knew the words were incriminating. At some point he revisited this entry, and rather ineffectively blotted and scratched out the word ‘campe’ on each of its three occurrences. The words remain clearly legible, perhaps because the ink has thinned and faded with the years, but the attempt to cover them up tells its own story, inexplicable if the entry was made long after the event or was merely an innocent reference to the equipping of royalist militia.
> 
> **6 Morebath Dismantled** (Location 3284)

---

> The chief reason for doubting the plain evidence of the Morebath accounts that the parish had joined the rebels at the siege of Exeter is of course precisely the apparent implausibility of such an indiscretion. How could any man in his right mind, much less one so intelligent and alert to the value and permanence of the written record as Sir Christopher, have been so idiotic as to compile so incriminating an account? The first thing to be said is that he was not alone.
> 
> **6 Morebath Dismantled** (Location 3289)

---

> But secondly, we need to register that at the time of the parish’s involvement in the siege of Exeter, the men of Morebath are most unlikely to have considered themselves to be rebels at all. The county was in arms to defend its ancient traditions against the king’s bad counsellors, not the king.
> 
> **6 Morebath Dismantled** (Location 3305)

---

> The involvement of Morebath in the Prayer Book rebellion not only adds five new names to the fifty or so identifiable rebels, it throws a good deal of light, too, on the motivation for the whole revolt. The articles of the rebels in their final form doubtless represented clerical as well as lay priorities, but there is a consistency about the fundamental grievances of the protestors from the very beginning of the commotions in the West, and the men besieging Exeter quite certainly saw themselves as defending their inherited faith.
> 
> **6 Morebath Dismantled** (Location 3332)

---

> The religious terms in which the demands are framed reminds us that the conservatism of communities like Morebath was more than a matter of the rejection of sheep taxes or the preservation of church furnishing and church funds. They were angry not only that the Reformation had doused the lights and destroyed the statues, but that it threatened the Mass and silenced their prayers for the departed, that it had emptied the religious houses, perhaps even that it had put the king in the place of the pope.
> 
> **6 Morebath Dismantled** (Location 3337)

---

> But there was no such thing in Tudor England as ‘religious causes alone’, for religion was inextricably woven into the social fabric, and a change in the doctrinal definitions was more than a slight adjustment in the way people prayed: apart from anything else, it had just smashed all the best statues in England.
> 
> **6 Morebath Dismantled** (Location 3346)

---

> The suppression of the saints at Morebath negated twenty years of the parish’s collective fund-raising, it had put out all the lights in the church, it had dispersed the Young Men and Maidens and dissolved the parish’s other organisations, it had bankrupted the parish church.
> 
> **6 Morebath Dismantled** (Location 3351)

---

> All we know is that the parishioners of Morebath, so prompt in obedience, so law-abiding, had at last come to see in the Edwardine reforms a force which threatened the foundations of their world. Vainly, belatedly, they had tried to call a halt.
> 
> **6 Morebath Dismantled** (Location 3358)

---

> By the time the parish assembled for the High Wardens’ annual account at All Saints 1549 the Prayer Book rebellion had been suppressed, and Morebath was obliged to come to terms with defeat.
> 
> **6 Morebath Dismantled** (Location 3362)

---

> Inch by inch, however, the parish met the continuing requirements of the Edwardine reform. Cost as much as conservatism kept their compliance slow.
> 
> **6 Morebath Dismantled** (Location 3380)

---

> Sir Christopher says nothing at all about the destruction of Morebath’s images, though it must have been for him, even after the years of cooling of devotion to them since 1538, a peculiarly painful moment.
> 
> **6 Morebath Dismantled** (Location 3388)

---

> But however his church might be reordered, Sir Christopher himself was totally unreconstructed. He continues to call the new communion table, set east and west in the people’s part of the church, the ‘altar’. The parish at large, however, was clearly treating the table as a desacralised object, in a way inconceivable for the old stone altar in the chancel.
> 
> **6 Morebath Dismantled** (Location 3421)

---

> The combination of the old sacral language of altars, alongside the quite new use of the table as a suitable surface for the solemn transfer of parochial resources and responsibilities, is instructive, and full of significance for the future. Already, however unwillingly, however tentatively, a new ceremonial sensibility was in formation.
> 
> **6 Morebath Dismantled** (Location 3428)

---

> The continuing crisis had the effect of moving the management of the parish’s affairs out of the hands of the elected wardens, all of them in these difficult years men of modest means, and more and more into those of the Six Men and the priest.
> 
> **6 Morebath Dismantled** (Location 3477)

---

> Edward’s reign ended for Morebath as it had begun, with confiscation.
> 
> **6 Morebath Dismantled** (Location 3528)

---

> The Five Men’s accounts for this year, made on 14 May, nevertheless, mark another very significant stage in Morebath’s accommodation to the realities of the Reformation. For the first time anywhere in the accounts, the monarch is described in the heading as ‘defender of the fayth and yn yerthe of the churche of inglonde and also of yerlonde the supreme hedd’.
> 
> **6 Morebath Dismantled** (Location 3559)

---

> The claim of Edward VI to be, like his father, Supreme Head of the Church in England, was not of course new to Sir Christopher in 1553. He himself, like every other beneficed clergyman, had taken the oath of supremacy in the 1530s, he was required to explain it to his parishioners four times a year, and it had been endlessly asserted in proclamations and injunctions ever since. But it had made no documentary impact in the Morebath records until now. His careful note of it and subsequent use in the accounts must therefore represent his acceptance, reluctant or complaisant, of a direct order from the authorities, or perhaps of pressure from his parishioners, or internal conviction.
> 
> **6 Morebath Dismantled** (Location 3570)

---

> Sir Christopher’s manifest enthusiasm for the restoration of Catholicism in Mary’s reign.
> 
> **6 Morebath Dismantled** (Location 3575)

---

> Within two months of Morebath’s adoption of Edward’s title to Supremacy, the young king was dead, and his Catholic sister Mary had become queen.
> 
> **6 Morebath Dismantled** (Location 3584)

---

> Herne was no isolated figure: about seventy clergy, 15% of the total number in the diocese, had married in Edward’s reign: these men must have subscribed to some at least of the teachings of the Reformation. All of them were now ejected from their livings by the diocesan authorities, but a third put away their wives, did public penance and found another benefice, where they functioned once more as Catholic priests (though at least half of those who did so were reported to be secretly consorting with their wives).
> 
> **7 Under Two Queens** (Location 3622)

---

> even in so conservative a region and in the face of so decisive a collapse of Protestantism, it was, to begin with at least, a time of confusion and mixed opinions.
> 
> **7 Under Two Queens** (Location 3626)

---

> It was the same elsewhere in the diocese, men and women being by and large willing to turn a blind eye to their Protestant neighbours’ heterodoxies,
> 
> **7 Under Two Queens** (Location 3634)

---

> The Queen issued a proclamation on 18 August enjoining charity and mutual tolerance in religion, but permitting the reintroduction of the old Latin liturgy alongside the still legal Book of Common Prayer, until ‘such time as further order by common assent may be taken therein’. 11 It was a signal for the restoration of Catholicism eagerly taken up all over the country.
> 
> **7 Under Two Queens** (Location 3649)

---

> This settlement was plainly seen as part and parcel of the restoration of Catholicism, a social and economic reordering to match the liturgical and doctrinal one.
> 
> **7 Under Two Queens** (Location 3664)

---

> The reckoning was in effect a resumé of all the disasters and demands of the reign of Edward for which there remained outstanding debts.
> 
> **7 Under Two Queens** (Location 3687)

---

> This 1554 Easter Week reckoning at Morebath, therefore, was a formal celebration of the restoration of parochial life, not merely its replacement on a viable financial footing, but the recovery of its pre-Edwardine spirit of ‘devotion’. That ‘devotion’, the practical expression of the charity existing between parishioners, was represented by their free service and gifts to the community, furthering both its secular concerns and the dignity and upkeep of its church building.
> 
> **7 Under Two Queens** (Location 3769)

---

> Best of all, confident that the Marian restoration was here to stay, parishioners and neighbours now brought out of hiding the flotsam rescued from the Edwardine purge of imagery.
> 
> **7 Under Two Queens** (Location 3848)

---

> Here Sir Christopher was perhaps idealising. Not everyone who returned goods to Morebath church was motivated by pure zeal for the Catholic truth. Edward Rumbelow, executor for small legacies to the church from his father and from Roger Budd, donated a valuable tunicle (not necessarily originally belonging to Morebath), which more than covered those legacies, but he wanted the church to reimburse him for the difference
> 
> **7 Under Two Queens** (Location 3854)

---

> The Marian authorities required every church to have two altars, the high altar and at least one side altar, a provision designed to re-establish the cult of the saints.
> 
> **7 Under Two Queens** (Location 3875)

---

> This bloody scuffle over seven-pence-worth of tithe provides a tantalising glimpse of otherwise hidden tensions: even Marian Morebath was not the garden of Eden. Sir Christopher, however, though bloody, was unbowed. The accounts he presented to the parish just four months later are suffused by manifest satisfaction with the progress of parish reconstruction. And by the end of 1558 Sir Christopher was able to look back over the previous five years as a period of triumphant recovery, a restoration not merely of the church’s ornaments and fabric, but of the parish’s Catholic spirit.
> 
> **7 Under Two Queens** (Location 3908)

---

> The advent of Mary changed all this, because there now emerged a public rhetoric of criticism of the Reformation, legitimating and giving form to conservative popular opinion. From the beginning, the Marian regime was extremely sensitive to the role of such official utterance in forming public opinion and a shared public ‘voice’.
> 
> **7 Under Two Queens** (Location 3968)

---

> Sir Christopher’s outburst, therefore, is not just an expression of personal opinion, though it was certainly heartfelt, and distilled the anger he had clearly felt at seeing so much of his life’s work and so many of his enthusiasms rubbished and undone under Edward. It is itself a sign of the endorsement in Morebath, or at any rate in Morebath’s vicarage, of the wider values of the new regime, the perception of the Reformation as arrogant, destructive and un-English, a disastrous rebellion against God and the faith of our fathers.
> 
> **7 Under Two Queens** (Location 3989)

---

> Queen Mary had died and Elizabeth had been proclaimed Queen in London, just three days before, on the 17th.
> 
> **7 Under Two Queens** (Location 4004)

---

> And so, with impeccably Catholic ceremonial, all over the country parishes celebrated what were to be in fact the funeral rites of Catholic England.
> 
> **7 Under Two Queens** (Location 4024)

---

> Elizabethan Anglicanism used Edward’s Prayer Book, rejected images, detested the pope. Nevertheless, after a draconian beginning, in most places it was far less abrasive than the Edwardine ‘Tudor Church Militant’ on which it was modelled. Elizabeth was a sincere Protestant, but she had none of her brother’s precocious reforming zeal, and in her reign some of the deep rhythms of pre-Reformation religion, outlawed or suspect under Edward, were allowed to reassert themselves. Women were churched, parish ales were drunk, rogation-tide processions visited the old boundaries.
> 
> **7 Under Two Queens** (Location 4160)

---

> And so in Morebath the Reformation came to be, quite literally, part of the furniture. A seat was built by the quire door in 1564 for Sir Christopher to sit in while he read the services, a new and handsomer pair of tables of the Commandments placed ‘by every syde of the auter’ in 1568.
> 
> **7 Under Two Queens** (Location 4192)

---

> Old habits died hard for Sir Christopher. He went on calling Sunday evening prayer ‘Second evenyng prayer’, a hangover from the observance of First and Second Vespers in the old Latin rite. 85 In the same way, he almost invariably referred to the communion table as ‘the auter’ or ‘the hye auter’.
> 
> **7 Under Two Queens** (Location 4214)

---

> By the early 1570s, then, the priest and parishioners of Morebath had all the accoutrements of reformed worship, their chalice excepted.
> 
> **7 Under Two Queens** (Location 4239)

---

> By the end of his life, even Sir Christopher’s conformity had more than mere prudence or resignation about it. He was not unaffected by the prayers he recited, the sermons he preached, the homilies he read. We catch just a single but poignant glimpse of his internalisation of the religion of communion table and prayer desk, just a year before his death.
> 
> **7 Under Two Queens** (Location 4256)

---

> We have to glean Sir Christopher’s changing attitude to religion from such hints, because the accounts he wrote and read to the parish throughout the first twenty-five years of Elizabeth’s reign become steadily and strikingly less religious, more and more dominated by secular concerns: taxation, the equipping of armies, the upkeep of bridges and beacons and bulwarks, the relief of the poor, the maintenance of law and order, and the marketing of Morebath’s livestock and wool.
> 
> **7 Under Two Queens** (Location 4278)

---

> Morebath’s accounts before the reign of Edward are dominated by devotional concerns, the maintenance of lights, the adornment of images and altars, the enrichment of the church building. There was merit in such things, they were the visible trace of love of God and neighbour, they pleased the saints and won their intercession, and they left behind a standing reminder to one’s fellow Christians to pray for the repose of one’s soul. The Reformation removed the rationale for all such giving – negatively, by denying the virtue of any pious acts for salvation, by outlawing prayer for the dead, by identifying this piety of externals with the worship of pagan idols – but also positively, by suggesting, on impeccable biblical warrants, that there was more virtue in generosity to the poor than in the gilding or girding of stocks and stones.
> 
> **7 Under Two Queens** (Location 4295)

---

> The English Reformation also established the rule of thumb that anything given to the glory of God was liable to end up, sooner rather than later, being confiscated by the Crown and turned into a gun or a soldier’s coat.
> 
> **7 Under Two Queens** (Location 4301)

---

> Everywhere, the streams of money and goods poured into the parish churches up to the mid-1530s, and in places like Morebath into the 1540s, dwindled and dried to a trickle.
> 
> **7 Under Two Queens** (Location 4308)

---

> But the process of secularisation of the parish was more than all this: it was in train before the break with Rome, and it was already marked at Morebath in Mary’s reign, for it owes as much to the extension of strong government, and the multiplication of responsibility within local community, as to any ideological shift. Mary reversed her brother’s religious policies, but she too fought France, and the costs of government did not diminish.
> 
> **7 Under Two Queens** (Location 4310)

---

> Crime and poverty loom larger than ever before in the accounts, as parish officials pay the Constable of Bampton for ‘rogis’ [rogues].
> 
> **7 Under Two Queens** (Location 4337)

---

> But we need to beware of easy generalisations here. Mid-Elizabethan Morebath shows signs of concern for poor parishioners, evident in the parish’s handling of the financial and medical decline of Robyn Isac in the 1560s.
> 
> **7 Under Two Queens** (Location 4364)

---

> Despite the fact that now four, not twelve, parishioners were called to office each year, Wardens were having to be elected to a second term of office with greater frequency than before. Morebath was becoming a less cooperative place, where power was less evenly distributed than had once been the case.
> 
> **7 Under Two Queens** (Location 4377)

---

> There were other signs of a coarsening of social fibre. In 1557, while Philip and Mary still ruled, Morebath had made itself a cucking-stool. This was an instrument for the ritual humiliation of women, normally in punishment for the social offence of scolding or back-biting, but also for sexual offences like whoredom or bastardy.
> 
> **7 Under Two Queens** (Location 4380)

---

> more often the stools were simply a form of tumbril, a chair mounted on wheels or a small cart in which the scold could be tied and dragged round the parish, or displayed at her door or the door of the person she had maligned:
> 
> **7 Under Two Queens** (Location 4384)

---

> But we hear nothing in the Morebath accounts of any stocks, the male equivalent of the cucking-stool, and it may be that their cucking-stool is indeed an ugly hint of developing animosity towards women,
> 
> **7 Under Two Queens** (Location 4396)

---

> Though it was introduced under a Catholic Queen, maybe here is one area where the Reformation made a palpable difference for the worse. It is hard to say whether a community which still venerated the Virgin and St Sidwell, and which had a Maiden store functioning alongside the Young Men, would have employed a cucking-stool.
> 
> **7 Under Two Queens** (Location 4398)

---

> If the sacred was receding at Morebath in favour of an increasing engagement with such ‘temporal matters’, its priest remained central to all its activities.
> 
> **7 Under Two Queens** (Location 4400)

---

> Morebath’s parochial life now was increasingly reactive, responding to external demands and stimuli rather than initiating projects,
> 
> **7 Under Two Queens** (Location 4418)

---

> He had been their priest, Catholic and Protestant, for fifty-four years, for fifty-four years the heart and voice, above everything the voice, of all their enterprises. He had been the spirit of Morebath, the chronicler of its dramatic and sometimes tragic share in the religious revolutions of that turbulent age, and the custodian of its blunt attitudes and salt speech. He had baptised their children, buried their dead, married every one of them. He had been the guide of their pieties, he had almost certainly encouraged their sons into rebellion, and, when the time came, he had eased them into a slow and settled conformity to a new order of things.
> 
> **7 Under Two Queens** (Location 4492)