---
title: "Un Verdor Terrible"
author: Benjamin Labatut
date: 2026-03-27
Rating: 10 / 10
---

### Highlights
> (…) We rise, we fall. We may rise by falling. Defeat shapes us. Our only wisdom is tragic, known too late, and only to the lost. GUY DAVENPORT
> 
> **Un verdor terrible** (Location 27)

---

> mordieron cápsulas de cianuro y fallecieron ahogados en el dulce olor a almendras que emite ese veneno.
> 
> **Azul de Prusia** (Location 52)

---

> programa especial que incluyó el Concierto para violín en do mayor de Beethoven,
> 
> **Azul de Prusia** (Location 82)

---

> La forma líquida del veneno, conocida en Alemania como Blausäure (ácido azul), es altamente volátil; hierve a los veintiséis grados centígrados y deja un ligero aroma almendrado en el aire, dulce pero levemente amargo, que no todos logran distinguir, ya que poder hacerlo requiere un gen específico del cual carece el cuarenta por ciento de la humanidad.
> 
> **Azul de Prusia** (Location 101)

---

> otros murieron oliendo la misma fragancia que saborearon los hombres que habían organizado su exterminio al morder sus cápsulas suicidas.
> 
> **Azul de Prusia** (Location 105)

---

> verdadero origen del cianuro, derivado en 1782 del primer pigmento sintético moderno, el azul de Prusia.
> 
> **Azul de Prusia** (Location 110)

---

> el ultramarino, el más refinado y costoso de los pigmentos azules, se obtenía moliendo lapislázuli extraído de cuevas en el valle del río Kocha, en Afganistán.
> 
> **Azul de Prusia** (Location 112)

---

> Uno de los componentes del elixir de Dippel fue lo que acabó produciendo el azul que adornaría no solo el cielo de La noche estrellada de Van Gogh y las aguas de La gran ola de Kanagawa de Hokusai, sino también los uniformes de la infantería del ejército prusiano, como si hubiera algo en la estructura química del color que invocara la violencia, una sombra, una mácula esencial heredada de los experimentos del alquimista, quien despedazó animales vivos y ensambló sus partes en horribles quimeras que intentó reanimar con electricidad, monstruos que inspiraron a Mary Shelley a escribir su obra maestra, Frankenstein o el moderno Prometeo, en cuyas páginas advirtió sobre el avance ciego de la ciencia, la más peligrosa de todas las artes humanas.
> 
> **Azul de Prusia** (Location 172)

---

> Fueron los mismos síntomas que sufrieron miles de niños europeos cuyos juguetes y dulces fueron teñidos con un color fabricado por Scheele con arsénico, sin que el hombre conociera su naturaleza tóxica, un verde esmeralda tan deslumbrante y seductor que se convirtió en el color favorito de Napoleón.
> 
> **Azul de Prusia** (Location 189)

---

> En sus últimas semanas de vida, la enfermedad devastó el cuerpo del Emperador con la misma velocidad con que sus soldados habían arrasado Europa: su piel adquirió un tinte gris y cadavérico, sus ojos perdieron el brillo y se hundieron en sus órbitas, su barba rala se llenó de trozos de vómito.
> 
> **Azul de Prusia** (Location 195)

---

> Si el arsénico es un asesino paciente, que se esconde en los tejidos más profundos de tu cuerpo y se acumula allí durante años, el cianuro te roba el aliento.
> 
> **Azul de Prusia** (Location 204)

---

> Esa rapidez lo volvió el veneno favorito de muchos asesinos;
> 
> **Azul de Prusia** (Location 207)

---

> el genio matemático y padre de la computación Alan Turing se suicidó mordiendo una manzana inyectada con cianuro.
> 
> **Azul de Prusia** (Location 216)

---

> En 1940, cuando Inglaterra se preparaba para una posible invasión alemana, Turing compró dos enormes lingotes de plata con sus ahorros y los enterró en un bosque cerca de su trabajo. Creó un elaborado mapa en código para saber dónde estaban, pero los escondió tan bien que él mismo fue incapaz de encontrarlos al final de la guerra, incluso usando un detector de metales.
> 
> **Azul de Prusia** (Location 227)

---

> El mejor testimonio del miedo que inspiró la primera arma de destrucción masiva de la historia fue la negativa de todos los países a usar gas durante la Segunda Guerra.
> 
> **Azul de Prusia** (Location 247)

---

> Incluso Hitler, que no tuvo reparo alguno en usar gas en los campos de exterminio, se negó a utilizarlo en los de batalla, aunque sus científicos habían fabricado cerca de siete mil toneladas de sarín, suficiente como para acabar con la población de treinta ciudades del tamaño de París. Pero el Führer conocía el gas. Lo había visto en las trincheras cuando no era más que un soldado raso y sufrido parte de la agonía que causaba.
> 
> **Azul de Prusia** (Location 250)

---

> El hombre que había planificado el ataque con gas en Ypres era el creador de esa nueva forma de hacer la guerra, el químico Fritz Haber.
> 
> **Azul de Prusia** (Location 273)

---

> En 1907, Haber fue el primero en extraer nitrógeno —⁠el principal nutriente que las plantas necesitan para crecer⁠— directamente del aire. Con ello, solucionó, del día a la mañana, la escasez de fertilizantes que a principios del siglo XX amenazaba con desencadenar una hambruna global como no se había visto nunca antes; de no haber sido por Haber, cientos de millones de personas que hasta entonces dependían de sustancias naturales como el guano y el salitre para abonar sus cultivos podrían haber muerto por falta de alimentos.
> 
> **Azul de Prusia** (Location 294)

---

> El proceso Haber-Bosch fue el descubrimiento químico más importante del siglo XX: al duplicar la cantidad de nitrógeno disponible, permitió la explosión demográfica que hizo crecer la población humana de 1,6 a 7 mil millones de personas en menos de cien años.
> 
> **Azul de Prusia** (Location 309)

---

> El mundo moderno no podría existir sin el hombre que «extrajo pan del aire», según palabras de la prensa de su época, aunque el uso inmediato de su milagroso hallazgo no fue alimentar a las masas hambrientas, sino proveer a Alemania de la materia prima que necesitaba para seguir fabricando pólvora y explosivos durante la Primera Guerra Mundial, luego de que la flota inglesa cortara su acceso al salitre chileno. Con el nitrógeno de Haber, el conflicto europeo se prolongó dos años más, aumentando las bajas de ambos lados en varios millones de personas.
> 
> **Azul de Prusia** (Location 313)

---

> De los doscientos cincuenta hombres que formaban su compañía, solo cuarenta lograron sobrevivir; Adi fue uno de ellos.
> 
> **Azul de Prusia** (Location 325)

---

> Estaba convencido de que podía minar el oro disuelto en los océanos, pero luego de años de arduo trabajo tuvo que aceptar que su cálculo original había sobrestimado el contenido de este metal precioso en varias órdenes de magnitud. Volvió a su país con las manos vacías.
> 
> **Azul de Prusia** (Location 343)

---

> sin saber que pocos años más tarde el pesticida que él había ayudado a crear sería utilizado por los nazis en sus cámaras de gas para asesinar a su media hermana, a su cuñado, a sus sobrinos, y a tantos otros judíos que murieron en cuclillas,
> 
> **Azul de Prusia** (Location 360)

---

> «Como puede ver, la guerra me ha tratado con la suficiente amabilidad, a pesar del intenso tiroteo, como para poder escapar de todo y hacer esta breve caminata en la tierra de sus ideas»,
> 
> **La singularidad de Schwarzschild** (Location 378)

---

> Schwarzschild le había enviado la primera solución exacta a las ecuaciones de la teoría de la relatividad general.
> 
> **La singularidad de Schwarzschild** (Location 382)

---

> ¿Cuánto hacía que se había publicado su teoría? ¿Un mes? ¿Menos de un mes? Era imposible que Schwarzschild hubiera resuelto ecuaciones tan complejas en tan poco tiempo, si incluso él —⁠que las había inventado⁠— solo había podido hallar soluciones aproximadas.
> 
> **La singularidad de Schwarzschild** (Location 383)

---

> Einstein ya se había resignado a que nadie sería capaz de resolver sus ecuaciones de forma satisfactoria, al menos no durante su vida. Que Schwarzschild lo hubiera hecho entre estallidos de mortero y nubes de gas venenoso era un verdadero milagro:
> 
> **La singularidad de Schwarzschild** (Location 388)

---

> El truco que Schwarzschild había usado para obtener su solución era simple: analizó una estrella idealizada, perfectamente esférica, sin rotación ni carga eléctrica, y luego empleó las ecuaciones de Einstein para calcular cómo esa masa alteraría la forma del espacio, similar a la manera en que una bala de cañón puesta encima de una cama curvaría su colchón.
> 
> **La singularidad de Schwarzschild** (Location 392)

---

> Según los cálculos de Schwarzschild, allí el espacio y el tiempo no se distorsionaban: se desgarraban.
> 
> **La singularidad de Schwarzschild** (Location 400)

---

> El resultado era un abismo sin escape, separado para siempre del resto del universo.
> 
> **La singularidad de Schwarzschild** (Location 402)

---

> con espanto, se dio cuenta de que si su singularidad llegase a existir, duraría hasta el fin del universo. Sus condiciones ideales la convertían en un objeto eterno,
> 
> **La singularidad de Schwarzschild** (Location 417)

---

> los médicos que lo trataron le dijeron que podía haber sido gatillada por su exposición a un ataque de gas ocurrido meses antes.
> 
> **La singularidad de Schwarzschild** (Location 427)

---

> había leído el Harmonice Mundi de Johannes Kepler, quien creía que cada planeta tocaba una melodía en su tránsito alrededor del sol, una música de las esferas que nuestros oídos no alcanzan a distinguir pero que la mente humana sería capaz de descifrar.
> 
> **La singularidad de Schwarzschild** (Location 464)

---

> Como muchas personas sensibles, a medida que se acercaba la Primera Guerra Mundial, Schwarzschild fue invadido por una sensación de desastre inminente.
> 
> **La singularidad de Schwarzschild** (Location 523)

---

> Adelantándose a Einstein, Schwarzschild había considerado la hipótesis de que la geometría del universo no fuera una simple caja de tres dimensiones, sino que pudiera torcerse y deformarse.
> 
> **La singularidad de Schwarzschild** (Location 538)

---

> una larga especulación sobre el efecto nocivo que la guerra tendría sobre el alma de Alemania, un país que Karl seguía amando pero que veía suspendido al borde de un abismo: «Hemos alcanzado el punto más alto de la civilización. Solo nos queda caer».
> 
> **La singularidad de Schwarzschild** (Location 586)

---

> En el último, Schwarzschild dedujo que cualquier objeto podría generar una singularidad si su materia era comprimida en un espacio lo suficientemente reducido: para el sol bastaban tres kilómetros, para la Tierra, ocho milímetros, para un cuerpo humano promedio, 0,000000000000000000000001 centímetros.
> 
> **La singularidad de Schwarzschild** (Location 597)

---

> Karl dedujo que si un hipotético viajero fuera capaz de sobrevivir a un viaje al interior de esa zona rarificada, recibiría luz e información del futuro, permitiéndole ver eventos que aún no habrían sucedido. Si pudiese alcanzar el centro del abismo sin ser despedazado por la gravedad, distinguiría dos imágenes superpuestas, proyectadas simultáneamente en un pequeño círculo sobre su cabeza, como las que uno ve al utilizar un calidoscopio: en una percibiría toda la evolución futura del universo a una velocidad inconcebible, en la otra, el pasado congelado en un instante.
> 
> **La singularidad de Schwarzschild** (Location 601)

---

> Alrededor de la singularidad existía un límite, una barrera que marcaba un punto de no-retorno.
> 
> **La singularidad de Schwarzschild** (Location 606)

---

> Como la luz no podía salir de allí, no podríamos nunca verla con los ojos del cuerpo. Pero tampoco podríamos entenderla con la mente, ya que las matemáticas de la relatividad general perdían su validez en la singularidad.
> 
> **La singularidad de Schwarzschild** (Location 623)

---

> Si ese tipo de monstruos eran un estado posible para la materia, le dijo Schwarzschild con la voz temblorosa, ¿tendrían un correlato en la mente humana? Una concentración suficiente de voluntades, millones de seres humanos sometidos a un solo propósito, sus mentes comprimidas en el mismo espacio psíquico, ¿desencadenarían algo parecido a su singularidad? Schwarzschild no solo estaba convencido de que era posible, sino que ocurriría en la Vaterland.
> 
> **La singularidad de Schwarzschild** (Location 629)

---

> El punto de no-retorno —⁠el límite más allá del cual no se podía ir sin quedar preso⁠— no estaba demarcado de ninguna manera. Para quien lo atravesara, no habría esperanza, su destino estaría irrevocablemente trazado; todas sus trayectorias posibles apuntarían directamente a la singularidad. Y si ese límite era así, le preguntó Schwarzschild con los ojos inyectados en sangre, ¿cómo saber si lo hemos traspasado?
> 
> **La singularidad de Schwarzschild** (Location 636)

---

> El primero de septiembre de 1939 —⁠el mismo día en que los tanques de los nazis cruzaron la frontera de Polonia⁠—, Robert Oppenheimer y Hartland Snyder publicaron un artículo en el volumen 56 de la revista Physical Review.
> 
> **La singularidad de Schwarzschild** (Location 648)

---

> En los años siguientes su radio de acción se volvió cada vez más estrecho. Primero se limitó a viajar dentro de Japón, luego no se aventuró más allá de la prefectura de Kioto, y finalmente sus desplazamientos se redujeron al estrecho circuito que unía su departamento y su pequeña oficina en la universidad.
> 
> **El corazón del corazón** (Location 686)

---

> Hablaba del «corazón del corazón», una extraña entidad que Grothendieck había descubierto en el centro de las matemáticas y que lo había desquiciado por completo.
> 
> **El corazón del corazón** (Location 721)

---

> No le interesaban los números, las curvas, las rectas ni ningún otro objeto matemático en particular: lo único que importaba era la relación entre ellos.
> 
> **El corazón del corazón** (Location 732)

---

> Ante la mirada de Grothendieck, el humilde punto dejó de ser una posición sin dimensiones para bullir con complejas estructuras internas.
> 
> **El corazón del corazón** (Location 736)

---

> La unificación de las matemáticas es un sueño que solo las mentes más ambiciosas han perseguido. Descartes fue uno de los primeros en demostrar que las formas geométricas pueden ser descritas por ecuaciones.
> 
> **El corazón del corazón** (Location 782)

---

> Parte del genio de Grothendieck fue reconocer que había una entidad mayor que se escondía detrás de cualquier ecuación algebraica. Bautizó ese algo como esquema.
> 
> **El corazón del corazón** (Location 787)

---

> La cima de sus investigaciones fue el concepto de motivo: un haz de luz capaz de alumbrar todas las encarnaciones posibles de un objeto matemático. «El corazón del corazón», llamó a esa entidad ubicada en el epicentro del universo matemático, de la cual no conocemos salvo sus más lejanos destellos.
> 
> **El corazón del corazón** (Location 817)

---

> «El gran giro»; así llamó Grothendieck al cambio que alteró la dirección de su vida a los cuarenta y dos años. De golpe se vio poseído por el espíritu de su época: se obsesionó con la ecología, con el complejo militar-industrial y la proliferación de las armas nucleares. Ante la desesperación de su mujer, fundó una comuna en su casa, en la cual convivieron vagabundos, profesores universitarios, hippies, pacifistas, revolucionarios, ladrones, monjes y putas.
> 
> **El corazón del corazón** (Location 835)

---

> Durante cinco años vivió dedicado a labores manuales, sin grandes proyectos, casi completamente aislado.
> 
> **El corazón del corazón** (Location 873)

---

> Ambas teorías no podían ser más opuestas; mientras que a Schrödinger le había bastado una ecuación para describir casi toda la química y la física modernas, las ideas y fórmulas de Heisenberg eran excepcionalmente abstractas, filosóficamente revolucionarias y tan endiabladamente complejas que solo un puñado de físicos las sabían utilizar. E incluso a ellos les generaban dolores de cabeza.
> 
> **Cuando dejamos de entender el mundo** (Location 993)

---

> En la mitad del discurso de Schrödinger, se incorporó de un salto y avanzó hasta el pizarrón ante la mirada atónita de todos los presentes, gritando que los electrones no eran ondas y que el mundo subatómico no podía ser visualizado.
> 
> **Cuando dejamos de entender el mundo** (Location 997)

---

> Pero Heisenberg sabía que todos estaban equivocados. Los electrones no eran ondas, olas ni partículas. El mundo subatómico no se parecía a nada que hubieran conocido.
> 
> **Cuando dejamos de entender el mundo** (Location 1004)

---

> Heisenberg vivía torturado por lo que él consideraba una falla esencial en los fundamentos de la disciplina: las leyes que habían funcionado tan bien para el mundo macroscópico desde Isaac Newton en adelante perdían validez en el interior de los átomos.
> 
> **Cuando dejamos de entender el mundo** (Location 1019)

---

> Heisenberg entendió que aplicar conceptos de la física clásica —⁠como posición, velocidad y momento⁠— a una partícula subatómica era un despropósito total. Ese aspecto de la naturaleza requería un idioma nuevo.
> 
> **Cuando dejamos de entender el mundo** (Location 1045)

---

> En su retiro en Heligoland, Heisenberg decidió someterse a un ejercicio de restricción radical. ¿Qué se podía saber realmente de lo que ocurría en el interior de un átomo? Cada vez que uno de los electrones que rodea el núcleo cambia su nivel de energía, emite un fotón, una partícula de luz. Esa luz puede ser registrada en una placa fotográfica. Y esa es la única información que se puede medir directamente, la única luz que sale de la oscuridad del átomo. Heisenberg decidió abandonar todo lo demás. Él deduciría las reglas que regían esa escala solo basándose en ese puñado escuálido de datos. No iba a utilizar ningún concepto, ninguna imagen, ningún modelo; iba a dejar que la realidad misma dictara lo que se podía decir sobre ella.
> 
> **Cuando dejamos de entender el mundo** (Location 1047)

---

> En su visión del átomo todo aquello se esfumaba; el minúsculo sol se extinguía, el electrón dejaba de girar en redondo y se disolvía en una niebla informe. Lo único que quedaba eran los números.
> 
> **Cuando dejamos de entender el mundo** (Location 1062)

---

> Sus matrices violaban todas las reglas del álgebra común. Obedecían a la lógica de los sueños, donde una cosa puede ser muchas: era capaz de sumar dos cantidades y obtener una respuesta diferente dependiendo del orden en que lo hiciera; tres más dos eran cinco, pero dos más tres podían sumar diez.
> 
> **Cuando dejamos de entender el mundo** (Location 1148)

---

> Todas sus matrices resultaron consistentes: Heisenberg había modelado un sistema cuántico solo en razón de lo que se podía observar directamente. Había reemplazado las metáforas con números y descubierto las reglas que gobernaban lo que ocurría en el interior de los átomos. Sus matrices le permitían describir dónde estaría un electrón de un momento a otro, y cómo interactuaría con otras partículas. Había replicado en el mundo subatómico lo que Newton había hecho para el sistema solar usando solo matemáticas puras, sin recurrir a ninguna imagen.
> 
> **Cuando dejamos de entender el mundo** (Location 1175)

---

> Lo que el joven alemán había logrado no tenía precedentes: equivalía a deducir todas las reglas del torneo de tenis de Wimbledon —⁠desde la indumentaria blanca que debían usar los jugadores hasta la tensión con que se tenían que estirar las redes⁠— solo según las pocas pelotas que salían disparadas por encima de los muros del estadio, sin jamás observar lo que ocurría en la cancha.
> 
> **Cuando dejamos de entender el mundo** (Location 1191)

---

> Pero lo que Einstein aborrecía no era el hermetismo de las fórmulas, sino algo mucho más fundamental: el mundo que Heisenberg había descubierto era incompatible con el sentido común.
> 
> **Cuando dejamos de entender el mundo** (Location 1204)

---

> El padre de la relatividad era el gran maestro de la visualización; todas sus ideas sobre el espacio y el tiempo habían nacido de su capacidad para imaginarse en las situaciones físicas más extremas. Por lo mismo, no estaba dispuesto a aceptar las restricciones que pedía el joven alemán, que parecía haberse sacado ambos ojos para poder ver más lejos.
> 
> **Cuando dejamos de entender el mundo** (Location 1207)

---

> «Durante más de un siglo hemos dividido los fenómenos del mundo en dos campos: los átomos y partículas de la sólida materia y las ondas incorpóreas de la luz, que se propagan por el mar del éter luminífero. Pero estos dos sistemas no pueden permanecer separados; debemos unirlos en una sola teoría que explique sus múltiples intercambios.
> 
> **Cuando dejamos de entender el mundo** (Location 1285)

---

> La luz existe de dos maneras distintas.
> 
> **Cuando dejamos de entender el mundo** (Location 1292)

---

> ¡toda la materia posee esta dualidad! No solo la luz padece este desdoblamiento, sino cada uno de los átomos con que la divinidad ha construido el universo. La tesis que tienen en sus manos demuestra que para cada partícula de materia —⁠sea un electrón o un protón⁠— existe una onda asociada que la transporta por el espacio.
> 
> **Cuando dejamos de entender el mundo** (Location 1295)

---

> la piedra en la mano del niño, que apunta al indolente gorrión en su rama, podría escurrirse como el agua entre sus dedos».
> 
> **Cuando dejamos de entender el mundo** (Location 1300)

---

> La materia, en cambio, era sólida. Que se comportara como una onda era inconcebible. Las dos cosas no podían ser más opuestas. Una partícula de materia, después de todo, es como una minúscula pepita de oro: existe en un espacio determinado y ocupa un solo lugar en el mundo.
> 
> **Cuando dejamos de entender el mundo** (Location 1303)

---

> Las ondas, en cambio, son como el agua del mar; grandes y espaciosas, extendidas a lo largo de una enorme superficie. Como tal, existen en múltiples posiciones al mismo tiempo; si una ola choca contra una roca, puede rodearla y continuar su camino.
> 
> **Cuando dejamos de entender el mundo** (Location 1307)

---

> Lo único que lo torturaba era la conciencia de haber desperdiciado su talento. Su superioridad intelectual había sido evidente desde su infancia: en el colegio siempre tuvo las mejores notas, no solo en las materias que disfrutaba sino en todas.
> 
> **Cuando dejamos de entender el mundo** (Location 1377)

---

> Su esterilidad biológica e intelectual lo llevó a fantasear con el divorcio; tal vez debía abandonarlo todo y comenzar su vida de nuevo, tal vez debía renunciar al alcohol y dejar de perseguir a todas las mujeres que conocía; u olvidar la física y dedicarse de lleno a otra de sus pasiones.
> 
> **Cuando dejamos de entender el mundo** (Location 1387)

---

> Erwin finalmente había encontrado algo en que hundir los dientes y durante su presentación se pavoneó frente a todo el Departamento de Física como si estuviera presentando sus propias ideas: explicó que la mecánica cuántica, que tantos problemas estaba causando, podía ser domada con un esquema clásico.
> 
> **Cuando dejamos de entender el mundo** (Location 1394)

---

> Una cosa era decir que la materia estaba hecha de ondas y otra, muy distinta, era explicar cómo ondulaban. Si Herr Schrödinger pretendía hablar con un mínimo de rigor, necesitaba tener una ecuación de ondas.
> 
> **Cuando dejamos de entender el mundo** (Location 1401)

---

> A diferencia de sus coetáneos, cultivaba la informalidad y se vestía más como un estudiante que como un profesor, lo que solía traerle problemas:
> 
> **Cuando dejamos de entender el mundo** (Location 1436)

---

> Lo que la noche anterior había sentido como el rapto intelectual más importante de su vida le pareció poco más que el desvarío de un físico amateur, un triste episodio de megalomanía.
> 
> **Cuando dejamos de entender el mundo** (Location 1458)

---

> No lograba descifrar qué argumento llevaba a qué resultado; lo único claro era la ecuación contenida en la última página —⁠que capturaba de forma perfecta el movimiento de un electrón en el interior del átomo⁠—, aunque parecía no estar conectada a nada de lo que había escrito antes.
> 
> **Cuando dejamos de entender el mundo** (Location 1501)

---

> Schrödinger había tenido que incluir un número complejo en su fórmula: la raíz cuadrada de menos uno. En la práctica, lo que eso significaba era que una parte de la onda que su ecuación describía se salía de las tres dimensiones del espacio.
> 
> **Cuando dejamos de entender el mundo** (Location 1535)

---

> Por hermosas que fueran, las olas de Schrödinger no eran parte de este mundo. Para él estaba claro que su nueva ecuación describía a los electrones como si fueran ondas. ¡El problema era entender qué diablos estaba ondeando!
> 
> **Cuando dejamos de entender el mundo** (Location 1537)

---

> Más difícil de entender era el hecho de que su ecuación no mostrara una ola individual para cada electrón, sino una enorme variedad de ondas superpuestas. ¿Todas describían el mismo objeto o cada una representaba un mundo posible? Schrödinger contempló la segunda posibilidad; esas múltiples olas serían el primer vistazo de algo completamente nuevo, cada una el breve destello de un universo que nacía cuando el electrón saltaba de un estado a otro, ramificándose hasta poblar el infinito, como las joyas de la red de Indra.
> 
> **Cuando dejamos de entender el mundo** (Location 1580)

---

> Se veía tan delgada que Schrödinger llegó a cuestionarse si acaso el tiempo había transcurrido de forma distinta para los dos; era imposible que un ser humano sufriera una alteración tan profunda en un par de días.
> 
> **Cuando dejamos de entender el mundo** (Location 1688)

---

> Pero Schrödinger no sabía lo que era. Tenía la forma de una ola, pero no podía ser un fenómeno físico real, ya que se movía fuera de este mundo, en un espacio multidimensional.
> 
> **Cuando dejamos de entender el mundo** (Location 1708)

---

> Pero ¿cómo iba a convencer a los demás de que algo así podía existir? Ψ no era detectable; no dejaría huella en ningún instrumento, no podría ser capturada por el aparato más ingenioso, ni el más avanzado de todos los experimentos.
> 
> **Cuando dejamos de entender el mundo** (Location 1711)

---

> Schrödinger sabía que era el descubrimiento que había añorado durante toda su vida, pero no tenía cómo explicarlo. No había derivado su ecuación de fórmulas anteriores. No había trabajado en base a nada conocido. La ecuación misma era un principio, y su mente la había arrancado de la nada.
> 
> **Cuando dejamos de entender el mundo** (Location 1714)

---

> Schrödinger se dedicó a viajar por Europa presentando sus ideas, cosechando aplausos en todas partes, hasta que se topó con Werner Heisenberg.
> 
> **Cuando dejamos de entender el mundo** (Location 1738)

---

> Para Heisenberg, lo que Schrödinger planteaba era un retroceso imperdonable. No se podían usar métodos de la física clásica para explicar el mundo cuántico.
> 
> **Cuando dejamos de entender el mundo** (Location 1740)

---

> La ecuación de Schrödinger podía ser hermosa y útil, pero fallaba en lo esencial, al no reconocer la radical extrañeza de esa escala de la materia.
> 
> **Cuando dejamos de entender el mundo** (Location 1742)

---

> aunque todos estuvieran hechizados por la herramienta que el austriaco les había regalado, él sabía que era un callejón sin salida, un camino ciego que solo los alejaría de la verdadera comprensión.
> 
> **Cuando dejamos de entender el mundo** (Location 1744)

---

> en lo que fue el golpe mortal en la pelea entre ambos, Schrödinger publicó un artículo que demostraba que su enfoque y el de Heisenberg eran matemáticamente equivalentes.
> 
> **Cuando dejamos de entender el mundo** (Location 1753)

---

> No había que sacarse los ojos para ver las partículas subatómicas, como le gustaba decir al joven Heisenberg: solo había que cerrarlos e imaginar.
> 
> **Cuando dejamos de entender el mundo** (Location 1755)

---

> Cuando el mismo Heisenberg fue incapaz de derivar el espectro de un átomo de hidrógeno con sus matrices, y se vio obligado a recurrir a la teoría de su rival, su odio alcanzó el paroxismo: hizo los cálculos rechinando los dientes, como si se los estuvieran arrancando uno a uno.
> 
> **Cuando dejamos de entender el mundo** (Location 1760)

---

> Bohr y Heisenberg tenían mucho en común: al igual que su pupilo, el danés era famoso por la casi deliberada oscuridad de sus argumentos, y aunque todos lo respetaban, muchos decían que sus ideas tenían la tendencia a caer más cerca de la filosofía que de la física.
> 
> **Cuando dejamos de entender el mundo** (Location 1766)

---

> Según él, los atributos de las partículas elementales surgían de una relación, y tenían validez solo en un contexto determinado. No se podían reducir a una sola mirada. Si eran medidas con un tipo de experimento, exhibirían las propiedades de una onda; con otro, aparecerían como partículas.
> 
> **Cuando dejamos de entender el mundo** (Location 1771)

---

> Heisenberg detestaba la complementariedad. Estaba convencido de que había que desarrollar un sistema único de conceptos, no dos que fueran contradictorios.
> 
> **Cuando dejamos de entender el mundo** (Location 1774)

---

> Sin la oposición de Bohr, Heisenberg se quedó solo con sus demonios y rápidamente se convirtió en su peor enemigo.
> 
> **Cuando dejamos de entender el mundo** (Location 1779)

---

> Eso era todo lo que uno podía ver con la mecánica de Schrödinger: imágenes borrosas, una presencia fantasmal, difusa e indefinida,
> 
> **Cuando dejamos de entender el mundo** (Location 1788)

---

> Pero ¿qué sucedía si uno consideraba esa perspectiva y la suya al mismo tiempo? La respuesta le pareció tan absurda como para ser interesante: un electrón que era —⁠a la vez⁠— una partícula confinada en un punto y una ola extendida a lo largo del tiempo y el espacio.
> 
> **Cuando dejamos de entender el mundo** (Location 1789)

---

> Lo terrorífico no son los cuerpos podridos flotando en el agua con la carne hinchada cayéndose de los huesos. No. Lo verdaderamente atroz es que yo supe todo eso de forma casi instantánea.
> 
> **Cuando dejamos de entender el mundo** (Location 1822)

---

> Cuando vio la ventana de su pieza, sintió que algo enorme le seguía los pasos. Miró por encima de su hombro y vio una figura negra que lo oscurecía todo. Se echó a correr despavorido, pero al tropezar se dio cuenta de que lo perseguía su propia sombra, proyectada hacia atrás por la luz que sostenía entre las manos. Giró para enfrentar a su espectro, extendió los brazos y abrió sus palmas. La luz y la sombra se extinguieron al unísono.
> 
> **Cuando dejamos de entender el mundo** (Location 1856)

---

> Un electrón, explicó Heisenberg, no existía en un solo lugar, sino en muchos; no tenía una velocidad, sino múltiples. La función de onda mostraba todas esas posibilidades superpuestas.
> 
> **Cuando dejamos de entender el mundo** (Location 1864)

---

> Analizando las matemáticas de Schrödinger y las suyas, había descubierto que ciertas propiedades de un objeto cuántico —⁠como su posición y su cantidad de movimiento⁠— existían de forma pareada, y obedecían a una extrañísima relación. Cuanto más precisa era la identidad que adoptaba en una de ellas, más incierta se volvía la otra.
> 
> **Cuando dejamos de entender el mundo** (Location 1866)

---

> Si el electrón tenía una cantidad de movimiento exacta, su posición se volvía tan indeterminada que podía estar en la palma de tu mano o al otro lado del universo. Esas dos variables eran matemáticamente complementarias: fijar una disolvía la otra.
> 
> **Cuando dejamos de entender el mundo** (Location 1871)

---

> el efecto en los objetos macroscópicos era imperceptible, mientras que para una partícula era gigantesco.
> 
> **Cuando dejamos de entender el mundo** (Location 1879)

---

> Su intuición original había sido correcta: era imposible «ver» una entidad cuántica por la sencilla razón de que no tenía una sola identidad.
> 
> **Cuando dejamos de entender el mundo** (Location 1885)

---

> En términos filosóficos, le dijo tomándolo del brazo, era el fin del determinismo. La incertidumbre de Heisenberg trizaba la esperanza de todos quienes habían creído en el universo de relojería que prometía la física de Newton.
> 
> **Cuando dejamos de entender el mundo** (Location 1889)

---

> Si todo lo que ocurría era consecuencia directa de un estado anterior, lo único que necesitaban era mirar el presente y echar a correr las ecuaciones para obtener un conocimiento similar al de Dios.
> 
> **Cuando dejamos de entender el mundo** (Location 1892)

---

> lo que estaba más allá de nuestro alcance no era el futuro. Tampoco el pasado. Era el presente. Ni siquiera el estado de una miserable partícula podía ser aprehendido de manera perfecta.
> 
> **Cuando dejamos de entender el mundo** (Location 1894)

---

> Ese era el genio de la ecuación de Schrödinger: de alguna manera era capaz de hilvanar los infinitos destinos de una partícula, todos sus estados, todas sus trayectorias, en una sola trama
> 
> **Cuando dejamos de entender el mundo** (Location 1900)

---

> Una partícula tenía muchas maneras de atravesar el espacio, pero elegía una sola. ¿Cómo? Por puro azar.
> 
> **Cuando dejamos de entender el mundo** (Location 1902)

---

> Conferencia Solvay, la reunión científica más prestigiosa de la época. Ni antes ni después hubo una concentración tan grande de genios bajo un mismo techo;
> 
> **Cuando dejamos de entender el mundo** (Location 1925)

---

> Durante la tarde, Heisenberg y Bohr presentaron su versión de la mecánica cuántica, que llegaría a ser conocida como la Interpretación de Copenhague.
> 
> **Cuando dejamos de entender el mundo** (Location 1941)

---

> La realidad, les dijeron a los presentes, no existe como algo aparte del acto de observación. Un objeto cuántico no tiene propiedades intrínsecas. Un electrón no está en ningún lugar fijo hasta que se lo mide; solo en este instante aparece. Antes de la medición, no tiene ningún atributo; antes de la observación, ni siquiera se puede pensar en él. Existe de una manera determinada cuando es detectado por un instrumento determinado. Entre una medición y otra, no tiene sentido alguno preguntar cómo se mueve, qué es, ni dónde está. Como la luna en el budismo, una partícula no existe; el acto de medición la vuelve un objeto real.
> 
> **Cuando dejamos de entender el mundo** (Location 1942)

---

> La física ya no debía preocuparse de la realidad, sino de lo que podemos decir sobre la realidad.
> 
> **Cuando dejamos de entender el mundo** (Location 1947)

---

> Viven en un mundo de potencialidades, explicó Heisenberg: no son cosas, sino posibilidades.
> 
> **Cuando dejamos de entender el mundo** (Location 1948)

---

> Medido como una onda, un electrón aparecería como tal; medido como partícula, tomaría esa otra forma.
> 
> **Cuando dejamos de entender el mundo** (Location 1950)

---

> Sencillamente, no existía un «mundo real» allá afuera que la ciencia pudiera estudiar.
> 
> **Cuando dejamos de entender el mundo** (Location 1952)

---

> Para Einstein, la física debía hablar de causas y resultados, y no solo de probabilidades. Se negaba a creer que los hechos del mundo obedecieran a una lógica tan contraria al sentido común.
> 
> **Cuando dejamos de entender el mundo** (Location 1962)

---

> Cada mañana en el desayuno (y de forma paralela a las discusiones oficiales) Einstein planteaba sus acertijos, y cada noche Bohr llegaba con el problema resuelto.
> 
> **Cuando dejamos de entender el mundo** (Location 1967)

---

> Einstein se convirtió en el mayor enemigo de la mecánica cuántica. Hizo innumerables intentos para tratar de encontrar un camino de regreso hacia un mundo objetivo, buscando un orden oculto que permitiera unir su teoría de la relatividad y la mecánica cuántica, para poder desterrar el azar que se había colado en la más exacta de todas las ciencias.
> 
> **Cuando dejamos de entender el mundo** (Location 1978)

---

> murió sin lograrlo, aún admirado por todos, aunque completamente alienado de las nuevas generaciones,
> 
> **Cuando dejamos de entender el mundo** (Location 1982)

---

> Schrödinger también llegó a odiar la mecánica cuántica. Inventó un elaborado experimento mental, un Gedankenexperiment, que daba como resultado una criatura aparentemente imposible: un gato que estaba vivo y muerto al mismo tiempo.
> 
> **Cuando dejamos de entender el mundo** (Location 1985)

---

> Los partidarios de Copenhague le dijeron a Schrödinger que tenía toda la razón: el resultado no solo era absurdo, sino también paradójico. Pero era cierto.
> 
> **Cuando dejamos de entender el mundo** (Location 1987)

---

> el nombre del austriaco quedó para siempre asociado a ese intento fallido de negar las ideas que él mismo había ayudado a crear.
> 
> **Cuando dejamos de entender el mundo** (Location 1989)

---

> El jardinero nocturno me contó que el científico que inventó los fertilizantes nitrogenados modernos —⁠un químico alemán llamado Fritz Haber⁠— fue también el primer hombre en crear un arma de destrucción masiva, el gas de cloro, que vertió en las trincheras de la Primera Guerra Mundial.
> 
> **Epílogo El jardinero nocturno** (Location 2071)

---

> Una de las cosas que siempre me han sorprendido de Chile es la aversión que sentimos por la cordillera. No habitamos las montañas. Los Andes son como una espada que nos atraviesa la columna, pero ignoramos esas cumbres ciclópeas y nos instalamos en los valles y en la costa,
> 
> **Epílogo El jardinero nocturno** (Location 2104)

---

> Al igual que el jardinero nocturno, cuando Grothendieck llegó a la mitad del camino de su vida, dejó su hogar, a su familia, su carrera y a sus amigos y vivió como un monje, recluido en los Pirineos.
> 
> **Epílogo El jardinero nocturno** (Location 2120)

---

> Pero no es solo la gente común: los propios científicos han dejado de entender el mundo.
> 
> **Epílogo El jardinero nocturno** (Location 2130)

---

> Sabemos cómo usarla, funciona por una suerte de milagro, y sin embargo no hay un alma en este planeta, nadie vivo o muerto, que realmente la entienda.
> 
> **Epílogo El jardinero nocturno** (Location 2134)