---
title: "La Amiga Estupenda"
author: Elena Ferrante
date: 2023-11-5
Rating: 9 / 10
---

### Highlights
> Subíamos despacio hacia el mayor de nuestros terrores de entonces, íbamos a exponernos al miedo y a interrogarlo.
> 
> **Infancia Historia de don Achille** (Location 149)

---

> me pareció que no solo sabía decir bien las cosas, sino que estaba desarrollando un don que yo conocía ya: con mayor destreza que cuando era niña, tomaba los hechos y los expresaba de forma natural, cargados de tensión; reforzaba la realidad mientras la traducía en palabras, le inyectaba energía.
> 
> **Adolescencia Historia de los zapatos** (Location 1611)

---

> Nino mira siempre enfurruñado, sus ojos ven más allá de las cosas y las personas y parecen asustarse; Donato siempre tiene una mirada dispuesta a adorar la apariencia de las cosas o las personas y no hace más que sonreír. Nino tiene algo que lo reconcome por dentro, como Lila, se trata de un don y un sufrimiento, no están contentos, no se sueltan, temen lo que ocurre a su alrededor; este hombre, no, parece amar todas las manifestaciones de la vida, como si cada segundo vivido fuera de una limpidez absoluta.
> 
> **Adolescencia Historia de los zapatos** (Location 3005)

---

> Lila sabía hablar a través de la escritura; a diferencia de mí cuando escribía, a diferencia de Sarratore en sus artículos y poemas, a diferencia incluso de muchos escritores que había leído y que leía, ella se expresaba con frases cuidadas, sin errores pese a no haber seguido estudiando, pero, además, no dejaba ni rastro de afectación, no se notaba el artificio de la palabra escrita.
> 
> **Adolescencia Historia de los zapatos** (Location 3055)

---

> se encontraba en la cocina, fregando platos, estaba cansada, sin fuerzas, cuando oyó una explosión. Se volvió de golpe y se dio cuenta de que había explotado la olla grande de cobre. Así, sola. Colgaba de su clavo de siempre, pero en el centro tenía un corte largo, con los bordes levantados y retorcidos, y la olla se había deformado por completo, como si no lograra conservar su apariencia de olla. Su madre entró corriendo en camisón y le echó la culpa de haberla dejado caer, de haberla estropeado. Pero una olla de cobre, aunque se caiga, no se rompe y no se deforma de esa manera. «Estas son las cosas —concluía Lila— que me asustan. Más que Marcello, más que nadie. Y siento que debo encontrar una solución, de lo contrario, poco a poco, acabará rompiéndose todo, todo, todo».
> 
> **Adolescencia Historia de los zapatos** (Location 3091)

---

> voz aflautada.
> 
> **Adolescencia Historia de los zapatos** (Location 3503)

---

> La plebe éramos nosotros. La plebe era ese disputarse la comida y el vino, ese pelearse para que te sirvieran el primero y mejor, ese suelo mugriento por el que los camareros iban y venían, esos brindis cada vez más vulgares. La plebe era mi madre, que había bebido y ahora se aflojaba apoyando la espalda contra el hombro de mi padre, serio, y se reía con la boca abierta de par en par de las alusiones sexuales del comerciante de metales. Reían todos, también Lila, con el aire de quien tiene un papel y lo interpreta hasta el final.
> 
> **Adolescencia Historia de los zapatos** (Location 4614)