---
title: "La Niña Perdida"
author: Elena Ferrante
date: 2023-11-21
Rating: 8 / 10
---

### Highlights
> era la punta del compás que permanece fija mientras la mina da vueltas alrededor trazando círculos.
> 
> **Madurez. La niña perdida** (Location 2354)

---

> —No, para producir ideas no hace falta ser unos santos. De todos modos, son muy pocos los auténticos intelectuales. La masa de los cultos se pasa la vida comentando perezosamente las ideas ajenas.
> 
> **Madurez. La niña perdida** (Location 3661)

---

> Fuera flotaba en el aire un fuerte olor a almendras tostadas,
> 
> **Madurez. La niña perdida** (Location 4560)

---

> Tal vez lo que había atraído a Nino era la impresión de haber encontrado en Lila eso que él también había supuesto tener y que ahora, efectuada la comparación, descubría no tener. Ella poseía inteligencia y no le sacaba partido, al contrario, la desperdiciaba como una gran señora para quien las riquezas del mundo solo son un signo de vulgaridad. Ese era el hecho innegable que debió de embelesar a Nino: la gratuidad de la inteligencia de Lila.
> 
> **Vejez. Historia de la mala sangre** (Location 5591)

---

> Solo en las malas novelas la gente piensa siempre lo correcto, dice siempre lo correcto, todo efecto tiene su causa, hay simpáticos y antipáticos, buenos y malos, al final todo te consuela.
> 
> **Vejez. Historia de la mala sangre** (Location 6279)

---

> Toda relación intensa entre seres humanos está plagada de cepos y si se quiere que dure hay que aprender a esquivarlos. Lo hice también en esa circunstancia y al final tuve la sensación de haberme topado con una enésima prueba de lo espléndida y tenebrosa que era nuestra amistad, de lo largo y complicado que había sido el dolor de Lila, de que ese dolor aún duraba y duraría siempre.
> 
> **Vejez. Historia de la mala sangre** (Location 6290)

---

> A diferencia de lo que narran los cuentos, la vida real, cuando ha pasado, no se asoma a la claridad sino a la oscuridad.
> 
> **Vejez. Restitución** (Location 6586)