---
title: "Las Deudas del Cuerpo"
author: Elena Ferrante
date: 2023-11-15
Rating: 9 / 10
---

### Highlights
> Cuanto más intentaba yo sacarla a descubierto e implicarla en mi deseo de aclarar las cosas, más se refugiaba ella en la penumbra. Parecía la luna llena cuando se agazapa detrás del bosque y las ramas le garabatean la cara.
> 
> **87** (Location 4190)

---

> ¿Dónde se ha visto que la gente hable «verdaderamente» y que las cosas ocurran «de repente»? Sabes mejor que yo que todo es un enredo y que a una cosa le sigue otra y después otra más. Yo ya no hago nada «de verdad», Lenù. Y he aprendido a estar atenta a las cosas, solo los imbéciles creen que pasan «de repente».
> 
> **88** (Location 4290)

---

> Llegar a ser. Frase verbal que siempre me había obsesionado, pero en la que reparé por primera vez en esa circunstancia. Yo quería llegar a ser, aunque jamás había sabido qué. Y había llegado a ser, no cabía duda, pero sin un objetivo, sin una auténtica pasión, sin una resuelta ambición. Había querido llegar a ser algo —ese era el punto— solo porque temía que Lila llegara a ser a saber quién, dejándome a mí atrás.
> 
> **96** (Location 4714)

---

> tal vez, frente al abandono seamos todos iguales: tal vez ni siquiera una cabeza bien ordenada puede aguantar al descubrir que no es amada.
> 
> **121** (Location 5658)