---
title: "Un Mal Nombre"
author: Elena Ferrante
date: 2023-11-11
Rating: 10 / 10
---

### Highlights
> siempre la misma historia, en el interior de lo pequeño siempre hay algo todavía más pequeño que quiere salir a relucir, y en el exterior de lo grande hay algo todavía más grande que quiere mantenerlo prisionero. Me voy a cocinar.
> 
> **Juventud** (Location 699)

---

> Hay momentos en que recurrimos a fórmulas insensatas y planteamos exigencias absurdas para ocultar sentimientos lineales.
> 
> **Juventud** (Location 3834)

---

> De repente comprendí por qué no había conseguido a Nino, por qué se lo había quedado Lila. Era incapaz de entregarme a los sentimientos verdaderos. No sabía dejarme arrastrar más allá de los límites. No poseía la fuerza emotiva que había empujado a Lila a hacer lo imposible para disfrutar de ese día y de esa noche. Me quedaba atrás, a la espera. En cambio ella tomaba posesión de las cosas, las quería de verdad, se apasionaba con ellas, jugaba al todo o nada, y no temía el desprecio, el escarnio, los escupitajos, las palizas. En una palabra, ella se había merecido a Nino porque consideraba que amarlo suponía tratar de conseguirlo, no esperar a que él la quisiera.
> 
> **Juventud** (Location 4131)

---

> aterrorizada por esa oferta de salvación.
> 
> **Juventud** (Location 4232)

---

> las personas tardan en comprender lo que está bien y lo que está mal, y ayudarlas supone hacer por ellas aquello que en un determinado momento de su vida son incapaces de realizar.
> 
> **Juventud** (Location 5228)

---

> —Se titula Ulises. —¿ Habla de la Odisea? —No, habla de la mediocridad de la vida de hoy. —¿ Y qué más? —Nada más. Dice que tenemos la cabeza llena de tonterías. Que somos carne, sangre y huesos. Que todas las personas valen lo mismo. Que solo queremos comer, beber, follar.
> 
> **Juventud** (Location 5474)

---

> Se pasó la impresión inicial de encontrarme en medio de una batalla intrépida. Se pasaron las palpitaciones en cada examen y la alegría de haberlo aprobado con la nota más alta. Se pasó el placer de reeducarme en la voz, en el gesto, en el modo de vestir y de andar, como si compitiera por el premio al mejor disfraz, a la máscara lucida tan bien que era casi rostro.
> 
> **Juventud** (Location 5789)

---

> el tiempo sencillamente se escurre sin sentido alguno, y que era bonito solo vernos de vez en cuando para oír el sonido loco del cerebro de la una resonando dentro del sonido loco del cerebro de la otra.
> 
> **Juventud** (Location 6730)