---
title: "Colophon"
---

This website is powered by [Quarto](https://www.quarto.org). All pages are written in Markdown, rendered with Pandoc and published to the web with GitHub Pages via VS Code. This is also the basic workflow I use for all of my note-taking and most of my writing. I'm partial to [files over apps](https://stephango.com/file-over-app), and Quarto allows me to follow this tenet while providing a great literate programming environment. 

During my PhD I spent an inordinate amount of time playing with $\mathrm{\LaTeX}$ font settings and poring over the [`microtype` documentation](https://ctan.math.illinois.edu/macros/latex/contrib/microtype/microtype.pdf). Nothing good came of it, except for a lasting appreciation for the amount of work and finesse behind good typesetting. The font I use here is [Alegreya Sans](https://huertatipografica.com/en/fonts/alegreya-sans-ht), "*a humanist sans serif family with a calligraphic feeling*". It's beautiful, Latin American and free --- just like myself. For code chunks, my go-to font is [Fira Code](https://firacode.org/), although I seem to have a different favorite every time I run a [blind test](https://www.codingfont.com/).