---
title: "Listening Notes"
toc: true
---

I started this file with the intention of registering memorable passages for some of my favorite pieces. Now I realize that there's so much more than I imagined and I will probably never complete them all

Initially I didn't get instrumental music. The first hook was sonata form

I came into classicalmusic by accident at FNAC

Some notable names are not included, like haydn, a little bach, bruckner


## Pieces

### Solo Piano

#### Almeida Prado, Cartas Celestes

#### Ligeti, Musica Ricercata

#### Liszt, B Minor Sonata

#### Schubert, Piano Sonata D. 959

#### Schubert, Piano Sonata D. 960



### Chamber Music

#### Bartók, String Quartet No. 4

#### Bartók, String Quartet No. 5

#### Bartók, String Quartet No. 6

#### Beethoven, String Quartet Op. 18 No. 6

#### Beethoven, String Quartet Op. 59 No. 3 "Razumovsky"

#### Beethoven, String Quartet Op. 95 "Serioso"

#### Beethoven, String Quartet Op. 130

#### Beethoven, String Quartet Op. 131

#### Beethoven, String Quartet Op. 132

#### Beethoven, String Quartet Op. 133

#### Beethoven, String Quartet Op. 135

#### Brahms, Clarinet Quintet

#### Brahms, Piano Trio No. 1

#### Brahms, Piano Quartet No. 1

#### Brahms, Piano Quintet

#### Brahms, String Sextet No. 2

#### Brahms, Violin Sonata No. 1

#### Brahms, Violin Sonata No. 2

#### Brahms, Violin Sonata No. 3

#### Debussy, String Quartet

#### Ligeti, String Quartet No. 1

#### Ligeti, String Quartet No. 2

#### Messiaen, Quartet for the End of Time

#### Mendelssohn, String Octet

#### Ravel, String Quartet

#### Shaw, Entr'acte

#### Schoenberg, String Quartet No. 1

#### Schoenberg, String Quartet No. 2

#### Schoenberg, Verklarte Nacht

#### Shostakovich, String Quartet No. 4

#### Shostakovich, String Quartet No. 8

#### Shostakovich, String Quartet No. 9

#### Shostakovich, String Quartet No. 10

#### Shostakovich, String Quartet No. 15

#### Schubert, Cello Quintet

#### Schubert, Piano Quintet "Trout"

#### Schubert, String Quartet No. 13 "Rosamunde"

#### Schubert, String Quartet No. 14 "Death and the Maiden"



### Concertos

#### Adams, Absolute Jest
The idea of a concert for string quartet is already great by itself. On top of that, the music is lively and playful, featuring a bunch of quotations from Beetoven's Scherzos and late quartets. 

#### Bartók, Violin Concerto No. 2

#### Beethoven, Piano Concerto No. 4

#### Beethoven, Piano Concerto No. 5 "Emperor"

#### Beethoven, Violin Concerto

#### Brahms, Piano Concerto No. 1

#### Brahms, Piano Concerto No. 2

#### Brahms, Violin Concerto

#### Bruch, Violin Concerto

#### Grieg, Piano Concerto

#### Elgar, Cello Concerto

#### Ligeti, Violin Concerto

#### Mendelssohn, Violin Concerto

#### Ravel, Piano Concerto in G Major

#### Shostakovich, Violin Concerto No. 1

#### Shostakovich, Cello Concerto No. 1

#### Sibelius, Violin Concerto

#### Tchaikovsky, Piano Concerto No. 1

#### Tchaikovsky, Violin Concerto



### Symphonies

#### Adams, Harmonielehre

#### Almeida Prado, Sinfonia dos Orixás

#### Bartók, Music for Strings, Percussion and Celesta

#### Beethoven, 3rd Symphony "Emperor"

#### Beethoven, 4th Symphony

#### Beethoven, 5th Symphony

#### Beethoven, 6th Symphony

#### Beethoven, 7th Symphony

#### Beethoven, 9th Symphony "Choral"

#### Berlioz, Symphonie Phantastique

#### Brahms, 1st Symphony

#### Brahms, 2nd Symphony

#### Brahms, 3rd Symphony

#### Brahms, 4th Symphony

#### Bruckner, 4th Symphony "Romantic"

#### Dvoràk, 9th Symphony

#### Grant Still, 1st Symphony "Afro-American"

#### Levi Dawson, Negro Folk Symphony

#### Mahler, 1st Symphony "Titan"

#### Mahler, 2nd Symphony "Ressurrection"

#### Mahler, 3rd Symphony

#### Mahler, 6th Symphony "Tragic"

At first glance, this symphony's overall shape is similar to Beethoven's 9th: charged first movement, angry scherzo, hymn-like slow movement and a crazy, unwieldy finale. But while Beethoven finishes his piece in triumph, Mahler ends his with crushing blows.

This analogy only works with the Scherzo-Andante order for the inner movements, which is [controversial](https://en.wikipedia.org/wiki/Symphony_No._6_(Mahler)#Order_of_the_inner_movements_and_performance_history_issue). Since Mahler himself seemed to go back and forth, I see no sense in being stubbornly attached to one specific order. That being said, I have consistently favored Scherzo-Andante recordings, and I'm afraid my enjoyment of the piece is hopelessly tied to this sequence at this point. The calm of the Andante fits perfectly as a much-needed relief after the boisterous Scherzo. On the other hand, there's much less need of relief after the optimistic ending of the first movement.

Whatever the order, the Andante is among my favorite of Mahler's slow movements, along with the finales of the 3rd and 9th symphonies. Overall, I love the variety of moods in the piece: there are military marches, cheerful celebrations, alpine cowbells, welcoming embraces.  And hammer blows, of course.

#### Mahler, 9th Symphony

#### Messiaen, Turangalila Symphony

#### Mozart, 40th Symphony

#### Mozart, 41th Symphony

#### Price, 1st Symphony

#### Price, 3rd Symphony

#### Saint-Saëns, Symphony No. 3 "Organ"

#### Schoenberg, Chamber Symphony No. 1
In *The Rest is Noise*, Alex Ross tell that when Mahler first heard this piece, he asked someone to play a C major chord as a palate cleanser. I get it.

#### Shostakovich, 4th Symphony

#### Shostakovich, 5th Symphony

#### Shostakovich, 7th Symphony

#### Shostakovich, 8th Symphony

#### Shostakovich, 9th Symphony

#### Shostakovich, 10th Symphony

#### Shostakovich, 11th Symphony

#### Shostakovich, 13th Symphony

#### Schumann, 4th Symphony

#### Sibelius, 2nd Symphony

#### Sibelius, 5th Symphony

#### Sibelius, 7th Symphony

#### Tchaikovsky, 4th Symphony

#### Tchaikovsky, 5th Symphony

#### Tchaikovsky, 6th Symphony



### Other Orchestral Music

#### Adams, City Noir

#### Adams, Fearful Symmetries

#### Assad, Nhanderú

#### Assad, Sin Fronteras

#### Assad, Três Pequenas Variações Sobre o Tema "A Maré Encheu"

#### Bartók, Concerto for Orchestra

#### Bartók, Divertimento for String Orchestra

#### Beethoven, Coriolan Overture in C minor

#### Beethoven, Egmont Overture

#### Grieg, Peer Gynt

#### Lena Frank, Elegia Andina

#### Lena Frank, Escaramuza

#### Lena Frank, Three Latin American Dances

#### Ligeti, Atmosphéres

#### Ligeti, Lontano

#### Ligeti, Lux Aeterna

#### Ligeti, Requiem

#### Mendelssohn, A Midsummer Night's Dream

#### Rachmaninoff, Symphonic Dances

#### Rachmaninoff, The Island of the Dead

#### Ravel, La Valse

#### Reich, Clapping Music

#### Reich, Different Trains

#### Reich, Music for 18 Musicians

#### Riley, In C

#### Villa-Lobos, Bachianas Brasileiras No. 1

#### Villa-Lobos, Bachianas Brasileiras No. 2

#### Villa-Lobos, Bachianas Brasileiras No. 4

#### Villa-Lobos, Bachianas Brasileiras No. 5

#### Villa-Lobos, Bachianas Brasileiras No. 6

#### Villa-Lobos, Choros No. 1

#### Villa-Lobos, Choros No. 3

#### Villa-Lobos, Choros No. 5 "Alma Brasileira"

#### Villa-Lobos, Choros No. 6

#### Villa-Lobos, Choros No. 7 "Settimino"

#### Villa-Lobos, Choros No. 8

#### Villa-Lobos, Choros No. 9

#### Villa-Lobos, Choros No. 10 "Rasga Coração"

#### Villa-Lobos, Choros No. 12

#### Wagner, Prelude & Liebestod from Tristan and Isolde

#### Wagner, Tannhäuser Overture



## Rankings

Ranking works of art is an exercise best left to fools. So here we are.

### Top 10 Symphonies

|\# | Composer     | Piece              | Note                                                    |
|---|--------------|--------------------|---------------------------------------------------------|
| 1 | Mahler       | [9th Symphony](#mahler-9th-symphony) | The first movement is the epitome of Mahler's motto: "Embrace Everything". The music that follows reacts to it by expressing irony, bitterness, and, finally, acceptance. |
| 2 | Shostakovich | [8th Symphony](#shostakovich-8th-symphony) | After 45 minutes of distress, violence, and gloom, the key change introducing the last movement feels like waking up from a nightmare. |
| 3 | Beethoven    | [9th Symphony](#beethoven-9th-symphony-choral) | This level of ambition and execution would only be matched (but not surpassed) generations later by Mahler's 2nd. |
| 4 | Mahler       | [6th Symphony](#mahler-6th-symphony-tragic) | A masterpiece of contrasts: military march, sunshine, pastoral contemplation and kindness. But it all ends with hammer blows and heartbreak. |
| 5 | Shostakovich | [10th Symphony](#shostakovich-10th-symphony) | A diffident artist prevails over authoritarian oppression. |
| 6 | Bartók       | [Music for Strings, Percussion and Celesta](#bartók-music-for-strings-percussion-and-celesta) | Dark fugues, dense counterpoint, creepy night music, folksy celebration. Perfect for those days when you crave a spicy dish. |
| 7 | Tchaikovsky  | [6th Symphony](#tchaikovsky-6th-symphony) | Gorgeous melodies, and the last movement can be unbearable if you're feeling down. Tchaikovsky doesn't get enough respect for this achievement. |
| 8 | Adams        | [Harmonielehre](#adams-harmonielehre) | Minimalism meets the late romantic style. I will always associate it with Civ IV. |
| 9 | Sibelius     | [2nd Symphony](#sibelius-2nd-symphony) | Since I first heard the opening chords back in high school, I knew I would love this music forever. |
|10 | Shostakovich | [4th Symphony](#shostakovich-4th-symphony) | Aggressive dissonances, raging outbursts, harrowing fugue. Heavy metal with an orchestra. |

### Top 10 Chamber Music

|\# | Composer     | Piece              | Note                                                    |
|---|--------------|--------------------|---------------------------------------------------------|
| 1 | Schubert     | [Cello Quintet](#schubert-cello-quintet)| In late Schubert, trills always serve as a harbinger of something ominous|
| 2 | Mendelssohn  | [String Octet](#mendelssohn-string-octet)| Energy, inspiration and balance without any weak points|
| 3 | Schoenberg   | [Verklarte Nacht](#schoenberg-verklarte-nacht)| Immense buildup of tension followed by a release of compassion and understanding|